### ISSUE TITLE
injectIntl throw error

### ISSUE THREAD

**Issue by guangming21** [formatjs/react-intl#1001]
![qq 20170802002337](https://user-images.githubusercontent.com/18028721/28857049-19ab1a06-7779-11e7-971d-effef56c344f.png)
![qq 20170802002348](https://user-images.githubusercontent.com/18028721/28857050-19e5c6c4-7779-11e7-9238-cee17e28b51e.png)
I follow the doc, but injectIntl throw this error, how to fix it

**Comment by papasmile** [comment]
Could be `Login`, `App`, or `FriendsList` is a class and not a React component... if you could post your project or a complete example that might help.

**Comment by guangming21** [comment]
I use it in common component , it works. thanks

**Comment by papasmile** [comment]
😎 like to post your solution?  You can close the issue if fixed.
