### ISSUE TITLE
why named 'locale'?? 

### ISSUE THREAD

**Issue by MAYDAY1993** [formatjs/react-intl#1006]
Hi, so far I know that we put certain language ,such as english, data to a file to store data ,why named localeData rather than localData,or am I misunderstood the meaning ? Thank you for answering 😃

**Comment by ghostd** [comment]
This is 'locale' for language/cultural data: https://en.wikipedia.org/wiki/Common_Locale_Data_Repository
Not local like 'remote <-> local'
