### ISSUE TITLE
Is there any chance you will put version 2 on CDNJS?

### ISSUE THREAD

**Issue by couturecraigj** [formatjs/react-intl#1008]
I have just started using this and now that I understand React's Context a little bit, I love this.  Is there any chance that you will be putting the most recent versions up on a CDN, that way we can keep our bundle size even smaller?  If I can do this I will as well.  I just want to find out if there are any plans to keep this updated on `CDNJS` for instance.

**Comment by mbrevda** [comment]
You can find anything published to npm on unpkg.com. The url for the latest version of react-intl is: https://unpkg.com/react-intl@2.4.0/lib/index.js
