### ISSUE TITLE
Pluralization problem - different results with FormattedPlural and FormattedMessage

### ISSUE THREAD

**Issue by dstudzinski** [formatjs/react-intl#1013]
Hello,

I have problem related to different behavior with FormattedPlural vs FormattedMessage with ICU Message Syntax. I use React 15.6.1 and react-intl 2.3.0

I use pl locale
```
...
import {addLocaleData} from 'react-intl';
import pl from 'react-intl/locale-data/pl';

import {IntlProvider} from 'react-intl';
import plTranslation from './translations/pl.json';

addLocaleData(pl);
const locale = 'pl';

ReactDOM.render(
  <IntlProvider locale={locale} messages={plTranslation}>
    <App />
  </IntlProvider>,
  document.getElementById('root')
);
```

Content of `pl.json`:
```
{
  "fm.pierogi": "{amount, plural, =0 {brak pierogów translation} one {# pieróg} few {# pierogi} many {# pierogów} other {# pieroga translation}"
}
```

This works great:
```
{this.state.amount}{' '}
<FormattedPlural
  value={this.state.amount}
  one="pieróg"
  few="pierogi"
  many="pierogów"
  other="pieroga"
/>
```

The result is:
0 pierogów
0.5 pieroga
1 pieróg
2 pierogi
...
5 pierogów
...

but this doesn't work:
```
<FormattedMessage
  id="fm.pierogi"
  description="Plural for pierogies"
  defaultMessage={`{amount, plural,
    =0 {brak pierogów}
    one {# pieróg}
    few {# pierogi}
    many {# pierogów}
    other {# pieroga}
  }`}
  values={{amount: this.state.amount}}
/>
```

The result is:
brak pierogów
0.5 pieroga
1 pieróg
2 pieroga
...
5 pieroga
...

The strange thing is that it always takes translation from `defaultMessage` (as you can see in pl.json translation is different: `brak pierogów translation` instead of `brak pierogów`).
When I change translation in `pl.json` to:
```
{
  "fm.pierogi": "{amount} Hi"
}
```

the result is:
Hi
0.5 Hi
1 Hi
...

When I remove `addLocaleData(pl)` FormattedPlural behaves similar to FormattedMessage so maybe it's a problem with loading locale data? And I still don't know why translation is not loaded from pl.json.
I have no idea what should I check next.
I can prepare working example based on Create React App.

**Comment by Eccenux** [comment]
Here are correct plural rules for Polish language:
1: 1 // e.g. 1 pieróg
2: (n % 10 in 2-4) and (n % 100 not in 12-14) // e.g. 2 pierogi, 3 piergoi
3: other // e.g. 0 pierogów, 5 pierogów, 12 piergów

There would also need to be a fourth rule if you also want fractions (as in the example above).

See other languages:
https://translatewiki.net/wiki/Plural/Mediawiki_plural_rules

**Comment by jeegurda** [comment]
I've been losing my mind around this issue as well and it turns out locale data is not used when formatting `defaultMessage`. If you pass your messages as a prop to IntlProvider it does work properly.

Check this out: https://codesandbox.io/s/2zv090v40j

@Eccenux 
> There would also need to be a fourth rule if you also want fractions (as in the example above).

That's incorrect – numbers with fractions do match the "other" rule.
