### ISSUE TITLE
Disable message fallbacks for `FormattedMessage` (during dev/testing)

### ISSUE THREAD

**Issue by TiddoLangerak** [formatjs/react-intl#1014]
In an ideal world the message fallbacks should never be used. After all, every key should have a proper translation. In practice fallbacks are a good thing to prevent the application from crashing, but that is only relevant in production - not during development or testing.

During development I want it to be extremely obvious when translations are missing such that I can fix it before shipping it. Additionally I want to be able to automatically fail my builds. Currently the only aid we get is an error logged to the console, but this is very easy to miss and difficult to test against. 

It would therefore be really useful to be able to turn off fallbacks and fail hard instead. This would help preventing shipping broken bundles in the first place.

As far as I could figure out this is currently not possible, but it would be a really welcome addition.

**Comment by okovpashko** [comment]
@TiddoLangerak how do you imagine an ability to fail the build if `react-intl` is a runtime tool?

**Comment by TiddoLangerak** [comment]
With the help of automated testing. E.g. we use snapshot testing for virtually all of our components, if `<MessageFormat>` would throw on invalid `id` then the snapshot tests would fail immediately. This is of course not entirely fool proof, but a lot better than nothing.

**Comment by papasmile** [comment]
If you just need to check translations why don't you extract them with something like https://github.com/yahoo/babel-plugin-react-intl and then do a simple comparison in javascript between your own translation file and that extraction to ensure all id's are covered?

**Comment by phillipj** [comment]
FWIW the introduction of configurable `<IntlProvider onError>` handler in #880, this seems plausible by throwing the error received in that function. Something like:

```html
  <IntlProvider
    locale={locale}
    messages={translatedMessages}
    onError={err => {
      throw err
    }}> 
    ... 
  </IntlProvider>
```

Blows up immediately in a create-react-app I've tested it on at least.
