### ISSUE TITLE
Some Currencies symbol don't change for Spanish(es)

### ISSUE THREAD

**Issue by sudharsan1988** [formatjs/react-intl#1015]
Hi, Thank you for the wonderful library.

I'm using React-intl for Multi-currency and Multi-language. I am currently using 5 languages respectively English-US, Spanish, Italian, Portuguese & French. It's working awesome. 

However, when I use Spanish, only few currencies showing with symbols(Euro, US dollars) and for rest of the currencies it's just showing the code(INR, GBP...etc). I have tested with other languages and currency symbols are showing for most of the currencies. Is it by default or am I missing something?

I use FormattedNumber for showing currencies,

```
<FormattedNumber
            value={convertedAmount}
            style="currency"
            currency={targetCurrency} 
            minimumFractionDigits={0}
            maximumFractionDigits={0}
            currencyDisplay={"symbol"}
          />
```

And I have added all local-data for en, es, it, fr and pt. 

```
import en from 'react-intl/locale-data/en';
import es from 'react-intl/locale-data/es';
import it from 'react-intl/locale-data/it';
import fr from 'react-intl/locale-data/fr';
import pt from 'react-intl/locale-data/pt';
```
Any help would be highly appreciated.

**Comment by obedparla** [comment]
Having a similar issue but with accents. #1063
