### ISSUE TITLE
[Question] Multi Language Router?

### ISSUE THREAD

**Issue by oguzhanaslan** [formatjs/react-intl#1027]
I'm a new React and next.js user. I plan to develop a multi language application. For language translation, I will use the react-intl package.

The app can run on more than one domain. The application will run as a single react client.

After you set the user's language  (window.location.hostname), I want to specify the route prefix for the common component.

I want to do these in a single Next client application.

For example :
EN -> xxx.com
DE -> yyy.com
FR -> zzz.com

If I want to explain:

xxx.com/register -> auth component
yyy.com/unterschreiben -> auth component
zzz.com/inscrivez-vous -> auth component

xx.com/unterschreiben -> Return 404
yyy.com/register -> Return 404

Can I build such a route with react-intl and Next.js? I have not found such an example.

**Comment by ghostd** [comment]
Maybe you could read this:
* https://medium.com/@markuretsky/react-router-multilingual-362eaa33ae20
* https://stackoverflow.com/questions/39080119/how-to-translate-react-router-route-paths
