### ISSUE TITLE
add support for babel-macros

### ISSUE THREAD

**Issue by knowbody** [formatjs/react-intl#1030]
Hi!

Similarly to the issue [here](https://github.com/facebook/relay/issues/1968), I try to investigate ways that create-react-app can use babel plugins without having to change configuration (see facebookincubator/create-react-app#2730 for more context).

> With `babel-macros`, users can install and configure this plugin and have access to use any macro available (or create their own) without configuring anything else. This is appealing to create-react-app users because so far they've had to eject if they wanted to use something like [`preval`](https://github.com/kentcdodds/babel-plugin-preval), [`emotion`](https://github.com/emotion-js/emotion).

Adding the support should be fairly easy and starting out with experimental support would be totally fine considering we face a catch 22 situation (CRA wants to see usage of babel-macros in the community before adopting it and you all probably feel the same).

What do you all think?

**Comment by ivosabev** [comment]
While on this it will be useful to think of running the macro across multiple packages in the case of monorepo setup. For example we have both React and React Native packages sharing some translations and would like to share some translations between them.
