### ISSUE TITLE
Is there now a way to create messages dynamically?

### ISSUE THREAD

**Issue by buesing** [formatjs/react-intl#1036]
I've read https://github.com/yahoo/react-intl/issues/80 and https://github.com/yahoo/react-intl/issues/162 but I couldn't find the answers I was looking for. I have a couple of .json files where I store my data, e.g.

```
[
  {
    title: 'Die Salonkultur des alten Wien – glanzvolle Bühne einer Gesellschaft',
    location: 'Ernst Fuchs Museum',
  }, {
    title: 'Gustav Klimt Atelier',
    location: 'Klimt Villa',
  }, {
    title: 'Von der Wiener Klassik zur zweiten Wiener Schule',
    location: 'Klimt Villa',
  }
]
```
I import these and then I would like to render the messages with e.g. 

    posts.map((post, index) => <FormattedMessage id={`post.title${index}`} defaultMessage={post.title} />)

I'm using yahoo/babel-plugin-react-intl to extract the messages for translation, which obviously doesn't work with this setup. 

Is there a way to dynamically define messages to extract them later? Or how would you suggest I change my setup in a sane way? The real data is much longer and I dont want to hand write hundreds of `FormattedMessages` in my JS, neither do I want to mix data and presentation and put the `FormattedMessages` into the JSON file and change it to a JS file. I'm sure this is a common use case and there must by a DRY way to handle it.

**Comment by obedparla** [comment]
I'm interested in the same. I searched like crazy for a solution but found none whatsoever.
The solution I saw @ericf proposing in a few opened issues was to simply use your JSON file and translate that, so you'd have a localized JSON file, then you can add it to the intl.messages and have access to them, without extracting them using the babel plugin. 
I would have used that solution, but we need have 1 file containing ALL the localizable text, so I painstakingly did what you're trying to avoid :P

**Comment by papasmile** [comment]
Don't know that I totally grasp what you are after, but throwing something out.  Basically, messages are based on the idea that each one is uniquely identifiable, e.g., "give me a translation for page1.titleText".  That's a problem if things are too 'dynamic' to even know what content you will have.

What I am getting at is that you can predefine all **possible** messages and then build your UI so that missing translations. e.g.
```
[...Array(5).keys()].map((i) => {
  return (
    <span className="handles-whitespace-well">
      <FormattedMessage id={`posts.${i}.shortTitle`} defaultMessage=" " />
    </span>
  );
})
```
messages.json
```
[
  {
    posts.0.shortTitle: 'Das Boot',
  }
]
```
Additionally, you could avoid empty keys by pre-processing the total number of keys once you process your translations do not impact visual layout e.g. 
```
import ItemCounts from './translatedItemCounts.json';
...
[...Array(itemCounts.postsCount).keys()].map(i => <FormattedMessage id={`posts.${i}.shortTitle`} defaultMessage=" " />)
```
Hope that helps.

**Comment by buesing** [comment]
@papasmile this is pretty much what I'm trying to do, but getting this exception: `Module build failed: SyntaxError: [React Intl] Messages must be statically evaluate-able for extraction.`

**Comment by papasmile** [comment]
Are you trying to use messages like you have up top?  You would actually need something like:
```
{
    posts.0.title: 'Die Salonkultur des alten Wien – glanzvolle Bühne einer Gesellschaft',
    posts.0.location: 'Ernst Fuchs Museum',
    posts.1.title: 'Gustav Klimt Atelier',
    posts.1.location: 'Klimt Villa',
}
```
That error is not in react-intl but in babel plugin btw https://github.com/yahoo/react-intl/issues/1036#issuecomment-332923165

**Comment by buesing** [comment]
I'm not sure what you mean. What you posted results in a syntax error, I suppose you forgot the quotes:
```
{
    'posts.0.title': 'Die Salonkultur des alten Wien – glanzvolle Bühne einer Gesellschaft',
    'posts.0.location': 'Ernst Fuchs Museum',
    'posts.1.title': 'Gustav Klimt Atelier',
    'posts.1.location': 'Klimt Villa',
}
```
This doesn't change anything though, still getting the error. This particular error is from the babel plugin, but the question how to handle dynamic data in general is for react-intl. I don't need to use the babel plugin, just looking for a clean way to handle this usecase. What I ended up doing is to have a script that searches the json files for objects that have an `id` and a `defaultMessage` and writes those to a flattened json file that can be used for translating. It's not pretty but it works for now.

**Comment by obedparla** [comment]
@buesing if you don't need to use the babel plugin then you're free to use any type of data coming from anywhere, react-intl is just javascript so it can handle any data as any other function would. The problem with the babel plugin is that it tries to parse the text and babel cannot deal with complex dynamic data. 

So, for example, if you're sure you'll have your  ID and defaultMessage you can do something like this without issues: `foo: {id: `text.${dynamicID}.awesome}, defaultMessage: `howCoolIs${this}`}. Then you can use <FormattedMessage /> or formatMessage to render your data. React-intl will automatically find the correct id in your messages and translate it.
