### ISSUE TITLE
Custom date format

### ISSUE THREAD

**Issue by Milena0** [formatjs/react-intl#1037]
Is there a way to change date format (with no locale changes), for example from mm/dd/yy to day first format?

**Comment by okovpashko** [comment]
I have only one suggestion: combine `FormattedMessage` with several `FormattedDate`, but I see no reason for that because you'll have to describe the format for each locale you're using.
Example: 
```javascript
const date = new Date();
...
<FormattedMessage 
  id="myId" 
  defaultMessage="{day}/{month}/{year}" 
  values={{
    day: <FormattedDate value={date} day="2-digit"/>,
    month: <FormattedDate value={date} month="2-digit"/>,
    year: <FormattedDate value={date} year="2-digit"/>
  }}
/>
```

**Comment by Milena0** [comment]
What if I have one locale? Do you think your method is only one solution?

2017-09-29 13:59 GMT+02:00 Oleksandr Kovpashko <notifications@github.com>:

**Comment by okovpashko** [comment]
@Milena0 if you have only one locale you can use my solution.

If you don't want to use several locales and want to have fully customizable date/time formats, then probably react-intl is not the tool you need.
The main purpose of this library is providing different strings for different languages and formatting date/time/numbers according to the locale (with little customization).

Maybe [date-fns](https://date-fns.org/) or [moment.js](https://momentjs.com/) could be a better option for your needs.
