### ISSUE TITLE
Return strings instead of <span> tags

### ISSUE THREAD

**Issue by rhysforyou** [formatjs/react-intl#1039]
So now that React 16 lets components return unadorned strings, is there any chance that react-intl will take advantage of that?

**Comment by bsr203** [comment]
This is useful for cases like internationalizing texts on select box (options). Now I get error

```
console.error node_modules/fbjs/lib/warning.js:33
      Warning: validateDOMNesting(...): <span> cannot appear as a child of <option>.
          in span (created by FormattedMessage)
```

**Comment by bsr203** [comment]
possible duplicate of https://github.com/yahoo/react-intl/issues/999
