### ISSUE TITLE
Disable console errors for lack of translations during testing

### ISSUE THREAD

**Issue by ggauravr** [formatjs/react-intl#1041]
### Expected behavior
It would be good to have a way to turn off the `console.error` messages from the terminal when the package is used in unit-testing with some flag or a specific environment variable(something like `process.env.IGNORE_INTL_TRANSLATIONS = true`) which could be checked in `src/lib/index.js` to just run with the fallback and not report any errors.

### Current behavior

Currently in `src/lib/index.js`, I see that the only way to turn off warnings due to lack of translations is to set `NODE_ENV` to `production`.

```
 PASS  src/components/cta-listing/index.test.js
  ● Console

    console.error node_modules/fbjs/lib/warning.js:35
      Warning: render(): Rendering components directly into document.body is discouraged, since its children are often manipulated by third-party scripts and browser extensions. This may lead to subtle reconciliation issues. Try rendering into a container element created for your app.
    console.error node_modules/react-intl/lib/index.js:706
      [React Intl] Missing message: "NOT_BOOKABLE_HEADER" for locale: "en"
    console.error node_modules/react-intl/lib/index.js:725
      [React Intl] Cannot format message: "NOT_BOOKABLE_HEADER", using message id as fallback.
    console.error node_modules/react-intl/lib/index.js:706
      [React Intl] Missing message: "LISTINGS_CTA_CONTENT" for locale: "en"
    console.error node_modules/react-intl/lib/index.js:725
      [React Intl] Cannot format message: "LISTINGS_CTA_CONTENT", using message id as fallback.
    console.error node_modules/react-intl/lib/index.js:706
      [React Intl] Missing message: "LISTINGS_CTA_EMAIL" for locale: "en"
    console.error node_modules/react-intl/lib/index.js:725
      [React Intl] Cannot format message: "LISTINGS_CTA_EMAIL", using message id as fallback.
```

### Your Environment

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.4.0 |
| `npm ls react` | 15.6.1 |
| `npm --version` | 3.10.10 |
| `node --version` | 6.11.2 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

| Browser | Version |
| --- | --- |
| NAME | VERSION |

**Comment by ggauravr** [comment]
We could discuss the approaches here and I'd be happy to raise a PR with the implementation.

**Comment by ghostd** [comment]
What do you think about #880 ?

**Comment by ggauravr** [comment]
@ghostd that's a good solution. Have left a suggestion. Please see if that seems reasonable.
