### ISSUE TITLE
React native

### ISSUE THREAD

**Issue by aurelienbr** [formatjs/react-intl#1042]
Hi everyone,
this is not really an issue, but I would like to know how to get started with this library on react native, I feel quite lost with the documentation and I cant set it up correctly without error. 
If one of you guys have a good "getting started with react intl on react native" tutorial to share :)

Anyway I keep having this error : "Invariant violation, the intl APIs must be avaible in the runtime and do not appear to be built in", Ive seen that it can be about old browser, but as im on native..

Thank you guys

**Comment by Noitidart** [comment]
I think you need to polyfill intl api, but still it seems it has a problem - https://github.com/yahoo/react-intl/issues/1025

**Comment by Noitidart** [comment]
It seems @vinogradov - got it working in RN - https://github.com/yahoo/react-intl/issues/921#issuecomment-298615809

@vinogradov - may you please chime in here on how you accomplished it. I actually haven't tried it yet, was researching various libs before picking, so this question is apart of that preliminary research.

**Comment by aurelienbr** [comment]
So here what solved my issue : 
    - I added `import 'intl';` at the top of my IntlProvider file, after downloading it.
    - Then imported all the languages I needed from react-intl : 
```
import en from 'react-intl/locale-data/en';
import fr from 'react-intl/locale-data/fr';
import cs from 'react-intl/locale-data/cs';
```

and `addLocaleData([...en, ...fr, ...cs]);`

After this I faced another issue, as I wanted to store the local and the messages in a redux store and to change the language throw an action, it did not rerender correctly my formatted messages.

So I returned my provider class and my page inside a function ( sorry I have not idea about the exact english term ), connect it to the redux store, and then connect my exported function to every component which needed translation.

Here is my solution : 
```
const withLocale = Page => {
  class IntlRoot extends Component {
    componentDidMount() {
      this.props.getTranslations();
    }
    render() {
      const { locale, loading, translations } = this.props;
      if (loading) {
        return <View />;
      }
      return (
        <IntlProvider
          locale={locale}
          messages={translations[locale]}
          textComponent={Text}
        >
          <Page {...this.props} />
        </IntlProvider>
      );
    }
  }
  return connect(mapStateToProps, actions)(IntlRoot);
};

export default withLocale;
```

and then in any other file that needed translation : 

first import it : 
 `import withLocale from '../intlRoot';`

then connect it : 

`export default withLocale(connect(mapStateToProps, actions)(SearchScreen));`

**Comment by aurelienbr** [comment]
Having another issue related to react native and maybe the polyfill,
I can't use `FormattedDate`, first I get **No locale data has been provided for this object yet**

Then I replaced 
```
import en from 'react-intl/locale-data/en';
import fr from 'react-intl/locale-data/fr';
import cs from 'react-intl/locale-data/cs';
```
by
```
import en from 'intl/locale-data/jsonp/en';
import fr from 'intl/locale-data/jsonp/fr';
import cs from 'intl/locale-data/jsonp/cs';
```
and get this error : 
**Missing locale data for locale fr using default locale: en as fallback**

tried to switch to
`Intl.__addLocaleData([...fr, ...en, ...cs]);`

and still have another error.

Someone has a workaround ?
It would be so nice to add a clear doc for React Native !

**Comment by ikhsanalatsary** [comment]
@aurelienbr i think, you need add [react-native-i18n](https://github.com/AlexanderZaytsev/react-native-i18n) cause it's native. for me, it works. I just added basic setup 
```jsx
<IntlProvider locale="en" textComponent={Text}>
  <App />
</IntlProvider>
``` 
and used `<FormattedDate />` as well

**Comment by ncfrak** [comment]
Hello @ikhsanalatsary can you elaborate please ?
@aurelienbr have you found something ?

I am not really used to all of this, I did a lot of research and I'm still stuck as to how to deal with dates and times.
The issue date and time formatting inside messages.

The file looks like this
`import "intl";
import "intl/locale-data/jsonp/en";
import appLocaleData from "react-intl/locale-data/en";
import "date-time-format-timezone";

export default {
	locale: "en-US",
	name: "English",

	"Message": "{value, date, short} at {value, time, short}",

	data: appLocaleData,

	formats: {
		date: {
			short: {
				year: "2-digit",
				month: "2-digit",
				day: "2-digit",
			},
			monthDayLong: {
				month: "long",
				day: "numeric",
			},
			long: {
				year: "numeric",
				month: "long",
				day: "numeric",
			},
		},
		time: {
			short: {
				hour12: false,
				hour: "2-digit",
				minute: "2-digit",
			},
		},
	},
};`

then on the Android Emulator device I got this error

console.error: "[React Intl] Error formatting message: "Message" for locale: "en-US", using default message as fallback.
TypeError: `this` value for format() is not an initialized Intl.DateTimeFormat object."

**Comment by Noitidart** [comment]
For dates and times you should use momentjs - http://momentjs.com/ -
https://github.com/SoftwareMansion/react-native-hour-format#integration-with-momentjs

**Comment by zabojad** [comment]
@ikhsanalatsary could you please describe how you integrate `react-native-i18n` with `react-intl`? I've tried to install `react-native-i18n` but I'm still getting the missing `intl` APIs/polyfill issue... Although I do not have anything fancy with my `react-intl` implementation...

**Comment by zabojad** [comment]
OK, I've just resolved it. Here is how I did for those who will fell on the same issue.

I've installed the [`intl` npm package](https://github.com/andyearnshaw/Intl.js) (`npm install intl --save`).

Then in my code, I've added: `global.Intl = require('intl');` before everything else initialize.

Then it worked ^^...

**Comment by ikhsanalatsary** [comment]
For react native in iOS is nothing todo to import intl, because it’s supported by default.
I did `Platform.select({ android: () => require('intl') })()` because android need intl polyfill.

**Comment by chawax** [comment]
Something strange for me ... If I run my app on a iOS 11.4 simulator, I don't need the `intl` polyfill. If I run it on iOS 9.3 I have a error message telling me I need it ! I can't understand that since Javascript core is bundled with the application, isn't it ? So it should not depend on iOS version ?

**Comment by jeanregisser** [comment]
Got that issue on iOS 9 as well.

@chawax iOS version of React Native uses the system provided JavaScriptCore (unlike on Android), which explains why you see this inconsistency.

**Comment by chawax** [comment]
Yes, I thought that React Native bundled JavascriptCore on  both Android and iOS but I was wrong. It does it only on Android. So it means you can have JS bug depending on iOS version, not what I expected from React Native 👎

**Comment by jeanregisser** [comment]
Got that issue on iOS 9 as well.

@chawax iOS version of React Native uses the system provided JavaScriptCore (unlike on Android), which explains why you see this inconsistency.

**Comment by kristerkari** [comment]
It seems that `Intl` is fully supported on iOS, but here's what I did to polyfill Android to support `Intl`:

```js
if (Platform.OS === "android") {
  require("intl");
  require("date-time-format-timezone");
  require("intl/locale-data/jsonp/en");
  require("intl/locale-data/jsonp/fr");
}
```
...which means that you need to install these two packages from npm: `intl` and `date-time-format-timezone`.

**Comment by rolandnagy** [comment]
> It seems that `Intl` is fully supported on iOS, but here's what I did to polyfill Android to support `Intl`:
> 
> ```js
> if (Platform.OS === "android") {
>   require("intl");
>   require("date-time-format-timezone");
>   require("intl/locale-data/jsonp/en");
>   require("intl/locale-data/jsonp/fr");
> }
> ```
> 
> ...which means that you need to install these two packages from npm: `intl` and `date-time-format-timezone`.

From React-native 0.60 by setting `jscFlavor` in your `build.gradle` to `'org.webkit:android-jsc-intl:+'` will resolve the issue
