### ISSUE TITLE
Need support for `DateTimeFormat/NumberFormat#formatToParts()`

### ISSUE THREAD

**Issue by zincli** [formatjs/react-intl#1048]
Is there any plan to support `formatToParts()`? We need this to style the price and the currency symbol...

Due to this [issue#30 of ECMA402](https://github.com/tc39/ecma402/issues/30#issuecomment-332303972), `formatToParts()` already reached Stage 4. [And the Intl Polyfill already have the implementations](https://github.com/andyearnshaw/Intl.js/pulls?utf8=%E2%9C%93&q=is%3Apr%20formatToParts).

Maybe we could do some work to make this available in react-intl as an optional function?

@ericf I saw you in [#30](https://github.com/tc39/ecma402/issues/30) and other related issues in react-intl. What do you think about this now?

**Comment by tlvenn** [comment]
@zincli can you please re-open, pretty interested to see some support for this as well.

**Comment by longlho** [comment]
@zincli @tlvenn can u guys provide some use cases?

**Comment by tlvenn** [comment]
This was a pretty compelling use case: https://github.com/formatjs/react-intl/issues/874

**Comment by longlho** [comment]
hmm I'm considering adding a new component like `<FormattedDateParts>` instead of overloading `<FormattedDate>` so we can keep the types sane. WDYT?

cc @redonkulus

**Comment by redonkulus** [comment]
@longlho What would the API look like for this?

**Comment by longlho** [comment]
```tsx
<FormattedDateParts>
	{(parts: Intl.DateTimeFormatPart[]) => (
		<b>{parts[0]}</b>
		{parts[1]}
		<small>{parts[2]}</small>
	)}
</FormattedDateParts>
```

although I'd like to learn more about this use case, because ordering of the parts along w/ length of the `parts` is non-deterministic (bc of different locale + bidi) so styling might be tricky? @tlvenn

**Comment by robrichard** [comment]
I think correct usage would be something like this:

```js
<FormattedDateParts>
    {parts => parts.map(part => 
        <span className={`number-part-${part.type}`}>{part.value}<span>
    )}
</FormattedDateParts>
```

```css
.number-part-integer {
    font-size: 14px;
}

.number-part-fraction {
    font-size: 10px;
}

**Comment by longlho** [comment]
yeah I got that, but I feel like the styling would still be fairly inconsistent cross-locale

![image](https://user-images.githubusercontent.com/198255/63563102-f53b1180-c52d-11e9-8c5d-4a239dc66a7e.png)

Anw, this does fit w/ the intention of the original `formatToParts` proposal and supporting it isn't too bad so I've added it to the backlog.

3.2 is looking like this feature + https://github.com/formatjs/formatjs/tree/master/packages/intl-unified-numberformat would make it

**Comment by longlho** [comment]
`3.2.0-rc.0` should have this.

**Comment by mrijke** [comment]
What about a `formatDateParts()` function next to https://github.com/formatjs/react-intl/blob/master/docs/API.md#formatdate ? Or is this already available some other way without having to use the `<FormattedDate>` component?
