### ISSUE TITLE
TypeScript and refs

### ISSUE THREAD

**Issue by orobert91** [formatjs/react-intl#1052]
How can I use type-cheking on refs?

Here is the parent component referencing the child component:

```
export default class ParentComponent extends React.Component<IParentComponentProps, any> {
    private _childComponent: any | null; //Problem here. Must use any instead of the real type.

    constructor(props: IParentComponent Props) {
        super(props);
        this.state = {};
    }

    public render(): JSX.Element | null {
        return (
            <ChildComponent ref={c => this._childComponent= c != null ? c!.refs.wrappedInstance : null} />
        );
    }
}
```
In the code above, if I change 

` private _childComponent: any | null;`

to

` private _childComponent: ChildComponent | null;`

which would normally work when not using React Intl, I get a "[ts] Cannot find name 'ChildComponent'" error message because the child component is wrapped with injectIntl.

Here is the referenced, child component:

```
class ChildComponent extends React.PureComponent<IChildComponentProps & InjectedIntlProps, any> {
    constructor(props: IChildComponentProps & InjectedIntlProps) {
        super(props);
        this.state = {};
    }

    public render() : JSX.Element | null {
        
    }
}

export default injectIntl(ChildComponent, {withRef: true});
```

Is there any solution to this? I don't want to give up type checking. Thank you for your help

**Comment by papasmile** [comment]
One obvious (though cruddy) solution would be to skip `injectIntl` either by 1) skip it on child components, instead just inject once on parent component and pass it down as a prop or 2) make exclusive use of declarative for for formatters so you don't need an instance of `intl` at all.
