### ISSUE TITLE
"Can't resolve 'prop-types'" when using react-intl

### ISSUE THREAD

**Issue by stefan-schweiger** [formatjs/react-intl#1054]
### Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

### Expected behavior
When your project is using react-intl but not prop-types there shouldn't be an error.

### Current behavior
Error "Can't resolve 'prop-types'" is thrown.

### Workaround
Add prop-types to your project

### Your Environment
| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.4.0 |
| `npm ls react` | 15.6.0 |
| `npm --version` | 5.5.1 |
| `node --version` | 8.7.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| Windows 10 | 1709 |

**Comment by amakhrov** [comment]
My particular use case is using Typescript in my React app - which eliminates the need in prop types.

If `react-intl`depends on prop-types (which is apparently the case) - shouldn't it be a dependency rather than peer dependency?

**Comment by NickGard** [comment]
The production build of `react-intl` should not rely on `prop-types` because `react` doesn't pull in `prop-types` anymore.
