### ISSUE TITLE
List of React elements as value

### ISSUE THREAD

**Issue by eliseumds** [formatjs/react-intl#1055]
### Is this a BUG REPORT or FEATURE REQUEST? (choose one)

Feature request

### Expected behavior

I'd like to able able to pass a list of React elements as value to a message

### Current behavior

It stringifies the list, for example: `[object Object], [object Object]`

### Step to reproduce for BUG REPORT

https://codesandbox.io/s/z2yxjopkv4

**Comment by k15a** [comment]
Simple workaround: Wrap your list into another React element.

```jsx
import React from 'react'
import { render } from 'react-dom'
import { IntlProvider, FormattedMessage } from 'react-intl'

const App = () => (
	<IntlProvider>
		<FormattedMessage
			id="bla"
			defaultMessage="Hello: {links}"
			values={{
				links: (
					<span>
						{[1, 2, 3].map(value => <a href="#">{value}</a>)}
					</span>
				),
			}}
		/>
	</IntlProvider>
)

render(<App />, document.getElementById('root'))
```
