### ISSUE TITLE
 Set the defaultMessage to look at "en-US" if the current locale is missing entry

### ISSUE THREAD

**Issue by LarsLiden** [formatjs/react-intl#1056]
FEATURE REQUEST / QUESTION

Rather than specify a defaultMessage for every FormattedMessage, it would be nice to set the defaultMessage to always be that of a particular language.  We know we are always going to have English translations for everything.   Specifically I'd like to set the defaultMessage to look at "en-US" if the current locale is missing.

**Comment by hunght** [comment]
same here, i thin it is must have featuer

**Comment by jeffsheets** [comment]
I'm also looking for a way to do this. Did anyone figure out a workaround?

**Comment by LarsLiden** [comment]
Created a util for this:

``````
export function getDefaultText(id: IntlMessages.FM): string {
    return IntlMessages.default["en-US"].hasOwnProperty(id) ? IntlMessages.default["en-US"][id] : ""
}

export function formatMessageId(intl: ReactIntl.InjectedIntl, id: IntlMessages.FM) {
    return intl.formatMessage({
        id: id,
        defaultMessage: getDefaultText(id)
    })
}
``````
