### ISSUE TITLE
在react -JS文件中，怎么使用方法，不是extend模式，是function方法，怎么替换数组中的文字？

### ISSUE THREAD

**Issue by lettywiterock** [formatjs/react-intl#1060]
react 项目JS页面都是方法这种模式的
怎么引用formatMessage方法？
方法页面没有props。
头大，希望能解答，谢谢

**Comment by lettywiterock** [comment]
没有人回答，我要纠结死了，(⊙﹏⊙)

**Comment by zincli** [comment]
如果不在IntlProvider上下文是用不了的，话说你为什么用中文提问。。。你可以试试把文案传参进去你的方法里面

**Comment by lettywiterock** [comment]
非常感谢，我这边已经解决了，使用参数传递，这个插件可以替换json，只需要把json赋值给参数，更改参数赋值，就可以直接用更新参数的方法。
在页面显示，引用参数而不是插件的标签，就可以达到替换的目的。
