### ISSUE TITLE
Feature Idea: PseudoLanguages to help development

### ISSUE THREAD

**Issue by fbartho** [formatjs/react-intl#1062]
### Is this a BUG REPORT or FEATURE REQUEST? (choose one)

Feature Request!

# Description
I'm looking at using react-intl for React-Native, currently our app env is only in English-US/English-GB, but later this year I expect to start having to consider more languages. It would be great if I could turn on a pseudo language like "string-doubled" in order to verify that our UI adapts correctly to longer strings.

Reference: [Apple Docs for iOS / macOS PseudoLanguage testing](https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/TestingYourInternationalApp/TestingYourInternationalApp.html#//apple_ref/doc/uid/10000171i-CH7-SW3)

Other useful pseudolanguages could include right-to-left virtual language support!

**Comment by tom-saunders** [comment]
I'm also interested in something along these lines.

**Comment by martijnthe** [comment]
+1

**Comment by vdh** [comment]
I've been able to do similar testing with other libraries by creating a fake additional language set using a private use subtag (e.g. our main language is `en-AU`, so I created `en-AU-x-testing`), that I run through a custom "gibberish" function.

moment.js already has a `x-pseudo` testing locale that I make use of instead of manually generating date-based gibberish, and it'd be great to have a similar equivalent for `react-intl`.

Otherwise, we could attempt to apply the "gibberish" transform technique on the existing `react-intl/locale-data/en.js` data and load that alongside other languages (which is what I'm about to attempt to do…)

**Comment by fbartho** [comment]
@vdh Do you have a trick that will parse the ICU-string, and let me apply my gibberish function without mangling my placeholders/variables?

**Comment by vdh** [comment]
@fbartho It sounds like you'd have to intercept something like `formatMessage` or other internal part of `react-intl` to do something like that, which could get way too messy. The only thing I'm doing is just automating the addition of an additional fake language, in the same format a real new language would be loaded into `react-intl`.

My boilerplate could probably be greatly reduced using some immutable copying and recursion over the `fields` of one of the values in the `react-intl/locale-data/en.js` array, but the general concept is still loading in a new fake language. I just went for this semi-static file as a path of lesser resistance over devoting time to write a more complex function.

**Comment by martijnthe** [comment]
I've used this package to generate pseudolocales as part of the build process:
https://www.npmjs.com/package/pseudolocale

I've used these options to leave placeholders/variables alone:
```
    pseudolocale.option.startDelimiter = '{';
    pseudolocale.option.endDelimiter = '}';
    pseudolocale.option.extend = 0.3;
```

So far it's been working fine for our needs.

**Comment by vdh** [comment]
@fbartho Oh sorry I completely misinterpreted your question there. Sorry for not answering it properly earlier. As for how I handle placeholders, it's mostly just a string split on a big regex:
```js
/(\{[a-zA-Z0-9_-]*\}|<[a-zA-Z0-9\s='"{}[\]()\\/.:;_-]+>|&#?[a-zA-Z0-9_]+;)/g
```
and skipping any bits starting with `{` (placeholders, `<` (html tags), or `&` (html entities)
