### ISSUE TITLE
Missing Currency Sign for NOK

### ISSUE THREAD

**Issue by Kaniz92** [formatjs/react-intl#1075]
### BUG REPORT
In react-intl `FormattedNumber` currency symbol for NOK is not displayed in Chrome and Firefox, except in Microsoft Edge.

### Expected behavior
KR10,000.00

### Current behavior
NOK10,000.00

### Step to reproduce for BUG REPORT
Following code snippet is used,

`<FormattedNumber 
           value={10000}
           style='currency' 
           currency='NOK'/>`

### Environment
| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.4.0|
| `npm ls react` | 16.0.0|
| `npm --version` | 5.3.0|
| `node --version` | v8.6.0|

| Browser | Version |
| --- | --- |
| Chrome |63.0.3239.84 |
| Microsoft Edge | 40.15063.0.0 |
| Firefox | 56.0.2 |

**Comment by ghostd** [comment]
Hi,

I think this is not related to react-intl. This seems to be a browser issue with its [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) support.

Try the following code into your browser console:
```
new Intl.NumberFormat('en-US', { style: 'currency', currency: 'KOR' }).format("123")
```

**Comment by Kaniz92** [comment]
Not helping. Got following results.

**Chrome**
[
![chrome](https://user-images.githubusercontent.com/31236289/34024736-dc05d976-e171-11e7-941e-448c2ca5cdd6.PNG)
](url)

**Firefox**
[
![firefox](https://user-images.githubusercontent.com/31236289/34024741-e570acca-e171-11e7-8a95-e1a793b09a76.PNG)
](url)

**Comment by ghostd** [comment]
These results show this is not a react-intl issue, but a missing support from the browsers.
