### ISSUE TITLE
Handle empty message parameters.

### ISSUE THREAD

**Issue by andylhansen** [formatjs/react-intl#1076]
I have a message that accepts a parameter that could be empty. Is there a way to handle the empty parameter case in the message syntax?

`defaultMessage: 'Paid ${total, number, USD} to {vendor}.'`

I want the "vendor" value to be optional, and if the value is not provided, then the message should simply be "Paid ${total, number, USD}."

Can I do this using the message syntax, rather than just creating two separate messages?

**Comment by papasmile** [comment]
It sounds like you could use `select` format with nested arguments, see: https://formatjs.io/guides/message-syntax/#select-format

**Comment by papasmile** [comment]
How about switching on a test for vendor.length?
```
intl.formatMessage({
    id: 'xyz',
    defaultMessage: '{vendorSize, plural, =0 {Paid ${total, number, USD}} other {Paid ${total, number, USD} to {vendor} }',
  },
  { vendor, vendorSize: vendor.length },
);
```

**Comment by lucasriondel** [comment]
@papasmile's solution is working but it is definitely not clean. It could be handled in a much better way without having to add another value to test.

**Comment by longlho** [comment]
Since `Paid ${total, number, USD} to {vendor}.` & `Paid ${total, number, USD}.` are 2 messages you either need to use `select` or make 2 messages
