### ISSUE TITLE
Documentation on React Native

### ISSUE THREAD

**Issue by adrienharnay** [formatjs/react-intl#1081]
Hey,

I managed to get this wonderful package to work with React Native pretty easily, but only because I have been using it with React, know the API, and looked into the issues/PRs. I would like to contribute to the documentation so that newcomers understand that it will work with RN right away (so I am thinking main Readme + documentation).

Any pointers / other suggestions before I do it?

Thanks!

**Comment by serhiipalash** [comment]
Hi @Zephir77167 !
Can you share you setup for React Native?
I always get this bug https://github.com/yahoo/react-intl/issues/371 and I can't find a solution.

**Comment by Zephir77167** [comment]
Hey,

```js
import { Text } from 'react-native';

render() {
    return (
      <IntlProvider
        textComponent={Text}
      >
        {this.props.children}
      </IntlProvider>
    );
  }
```

does it!

**Comment by serhiipalash** [comment]
Hi @Zephir77167 !

No, that is not the best solution. I tested it and you can't pass `style` into `<FormattedMessage />`. Also you can't use `<FormattedMessage />` as the child of `<TouchableOpacity>...</TouchableOpacity>`.

There is library `react-intl-native`. I use its `FormattedMessage` component. With it you can style `<FormattedMessage />`.

And I customized it a little bit to use `<FormattedMessage />` as the child of `<TouchableOpacity>...</TouchableOpacity>`.

My variant

```
import React from 'react'
import PropTypes from 'prop-types'
import { Text } from 'react-native'
import { FormattedMessage } from 'react-intl'

export default class RNFormattedMessage extends React.Component {
  static propTypes = {
    style: PropTypes.any,
  }

  render() {
    return (
      <FormattedMessage {...this.props}>
        {(...nodes) => {
          const newNodes = nodes.map(node => {
            if (!React.isValidElement(node)) {
              return (
                <Text
                  ref={component => (this._root = component)}
                  style={this.props.style}
                >
                  {node}
                </Text>
              )
            }

            return node
          })

          return React.createElement(
            Text,
            {
              style: this.props.style,
              ref: component => (this._root = component),
            },
            ...newNodes
          )
        }}
      </FormattedMessage>
    )
  }

  setNativeProps = nativeProps => {
    this._root.setNativeProps(nativeProps)
  }
}
```

**Comment by Zephir77167** [comment]
For `style`, nested Text inherit styles so what I do is:

```js
<Text style={style}>
  <FormattedMessage />
</Text>
```

(ideally wrapped in a component which directly accepts a `style` props)

And I never encountered the problem with `TouchableOpacity`, but will keep your solution in mind when I do :)

**Comment by serhiipalash** [comment]
> And I never encountered the problem with TouchableOpacity

That is because you always wrap `<FormattedMessage />` in `Text`.
If you will pass `react-intl` `<FormattedMessage />` as a child into `TouchableOpacity`, you will get this error https://github.com/facebook/react-native/issues/1040

**Comment by serhiipalash** [comment]
But my main problem is this one https://github.com/yahoo/react-intl/issues/371
I have to rerender the whole DOM tree on locale change because StackNavigator is PureComponent.
That is very bad approach. Need to find a solution for that.

**Comment by Zephir77167** [comment]
Ah, I see.

**Comment by thcolin** [comment]
> For style, nested Text inherit styles so what I do is:
> 
> ```js
><Text style={style}>
>  <FormattedMessage />
></Text>
>```

Any update on this issue ? 🙏

**Comment by MartinCerny-awin** [comment]
You can use 

`
<Text style={style}>
     {intl.formatMessage(messages.firstScreen)}
</Text>
`

**Comment by ChickenAhn** [comment]
Still work 

`
<Text style={style}>
  <FormattedMessage id={id} />
</Text>
`

Because <Text /> style can be inherited to the child element

**Comment by 39otrebla** [comment]
It seems `FormattedMessage` does not support other react-native components as values. For example, the following code produces only `Hello`, everything after the first `{` gets lost:

```javascript
const messages = {
  "HelloAll": "Hello{all}!"
};

[...]

const allText = <Text>, world</Text>;

[...]

render() {
  return <FormattedMessage id="HelloAll" values={{ all: allText }} />;
}
```

It's quite annoying since we have tons of custom `Text` components to highlight text around the app. 

Does anyone know if there's another way to achieve this in react-native?

**Comment by adrienharnay** [comment]
Hey, I suppose you can't just do `const allText = ', world';`?

What version of react-native are you using?

**Comment by longlho** [comment]
@39otrebla what version of `react-intl` are u using as well?
