### ISSUE TITLE
FormattedMessage

### ISSUE THREAD

**Issue by mirik999** [formatjs/react-intl#1082]
Dear developers, please explain why FormattedMessage some words translate but some words doesnt . I do everything the same way.

**Comment by mirik999** [comment]
solved , i must add 
`function mapStateToProps(state) {
	return {
		lang: state.locale.lang
	}
}`

for every component where i use FormattedMessage, else it doesnt translate.

**Comment by ghostd** [comment]
This is weird, the [IntlProvider component](https://github.com/yahoo/react-intl/wiki/Components#intl-provider-component) should handle the locale (with the react context)
