### ISSUE TITLE
[injectIntl] Flow error: This type is incompatible with 'empty'

### ISSUE THREAD

**Issue by joncursi** [formatjs/react-intl#1086]
When `injectIntl` is used to inject the `intl` prop, I get flow errors on screens that use the component that is doing the injection. Example:

```jsx
type Props = {
  intl: Object,
};

const SomeComponent = (props: Props) => (
  <div />
);

export default injectIntl(SomeComponent);
```

```jsx
// Flow error: props: This type is incompatible with 'empty'. See https://github.com/facebook/flow/blob/v0.62.0/lib/react-intl_v2.x.x.js#L163
const Screen = () => (
  <SomeComponent />
);
```

**Comment by papasmile** [comment]
I don't see that error (w flow 0.63.1, react-intl 2.4.0, react 16.2.0).  But I also don't see your `IntlProvider`, where is it?  eg
```
const Screen = () => (
  <IntlProvider locale='en'><SomeComponent /></IntlProvider>
);
```
https://github.com/yahoo/react-intl#example
https://github.com/yahoo/react-intl/wiki/Components#intlprovider

**Comment by guigonc** [comment]
@joncursi I had the same problem. I saw it was possible to solve it as described in this issue https://github.com/flowtype/flow-typed/issues/1529. Although it didn't sound good, I could see that the possible problem is in the type definition in flow-typed. 

By now I solved it by changing the implementation of our components (which were just a few of them) from functional stateless components to class components. It isn't actually a solution but bought us a time till they merge a PR that fixes the issue.

**Comment by callumlocke** [comment]
We have about 20 of these errors in our codebase since updating either Flow or the react-intl flow-typed definition (or maybe it's a combination of both). We had to go with `$FlowFixMe` suppressions everywhere. I would be really happy to see this fixed.

**Comment by remithomas** [comment]
I got the same issue, my codebase uses `redux` and `react-intl`
I solved it with the using order of HOC, like this

Wrong implementation 
```js
const ConnectedSearchIndividual = connect(mapStateToProps, mapDispatchToProps)(SearchIndividual);
export default injectIntl(ConnectedSearchIndividual);
```

Correct implementation
```js
const SearchIndividualWithI18n = injectIntl(SearchIndividual);
const ConnectedSearchIndividualWithI18n = connect(mapStateToProps, mapDispatchToProps)(SearchIndividualWithI18n);

export default ConnectedSearchIndividualWithI18n;
```

maybe is the same behavior @callumlocke ?
