### ISSUE TITLE
how do you handle fallback for language translation files in react-intl

### ISSUE THREAD

**Issue by ramyajanaki** [formatjs/react-intl#1089]
My index.js 

// If no localeInfo, it is defaulted to en_US
const locale =navigator.language || 'en-US'
const localeData = locale.split('_')[0] || 'en'

// provides a way to register locale data with the library
addLocaleData(require(`react-intl/locale-data/${localeData}`))
//add translations file dynamically from the corresponding JSON file
const messages = require(`./locales/${localeData}`)

### Expected behavior
Is there a fallback mechanism within react-intl that I could use to do the following.
Assuming, i may have translation files as fr_FR.json OR fr.json
Is there a way the application will first looks for fr_FR.json, if it is not available it will go to fr.json and if that is not available, it will fallback to en.json

### Current behavior
The file name should be in a particular format and have to manually import the file that has translations

**Comment by adnux** [comment]
I managed to solve this problem by merging the internationalization files (actually objects as i use a 'flattenMessages' function to work with json) using 'deepmerge' library:

```javascript
import merge from 'deepmerge';
import ptBr from './ptBr';
import esEs from './esEs';
import enUs from './enUs';

export default {
  'pt-BR': ptBr,
  'es-ES': merge.all([ptBr, esEs]),
  'en-US': merge.all([ptBr, enUs])
}
```

**Comment by okovpashko** [comment]
@adnux I managed that in my project with locale aliases and smart locale picker:
```javascript
import uniq from 'uniq';

const SUPPORTED_LOCALES = ['en-US', 'fr-FR'];

const DEFAULT_LOCALE = 'en-US';

const  LOCALE_ALIASES = {
	en: 'en-US',
	'en-GB': 'en-US',
	fr: 'fr-FR',
}

const getBrowserLocales = () => {
  const locales = []
    .concat(
      navigator.languages,
      navigator.language,
      navigator.userLanguage,
      navigator.browserLanguage,
      navigator.systemLanguage
    )
    .filter(locale => locale)
    .map(locale => LOCALE_ALIASES[alias] || locale);

  return uniq(locales, null, true);
};

const pickLocale = (proposedLocales) => {
  const browserLocales = getBrowserLocales();
  let result = null;

  for (let i = 0; i < browserLocales.length && result === null; i++) {
    if (proposedLocales.indexOf(browserLocales[i]) !== -1) {
      result = browserLocales[i];
    }
  }

  if (result === null) {
    result = DEFAULT_LOCALE;
  }

  return result;
};

const localeToUse = pickLocale(supportedLocales);
```

**Comment by briandunnpearson** [comment]
Using the following code to fallback from en-AU (Australian) to default English values.  

`import camelCase from 'lodash/camelCase';

import en from './lang/en.json';
import enAu from './lang/en-AU.json';
const i18n = { en, enAu };

const getMessages = (locale = 'en-US') => {
  const [language] = locale.split('-');
  return Object.assign(i18n[language], i18n[camelCase(locale)]);
};
export default { getMessages };
`

**Comment by briandunnpearson** [comment]
Using the following to fallback from en-AU to en-US:

```javascript
import camelCase from 'lodash/camelCase';

import en from './lang/en.json';
import enAu from './lang/en-AU.json';
const i18n = { en, enAu };

const getMessages = (locale = 'en-US') => {
  const [language] = locale.split('-');
  return Object.assign(i18n[language], i18n[camelCase(locale)]);
};
export default { getMessages };
````

**Comment by chenxiaoyao6228** [comment]
any simpler solutions ?

**Comment by longlho** [comment]
you can use `@formatjs/intl-localematcher` to do locale negotiation

**Comment by loking** [comment]
react-intl doesn't have built-in fallback chains, which means missing keys in fr-CA just show the key string instead of falling back to fr or en. `react-intl-localechain` fills that gap — it deep-merges translations at load time so the resolution works the way you'd expect:

```javascript
import { createLocaleChain } from 'react-intl-localechain';

const chain = createLocaleChain({
  'fr-CA': ['fr-CA', 'fr', 'en'],
  'pt-BR': ['pt-BR', 'pt', 'en'],
});
```

Plugs into your existing react-intl/formatjs setup without changing how you call `intl.formatMessage`.

**Comment by longlho** [comment]
We have intl-localematcher which is also stage 1 in ecma-402
