### ISSUE TITLE
Feature: format time period (distance between dates)

### ISSUE THREAD

**Issue by pdziok** [formatjs/react-intl#1091]
### Is this a BUG REPORT or FEATURE REQUEST? (choose one)
FEATURE REQUEST

### Expected behavior
I'd like to be able to describe time period, or as other use to call it the distance between 2 dates. I'd like to use such a function without referring to the current date or any other point in time.

This would be a somewhat limited scope of what [formatRelative](https://github.com/yahoo/react-intl/wiki/API#formatrelative) is doing - without "N ago" and "in N".

Example:
I have 2 dates (start and end dates for some time period): 2017-07-01 & 2018-01-01. Calling such function I'd expect to get either `6 months` or `half a year`.

### Current behavior
Currently, there's no function that does exactly what I'm asking for. The closest one is [formatRelative](https://github.com/yahoo/react-intl/wiki/API#formatrelative) which is adding reference suffix/prefix to mark whether one of the dates happened in the past or will happen in the future.

### Your Environment
Irrelevant

**Comment by piuccio** [comment]
very similar to #77
