### ISSUE TITLE
`FormattedMessage.shouldComponentUpdate` returns `undefined` in tests

### ISSUE THREAD

**Issue by kroltan** [formatjs/react-intl#1095]
### Is this a BUG REPORT or FEATURE REQUEST? (choose one)
Bug Report

### Expected behavior
Library should respect the React invariants in all environments.

### Current behavior
When run under a test environment (Jest+Enzyme), `FormattedMessage.shouldComponentUpdate` returns `undefined`. This causes React to log the following error message to the console:

    Warning: FormattedMessage.shouldComponentUpdate(): Returned undefined instead of a boolean value. Make sure to return true or false.

It does not seem to cause any other side effects besides spamming the test output console log.

### Step to reproduce for BUG REPORT
 1. Create a `create-react-app`;
 2. Make sure Jest and Enzyme are installed, as well as react-intl;
 3. Set up react-intl, with a component that uses `FormattedMessage`;
 4. In a test, `mount` it.

### Your Environment

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.4.0 |
| `npm ls react` | 16.2.0 |
| `npm --version` | 5.6.0 |
| `node --version` | 6.12.0 |

| OS | Version |
| --- | --- |
| Linux Mint | 18.3 Sylvia |

**Comment by iiison** [comment]
Facing the same issue 😬, I am mocking react-intl(as mentioned [here](https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl#jest-mock)). Getting this error:
```js
console.error node_modules/fbjs/lib/warning.js:33
    Warning: FormattedMessage.shouldComponentUpdate(): Returned undefined instead of a boolean value. Make sure to return true or false.
```

**Comment by jessicabyrne** [comment]
I'm getting a similar thing, but with AgGrid 

`console.error node_modules/fbjs/lib/warning.js:33
      Warning: AgGridReact.shouldComponentUpdate(): Returned undefined instead of a boolean value. Make sure to return true or false.
`

**Comment by otroboe** [comment]
Same issue here with `react@16.4.1` and `react-intl@2.4.0`.

Any workaround ?

**Comment by akinorew** [comment]
I have exactly same issue as @iiison. Any help please?

**Comment by akinorew** [comment]
For now you can hide warnings by mocking console.error like this i.e. in beforeEach:
```
const consoleErrorMock = jest.fn();
const consoleError = console.error;
console.error = consoleErrorMock;

```
and enabling it again in afterEach:
`console.error = consoleError;`

**Comment by akinorew** [comment]
Also a fix is using helpers methods:

```
import React from 'react';
import { IntlProvider, intlShape } from 'react-intl';
import { mount, shallow } from 'enzyme';

const messages = require('src/intl/translations/en-US');

const intlProvider = new IntlProvider({ locale: 'en', messages }, {});
const { intl } = intlProvider.getChildContext();

function nodeWithIntlProp(node) {
	return React.cloneElement(node, { intl });
}

export function shallowWithIntl(node, { context, ...additionalOptions } = {}) {
	return shallow(nodeWithIntlProp(node), {
		context: Object.assign({}, context, { intl }),
		...additionalOptions,
	});
}

export function mountWithIntl(
	node,
	{ context, childContextTypes, ...additionalOptions } = {}
) {
	return mount(nodeWithIntlProp(node), {
		context: Object.assign({}, context, { intl }),
		childContextTypes: Object.assign(
			{},
			{ intl: intlShape },
			childContextTypes
		),
		...additionalOptions,
	});
}
```

But make sure you don't have intl mocked in __mocks__ directory.

**Comment by kozlosoft** [comment]
Good news, everyone. Try this:
`
jest
      .spyOn(<ClassNameFromYourWarning>.prototype, "shouldComponentUpdate")
      .mockImplementation(() => true);
`
ps. jest + enzyme (e.g. when you call wrapper.setProps(...)
