### ISSUE TITLE
Formatted Number displays dollars with added 'US' at the beginning for locales other than en-US

### ISSUE THREAD

**Issue by otajor** [formatjs/react-intl#1096]
### Expected behavior
Dollar values ('USD') should display as `$100.50` for users with both `en-GB` and `en-US` locale.

### Current behavior
Dollars display as `US$100.50` for users with locale `en-GB`. 

### Step to reproduce for BUG REPORT
Use the following code with your locale set to `en-GB`:
```javascript
<FormattedNumber
  minimumFractionDigits={2}
  value={100.50}
  style='currency'
  currency={'USD'}
/>
```
| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.4.0 |
| `npm ls react` | 15.6.2 |

| Browser | Version |
| --- | --- |
| Chrome | 61.0.3163.71 |

**Comment by papasmile** [comment]
Maybe that's a feature request for Intl?  It's not a bug in react-intl, that's just how it works:
```
var number = 100.50;
console.log(new Intl.NumberFormat('en-GB', { style: 'currency', currency: 'USD' }).format(number));
// => US$100.50
```

**Comment by bhishp** [comment]
This is a feature we would be keen for too
