### ISSUE TITLE
How to access nested translations in messages.js?

### ISSUE THREAD

**Issue by ChCosmin** [formatjs/react-intl#1104]
If my messages.js folder has nested messages how do i access them in an id of <FormattedMessage>?

for example this will work
`<FormattedMessage id="homepage.title" defaultMessage="BECOME AN ADVENTURER"/>`
how would i go about getting the ro.nav.dashboard in a formatted message id to be recognized in the nesting?
```
export default {
  en: {
    'nav.dashboard': "Dashboard",
    'nav.characters': "My Characters",
    'nav.languages': "English",
    'nav.welcome': "Welcome {username}",
    'nav.myaccount': "My Account",
    'nav.logout': "Logout",

    'homepage.title': "BECOME AN ADVENTURER",
    'homepage.signup': "JOIN THE PARTY"
  },
  ro: {
    nav: {
      dashboard: "Bord",
      characters: "Caracterele mele",
      languages: "Romana",
      welcome: "Bun venit {username}",
      myaccount: "Contul meu",
      logout: "Delogare"
    },

    'homepage.title': "DEVINO UN AVENTURIER",
    'homepage.signup': "ALĂTURĂ-TE ECHIPEI"
  }
}
```

**Comment by SleepWalker** [comment]
Hi @ChCosmin, the messages must be flat.

If you want to use nested messages, you can create a function, that will convert your nested object into a flat one (e.g. by concatenating keys with dot) and use it before passing `messages` prop into `IntProvider`

**Comment by SleepWalker** [comment]
Here is more detailed info from the migration docs: https://github.com/yahoo/react-intl/wiki/Upgrade-Guide#flatten-messages-object

**Comment by etienne-martin** [comment]
I ended up using this little npm package: https://www.npmjs.com/package/flat

```typescript
import flatten from "flat";

const messages = {
  foo: {
    bar: "yolo"
  }
};

console.log(flatten(messages));

// {
//   "foo.bar": "yolo"
// }
```
