### ISSUE TITLE
addLocaleData fails when adding locales using the spread syntax

### ISSUE THREAD

**Issue by tzfrs** [formatjs/react-intl#1107]
The documentation https://github.com/yahoo/react-intl/wiki#locale-data-in-browsers states that in order to add multiple locales (if not many are used) the preferred way to do that is:

```js
// app.js
import {addLocaleData} from 'react-intl';
import en from 'react-intl/locale-data/en';
import fr from 'react-intl/locale-data/fr';
import es from 'react-intl/locale-data/es';

addLocaleData([...en, ...fr, ...es]);
// ...
```

I now created a class which does this task that can be called from other scripts.

```ts
import {addLocaleData} from 'react-intl';
import de from 'react-intl/locale-data/de';
import en from 'react-intl/locale-data/en';
import fr from 'react-intl/locale-data/fr';
import it from 'react-intl/locale-data/it';
import tr from 'react-intl/locale-data/tr';

export default class LocaleLoader
{
    public static load(): void
    {
        addLocaleData([...de, ...en, ...fr, ...it, ...tr]);
    }
}
````

However, when I use this class somewhere else, compile it and open the page in the browser, the console displays this error: 

> Uncaught TypeError: Cannot read property 'concat' of undefined

for this compiled js.

```js
LocaleLoader.load = function () {
    react_intl_1.addLocaleData(de_1.default.concat(en_1.default, fr_1.default, it_1.default, tr_1.default));
};
```

### Expected behavior
Locales get added without any error.

### Current behavior
Error is thrown when using spread syntax for adding locale data

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.4.0 |
| `npm ls react` | 16.2.0 |
| `npm --version` | 3.10.10 |
| `node --version` | v6.13.0 |

| OS | Version |
| --- | --- |
| Linux Mint | 18.03 (Sylvia) |

| Browser | Version |
| --- | --- |
| Chrome | 64.0.3282.186 |

If needed, I can provide more data, but I think this is the most important info

**Comment by tzfrs** [comment]
I "solved" this by importing the languages as follows

```js
import * as de from 'react-intl/locale-data/de';
import * as en from 'react-intl/locale-data/en';
import * as fr from 'react-intl/locale-data/fr';
import * as it from 'react-intl/locale-data/it';
import * as tr from 'react-intl/locale-data/tr';
```

but I'm still confused because the documentation states to do this differently.

**Comment by papasmile** [comment]
Hi, @tzfrs looks like it might be a polyfill issue... your solution is sound: it is 'safer' to use `*` or `import {default as de}` in general then to rely on default exports.

But it might be useful to post your versions of: babel-cli, babel-polyfill, intl, or any other intl polyfill you use.
