### ISSUE TITLE
formatMessage crashes in production when called with a falsey message id

### ISSUE THREAD

**Issue by sosmo** [formatjs/react-intl#1108]
I'm not sure if this is intended behavior but when you execute

```
intl.formatMessage({id: undefined});
```
in production, an error gets thrown, potentially crashing the app.

```
[React Intl] An `id` must be provided to format a message.
```

This is due to the use of the "invariant" library in the [format.js file](https://github.com/yahoo/react-intl/blob/master/src/format.js#L183). I can see the rationale behind this check but "invariant" doesn't just give you a warning, it crashes the app, even in production. If the check was omitted, `formattedMessage` would return `defaultMessage` or `undefined` and the app could continue the function instead of crashing over a missing message id. It seems to me that using the ["warning" library](https://www.npmjs.com/package/warning) instead of "invariant" would be preferable here. Thoughts?

**Comment by itssumitrai** [comment]
I would totally agree, it should be a warning but not crash the whole app. I have seen the same behavior as well.

**Comment by kristof01** [comment]
Is there any news on this? I'm seeing the same behaviour and it is not desired.

**Comment by akarabach** [comment]
Why ? We need this

**Comment by kydecker** [comment]
+1 to react-intl failing silently rather than crashing the entire app. Just ran into this issue.

**Comment by caseychoiniere** [comment]
For anyone who also finds it maddening that a missing message crashes a production app I've worked around it using a custom React hook. In the following example it returns the ID (descriptor) because in my case the IDs are all fairly human readable but you could also just return an empty string. 

```javascript
function useHumanize() {
  const intl = useIntl();
  return (descriptor, values) => {
    if (!MESSAGES.hasOwnProperty(descriptor)) {
      console.error(`No message configured for '${descriptor}'`);
      return descriptor;
    }
    return intl.formatMessage(MESSAGES[descriptor], values);
  };
}
```

And then use it in your component like so

```javascript
const humanize = useHumanize();

<SubMenu key={category} title={humanize(category)}>
```

**Comment by charlie632** [comment]
I patched the `useIntl` using patch-package and opened an issue: https://github.com/formatjs/formatjs/issues/4323. Hope this helps!
