### ISSUE TITLE
Feature: Message lookup bubbling when using nested IntlProvider

### ISSUE THREAD

**Issue by SleepWalker** [formatjs/react-intl#1109]
When you are nesting `IntlProvider` components, they should allow to use all the available translations inside them.

When you have the following code (examples/nested):

```js
<IntlProvider
    locale={locale}
    messages={messages.app}
>
    <IntlProvider
        locale={locale}
        messages={messages.greeting}
    >
        <div>
            <FormattedMessage
                id="app.title"
                defaultMessage="React Intl Nested Messages Example"
            />
            <FormattedMessage
                id="greeting.welcome_message"
                defaultMessage="Welcome"
            />
        </div>
    </IntlProvider>
</IntlProvider>
```

### Expected behavior

The both `FormattedMessage` should render translation

### Current behavior

`app.title` string is unavailable due to nesting of providers

### Details

To allow backward compatibility, this feature may be implemented as opt-in. E.g.:

```js
<IntlProvider
    locale={locale}
    messages={messages.app}
>
    <IntlProvider
        locale={locale}
        inheritMessages // this flag will instruct provider to merge with parent messages
        messages={messages.greeting}
    >
        <div>
            <FormattedMessage
                id="app.title"
                defaultMessage="React Intl Nested Messages Example"
            />
            <FormattedMessage
                id="greeting.welcome_message"
                defaultMessage="Welcome"
            />
        </div>
    </IntlProvider>
</IntlProvider>
```

**Comment by msluther** [comment]
I would love to see this happen, even if it has to be on an opt-in basis.  It'd be relatively easy to build as an outside component with `IntlProvider` and `injectIntl`, but having first-class support in-library seems like the way to go.  I've seen lots of people get bit by expecting `IntlProvider` to work in the way suggested here.

**Comment by Swaagie** [comment]
Agreed, also due to how the nested example isn't actually using `FormattedMessage` with in `id` that is from the higher order `IntlProvider`, both messages use an `id` that is relative to their parent `IntlProvider`.

**Comment by janitza-trhi** [comment]
@[bmihelac](https://github.com/bmihelac) Thank you for this working snippet.
However we use a version with useMemo. 
Without the hook "useIntl" would change its reference equality a bit too often.
Thus some "useEffect" hooks did unnecessary calls.
```
import React, { useMemo } from "react";
import { useIntl } from "react-intl";

export default function NestedIntlProvider({ messages, children, locale, defaultLocale }): React.ReactElement {
  const intl = useIntl();
  const mergedMessages = useMemo(() => {
    return { ...intl.messages, ...messages };
  }, [intl, messages]);
  return (
    <IntlProvider locale={locale} defaultLocale={defaultLocale} messages={mergedMessages}>
      {children}
    </IntlProvider>
  );
}
```
