### ISSUE TITLE
Feature Request : Expose hasLocaleData

### ISSUE THREAD

**Issue by coderkd10** [formatjs/react-intl#1110]
### Is this a BUG REPORT or FEATURE REQUEST? (choose one)
FEATURE REQUEST

### Feature Request
I want `hasLocaleData` function to be made public.

### Reason
I'm adding locale data dynamically in my component, but to avoid an extra http request I want to check if the locale data (for the given locale) has already been added by some other part of the app (which is outside my control). 
If I get that locale data already been added, I'll not have to make an extra (useless) request to fetch the locale data.

**Comment by longlho** [comment]
Closing since we no longer package custom CLDR
