### ISSUE TITLE
Date Short returns Date Long

### ISSUE THREAD

**Issue by theboyWhoCriedWoolf** [formatjs/react-intl#1111]
Hello,

I am trying to format my dates for Mexican Spanish and keep running into issues.

Setting date short as the format I am still getting the date long format. There seems to be no setting or configuration that I have found that makes it work. I am unsure if its the component or the default Intl behavior, so sorry in advance if its not the component.

The desired result is `5 Apr 2016` but keep getting `5 de abril de 2016`.

I am loading the required json config 
```js
require('react-intl/locale-data/es');
```
But still the result is the same. any attempt to change the date to date short seems to fail.

Thanks in advance

**Comment by okovpashko** [comment]
Looks like this is native **Intl** behavior and **react-intl** can't change it.
Execute this code in the console and you'll see the same result:
```javascript
console.log(new Intl.DateTimeFormat('es-mx', {day: 'numeric', month: 'short', year: 'numeric'}).format(Date.now()));
```

**Comment by papasmile** [comment]
Yea, only difference between short and long is abbreviated month e.g: "29 de mar de 2018" vs "29 de marzo de 2018"

You could still use `formatDate` to create your own display format using abbreviated month
```
const shortMonthString = intl.formatDate(new Date(), { month: 'short' });
console.log(`${day} ${shortMonthString} ${year}`);
```
