### ISSUE TITLE
Question:  Can react-intl read a JSON file using chrome i18n format?

### ISSUE THREAD

**Issue by sergioviniciuss** [formatjs/react-intl#1119]
I am testing the possibility to use react-intl as an i18n tool for my project and I am struggling to find a solution for one of my requirements:

I want to add the possibility to use [transifex](http://transifex.com) as a tool for our translators. In this scenario, I am reading all the messages inside my components and transforming the file into a [chrome i18n JSON file](https://developer.chrome.com/apps/i18n-messages) (The reason why I wanted to use this format is that I can provide some context for each label, making it more clear to our translators).
Then I get this file, upload into transifex and when it's translated, I download it and read it with react-intl, then the problem happens:

> [React Intl] Error formatting message: "app.playing" for locale: "en", using default message as fallback. TypeError: A message must be provided as a String or AST.

For each label I am getting this error, and the problem is that react-intl reads a key-value JSON object, but the format I am providing has this structure:

```
{
  "app.counting": {
    "message": "Ich muss {count, number} {count, plural, one {apfel} other {Äpfel}} kaufen",
    "description": "DESCRIPTION_NOT_PROVIDED"
  },
"localebutton.label": {
    "message": "ändern",
    "description": "DESCRIPTION_NOT_PROVIDED"
  },
  "app.hello_world": {
    "message": "Hallo Welt!",
    "description": "Hello world header greeting"
  },
  "app.playing": {
    "message": "spielen mit intl",
    "description": "just another message test"
  },
  "app.hello_world2": {
    "message": "Hallo Welt 2!",
    "description": "DESCRIPTION_NOT_PROVIDED"
  }
}
```
Any thoughts on how to make react-intl read this chromei18njson files and convert it into labels?

**Comment by danielbigler** [comment]
@sergioviniciuss I think the reason is, that react-intl only accepts flat JSON data. You can try flattening your object before passing it into `IntlProvider`. For more information have a look at the official migration docs [https://github.com/yahoo/react-intl/wiki/Upgrade-Guide#flatten-messages-object](here).

**Comment by danielbigler** [comment]
So flattening the JSON (at runtime) works for you? Or doesn´t it?

**Comment by sergioviniciuss** [comment]
@danielbigler I wanted to avoid this having to write a script for each because I am downloading the translated files from transifex in this format and, if we have many, we'd have to read them all and convert each of them into a flat json file.. so I thought that passing the description to translators didn't worth this effort at least for now

**Comment by papasmile** [comment]
@sergioviniciuss what I noticed is that Chrome format is very close to react-intl message descriptor[1] format.  If you can put your json in a reliable location you could import and convert them at runtime.  For example:

```
import { defineMessages } from 'react-intl';
import my_translations_1 from './my_translations_1.json';
...
const myMessages = {};
Object.keys(my_translations_1).forEach((key) => {
  myMessages[key] = {
    id: key,
    defaultMessage: my_translations_1[key].message,
    description: my_translations_1[key].description,
  };
});
const messages = defineMessages(myMessages);
...
<Button>{intl.formatMessage(messages['localebutton.label'])}</Button>;
```

[1] https://github.com/yahoo/react-intl/wiki/API#definemessages

**Comment by marcin-piela** [comment]
You can check-out source code of this package https://github.com/TheSoftwareHouse/react-packages/tree/master/packages/react-json-translation-provider 
You can create your own provider which do the flattening of json before send it to react-intl provider.

**Comment by Ghevond97** [comment]
Hey @sergioviniciuss  did you find a solution for this issue, I think i am facing something similiar in my code and seems like there is no any obvious answer to this one

**Comment by Nestoro** [comment]
```
export function flattenObject(ob: any) {
	const toReturn = {};

	for (const i in ob) {
		if (!ob.hasOwnProperty(i)) { continue; }

		if ((typeof ob[i]) === 'object') {
			const flatObject = flattenObject(ob[i]);
			for (const x in flatObject) {
				if (!flatObject.hasOwnProperty(x)) { continue; }
				// @ts-ignore
				toReturn[i + '.' + x] = flatObject[x];
			}
		} else {
			// @ts-ignore
			toReturn[i] = ob[i];
		}
	}
	return toReturn;
};
```

@Ghevond97 
i am using this function to flatten the object. then it works.
