### ISSUE TITLE
Can i import multi locale from react-intl/locale-data in destructuring ?

### ISSUE THREAD

**Issue by Xooone47** [formatjs/react-intl#1122]
Hello, now if i wanna import multi locales from react-intl/locale-data, i have to do like this:
```js
import localeEn from 'react-intl/locale-data/en';
import localeZh from 'react-intl/locale-data/zh';
addLocaleData([...localeEn, ...localeZh]);
```

Wondering if i can import in destructuring  like this:
```js
import {en, zh} from 'react-intl/locale-data';
addLocaleData([...en, ...zh]);
```

Sincerely.

**Comment by felipemarinho97** [comment]
This is very useful

**Comment by redonkulus** [comment]
This would require another file in the package to export each of these locales as a named export. Feel free to provide a PR for this if still needed.
