### ISSUE TITLE
moment

### ISSUE THREAD

**Issue by timothyarmes** [formatjs/react-intl#1126]
FEATURE REQUEST

If we pass a moment object as a value to be formatted then it isn't displayed correctly because it's covered to a `Date` first. This strips off timezone information.

It would be nice to detect moments and format them directly instead.

**Comment by StorytellerCZ** [comment]
Just checking, you mean [moment.js](http://momentjs.com/)?

**Comment by timothyarmes** [comment]
Sorry for the lack of precision.

Yes.

**Comment by redonkulus** [comment]
Don't think we want to add direct moment support in this library, would bloat it more than it needs to be.
