### ISSUE TITLE
Get access to locale in components

### ISSUE THREAD

**Issue by sepehr1313** [formatjs/react-intl#1127]
Hi,

Is there any way to get access to **locale** inside of the components? 
I know there is a HOC named **injectIntl**. it sends whole of the intl object but I only need the locale prop.
It would be great if we could get access to the locale via a separate HOC. For example something like **withLocale(MyComponent)**.

**Comment by lexanth** [comment]
If you want to put this in your own project, it would just look something like:
```
import React from 'react'
import { injectIntl } from 'react-intl'

const withLocale = Component => {
  const WrappedComponent = ({ intl, ...props }) => (
    <Component {...props} locale={intl.locale} />
  )
  WrappedComponent.displayName = `withLocale(${Component.displayName ||
    Component.name ||
    'Component'})`
  return injectIntl(WrappedComponent)
}

export default withLocale
```

Otherwise, it would probably be better to wait for an upgrade to the new context API to do this.
