### ISSUE TITLE
defineMessages dynamic keys extraction error

### ISSUE THREAD

**Issue by mtrzesniowski** [formatjs/react-intl#1128]
### Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

### Expected behaviour
Extraction with dynamic keys passes.

### Current behaviour
Error from the terminal:
```
Error transforming file: <FILENAME>.js
SyntaxError: unknown: [React Intl] Messages must be statically evaluate-able for extraction.
```

### Step to reproduce for BUG REPORT
I've set up messages using `defineMessages` with dynamic keys of the object passed as argument of defineMessages.

```
export default defineMessages({
    [SOME_VAR]: {
        id: `${scope}.${SOME_VAR}`,
        defaultMessage: 'Some value',
    },
});
```

### Your Environment
| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | react-intl@2.3.0 |
| `npm ls react` | react@15.6.1 |
| `npm --version` | 6.0.1 |
| `node --version` | 8.11.1 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.13.4 |

Please guide me if I am approaching dynamic keys in a wrong way. Thank you very much for any help!

**Comment by cloakedninjas** [comment]
FWIW I've been looking for some guidance on the same issue and came to the same understanding about the fact keys need to be evaluated statically (i.e. not dynamically at run time)

So I've created self contained files that contain all variations that can be imported into components that need them and use `defineMessages` in order them to be extractable

Example (a product attribute coming from our ecom db has english colour names as keys)

```
// app/translations/colours.js
import {defineMessages} from 'react-intl';

export default defineMessages({
  blue: {
    id: 'colour.blue',
    defaultMessage: 'Blue'
  },
  red: {
    id: 'colour.red',
    defaultMessage: 'Red'
  },
  white: {
    id: 'colour.white',
    defaultMessage: 'White'
  }
});
```

Usage:
```
// app/components/ProductDetail.js

import {injectIntl} from 'react-intl';
import colourTranslations from '../translations/colours';

class ProductDetail extends Component {
  ...
  render() {
    const {colour, intl} = this.props;
    const colourAttr = intl.formatMessage(colourTranslations[colour]);
  }
  ...
}

export default injectIntl(ProductDetail);
```

Would be curious to see if there are other ways of doing this 🤔

**Comment by BramDecuypere** [comment]
I'm seeing this error popping up over the years, now that I've changed my next.js project to a ssr project. I'm also getting this error. While this wasn't an issue in the past. 

I'm using react hooks.

```
function() {
  const { formatMessage, locale } = useIntl();
  
  return (...)
}
```

**Comment by longlho** [comment]
dynamic keys are not extractable since we cannot evaluate js at build time

**Comment by BramDecuypere** [comment]
Thanks for the great response time! Hope you are doing well. My example obviously wasn't clear enough to show what I'm actually meaning. How would you deal with reusable FormattedMessages? Being sure that you have exported all of them?

Then it feels more like a limitation, making sure defaultMessages stay the same.

```
// Component.tsx
....
import { placeholderMessages } from "components/atoms/Form/form.messages";
import { FormattedMessage, useIntl, defineMessages } from "react-intl";
....

const Component = ({}: Props) => {
  const { formatMessage, locale } = useIntl();
  ...
  ....

  return (
     .....
              <Input
                id="email"
                inputLabel={
                  <FormattedMessage id="email" defaultMessage="Email" />
                }
                type="email"
                placeholder={formatMessage({ ...placeholderMessages.email })}
                name="email"
                ref={register}
                errors={errors}
              />
       .... 
  );
};

export default ContactPopup;


// placeholderMessages
import { defineMessages } from "react-intl";

export const placeholderMessages = defineMessages({
....
  firstName: {
    id: "placeholder.firstName",
    defaultMessage: "First name",
  },
....
});

``` 

It's for these cases, that I would like to overwrite that behaviour...

**Comment by longlho** [comment]
I'm not sure I understand your use case. Can you create a new GH issue & put together a minimal repro?
