### ISSUE TITLE
Add sideEffects flag so that webpack v4 can remove code through tree-shaking.

### ISSUE THREAD

**Issue by Ross-Esmond** [formatjs/react-intl#1132]
### Feature Request
Assuming none of the files have any side-effects (messing with localStorage, globals, etc.) add a single line to the package.json. `"sideEffects": false` This will allow webpack v4 with uglify to skip bundling unused files.

**Comment by paolostyle** [comment]
Any thoughts on that? I only use FormattedMessage and IntlProvider, I'm sure I won't need all 13 kB gzipped split between 5 packages.

**Comment by adjourn** [comment]
Are you sure this package is even tree-shakeable right now? I see whole `lib/index.es.js` included to my blundle (it contains whole API and every component) and `"sideEffects": false` has no effect.
