### ISSUE TITLE
How to catch error of missing message 

### ISSUE THREAD

**Issue by ngoctuan001** [formatjs/react-intl#1133]
So basically this is what I am facing : 
```
index.js:2178 [React Intl] Missing message: "app.title" for locale: "en"
index.js:2178 [React Intl] Cannot format message: "app.title", using message id as fallback
```
This is because i want to test what happen if I didn't provide this key in en.json file. However, is there any way for me to console.log some thing more when this error appear. 
Because I want to further notify to the other developers when they facing this problem. For example I want something like this
```
index.js:2178 [React Intl] Missing message: "app.title" for locale: "en"
index.js:2178 [React Intl] Cannot format message: "app.title", using message id as fallback 
(This problem is due to you havent provide the key in en.json)
```

I try using try/catch or componentdidcatch things , but it seems that they cannot catch this error. Anyone have any idea ??

**Comment by papasmile** [comment]
Hi, @ngoctuan001, that error is simply a console log, but nothing is thrown: https://github.com/yahoo/react-intl/blob/master/src/format.js#L219-L222

We also wanted to fail unit tests when messages are missing.  We chose to simply override `console.error` to throw an exception during tests.  We are using Jest, so we put that code in file listed in Jest 'setupFiles' in Jest config:
```
console.error = (message) => {
  throw new Error(message);
};
```

**Comment by ghostd** [comment]
This seems to be a duplicated of #613 (and there is a PR about it: #880 )
