### ISSUE TITLE
Supporting the ability to format date and time without timezone adjustment

### ISSUE THREAD

**Issue by lduros** [formatjs/react-intl#1135]
### FEATURE REQUEST
The ability for <FormattedDate/> and <FormattedTime/> to ignore the Timezone and display the datetime as is, without adjusting for a timezone.

I have date/time strings coming formatted as the following:
2018-01-29T18:50:20.847426+00:00

This obviously includes a timezone, and I'm then using the FormattedTime and FormattedDate components from React Intl to format them, as follows:

    <FormattedDate value="2018-01-29T18:50:20.847426+00:00" />
    <FormattedTime value="2018-01-29T18:50:20.847426+00:00" /> 

While they are properly rendered, a timezone adjustment happens and what is 18:50:20 in terms of time may be displayed as 6:50pm on one server, but 1:50PM on another system, depending on the system's timezone settings, I'm assuming. I would like for these components and their respective functions that format time and date to display the time as it came in regardless of the timezone. That is, 6:50pm, always. I am displaying the timezone in another field, and so adjusting the time and date based on the timezone is confusing in my case. I have not found a good way of doing this reading React-Intl source code so far.

Thanks,

**Comment by aaronleesmith** [comment]
I'm dealing with the same issue right now. In fact, without having the IANA timeZone string available it's impossible to get the date to format into any timezone except local.

**Comment by millette** [comment]
You can pass the prop timeZone='utc' to get the expected behaviour.
