### ISSUE TITLE
How do I handle array of messages?

### ISSUE THREAD

**Issue by artemisIrelia** [formatjs/react-intl#1137]
I have a message type like [{'title':'title1'}, {'title', 'title2'}] that I map to a component.

How do I handle such type of array of messages in react intl? I have referenced this issue:
https://github.com/yahoo/react-intl/issues/1036
But is there a better way I can use array of messages?

**Comment by papasmile** [comment]
Hi, @artemisIrelia, as mentioned in #1104, could it just be an issue of flattening your messages?

If you just have a few messages and don't want to flatten, can you explain what you don't like / want to see that would be 'better' than my example code: https://github.com/yahoo/react-intl/issues/1036#issuecomment-332919754 ?

**Comment by xiaomaini** [comment]
Maybe you have figured it out by now but this might help others. I think you should use defineMessages to make sure your messages are registered correctly. This function will not modify the object you send it, so it will return the same object.

```
import React, {PureComponent} from "react";
import {defineMessages, FormattedMessage} from "react-intl";

export default class ExampleCont extends PureComponent {
  static messages = [
    defineMessages({
      title: {
        id: "example-cont.title-a",
        defaultMessage: "Title a",
      },
    }),
    defineMessages({
      title: {
        id: "example-cont.title-b",
        defaultMessage: "Title b",
      },
    }),
    defineMessages({
      title: {
        id: "example-cont.title-c",
        defaultMessage: "Title c",
      },
    }),
  ];

  render() {
    return (
      <div className="example-cont">
        {ExampleCont.messages.map(message => (
          <h1>
            <FormattedMessage
              {...message.title}
            />
          </h1>
        ))}
      </div>
    );
  }
}
```
