### ISSUE TITLE
Escaping curly braces does not work in production mode if the message has no format parameters

### ISSUE THREAD

**Issue by FabianFrank** [formatjs/react-intl#1158]
### Step to reproduce
Say you have a translations file that contains the following:
```JSON
{
  "example": "The string \\{token\\} is replaced with the actual token."
}
```

And you render this string in your React app like so:
```JS
props.intl.formatMessage({ id: "example" })
```

Then all is well in development mode and the string that gets inserted into the page is
```
The string {token} is replaced with the actual token.
```

However, once you run in production mode (`NODE_ENV === 'production'`), the string gets inserted with the backslash still present and the page renders as follows:
```
The string \{token\} is replaced with the actual token.
```

It looks like the root cause of this bug was introduced in the following commit:
https://github.com/yahoo/react-intl/commit/44168fb883f0419f0ddbbc3c154d127ca3d8c1f3. The relevant snippt is:
```JS
    if (!hasValues && process.env.NODE_ENV === 'production') {
        return message || defaultMessage || id;
    }
```
which skips formatting, which then means the correctly escaped curly is never unescaped.

| Executable | Version |
| ---: | :--- |
| react-intl | 2.4.0 |
| react | 16.4.1 |
| npm | 5.6.0 |
| node | v9.11.2 |

**Comment by daviddooer** [comment]
Any progress on this issue? Got the same problem.

**Comment by gaetano-guerriero** [comment]
I can reproduce this issue with 2.9.0 version. I think it should be reopened.

**Comment by redonkulus** [comment]
@gaetano-guerriero just to be sure, can you verify that this issue still exists in 3.x?

**Comment by gaetano-guerriero** [comment]
Yes, reproduced with 3.0.0-beta6
(anyway are beta7 and beta8 broken ? `addLocaleData` function seems missing)

**Comment by redonkulus** [comment]
Nope, that is part of the migration https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#migrate-to-using-native-intl-apis.

I can re-open this as a bug.
