### ISSUE TITLE
Flow-type cannot resolve module `locale-data`

### ISSUE THREAD

**Issue by remithomas** [formatjs/react-intl#1162]
I using `flow` and I got this strange error when validating.

Error

```bash
Cannot resolve module react-intl/locale-data/en
```

Original code

```js
import en from 'react-intl/locale-data/en'
```

maybe is missing some typing ?

**Comment by odiseo42** [comment]
> import fr from 'react-intl/locale-data/en'

I think you might be using the wrong import (`fr` from `en`). So try:

`import en from 'react-intl/locale-data/en'`

**Comment by alliuca** [comment]
I'm having the same issue myself

**Comment by songva** [comment]
A walk around is to create a custom definition like
```
declare module 'react-intl/locale-data/en' {
    declare module.exports: Array<{ [key: string]: any }>
}
```
