### ISSUE TITLE
Escape &

### ISSUE THREAD

**Issue by Falci** [formatjs/react-intl#1164]
### Is this a BUG REPORT or FEATURE REQUEST? (choose one)
Support request?

### Expected behavior
I have this tranlastion: `&lt;2`. I expect to see `<2`

### Current behavior
I got a `&lt;2` (that's actually: `&amp;lt;2`)

### Your Environment
| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.4.0 |
| `npm ls react` | 16.4.1 |
| `npm --version` | 6.4.0 |
| `node --version` | v8.11.3 |

| OS | Version |
| --- | --- |
| CentOS | 7 |

| Browser | Version |
| --- | --- |
| Chrome | 68.0.3440.106 (Official Build) (64-bit) |

**Comment by Falci** [comment]
No comments?

**Comment by DragonRaider5** [comment]
Lacking which component you use for displaying etc.
Given code is not recognized by JS, just use '<' or `FormattedHTMLMessage` (not recommended).
