### ISSUE TITLE
No space between Currency Code and the number

### ISSUE THREAD

**Issue by abtinr** [formatjs/react-intl#1165]
Feature Request

Expected behavior
There should an space between the currency code and the number when using FormattedNumber, e.g.:

CAD 33.00

Current behavior
Currently this component

<FormattedNumber
   value={33}
   style="currency"
   currencyDisplay="code"
   currency={"CAD}
/>

result in 

CAD33.00

**Comment by ghostd** [comment]
Hi,

This depends on the locale, eg.:
- you'll get a space with [fr-CA](https://github.com/andyearnshaw/Intl.js/blob/master/locale-data/json/fr-CA.json#L277)
- and no one with [en-CA](https://github.com/andyearnshaw/Intl.js/blob/master/locale-data/json/en-CA.json#L281)

**Comment by Trapsta** [comment]
Managed to work around this using `Intl.NumberFormat formatToParts`. Check this out [Intl.NumberFormat formatToParts](https://codesandbox.io/s/intlnumberformat-formattoparts-yp3ce) .  Thanks to [this answer ](https://stackoverflow.com/a/54660725/5480444)
