### ISSUE TITLE
Can I bind JSON with localization directly to a component?

### ISSUE THREAD

**Issue by egor-a-trubnikov-panov** [formatjs/react-intl#1167]
Can I bind JSON with localization directly to a component? I need each component to have its own translation file. But language switching will be in the main Provider. I don't want to have one translation file for the whole application. Can I implement this with react-intl?

**Comment by papasmile** [comment]
Hi, @egor-a-trubnikov-panov, sounds like you might be able to use nested IntlProvider's: https://github.com/yahoo/react-intl/wiki/Components#multiple-intl-contexts

Also see that issue for prior discussion: https://github.com/yahoo/react-intl/issues/720

Hope that helps!
