### ISSUE TITLE
Get date format DD/MM/YYYY for french local

### ISSUE THREAD

**Issue by KrifaYounes** [formatjs/react-intl#1172]
It's possible to get date for french local with format DD/MM/YYYY
Currently I get this 2018-03-18   (YYYY-MM-DD)

Format YYYY-MM-DD is not correct for french local 
The best format is DD-MM-YYYY or DD/MM/YYYY for french localization

Thanks

**Comment by papasmile** [comment]
Hi, @KrifaYounes, can you post your code?  By default, you should get with `Intl` gets.
```
console.log(new Intl.DateTimeFormat('fr').format(new Date(Date.UTC(2012, 11, 20, 3, 0, 0))));
\\ => 19/12/2012
```
https://jsfiddle.net/Lgj9bdzy/
