### ISSUE TITLE
FormattedRelative uses componentWillReceiveProps which is now deprecated

### ISSUE THREAD

**Issue by ssylvia** [formatjs/react-intl#1183]
### Is this a BUG REPORT or FEATURE REQUEST? (choose one)
FEATURE REQUEST

If this is a FEATURE REQUEST, please:

  - `FormattedRelative` component uses the now deprecated `componentWillReceiveProps`. Update to use `getDerivedStateFromProps`.

https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#updating-state-based-on-props

App will throw error messages in console when using `StrictMode`.

**Comment by DragonRaider5** [comment]
This will be fixed with #1186 :)

**Comment by leoyli** [comment]
I guess this issue should be then closed?

**Comment by redonkulus** [comment]
Yup, but it was actually fixed by #1273

**Comment by fletcher91** [comment]
This bug was reintroduced in https://github.com/formatjs/react-intl/pull/1338 (here: https://github.com/formatjs/react-intl/pull/1338/files#diff-2e0ecf2005c172369b1d5ac594673b91L134)

**Comment by longlho** [comment]
Thanks we'll investigate

**Comment by longlho** [comment]
fixed in 964159ba144cf872ee8c19525da887f42ed65801
