### ISSUE TITLE
(Question) Using react-intl with react portal

### ISSUE THREAD

**Issue by GersonDias** [formatjs/react-intl#1192]
There are plenty of libraries that use the react portal to create their functionalities. I'm using some of them in my project, like React-Contextify and react-confirm-alert and I receive the message 

```[React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.``` 

What is the best way to deal with that?

**Comment by DragonRaider5** [comment]
Hm, good question. My PR #1186 might fix this by utilizing the new context API.
However I'm not sure about that one. I'd suggest waiting for it being merged and trying whether it's fixed by that.

**Comment by sergioviniciuss** [comment]
Wouldn't that be the case of using the imperative api to provide the intl object? like it's being suggested here: https://github.com/yahoo/react-intl/issues/416
