### ISSUE TITLE
How to render a list of formatted messages using React-Intl

### ISSUE THREAD

**Issue by Nastromo** [formatjs/react-intl#1197]
I have a navigation with standard items like: contact, services, prices, etc... I render it like this:

```
const menuItemList = menuItems.map((item, index) => {
            return (
                <li key={index}>
                    <NavLink to={item.url}>{item.title}</NavLink>
                </li>
            );
        });
```
It works fine. But now I need to translate this navigation and I use react-intl library for this purpose. Accordingly to react-intl doc I have to use FormattedMessage like this:

```
<p>
   <FormattedMessage id="mainText"/>
</p> 
```
It works. But how I can use it for list rendering? I think it would work with this, but it doesn't.

```
const menuItemsList = menuItems.map((item, index) => {
            return (
                <li key={index}>
                    <NavLink to={item.url}>
                        <FormattedMessage id="mainText" values={item.title}/>
                    </NavLink>
                </li>
        );
});
```
Guys, help please. How to render list with items in React using FormattedMessage from react-intl?

**Comment by redonkulus** [comment]
@Nastromo That should work, can you put your code in a codesandbox so we can see it in action?
