### ISSUE TITLE
formatMessage does not update config (bound args) when IntlProvider updates locale

### ISSUE THREAD

**Issue by dtodo1paco** [formatjs/react-intl#1198]
### Is this a BUG REPORT or FEATURE REQUEST? (choose one)
BUG REPORT

### Expected behavior

When I change locale in IntlProvider all FormattedMessage updates correctly, but where formatMessage method is used, the locale is not updated. I expect the config element of formatMessage to be updated accordingly or at least, formatMessage to accept a locale argument to force the change.

### Current behavior

When I change locale in IntlProvider all FormattedMessage updates correctly, but where formatMessage method is used, the locale is not updated. Even if I update manually nextProps.intl.locale in componentWillReceiveProps the formatMessage method has the same config (with old locale).

![formatmessage_bug](https://user-images.githubusercontent.com/3096057/46759422-aa2a5e00-cccf-11e8-836a-f23c5755804e.png)

### Step to reproduce for BUG REPORT

Bind the locale of IntlProvider to redux-store.
```
      <IntlProvider
        locale={this.props.locale}
        messages={this.props.messages[this.props.locale]}
      >
        {React.Children.only(this.props.children)}
      </IntlProvider>
```
 It is important not to use the key prop to avoid re-mount of whole app (for performance reasons).  When I set the key prop, formatMessage gets the correct locale in its config

### Your Environment

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.4.0 |
| `npm ls react` | 16.4.1 |
| `npm --version` | 6.4.1 |
| `node --version` | 8.11.4 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| Ubuntu | 16.10 |

| Browser | Version |
| --- | --- |
| NAME | VERSION |
| Chrome | 61.0.3163.71 |

Sorry if I missed something, but I really think it's a bug.
Thanks

**Comment by dtodo1paco** [comment]
> its probably by design based on
> https://github.com/yahoo/react-intl/wiki/Components#dynamic-language-selection

But this will throw a unmount/mount on children, which I want to avoid. Is there any workaround ?

**Comment by dtodo1paco** [comment]
Ok, I ended up avoiding the use of formatMessage to build my Options for Select field because it allows the use of <span> inside

```
<option value={key}>
  <FormattedMessage {...messages[key]} />
</option>
```

Anyway, the bug still remains. If I needed the plain text translation, I couldn't get it as the docs says. Can I ?

**Comment by 1069080359** [comment]
![2018-12-05 4 35 21](https://user-images.githubusercontent.com/38374326/50334059-1502db80-0542-11e9-9764-584b96792e36.png)
How about this
