### ISSUE TITLE
(Question) Switch language without Redex

### ISSUE THREAD

**Issue by CMonjo** [formatjs/react-intl#1200]
Hey !

I'm using react-intl since one week and it's working fine, I detect the user's language thanks to his browser. However I would like to be able to have buttons to be able to change the language, knowing that it is a small site I do not try to use Redux, however I can not find the way to change the language without using Redux. I use cookies to save the language and it works. I would have liked to know how to change the language once in my components ?

I thank you in advance !

**Comment by redonkulus** [comment]
@CMonjo try taking a look at this doc, https://github.com/yahoo/react-intl/wiki/Components#dynamic-language-selection, does this help you?

**Comment by ptomasroos** [comment]
@CMonjo what @redonkulus said above is what we're using to define languages from a user selection instead of relying on the browser locale just
