### ISSUE TITLE
FACC pattern does not render jsx

### ISSUE THREAD

**Issue by anwaukoni** [formatjs/react-intl#1204]
### BUG REPORT
When I use the FACC pattern suggested in your docs to render my localized component, the `values` prop does not render jsx, but renders strings.

### Expected behavior
```
<FormattedMessage
        id='alerts.closingGreeting'
        defaultMessage='Best Regards, {signature}'
        values={{
          signature: <strong><br/> Support Team</strong>
        }}
      >
        { formattedMessage => 
          <div>{ formattedMessage }</div>
        }
</FormattedMessage>

// Expect to see
<div>
    Best Regards,
    <strong>
         <br>
          Support Team
     <strong>
</div>
```

### Current behavior
Instead I see:
```
<div>
    Best Regards,
</div>
```
However when I change the `signature` to a string everything is fine:

```
<FormattedMessage
        id='alerts.closingGreeting'
        defaultMessage='Best Regards, {signature}'
        values={{
          signature: ' Support Team'
        }}
      >
        { formattedMessage => 
          <div>{ formattedMessage }</div>
        }
</FormattedMessage>


// I see
<div>
    Best Regards,  Support Team
</div>

```
The above is not very helpful as I would like to be able to style the `values` property.

### Step to reproduce for BUG REPORT

https://jsfiddle.net/b1yfovL6/

**Comment by anwaukoni** [comment]
Just wondering if there are any thoughts on this issue?

**Comment by anwaukoni** [comment]
Ok, I guess that is how they have made it work. It either supports rich text formatting or the Function as a child component pattern. But not both at the same time. However, it would have been helpful if it supported both.

**Comment by xzyfer** [comment]
This is a really unfortunately disparity. Are y'all open to a patch to fix this?

**Comment by DragonRaider5** [comment]
Have you considered `formattedMessage` being an array?

**Comment by roy-bakker-new10** [comment]
Still an issue for me as well, any plans to fix this?

**Comment by roy-bakker-new10** [comment]
Still an issue for me as well, any plans to fix this?

**Comment by DragonRaider5** [comment]
@roy-bakker-new10 for this use-case I'd advise you to use the `textComponent` prop on your `FormattedMessage` instead of using the FACC pattern :+1:

**Comment by DragonRaider5** [comment]
@anwaukoni

JSX needs to be split from text for rendering purposes.
To properly render JSX do the following:
```js
<FormattedMessage {...message} values={values}>
  {(...chunks) => (
    <div>
      { chunks.map((Chunk, id) => <Chunk key={id} />) }
    </div>
</FormattedMessage>
```
