### ISSUE TITLE
Feature idea: use error boundaries to avoid crashing whole app

### ISSUE THREAD

**Issue by bensventures** [formatjs/react-intl#1207]
### Expected behavior
When a message is missing a variable or the id supplied is wrong, the message is not formatted correctly but the rest of the app still works as expected

### Current behavior
Errors in react-intl components bubble up in the tree and can crash entire sections of the app or the whole page if no error boundaries have been set.

I really like this package but I have some problem with the way error are handled. It happened more than once that my whole app crashed because a single FormattedMessage component was missing a variable or because the message id was missing.

Since React 16, an error in any component unmounts the entire tree until it reaches an ErrorBoundary component. I am wondering if we could avoid a lot of major crashed by wrapping all the component provided by react-intl in ErrorBoundaries. This way the single component would crash but the rest of the app would carry on working.

What do we think about this? Is this something that has been discussed already? I'd happily work on a PR if this is something that sounds like a good option.

Here is the relevant doc: https://reactjs.org/docs/error-boundaries.html

**Comment by redonkulus** [comment]
@bensventures Whats the performance cost of adding an error boundary for every react intl component? Seems like it wouldn't be efficient. I would prefer that apps manage this higher up, since the tree for FormattedMessage is quite small.

**Comment by bensventures** [comment]
Good question, I've done a quick benchmark with React DevTools, rendering 200 elements on a blank page. Here is the breakdown:

<img width="352" alt="Screenshot 2019-05-15 at 08 38 14" src="https://user-images.githubusercontent.com/913081/57754381-95db9300-76ee-11e9-98b9-03969bdccfe7.png">
<img width="352" alt="Screenshot 2019-05-15 at 08 43 50" src="https://user-images.githubusercontent.com/913081/57754382-95db9300-76ee-11e9-8db9-26b52ddd815a.png">

The first screenshot is the default component from `react-intl`, the second is a component wrapping FormattedMessage and including an error boundary. See code [here](https://gist.github.com/bensventures/7e87fbd8a843cf5aeaaa4cdf08bda2ff)

So yeah, there is a slight performance drop, not sure if it is significant or not tbh. I'm happily using my modified version in a project since a few month. I did first try to place an error boundary higher up in the tree but I was still getting some big chunks of app dropped on some occasions.

**Comment by redonkulus** [comment]
Thanks for digging in. I would prefer to keep this in user land, rather than add the error boundary from within the low level components. Thanks!
