### ISSUE TITLE
FormattedNumber: Legacy context API

### ISSUE THREAD

**Issue by juergenzimmermann** [formatjs/react-intl#1209]
I'm using version 2.7.2 and get the following message in Chrome DevTools:
![grafik](https://user-images.githubusercontent.com/734334/47912982-ad61d580-de9a-11e8-8ad1-53f69fcb9f1a.png)

**Comment by iamstarkov** [comment]
its not about FormattedNumber

**Comment by iamstarkov** [comment]
old context is being deprecated since 16.6 https://reactjs.org/blog/2018/10/23/react-v-16-6.html#deprecations-in-strictmode

**Comment by redonkulus** [comment]
Closing this as https://github.com/formatjs/react-intl/pull/1186 was merged.
