### ISSUE TITLE
Any plans to use forwardRef with injectIntl?

### ISSUE THREAD

**Issue by esellin** [formatjs/react-intl#1211]
Currently, If I use injectIntl(), I need to call getWrappedInstance() to access the wrapped instance.

It would be much easier if I could just assign a ref, and that ref would transparently be forwarded to the wrapped instance, so I ended up writing the HOC below.

Any plans to support this in a future version of react-intl, or have I lost the plot?

```
function withIntl(Component) {
  class Wrapper extends React.Component {
    render() {
      const {innerRef, ...props} = this.props;
      return (
        <Component
          ref={innerRef}
          {...props} />
      );
    }
  };
  const IntlWrapper = injectIntl(Wrapper);
  return forwardRef((props, ref) => (
    <IntlWrapper {...props} innerRef={ref} />
  ));
};
```

**Comment by DragonRaider5** [comment]
This would drop support for older `react` versions...

**Comment by antoinerousseau** [comment]
that's what semver is for

**Comment by HauptmannEck** [comment]
I would like to revive this issue, as I just ran into this in my project. Trying to add `react-intl` is currently not possible, or at least not obvious on how to, if we use with the new ref api.
