### ISSUE TITLE
Wrong work with plural forms.

### ISSUE THREAD

**Issue by shown24** [formatjs/react-intl#1218]
### Expected behavior

I use this library for plural form for Russian language. Russian language has this plural formula((n%10==1 && n%100!=11 ? 0 : n%10 >= 2 && n%10<=4 &&(n%100<10||n%100 >= 20)? 1 : 2)) and I must see this result for numbers for example: 1 яблоко(1,21,31), 2 яблока(22,23,24), 0, яблок (5-20,25,26,27,28,29,30)

### Current behavior

Current behavior is different and I can`t inmplement this rule (n%10==1 && n%100!=11 ? 0 : n%10 >= 2 && n%10<=4 &&(n%100<10||n%100 >= 20)? 1 : 2)

### Step to reproduce for BUG REPORT

You can reproduce it in any environment. Try only implement this rule for language that has more then 2 plural cases? for example Russian

### Your Environment

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.7.2 |
| `npm ls react` | 16.6.0 |
| `npm --version` | 6.4.1 |
| `node --version` | 10.13.0 |

| OS | Version |
| --- | --- |
| Windows | 10 |

| Browser | Version |
| --- | --- |
| Chrome | 70.0.3538.110 |

**Comment by shown24** [comment]
I try to use this string for example: "Hello {name}, you have {unreadCount, number} {unreadCount, plural, one {message} other {messages}}". This is for English, but in Russian i use this: "Привет {name}, у вас {unreadCount, number} {unreadCount, plural, one {сообщение} few {сообщения} many {сообщений} other {сообщения}}"

**Comment by justintemps** [comment]
I'm also having this problem.

**Comment by papasmile** [comment]
Hi, @shown24 , it seems CLDR defines those rules, including 22 as 'few': http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html#ru

I have no knowledge of Russian but if you feel that's wrong there are instructions for logging a bug over there: http://cldr.unicode.org/index/cldr-spec/plural-rules#TOC-Reporting-Defects

**Comment by shown24** [comment]
You can see this
http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html
and
https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html.

ср, 29 мая 2019 г. в 16:49, papasmile <notifications@github.com>:

**Comment by l3v1k** [comment]
My problem was with  <FormattedMessage defaultMessage="{someCount, plural, ...}"/>
You need to set defaultLocale on IntlProvider to your locale ("ru" in my case), after that defaultMessages will pluralize with defaultLocale :)
