### ISSUE TITLE
Documentation around `injectIntl` and refs

### ISSUE THREAD

**Issue by LucaColonnello** [formatjs/react-intl#1220]
There's no documentation around the `injectIntl` `withRef` option.
After digging in the docs, the only document mentioning how to use it is the following:
https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl#dom-rendering

The problem with this is that a recent commit changed the internal variable from `this.refs.wrappedInstance` to be `this._wrappedInstance`.

https://github.com/yahoo/react-intl/commit/1c5afd236e99bdb22ed253612ca2ffde21feaacf

The commit says that it's not a breaking change, but since the doc is telling people to use the internal var, this should be a breaking change...

I suggest updating the doc referring to the `getWrappedInstance` method already exposed by the injector and then implement `forwardRef` as suggested here https://github.com/yahoo/react-intl/issues/1211 as a breaking change.

Happy to contribute if no one can pick this up! :)

**Comment by redonkulus** [comment]
@LucaColonnello @antoinerousseau  You can follow https://github.com/formatjs/react-intl/pull/1271 which will fix this issue.

**Comment by papasmile** [comment]
Is this issue closed now?

**Comment by redonkulus** [comment]
Yup closing.
