### ISSUE TITLE
[QUESTION] How to split locale file in Next.js?

### ISSUE THREAD

**Issue by applebaum** [formatjs/react-intl#1223]
Loading single giant locale file is creating bloated HTML and potentially harmful for SEO, so I'd like to split the locale file to only serve the strings used on the active page.
I've found this [example of nested <IntlProvider> instances](https://github.com/yahoo/react-intl/tree/master/examples/nested), however its unclear how to apply the same logic to the [Next.js integration](https://github.com/zeit/next.js/tree/canary/examples/with-react-intl).
Has anyone successfully accomplished locale splitting with Next.js?

**Comment by pristas-peter** [comment]
Hi, I haven't used next.js, but I wrote this webpack plugin for my personal use to code-split translations. You can have a look here, maybe it helps.

https://github.com/pristas-peter/react-webpack-utils/tree/master/packages/react-intl-extract-webpack-plugin
