### ISSUE TITLE
(Question)Dynamically importing locales on non component script without using import

### ISSUE THREAD

**Issue by sergioviniciuss** [formatjs/react-intl#1225]
### BUG REPORT
I have an 'external' intl provider because I have to handle some labels outside react components.
I am trying to dynamically load the locales without using  `require` statements and I am having a issue I am not sure why it's happening.
So, the following code works:

```javascript 
//intlProvider.js
import { IntlProvider, addLocaleData } from 'react-intl';
import Locale from '../../../../utils/locale';

const locale = Locale.getLocale();
addLocaleData(require(`react-intl/locale-data/${locale}`));
const messages = Locale.getMessages('prot');
const intlProvider = new IntlProvider({ locale, messages });
const { intl } = intlProvider.getChildContext();

export default intl;
```

then I read the intl in a sharedMessages.js file:
``` javascript
import { defineMessages } from 'react-intl';
import intl from '../components/i18n/Intl';

const messages = defineMessages({
  interest: {
    id: 'sharedMessages.rate.label',
    defaultMessage: 'Interest',
  },
  bank: {
    id: 'sharedMessages.bank.label',
    defaultMessage: 'Bank',
  },
});
function prepareSharedMessages() {
  const msgsObj = {};
  Object.keys(messages).forEach(item => {
    msgsObj[item] = intl.formatMessage(messages[item]);
  });
  return msgsObj;
}
const sharedMessages = prepareSharedMessages();

export default sharedMessages;
```
The above code works fine, but since I want to get rid of the `require` statement in this line: 
```javascript
addLocaleData(require(`react-intl/locale-data/${locale}`));
```
I tryed to replace it for: 
```javascript
(async localeCode => {
  const localeData = await import(`react-intl/locale-data/${localeCode}`);
  addLocaleData(localeData.default);
})(locale);
```

### Expected behavior
I'd expect the locale to be loaded properly, but apparently the application is trying to get it before it should. Since I am using async/await, I'd expect it to be set before the rest of the application tries to use it. (If it was inside react components, I could use componentDidMount to trigger the locale, but how can I achieve this behavior for non react components?)

### Current behavior
After replacing the require for the import statement above mentioned, I am getting the **react-intl warning:** [React Intl] Missing locale data for locale: "de". Using default locale: "en" as fallback.

### Step to reproduce for BUG REPORT
Use of async/await to dynamically import the locales on addLocaleData

### Your Environment

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.7.0 |
| `npm ls react` | 16.0.0 |
| `npm --version` | 6.2.0 |
| `node --version` | 9.10.0 |

| OS | Version |
| ---: | :--- |
| macOS Mojave | 10.14 |

| Browser | Version |
| :--- | :--- |
| Chrome | 71.0.3578.98 (Official Build) (64-bit) |

**Comment by DragonRaider5** [comment]
Actually this looks like your locale is set to `de` and you don't provide translations for it (hence falling back to your default strings in English).

However based on your code this issue is, that you load the locale data asynchronously. While you do so, the rest of your code gets executed in parallel (due to your use of an asynchronous IIFE) which results in you `new IntlProvider()` getting executed before the locale data is loaded.

As `IntlProvider` checks for the required locale data in its constructor, it generates a warning.

**Comment by sergioviniciuss** [comment]
You're right @DragonRaider5 . The problem is that `require` is synchronous while `import`s are asynchronous and if I want to use the `import`, I have to big changes in other areas to make my code async. With this code I showed, as you mentioned, the locale was async so it's not there when the app tries to reach it, then I get the warning and the app defaults to english.

**Comment by yanickrochon** [comment]
The problem is that `const localeData = await import(`react-intl/locale-data/${localeCode}`);` does not work well with bundling managers.

**Comment by sergioviniciuss** [comment]
@yanickrochon could you explain more? I'm very interested in this topic. What are the biggest issues you're aware of?

**Comment by yanickrochon** [comment]
@sergioviniciuss for example, MeteorJS parse all imports in the source files to build a dependency graph of all modules. So, when the app starts, a main bundle is downloaded, including all ES modules. Then, other bundles are created from the asynchronously imported modules. Meteor comes with a [bundle-visualizer](https://docs.meteor.com/packages/bundle-visualizer.html) tool to see the size of the initial bundle, and any subsequent bundle sizes.

**Comment by DragonRaider5** [comment]
@yanickrochon if that was the problem, shouldn't the `import` statement completely fail?
@sergioviniciuss have you tried printing the content of your imported file after importing it?

**Comment by sergioviniciuss** [comment]
@DragonRaider5 at the end we had to do way more changes and reimplement almost the entire solution, with a new HOC to load the messages on demand. The issue @yanickrochon mentioned I am not aware, but I was also using a bundle analyzer tool in my project (this is actually how I noticed that dynamically loading the locales with `require` ( addLocaleData(require(`react-intl/locale-data/${locale}`));)  was increasing my bundle and was not a good idea).

**Comment by pristas-peter** [comment]
I wrote this webpack plugin for my personal use to code-split translations. You can have a look here, maybe it helps.

https://github.com/pristas-peter/react-webpack-utils/tree/master/packages/react-intl-extract-webpack-plugin

**Comment by DragonRaider5** [comment]
@sergioviniciuss can this issue be considered resolved?
