### ISSUE TITLE
Creating intlStore (?) outside the provider

### ISSUE THREAD

**Issue by Ancinek** [formatjs/react-intl#1227]
Currently to access the translated messages and the methods I need to create some kind of workaround described in one of the issues if this repo. Would it be possible to create the instance of the translations before actually providing it to the provider? 

We all know the that it's pretty useful to access redux store outside the react components, and we can do it just be simple exporting the store created with `createStore()`.

For me it would be a big improvement if I could do something like:
```javascript
export const intl = createIntl();
``` 
and then use a code like below anywhere in my code:
```javascript
import { intl } from 'My/Intl/Path';
intl.formatMessage(...)
```

Would love to hear some opinion on this :)
BTW: Love this project! ❤️

**Comment by wereHamster** [comment]
I'm in favour of that. I've been in a situation many times where I needed to access the intl store outside of the provider, for example in tests, or when I wanted to use the same intl code and translations outside of a react context (eg. a small command line tool that's developed alongside my react application).

**Comment by DragonRaider5** [comment]
In the new version (see PR #1186) this should be possible as follows (not tested, I developed it though):

`intl.js`
```javascript
import { IntlProvider } from 'react-intl'

export default new InltProvider(/* your translations etc. */)
```

`translator.js`
```javascript
import intl from './intl.js'

const translation = intl.getContext().formatMessage(...)
console.log(translation)
```

**Comment by wereHamster** [comment]
Constructors don't automatically invoke any (static) methods. It looks like your PR is still open, it would be nice if that PR could be merged so we can build this–and other–features on top of it.

**Comment by DragonRaider5** [comment]
I know that they don't - but I don't exactly know what's inside `React.Component`. That's why I don't know :)
