### ISSUE TITLE
Supporting own format functions

### ISSUE THREAD

**Issue by Ancinek** [formatjs/react-intl#1231]
We currently can define variables inside the message strings like it is described [here](https://formatjs.io/guides/message-syntax/#custom-formats).

Is there also a possibility to define a custom format that will take in the supplied value and return the formatted value we need? I have German/English app in the development and there are differences in in the sentences - in German I need to have them capitalized.

I've tried things like this for a message (`example {record, string, lowercase}`) but it did not worked:
```javascript
const formats = {
  string: {
    lowercase: (v) => {
      return v.toLowercase();
    },
  },
};
```

**Comment by papasmile** [comment]
Hi, @Ancinek React JS (and Format JS) are built on top of ICU Message syntax (http://userguide.icu-project.org/formatparse/messages) which does not use functional programming but rather it essentially uses patterns and tokenizers.

Is there a problem with parsing output of `formatMessage()` perhaps using a custom function?

e.g.
```
const withPostProcess = (intl, message) => {
  const formatted = intl.formatMessage(message);
  return formatted && 'de' === intl.locale ? formatted.toLowercase() : formatted;
}
...
render() {
<div>
  <span>{{ withPostProcess(intl, messages.helloMessage) }}</span>
</div>
}
```

**Comment by septs** [comment]
locale.yaml
```yaml
example: "example {record, string, lowercase}"
```

react code
```html
<FormattedText id="example" values={{ record: "SAMPLE" }} /> 
```
rendered html
```
<span>sample</span>
```

**Comment by longlho** [comment]
I'm closing this since it's not supported in ICU spec. The workaround would be to tokenize the var & pass it in
