### ISSUE TITLE
adding markup to values breaks string

### ISSUE THREAD

**Issue by cezarneaga** [formatjs/react-intl#1233]
hi everyone, 

i am having a problem: 

given 
```
{!this.state.isLoading && (
  <FormattedMessage
    id='databases.titleSingle',
    defaultMessage={`Database {dbName}`},
    values={{
     dbName: (
      <span className="txtcolor--tolerance">
        {this.state.name}
      </span>
     ),
   }}>
     {(title: string) => (
       <Layout title={title}>hello</Layout>
     )}
  </FormattedMessage>
)}
```
i only get "Database " as replacement for `title`

if instead i remove the markup in the `values.dbName`

```
{!this.state.isLoading && (
  <FormattedMessage
    id='databases.titleSingle',
    defaultMessage={`Database {dbName}`},
    values={{
     dbName: this.state.name
   }}>
     {(title: string) => (
       <Layout title={title}>hello</Layout>
     )}
  </FormattedMessage>
)}
```
`title` is correctly shown as `Database wordpress`

more so, this seems to be very inconsistent as some other times the first case in another place in the codebase works as expected. 

i use state to provide value but the same is valid if dbName is a string.

### Environment

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.7.2 |
| `npm ls react` | 16.7.0 |
| `npm --version` | 6.4.1 |
| `node --version` | v8.14.0 |

| OS | Version |
| --- | --- |
| Debian | 8 |

| Browser | Version |
| --- | --- |
| NAME | VERSION |

| Firefox | 65.0b10 |

any help appreciated, 
Cezar

**Comment by kaldebert** [comment]
Same issue:

**Given:**
```
const currentDate = new Date();
...
<FormattedMessage
  id="dashboard.accounts.card.title.date"
  defaultMessage="on {date}"
  values={{
    date: <FormattedDate value={currentDate} />
  }}>
    {formattedMessage => (
      <span className={styles.headerTitleDate}>{formattedMessage}</span>
    )}
</FormattedMessage>
```

**Output:**
> on 

**Expected:**
> on 01/01/2019

**This works:**
```
const currentDate = new Date();
...
<FormattedMessage
  id="dashboard.accounts.card.title.date"
  defaultMessage="on {date}"
  values={{
    date: currentDate
  }}>
    {formattedMessage => (
      <span className={styles.headerTitleDate}>{formattedMessage}</span>
    )}
</FormattedMessage>
```

Package | Version
------------ | -------------
react | 16.7.0
react-intl | 2.8.0
node | 10.13.0
npm | 6.6.0
