### ISSUE TITLE
Option to ignore hydration warnings

### ISSUE THREAD

**Issue by eliseumds** [formatjs/react-intl#1234]
### Keywords

mismatch, hydration, ssr, server, discrepancy, suppressHydrationWarning

### Is this a BUG REPORT or FEATURE REQUEST?

This is a feature request.

### Expected behavior

I'd like to be able to tell the library that I don't care about differences between the server and the client. We're currently loading a big Intl polyfill to make them work exactly the same but I don't think it's really necessary. For example, this is what I get with (en-AU MacOS):

* Node v11.6.0: 2 Mar 2018
* Chrome 71: 2 Mar. 2018

Just one dot, not a big deal. It doesn't cause any big flash while the page loads. Not loading the polyfill would save us about 30KB.

Docs related to the React prop *suppressHydrationWarning* can be found at https://reactjs.org/docs/react-dom.html

**Comment by redonkulus** [comment]
@eliseumds Have you tried adding `suppressHydrationWarning` to the react intl component? If so, what happens?

**Comment by eliseumds** [comment]
@redonkulus I believe [lean-intl](https://github.com/sebastian-software/lean-intl) fixed the inconsistency.

**Comment by redonkulus** [comment]
@eliseumds can you provide a link to the code that fixed it?

**Comment by eliseumds** [comment]
@redonkulus oh, I think it's unrelated to lean-intl, actually. We're now loading the polyfill on both the client and the server, so that's why there are no mismatches.

**Comment by redonkulus** [comment]
Ok makes sense.

**Comment by ericklarsen** [comment]
> @eliseumds Have you tried adding `suppressHydrationWarning` to the react intl component? If so, what happens?

it's save me hahaha! Thanks!
