### ISSUE TITLE
defaultMessage API How to use

### ISSUE THREAD

**Issue by 1069080359** [formatjs/react-intl#1237]
const {intl} = this.props;
let tmp = intl.formatMessage({id: 'intl.name'},{name: 'joe'});
How to add defaultMessage default ？

**Comment by 1069080359** [comment]
<FormattedMessage 
　　id="intl.hello"
　　defaultMessage={'The default language'}
/>
Is the component API usable ？

**Comment by Erdwolf** [comment]
Looking at the current implementation, you would add it to the message descriptor like this:
`intl.formatMessage({id: 'intl.name', defaultMessage: 'The default language'},{name: 'joe'});`

Not an official answer, though, so I'd assume this might change in future versions.
