### ISSUE TITLE
How about enabling to get id from children in FormattedMessage

### ISSUE THREAD

**Issue by dinukadesilva** [formatjs/react-intl#1238]
I think this could be enabled and it could make the code more readable and efficient.

```
<FormattedMessage id="abcd" values={{name: <b>{name}</b>, unreadCount}} >
</FormattedMessage>
```

To be equals to

```
<FormattedMessage values={{name: <b>{name}</b>, unreadCount}} >
       abcd
</FormattedMessage>
```

**Comment by redonkulus** [comment]
Thanks for the idea! I think passing it in as props is a cleaner interface and removes any confusion with how or why the children are used.
