### ISSUE TITLE
FormattedNumber Rounding Issues on large numbers

### ISSUE THREAD

**Issue by liyun-li** [formatjs/react-intl#1239]
### Bug Report

Description: The number formatter rounds up large numbers. 

### Expected behavior
* 9999999999999999.99 remains $9999999999999999.99
* 99999999999999.99 remains $99999999999999.99

### Current behavior
* 9999999999999999.99 becomes $10,000,000,000,000,000
* 99999999999999.99 becomes $99999999999999.98

### Step to reproduce
`<FormattedNumber value={cell} style={"currency"} currency="USD" />`

### Environment
Chrome on Windows

**Comment by papasmile** [comment]
HI, @liyun-li that is not an issue with `react-intl` rather a limitation of JavaScript number sizes (16 digits).  
```
double only has 15/16 digits of accuracy and when you give it a number it can't represent (which is most of the time, even 0.1 is not accurate) it takes the closest representable number.

If you want to represent 9999999999999999 exactly, you need to use BigDecimal.
...
```
from: https://stackoverflow.com/questions/8907666/why-is-the-double-parsedouble-making-9999999999999999-to-10000000000000000?rq=1
