### ISSUE TITLE
IntlProvider prop values lost when using injectIntl()

### ISSUE THREAD

**Issue by gknapp** [formatjs/react-intl#1240]
Bug Report

### Expected behavior
Expect `locale` and `messages` to be populated with values passed to `<IntlProvider>` props.

### Current behavior
Component wrapped with `injectIntl(...)` (in my case `App`) does not receive `intl` with prop values. Locale has reverted from `ja` to default value `en`.

### Step to reproduce for BUG REPORT
Switching locale translates strings as expected. However, on first load metadata passed (or not passed?) to `<IntlProvider>` does not propagate.

![react-intl](https://user-images.githubusercontent.com/143027/52344493-d1d9ca80-2a12-11e9-9daa-fea52c93f112.png)

My `App` component is wrapped with `injectIntl()` to access `props.intl`.

### Your Environment

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.4.0 |
| `npm ls react` | 16.3.2 |
| `yarn -v` | 1.13.0 |
| `node --version` | v8.11.4 |

| OS | Version |
| --- | --- |
| Windows 10 | 1803 (build 17134) |

| Browser | Version |
| --- | --- |
| Chrome | 71.0.3578.98 |
| Firefox | 65.0 |

**Comment by gknapp** [comment]
I tested this with `2.8.0`, no change in behaviour.

**Comment by suancarloj** [comment]
@gknapp Hey, I just had the same issue for two days, turns out that in my case, I just forgot to add the locale data like in (when you uncomment line 7 it works) [https://codesandbox.io/embed/j430opx4w5](https://codesandbox.io/embed/j430opx4w5)

**Comment by gknapp** [comment]
Thanks @suancarloj I've added this but still no joy.

What I ended up doing was detecting if the locale data was missing (translation key returned) and issuing a locale change - it's flakey but I needed some grace period (well, `setImmediate()` to push it on to the macro task queue. Perhaps this lets the remaining micro tasks complete) for the locale messages to become available.

English is the fallback language (and inlined in the UI, so never fails), for any other supported language, I had to switch to English and back to the target language. Fortunately this happens quickly enough not to cause UI jankyness.

In `componentDidMount()`:
```
    if (this.props.translate("add-ins.extension", "") === "add-ins.extension") {
      const selectedLocale = this.fetchLocale();
      const targetLocale = selectedLocale || this.props.defaultLocale;

      if (selectedLocale !== "en") {
        this.changeLocale("en");
        window.setImmediate(() => this.changeLocale(targetLocale));
      }
    }
```

This propagates `selectedLocale` to both interfaces.

**Comment by gknapp** [comment]
I'm still seeing some sporadic behaviour, even with my switch locale ~not so~ workaround. I'll try the 3.x release and see if it remedies this issue.

**Comment by DragonRaider5** [comment]
@gknapp did `react-intl@next` fix your issue?

In older releases this could easily happen due to components in your tree not having their `shouldComponentUpdate` check for context changes, which would then stop the context update from cascading.

**Comment by gknapp** [comment]
Warning from yarn on install of `react-intl@next`:

```
warning " > react-intl-loader@1.0.2" has incorrect peer dependency "react-intl@^2.0.1".
```

Good news, no code changes / API breakage errors.

`package.json`: `"react-intl": "^3.0.0-beta-1",`

I'm still seeing errors in my console that messages for the selected locale are missing:

`[React Intl] Missing locale data for locale: "fr". Using default locale: "en" as fallback.`

The app is started after locale data has been loaded.

```js
import loadLocales from "./locales-setup";

const run = isProd => {
  loadLocales(isProd).then(init(isProd));
};

const isProduction = process.env.NODE_ENV === "production";
run(isProduction);
```

`locales-setup.js`:

```js
import axios from "axios";
import { addLocaleData } from "react-intl";
import { apiConfig } from "./config";

/* eslint-disable global-require, import/no-dynamic-require */
const localeData = {
  de: () => import(/* webpackChunkName: "locale-de" */ "react-intl/locale-data/de"),
  en: () => import(/* webpackChunkName: "locale-en" */ "react-intl/locale-data/en"),
  es: () => import(/* webpackChunkName: "locale-es" */ "react-intl/locale-data/es"),
  fr: () => import(/* webpackChunkName: "locale-fr" */ "react-intl/locale-data/fr"),
  ja: () => import(/* webpackChunkName: "locale-ja" */ "react-intl/locale-data/ja")
};

const loadLocale = lang =>
  localeData[lang.code]().then(data => {
    addLocaleData(data.default);
    return lang;
  });

const fetchTranslationFile = lang =>
  axios.get(
    `/${apiConfig.resourceRoot}/${lang.code}.json`
  ).then(({ data }) => {
    lang.messages = data;
    return loadLocale(lang);
  });

const fetchLocales = ({ available }) =>
  Promise.all(available.map(lang => fetchTranslationFile(lang)));

const prodLocaleSetup = () =>
  axios.get(
    `/${apiConfig.resourceRoot}/locale-config.json`
  ).then(({ data: locales }) =>
    fetchLocales(locales).then(langs =>
      langs.reduce((result, lang) => ({
        ...result,
        all: {
          ...result.all,
          [lang.code]: lang
        }
      }), { all: {}, default: locales.default })
    )
  );

// production loads locales from network, dev from disk (dev not included here)
const loadLocales = production => (
  production ? prodLocaleSetup() : devLocaleSetup()
);

export default loadLocales;
```

Inside the react app I have a component that wraps `<App>` with `<IntlProvider>` and has a `shouldComponentUpdate` check for locale change, do I need to inspect context too?

```js
class ConnectedIntlProvider extends Component {
  shouldComponentUpdate(nextProps) {
    return nextProps.locale !== this.props.locale;
  }

  render() {
    const { defaultLocale, locale, messages, children } = this.props;
    return (
      <IntlProvider
        key={locale}
        {...{ defaultLocale, locale, messages }}
      >
        {children}
      </IntlProvider>
    );
  }
}

ConnectedIntlProvider.defaultProps = {
  defaultLocale: "en"
};
```

First time the component run, the values are as expected (I selected French as the UI language in the app).

![image](https://user-images.githubusercontent.com/143027/57767432-40f54800-7701-11e9-945b-c5535aaee688.png)

When I step into `<App>` I've encountered the above error in the console.

`[React Intl] Missing locale data for locale: "fr". Using default locale: "en" as fallback.`

`App`:

```js
const App = ({ history, defaultLocale }) => (
  <ConnectedRouter history={history}>
    <Route
      path="/"
      render={routeProps => (
        <MainLayoutContainer
          {...routeProps}
          defaultLocale={defaultLocale}
        />
      )}
    />
  </ConnectedRouter>
);
```

`MainLayoutContainer` is wrapped with a HOC to provide a translate function:

```js
...

export default compose(
  withTranslation,
  connect(mapStateToProps, mapDispatchToProps)
)(MainLayoutContainer);
```

The HOC is as follows:

```js
import React from "react";
import { injectIntl } from "react-intl";
import getDisplayName from "./utility";

const withTranslation = WrappedComponent => {
  const translate = class Translate extends React.Component {
    // displayName used by React Developer Tools
    static displayName = `withTranslation(${getDisplayName(WrappedComponent)})`;

    /**
     * Wrapper function for react internationalisation API.
     * Encapsulate MessageDescriptor structure
     *   https://github.com/yahoo/react-intl/wiki/API#formatmessage
     * 
     * @param {string} id locale tag name
     * @param {string} defaultMessage fallback label to use
     * @param {object} [values] fill placeholders in message
     * @returns {string} translated string
     */
    translate = (id, defaultMessage, values = {}) =>
      this.props.intl.formatMessage({ id, defaultMessage }, values);
    
    render() {
      const newProps = {
        translate: this.translate
      };
      // eslint-disable-next-line no-unused-vars, react/prop-types
      const { intl, ...props } = this.props;

      return <WrappedComponent {...props} {...newProps} />;
    }
  };

  // Avoid double wrapping components
  return /withTranslation\(/.test(getDisplayName(WrappedComponent))
    ? WrappedComponent
    : injectIntl(translate);
};

export default withTranslation;
```

When stepping through breakpoints in the debugger, I notice `MainLayoutContainer` is reached first, before `ConnectedIntlProvider`. Would this be because react renders child to parent?

I'm beginning to think `injectIntl()` is called before (and outside?) `<IntlProvider>`.

**Comment by gknapp** [comment]
Oops, wrong button

**Comment by gknapp** [comment]
I might have spoken too soon, I might need to update how I consume v3. I'll investigate.

```js
The above error occurred in one of your React components:
    in withIntl(withTranslation(MaterialTextField)) (created by ConnectedField)
    in ConnectedField (created by Connect(ConnectedField))
    in Connect(ConnectedField) (created by Field)
    in Field (created by MapForm)
    in div (created by MapForm)
    in form (created by Form)
```

**Comment by gknapp** [comment]
I ended up downgrading to 2.9.0 to fix my dialog issue. I'll close this issue for now as I need to update my project in significant parts to the latest dependencies, including React (16.3 -> 16.9). I'll reopen if this issue persists after upgrade.
