### ISSUE TITLE
Short units for Relative time

### ISSUE THREAD

**Issue by urvashi01** [formatjs/react-intl#1241]
### Is this a BUG REPORT or FEATURE REQUEST? (choose one)
FEATURE REQUEST

### Expected behavior
I would like to have the ability to format the time in short units (irrespective of the its style).
Eg. 1 hr. ago, 1 min. ago

### Current behavior
Currently, there are two controls - `style` to choose between numeric or best fit and `units` to specify the specific unit I'd like to see. 
`units` control only asks me for one unit (eg.  second / second-short) and will always show all the relative time in that unit (seconds in this case).
But what I want to achieve here is that whenever the unit is auto derived, it can be either `long` or `short`. So, all we tell is that it should be short styled and all units are shortened.

`Intl.RelativeTimeFormat` allows me to achieve the same with its `style` option.

**Comment by srcnalt** [comment]
I need the same, even shorter forms if possible such as:
`5s, 2m, 4h, 12 Feb` and so on, a short time style as in twitter, with out `ago` keyword.

**Comment by longlho** [comment]
@srcnalt you're looking for `Intl.NumberFormat`
```ts
new Intl.NumberFormat('en', {style: 'unit', unit: 'hour', unitDisplay: 'narrow'}).format(12)
// 12h
```
available in [Chrome 77+](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat) or with our [polyfill](https://formatjs.io/docs/polyfills/intl-numberformat)
