### ISSUE TITLE
Warning: Failed prop type: Invalid prop `values` of type `array` supplied to `FormattedMessage`, expected `object`.

### ISSUE THREAD

**Issue by joshunger** [formatjs/react-intl#1243]
### Expected behavior
No prop type warning?

### Current behavior
The warning is displayed
```
Warning: Failed prop type: Invalid prop `values` of type `array` supplied to `FormattedMessage`, expected `object`.
```

### Step to reproduce for BUG REPORT
```
<FormattedMessage defaultMessage="The message has: {0}, {1}, and {2} values." id="sentence" values={['one', 'two', 'three']} />
```

### Your Environment

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.8.0 |
| `npm ls react` | 16.8.1  |
| `npm --version` | 6.4.1 |
| `node --version` | v11.0.0 |

**Comment by bmeneghini** [comment]
I'm having a similar issue:

`Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `FormattedMessage`, expected `function`.
    in FormattedMessage`

Maybe it's something related. I'm gonna wait for a reponse here before oppening a new thread.

**Comment by redonkulus** [comment]
@joshunger I'm confused, are you saying that this should accept arrays as a valid prop type?

**Comment by DragonRaider5** [comment]
@redonkulus yes I think that's what he's asking for, as it also works with arrays.

However I'm uncertain about this. I don't know, if fully allowing arrays might confuse users and make them think they could also map them in some way or another...

**Comment by joshunger** [comment]
@redonkulus yes, but it is confusing because you have to use numeric arguments names? https://github.com/formatjs/intl-messageformat/issues/99#issuecomment-75576133

**Comment by DragonRaider5** [comment]
Funny to see that the array support makes for exactly the confusion I was afraid of :rofl:

@redonkulus what do you think?

**Comment by redonkulus** [comment]
The number arguments do not bother me, as its been something I have been using on projects for years and matches well to the array indexes. Perhaps we could document this better.
