### ISSUE TITLE
How to define default value for context variables?

### ISSUE THREAD

**Issue by Victorien-Tardif** [formatjs/react-intl#1247]
### FEATURE REQUEST

When defining context variables, I'd like to define a default value if value is not passed.
Let's say I have a message `{count, plural, zero {no items} one {one item} many {many items}}`, I would like to be able to define a default value, like `{count, plural, zero {no items} one {one item} many {many items}} default {items}` so that I could use it this way:

### Expected behavior
```
const messages = defineMessages({
   items: '{count, plural, zero {no items} one {one item} many {many items}} default {items}',
});

const messageWithDefinedValue = formatMessage(messages.items, { count: 1 });
console.log(messageWithDefinedValue); // one item

const messageWithUndefinedValue = formatMessage(messages.items);
console.log(messageWithDefinedValue); // items
```

### Current behavior
```
const messages = defineMessages({
   items: '{count, plural, zero {no items} one {one item} many {many items}} default {items}',
});

const messageWithDefinedValue = formatMessage(messages.items, { count: 1 });
console.log(messageWithDefinedValue); // one item

const messageWithUndefinedValue = formatMessage(messages.items);
console.log(messageWithDefinedValue); // Error: The intl string context variable 'count' was not provided
```

**Comment by DragonRaider5** [comment]
Hey @Victorien-Tardif,

Thanks for your suggestion.

I agree this would make a nice improvement.
However this isn't in the scope of this package, as it only provides an API for easy usage of the `intl` APIs in React.

A feature like this would need to be implemented in `intl-messageformat`. If you'd like to, you can open a new issue there and post a link here.

@redonkulus can be closed :)

**Comment by Victorien-Tardif** [comment]
Done :) https://github.com/formatjs/intl-messageformat/issues/182
Thx for your answer!

**Comment by DragonRaider5** [comment]
You're welcome. Thanks for sharing!
