### ISSUE TITLE
BUG: formatNumber won't set a different locale on server render

### ISSUE THREAD

**Issue by maystrenkoYurii** [formatjs/react-intl#1248]
My code. This props language = 'ru'. But serser render format date with 'en'.

`import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { IntlProvider, addLocaleData } from 'react-intl';

import uk from 'react-intl/locale-data/uk';
import ru from 'react-intl/locale-data/ru';
import en from 'react-intl/locale-data/en';

import translationUk from '../../core/languages/uk.json';
import translationRu from '../../core/languages/ru.json';
import translationEn from '../../core/languages/en.json';

import { constants } from '../../core/constants/index';

addLocaleData([...uk, ...ru, ...en]);

class CustomIntlProvider extends Component {
  static propTypes = {
    children: PropTypes.oneOfType([
      PropTypes.arrayOf(PropTypes.node),
      PropTypes.node,
      PropTypes.string,
    ]),
    language: PropTypes.string.isRequired,
  };

  getMessages() {
    const { language } = this.props;
    switch (language) {
      case constants.LANGUAGE_EN:
        return translationEn;
      case constants.LANGUAGE_RU:
        return translationRu;
      case constants.LANGUAGE_UK:
        return translationUk;
      default:
        return translationEn;
    }
  }

  render() {
    const { language, children } = this.props;

    const messages = this.getMessages();

    return (
      <IntlProvider
        defaultLocale={language}
        locale={language}
        key={language}
        messages={messages}
      >
        {children}
      </IntlProvider>
    );
  }
}

export default CustomIntlProvider;`

![default](https://user-images.githubusercontent.com/23016311/53664709-fc195380-3c71-11e9-8039-40c131c65999.PNG)

**Comment by ghostd** [comment]
Hi,

It seems the server (or the client) has the i18n data and the other size does not.

Did you have load the intl polyfill ? Or do you use the full icu npm package on the server side ? (see https://nodejs.org/api/intl.html#intl_providing_icu_data_at_runtime)

**Comment by maystrenkoYurii** [comment]
No, I not download intl polifils

**Comment by maystrenkoYurii** [comment]
I fix this problem. After install intl polifils good work. Plese add in documentation this problem.

**Comment by ghostd** [comment]
The documentation already mentions this part: https://github.com/yahoo/react-intl/wiki#i18n-in-javascript

**Comment by DragonRaider5** [comment]
Thanks @ghosts!

Can be closed @redonkulus - let's clean the issues up day by day :D
