### ISSUE TITLE
FormattedMessage  doesn't reflect locales in firefox, but can be reflected in Chrome

### ISSUE THREAD

**Issue by WeiViLu** [formatjs/react-intl#1251]
`<FormattedMessage defaultMessage={' '} id="bracket.title" />`
When rendering it in Firefox browser, it always show `defaultMessage`, because it can't find the value of bracket.title, it may not reflect locales. But in Chrome browser, it is fine.

In addition, not all Firefox has this problem. I don't know whether it is also related to the version of the os and Firefox.

| NAME | VERSION |
| Firefox | 65.0 |

**Comment by redonkulus** [comment]
Please provide a jsbin/codepen example to help with debugging.
