### ISSUE TITLE
Feature request: Docs to tests and example with react-testing-library

### ISSUE THREAD

**Issue by viniciusavieira** [formatjs/react-intl#1254]
### Expected behavior

A documentation more clear example could be like this codesandbox:
https://codesandbox.io/s/yq2jz85jx1

If you're using Jest and React-testing-library you need to setup your environment inside your tests to deal with Intl Polyfills, since you should probably wanting to write tests to check if your translations match.

The trick is to understand that you need to require the polyfills in order to test if dates, for example, are being displayed as expected.
https://formatjs.io/guides/runtime-environments/#server

I've done a small HOC that render and encapsule the logic, in the example is ```RenderWithReactIntl```

And in your tests you should simply call ```renderWithReactIntl(<MyComponentWithIInjectIntl>)``` passing your view component.  

### Current behavior

React-intl is an amazing library, and using it has helped a lot in projects to many people, but to understand how to properly addLocales to test environment is being a little trick, since the documentation to that is spread across issues and external references, and when doing so tests are running on Node environment, that demand as far as I understand, that you inject the polyffils, using require intl.

References that I found and were useful to me put all the pieces together:
https://github.com/yahoo/react-intl/issues/846
https://github.com/yahoo/react-intl/issues/274
https://formatjs.io/guides/runtime-environments/#server

I'll be glad to pick a PR about it, if it makes sense.

**Comment by redonkulus** [comment]
@viniciusavieira If you have an example repository we could link to it from the wiki. I'm not too sure on adding examples for a library we do not directly use.

**Comment by viniciusavieira** [comment]
@redonkulus I've added examples of the usage on the react-testing-library and added a recipe on the docs site, perhaps you could link it?

https://testing-library.com/docs/example-react-intl

https://github.com/testing-library/react-testing-library/blob/master/examples/__tests__/react-intl.js

**Comment by redonkulus** [comment]
@viniciusavieira Feel free to update [the Testing wiki](https://github.com/formatjs/react-intl/wiki/Testing-with-React-Intl) with a section about `react-testing-library` which includes links to your examples. Thanks!

**Comment by viniciusavieira** [comment]
I'll get that done by today, thank you @redonkulus.

**Comment by redonkulus** [comment]
@viniciusavieira you can edit directly from the GitHub UI as well. There should be an edit button on the page. Or you can clone, edit and push as well.

**Comment by viniciusavieira** [comment]
@redonkulus Seems that I'm not allowed to edit the wiki repo.
The edit button is not visible to me, and if I try to push code the repo denies, it says invalid username or password, even when it is correct(I did logout and login to check, and provided the same credentials when trying to push).

**Comment by redonkulus** [comment]
@viniciusavieira Interesting, that must be a new thing GitHub enforced.

How about if you send me a gist of the Wiki changes and I can add it myself. Eventually these wiki docs should just move to a "docs/" folder in the repo so its part of the code.

**Comment by viniciusavieira** [comment]
@redonkulus feel free to give me some feedback or even edit it.

https://gist.github.com/viniciusavieira/1a52e56f0f7c64beb781cad0c1eba3fd

Thanks.

**Comment by redonkulus** [comment]
@viniciusavieira ok added to the wiki with slight modifications. Thanks for contributing!

https://github.com/formatjs/react-intl/wiki/Testing-with-React-Intl#react-testing-library

**Comment by viniciusavieira** [comment]
Thank you!
