### ISSUE TITLE
How to insert HTML tag with injectIntl formatMessage using React-Intl ?

### ISSUE THREAD

**Issue by dc198689** [formatjs/react-intl#1255]
I am not sure is this a Bug or I am missing something about syntax.

I am using an `injectIntl` way to use props in the component. 
Pure String is fine, but it will not work if I wrapped the HTML tag.

My locale message
`
const messages = {
    'footer': {
        'table_no': 'Table {value}'
    }
}
`

**[ Success ] Case 1 ( Pure String and Nothing HTML tag wrapped )**
`const _tableNoText = intl.formatMessage(`
`    { id: 'footer.table_no' },`
`    { value: basket.table }`
`);`
`//console -> Table 1`

**[ Fail ] Case 2 ( Pure String and HTML tag wrapped )**
`const _tableNoText = intl.formatMessage(`
`    { id: 'footer.table_no' },`
`    { value: <b>basket.table</b> }`
`);`
`// console -> Table [object object]`

If I change the `formatMessage` to `formatHTMLMessage`, 
It will output the same above result, how should I fix that ?

Thanks very much

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | ^2.8.0 |
| `npm ls react` | ^16.4.2 |

**Comment by Lelith** [comment]
I also tried this and it does not work for me too. the only way i was able to make a string with html inside working is by using the HOC 

`<FormattedHTMLMessage { ...messages.title } />`

but then again you're stuck with the nasty wrapper components

**Comment by panosangelopoulos** [comment]
I read that the `formattedHTMLMessage` is not recommended but, as the documentation section mentions, we should use `<FormattedMessage>` instead. 

Any ideas about how to use HTML elements with `FormattedMessage`?

**Comment by Lelith** [comment]
@panosangelopoulos  The owners of the package have the believe that HTML strings are a thing only legacy applications have. At least this is how it reads for me in the documentation.

**Comment by VapiSoft** [comment]
I have the same problem, I just want to add a new line in the text, but don't know how.

**Comment by Lelith** [comment]
@VapiSoft: 
Using ```<FromattedHTMLMessage>``` works in general for me. But you have to live then with another wrapper around your translation. You are able to customize the wrapper Tag bei adding the tagName prop as descriped in my answer [here](https://github.com/yahoo/react-intl/issues/1255#issuecomment-481215761) .

**Comment by VapiSoft** [comment]
@Lelith 
I tried it and it doesn't work with the injectMessage that I use for the translations.
I just replaced the FormattedMessage with FormattedHTMLMessage and added the tagName.
Now it doesn't show any text.
`import React from 'react';
import {FormattedHTMLMessage, injectIntl} from 'react-intl';

const InjectMassage = props => <FormattedHTMLMessage tagName='br' {...props} />
export default injectIntl(InjectMassage, {
    withRef: false
});

`

**Comment by Lelith** [comment]
tagName prop is supposed to get a wrapper Tag, like a div, span or p.
You have to add the br inside your translation string. 
If you feel that you need to add a line break at the end of a sentence, you are probaply have an issue in your CSS.

**Comment by dc198689** [comment]
OK, thanks a lot to discuss my issue, sorry for late reply.
Currently, I am using this way which is `dangerouslySetInnerHTML` if I need to include HTML tag inside my value.

`
const translated = intl.formatMessage(
  { id: 'footer.table_no' },
  { value: '<strong>Hello</strong>' }
);

return (
  <div dangerouslySetInnerHTML={{__html: translated}} />
)
`

**Comment by panosangelopoulos** [comment]
@dc198689 I tried to use this one as well but the `dangerouslySetInnerHTML` is not the best way, imo.

Why you don't use something like this 

```
<strong>
    <FormattedMessage id="footer.table_no" defaultMessage="Hello" />
</strong>
```

?

**Comment by Lelith** [comment]
@panosangelopoulos that works if you want your whole translation string be surrounded by that tag. 
Which can already be achieved by

`<FormattedMessage tagName="strong" id="footer.table_no" defaultMessage="Hello" />`

Bust most of the time i have things where only one part / word of the translation should be emphasised. Or when i have a link that is translated.

**Comment by panosangelopoulos** [comment]
@Lelith then you can use something like 

```
    <FormattedMessage id="footer.table_no" defaultMessage="Hello {worldVal}" values={{ worldVal: <b>World</b> }}/>
```

**Comment by Lelith** [comment]
@panosangelopoulos 
but World is not a variable, its part of the translation. which is why it is there in the first place.

**Comment by DragonRaider5** [comment]
I can at least tell you why it doesn't work - JSX detection is done inside our Wrapper components and not by the intl formatters themselves, as the formatters are platform agnostic.

**Comment by cloakedninjas** [comment]
If you don't mind doing the variable replacement yourself (and the extra verbosity), you can do something like this:

Example message: **Filter by &lt;em>%filter%&lt;/em>**

```
// define the message, don't use braces to wrap the dynamic part
const translation = defineMessages({
    heading: {
        id: 'filter-by-x',
        defaultMessage: 'Filter by %filter%'
    }
});

// the dynamic part
const filterName = 'Colour';

// usage inside our render method
const label = this.props.intl
    .formatMessage(translation.heading)
    .split('%filter%')
    .map((str) => {
        if (str === '') {
            return <em key="label">{filterName}</em>;
        }

        return str;
    });

return <h3>{label}</h3>;
```

**Comment by okovpashko** [comment]
Why don't just use `FormattedMessage` component and pass the value wrapped in JSX tag?

```javascript
const user = {
	name: 'John',
};

//...

<FormattedMessage 
	id="greeting"
	defaultMessage="Hello, {username}"
	values={{ 
		username: <b>{user.name}</b>,
	}}
>
```

You can pass nested `FormattedMessage` components as values as well.

**Comment by vishalrajole** [comment]
I am updating react-intl to **4.3.1** from 3.11.0 and I am facing weird issues with formatMessage api. 
  _NOTE:_ I have a defaultMessage with html tags into it. 

  ```
retailConfirmReadLegalTerms: {
    id: 'retail.readAndConfirmLegalStatements.label',
    defaultMessage: `I have read and understood <a href="{privacyPolicy}" target="_blank" rel="noopener noreferrer"> Terms and Conditions</a>`,
  }
```

```
 <p className={styles.legalStatements} 
     dangerouslySetInnerHTML={{
        __html: intl.formatMessage(messages.retailConfirmReadLegalTerms, {
                      privacyPolicy: settings.url.privacyPolicy });
         }}
/>
```

```
<FormattedMessage
      id={messages.retailConfirmReadLegalTerms.id}
      defaultMessage={messages.retailConfirmReadLegalTerms.defaultMessage}
      values={{
        privacyPolicy: settings.url.privacyPolicy,
      }}
    ></FormattedMessage>
```

<img width="1435" alt="Screenshot 2020-04-03 at 11 20 15 AM" src="https://user-images.githubusercontent.com/4668780/78344922-5e433700-759d-11ea-928b-5100cef590b1.png">

**Comment by longlho** [comment]
Take a look at our release notes: https://github.com/formatjs/react-intl/releases/tag/v4.0.0

Rendering embedded HTML as is a XSS risk, in your case you gotta do:
```tsx
<FormattedMessage defaultMessage="I have read and understood <a> Terms and Conditions</a>" values={{
a: (...chunks) => <a href="{privacyPolicy}" target="_blank" rel="noopener noreferrer">{chunks}</a>
}}/>
```

**Comment by vishalrajole** [comment]
@longlho thanks a lot your help. really appreciate it. I tried above solution which works well. I have to support another case 

```
fieldTaxNumberHintBEL: {
    id: 'field.taxNumber.hint.BEL',
    defaultMessage: `You can find your Belgian TIN (Numéro national) (11 digits) on:\n
    <ul>\n
    <li>The back of the national ID card</li>\n
    <li>The social security card (Carte de sécurité sociale)</li>\n
    <li>The residence card</li>\n
    <li>The car registration for foreign residents in Belgium</li>\n
    </ul>`,
  }
```

```
<FormattedMessage
      defaultMessage={param.defaultMessage}
      id={param.id}
      values={{
        ul: (...chunks) => <ul>{chunks}</ul>,
        li: (...chunks) => {
          return <li key={chunks[0]}>{chunks}</li>;
        },
      }}
/>
```
But I am getting 

`[object Object]`

Can you please help me what I am missing here. Thanks!

**Comment by vishalrajole** [comment]
Thanks @longlho . It worked !

**Comment by takkyuuplayer** [comment]
What to do locales with HTML content?

```javascript
import React from "react";
import ReactDOM from "react-dom";
import { createStore, combineReducers } from "redux";
import { FormattedMessage } from "react-intl";
import { Provider, intlReducer } from "react-intl-redux";

// locales come from an external JSON.
const locales = {
  ja: {
    terms: `<a href="https://example.com/ja.html">利用規約</a>`,
  },
  en: {
    terms: `<a href="https://example.com/en.html">Terms of use</a>`,
  },
};
const initialState = {
  intl: {
    locale: "ja",
    messages: locales.ja,
  },
};
const reducer = combineReducers({
  intl: intlReducer,
});

const store = createStore(reducer, initialState);

const App = () => (
  <Provider store={store}>
    <FormattedMessage id="terms" />
    {/* We were able to use <FormattedHTMLMessage id="terms" /> */}
  </Provider>
);

ReactDOM.render(<App />, document.getElementById("root"));
```

**Comment by paul-vd** [comment]
@takkyuuplayer just use dangerouslySetInnerHTML

```jsx
const App = () => (
  <Provider store={store}>
    <div  dangerouslySetInnerHTML={{ __html: intl.formatMessage({ id: 'terms' }) }} />
  </Provider>
);
```

or you could use the chunks

```jsx
<FormattedMessage
  id="terms"
  values={{
    a: (...chunks) => <a>{chunks}</a>,
  }}
/>
```

**Comment by longlho** [comment]
```tsx
import React from "react";
import ReactDOM from "react-dom";
import { createStore, combineReducers } from "redux";
import { FormattedMessage } from "react-intl";
import { Provider, intlReducer } from "react-intl-redux";

// locales come from an external JSON.
const locales = {
  ja: {
    terms: `<a>利用規約</a>`,
  },
  en: {
    terms: `<a>Terms of use</a>`,
  },
};
const initialState = {
  intl: {
    locale: "ja",
    messages: locales.ja,
  },
};
const reducer = combineReducers({
  intl: intlReducer,
});

const store = createStore(reducer, initialState);

const App = () => (
  <Provider store={store}>
    <FormattedMessage 
		id="terms" 
		values={{
			a: link => `<a href="https://example.com/ja.html">${link}</a>`
		}}
	/>
    {/* We were able to use <FormattedHTMLMessage id="terms" /> */}
  </Provider>
);

ReactDOM.render(<App />, document.getElementById("root"));
```

**Comment by BobanBg79** [comment]
```<FormattedMessage {...myMessage} values={{ someName: <strong>{someName}</strong>, lineBreak: <br /> }} />```

then just put the lineBreak where you want...

**Comment by nassif7** [comment]
> ```tsx
> import React from "react";
> import ReactDOM from "react-dom";
> import { createStore, combineReducers } from "redux";
> import { FormattedMessage } from "react-intl";
> import { Provider, intlReducer } from "react-intl-redux";
> 
> // locales come from an external JSON.
> const locales = {
>   ja: {
>     terms: `<a>利用規約</a>`,
>   },
>   en: {
>     terms: `<a>Terms of use</a>`,
>   },
> };
> const initialState = {
>   intl: {
>     locale: "ja",
>     messages: locales.ja,
>   },
> };
> const reducer = combineReducers({
>   intl: intlReducer,
> });
> 
> const store = createStore(reducer, initialState);
> 
> const App = () => (
>   <Provider store={store}>
>     <FormattedMessage 
> 		id="terms" 
> 		values={{
> 			a: link => `<a href="https://example.com/ja.html">${link}</a>`
> 		}}
> 	/>
>     {/* We were able to use <FormattedHTMLMessage id="terms" /> */}
>   </Provider>
> );
> 
> ReactDOM.render(<App />, document.getElementById("root"));
> ```

this actually almost works, 
but what if you have nested tags and some params
something like this might be even more interesting
```
en : { 
    "welcomeMessage": `<p>Hello <b>{user}</b></p>`
}
```

**Comment by longlho** [comment]
First of all the `p` tag should be a React `<p>` element to begin with :) So instead of `<p>` being in that message, it should be `<p><FormattedMessage defaultMessage="Hello <b>{user}</b>"/></p>`
But anw, the values would be similar:
```tsx
<FormattedMessage 
	defaultMessage="<p>Hello <b>{user}</b></p>"
	values={{
		b: chunks => <b>{chunks}</b>
		p: chunks => <p>{chunks}</p>
	}}
/>
```

**Comment by nassif7** [comment]
Thank you, 
can please provide an example on how to handle markdowns with FormattedMessage ? 
i have been looking for this but i could not find a proper example on how make it work

sometthing like 

```
en: {
"markDown":  "## Emphasis **This is bold text** __This is bold text__ *This is italic text*"
}
```

**Comment by nassif7** [comment]
Thank you for clarifying this, it works fine, but is there is another way to do it. 
what i really want to achieve is a component to wrap the `<FormattedMessage />` so we don't end up typing all this code, 
I mean in this example 
```<FormattedMessage 
	defaultMessage="<p>Hello <b>{user}</b></p>"
	values={{
		b: chunks => <b>{chunks}</b>
		p: chunks => <p>{chunks}</p>
	}}
/>
```
as a developer you still need type the default message and find every single tag in the reach text and give it the value. 
what i was thinking about is to make it simpler in a way as a developer all i need to know is the message id, so i don't need to type a default message nor the tags in the values like this, 

what i was trying to get is a component to look like this `<Translation id={someId} type='html' values={{user: 'userName'}} />`

and my Translation component will do the work 

but this 
```
<FormattedMessage 
	defaultMessage="<p>Hello <b>{user}</b></p>"
	values={{
		b: chunks => <b>{chunks}</b>
		p: chunks => <p>{chunks}</p>
                user: user
	}}
/>
```
can't work

i don't know if anyhow we can achieve that, or someone has done something similar

**Comment by longlho** [comment]
`defaultRichTextElements` in https://formatjs.io/docs/react-intl/components/#intl-provider-component might help u with that

**Comment by nassif7** [comment]
Thank you for the link @longlho this was very helpful, 
i could find the solution here https://github.com/formatjs/formatjs/issues/1752

just so to summarise the way i managed it. 
i had used the hook that returns the messages
```
  const intl = useIntl()
  const message = intl.formatMessage(messageId)
```
then created a temp doc to contain the message 
```
 let temp: any = document.createElement("div")
 temp.innerHTML = message
```

then i get all the tags in one object
and for each tag i run createReactElement like this 
this was mentioned here 
https://github.com/formatjs/formatjs/issues/1752

```
let all = temp.getElementsByTagName("*")
  let tags = {}

  for (const tag of all) {
    const tagname = { [tag.localName]: (chunks: any) => createElement(tag.localName, {}, ...chunks) };
    tags = { ...tags, ...tagname }
  }
```

and finally render the component 
```
 const formValues = { ...tags, ...values }
  return <FormattedMessage
    id={id}
    values={{ ...formValues }}
  />
}
```

and this was exactly what i needed. 

I still don't know what kinda issues i might get using this, but it seems to be fine so far. 

thank you again @longlho and also for @pyrocat101

**Comment by ghost** [comment]
With `react-html-parser` : 

````js
import React, { Component } from "react";
import { compose } from "recompose";
import { defineMessages, injectIntl } from "react-intl";
import ReactHtmlParser from "react-html-parser";

const messages = defineMessages({
  myMessage: {
    id: "my.message.id",
    defaultMessage: "There is <strong>HTML</strong> here"
  }
});

class MyComponent extends Component {
  render() {
    return (
      <div className="my-component">
        {ReactHtmlParser(this.props.intl.formatMessage(messages.myMessage))}
      </div>
    );
  }
}

export default compose(injectIntl)(MyComponent);

````

**Comment by rizwanellahi** [comment]
> @takkyuuplayer just use dangerouslySetInnerHTML
> 
> ```js
> const App = () => (
>   <Provider store={store}>
>     <div  dangerouslySetInnerHTML={{ __html: intl.formatMessage({ id: 'terms' }) }} />
>   </Provider>
> );
> ```
> 
> or you could use the chunks
> 
> ```js
> <FormattedMessage
>   id="terms"
>   values={{
>     a: (...chunks) => <a>{chunks}</a>,
>   }}
> />
> ```

@takkyuuplayer  Bravo  👏 👏

**Comment by panth-flexport** [comment]
Is there any work around for this ? I have 2 lines of text. One of it needs to be bold and one of it needs to be normal text starting from next line basically 
<b> Hello World </b>
<br /> 
<div> Lorem posum Lorem posum </div>

any way i can achieve this using FormattedMessage component of react-intl ?

**Comment by slavko-clubee** [comment]
> ```tsx
> import React from "react";
> import ReactDOM from "react-dom";
> import { createStore, combineReducers } from "redux";
> import { FormattedMessage } from "react-intl";
> import { Provider, intlReducer } from "react-intl-redux";
> 
> // locales come from an external JSON.
> const locales = {
>   ja: {
>     terms: `<a>利用規約</a>`,
>   },
>   en: {
>     terms: `<a>Terms of use</a>`,
>   },
> };
> const initialState = {
>   intl: {
>     locale: "ja",
>     messages: locales.ja,
>   },
> };
> const reducer = combineReducers({
>   intl: intlReducer,
> });
> 
> const store = createStore(reducer, initialState);
> 
> const App = () => (
>   <Provider store={store}>
>     <FormattedMessage 
> 		id="terms" 
> 		values={{
> 			a: link => `<a href="https://example.com/ja.html">${link}</a>`
> 		}}
> 	/>
>     {/* We were able to use <FormattedHTMLMessage id="terms" /> */}
>   </Provider>
> );
> 
> ReactDOM.render(<App />, document.getElementById("root"));
> ```

Works for me, thanks
If any one curious how to use it with `useIntl` hook

```tsx
const intl = useIntl()

...

label={intl.formatMessage(
{
  id: 'form.tac_label',
  defaultMessage: 'I have read and accept the <tac>Terms & Conditions</tac> and <pp>Privacy Policy</pp>.',
},
{
  tac: (chunks: any) => <a href="/terms-conditions-users" rel="noopener noreferrer" target="_blank">{chunks}</a>,
  pp: (chunks: any) => <a href="/privacy-policy" rel="noopener noreferrer" target="_blank">{chunks}</a>,
}
)}

```

**Comment by mewdev** [comment]
> Works for me, thanks If any one curious how to use it with `useIntl` hook
> 
> const intl = useIntl()
> 
> ...
> 
> label={intl.formatMessage(
> {
>   id: 'form.tac_label',
>   defaultMessage: 'I have read and accept the <tac>Terms & Conditions</tac> and <pp>Privacy Policy</pp>.',
> },
> {
>   tac: (chunks: any) => <a href="/terms-conditions-users" rel="noopener noreferrer" target="_blank">{chunks}</a>,
>   pp: (chunks: any) => <a href="/privacy-policy" rel="noopener noreferrer" target="_blank">{chunks}</a>,
> }
> )}

Getting ts error although it is working, haven't you gotten any?
