### ISSUE TITLE
FormattedNumber style prop clashes with react eslint rule

### ISSUE THREAD

**Issue by arvinsim** [formatjs/react-intl#1257]
[FormattedNumber's](https://github.com/yahoo/react-intl/wiki/Components#formattednumber) `style` prop clashes with the [react/style-prop-object](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/style-prop-object.md) eslint rule

**Comment by redonkulus** [comment]
This is following the [NumberFormat API spec](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) so I don't believe we will be modifying that for this eslint rule. Best bet is to disable this rule on the lines that produce the error.
