### ISSUE TITLE
defaultProps no more provided after injectIntl use

### ISSUE THREAD

**Issue by castrogne** [formatjs/react-intl#1258]
Hi,

I have some trouble using injectIntl with defaultProps. my default worked before I started using injectIntl.

Thanks a lot

### Expected behavior
I need to use "defaultProps" in a component, with injectIntl support. Now defaultProps seems to be ignored when I use injectIntl .

### Current behavior
I have a component which have an obtional "oncreate" callback. That simple test worked before : 
```
describe("Board component", () => {
    it("renders without crashing", () => {
        const div = document.createElement("div");
        ReactDOM.render(
            <IntlProvider locale="fr" messages={frTranslations}>
                <AddSiteDialog api={api}/>
            </IntlProvider>, div);
        ReactDOM.unmountComponentAtNode(div);
    });
});
```
Now i have that error : 
![image](https://user-images.githubusercontent.com/13225776/55065635-7922c780-507c-11e9-9a62-ddc8b37786be.png)

### Step to reproduce for BUG REPORT
Guiven this component (a little simplified for issue use) : 

```
interface IAddSiteDialogProps {
    api: ISiteApi;
    onCreate: (creationState: string) => void;
}

const AddSiteDialog = injectIntl<IAddSiteDialogProps>(
    class AddSiteDialogInner extends Component<IAddSiteDialogProps & InjectedIntlProps> {

        public static defaultProps = {
            onCreate: () => void 0,
        };

        constructor(props: IAddSiteDialogProps & InjectedIntlProps) {
            super(props);

            this.state = {
                newSite: new SiteDto("", 0),
                open: false,
            };
        }

        public render() {
            return (
                            <TextField
                                autoFocus={true}
                                margin="dense"
                                id="name"
                                label={this.props.intl.formatMessage(dialog.textField)}
                                type="email"
                                fullWidth={true}
                                onChange={(e) => this.handleChanged(e)}
                            />
        }
    },
    {withRef: true},
);
```
Now defaultprops is ignored.

### Your Environment

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | react-intl@2.8.0|
| `npm ls react` |  react@16.8.4|
| `npm --version` | 6.9.0|
| `node --version` | 8.11.3|

| OS | Version |
| --- | --- |
| Windows 10 Pro| ?|

| Browser | Version |
| --- | --- |
| Chrome | 73.0.3683.86 |

**Comment by s-h-a-d-o-w** [comment]
You need to split up your props into regular props and default props. Then create two different prop types and use the one where you've made default props partial to cast your class. Something like:

```js
type Props = BaseProps & DefaultProps;
type AddSiteDialogProps = BaseProps & Partial<DefaultProps>;

class AddSiteDialogInner extends Component<Props> {
  ...
}

const AddSiteDialog = injectIntl(AddSiteDialogInner as React.ComponentClass<AddSiteDialogProps>);
```

**Comment by Klemensas** [comment]
@redonkulus can this be reopened?

The approach suggested by @s-h-a-d-o-w works but is more like a workaround. Seems to me like this should be handled by the lib.
`defaultProps` on HOCs can be preserved without forcing specific prop formatting, see https://github.com/typescript-cheatsheets/react-typescript-cheatsheet/blob/master/HOC.md#docs-example-use-hocs-for-cross-cutting-concerns

**Comment by s-h-a-d-o-w** [comment]
@Klemensas You're right, it is just a workaround. 

But did you actually get the approach in the example that you linked to working? (Sidenote - which also contains a workaround. Look at the comment in `render()`)
At least I failed. See `Subscriptions.tsx` here: https://codesandbox.io/s/heuristic-yonath-rc4id

What I came up with myself is what is in `ShadowsApproach.tsx`. Which elaborates a bit on that Subscription example in order to demonstrate the flexibility. However, it still can't be used for `react-intl` because here, things are done with `forwardedRef` and `hoistNonReactStatics`.

(I considered contributing both here and/or to that cheat sheet but I'm mostly using hooks these days and considering how much of a pain typing HOCs is, I'm not confident that it would be a wise time investment for me. 😉 )

**Comment by Klemensas** [comment]
Yeah, it should be working. Looking at your sandbox it seems like you've missed adding the `data` prop to `CommentListProps`, adding it makes it work :)

And I think your approach is perfectly fine. But I think a library should be flexible enough not to force specific typings on its users

**Comment by s-h-a-d-o-w** [comment]
@Klemensas Huh, seems I never got a notification about your comment back then. Thanks for the note about the `data` prop! It's been a while but I think when I created my sandbox, I missed the fact that `data` actually should exist in the props.

As for the typings - sure, I agree. I just wasn't convinced that a better way is possible. Now that it seems to be, I have to bookmark this in case I ever have to type HOCs again. :)

**Comment by this-miguel** [comment]
in version `^2.4.0` I istill have this behavior, has been this solved in other version?

**Comment by longlho** [comment]
Have you given it a try?

**Comment by this-miguel** [comment]
:/ I actually have the version `2.9.0` that seems to be the last before the version `3`.  I think I would have to migrate to the next version to avoid this problem using the `useIntl` hook  instead of `injectIntl `

**Comment by longlho** [comment]
You should just upgrade to the latest version and see if you have the issue
