### ISSUE TITLE
react-router example does not show language change

### ISSUE THREAD

**Issue by AndyOGo** [formatjs/react-intl#1259]
### Is this a BUG REPORT or FEATURE REQUEST? (choose one)
Feature

### Expected behavior

Well, the example should also show how to change the language based on route changes.

### Current behavior

The example does not consider language changing at all.
In fact the locale is hardcoded:
https://github.com/yahoo/react-intl/blob/ee1dfb6f1b22fa274157656e1185d34f509c5f91/examples/react-router/src/index.js#L9

### Step to reproduce for BUG REPORT

- run this locally: https://github.com/yahoo/react-intl/tree/master/examples/react-router
- try to change the locale (you can't, it's hardcoded)

**Comment by weiwangdd01** [comment]
赶快改一哈

**Comment by DragonRaider5** [comment]
Hello @AndyOGo,

thanks for your suggestion. Would you mind opening a PR for this or can I help you with what you're trying to achieve in your own app in the first place?

**Comment by AndyOGo** [comment]
@DragonRaider5 

Well i18n is all about different languages, regions etc. and changing these.
The example above does show how to switch from `en-GB` to `de-DE`.

**Comment by DragonRaider5** [comment]
@AndyOGo so did you manage to do it in your app? Are you willing to open a PR updating the example?

**Comment by AndyOGo** [comment]
@DragonRaider5 

Well the think is, a college ask me for help with this tool, so I referred him to the main parts of the docs and the examples. Unfortunately turned out the examples do not show a main feature, like changing language.

No I will not provide a PR, personally I prefer tools like `i18next`.

**Comment by DragonRaider5** [comment]
@AndyOGo I see. Changing the language can be done by just providing a different value for the `locale` prop. I think this is pretty straight forward. You can either store it in something like redux and just inject it using `connect` or save it in a components local state like that:

TranslationProvider.js
```js
import React from 'react'
import { IntlProvider } from 'react-intl'

const Context = React.createContext(() => throw new Error(
  'No TranslationProvider found in component ancestory.'
))

export default class TranslationProvider extends React.PureComponent {
  state = {
    locale: 'en-GB'
  }

  setLocale = (locale) => this.setState({ locale })

  render () {
    const { children, ...props } = this.props;
    
    return (
      <Context.Provider value={this.setLocale}>
        <IntlProvider {...props} locale={this.state.locale}>
          { children }
        </IntlProvider>
      </Context.Provider>
    );
  }
};

export const LocaleSetter = Context.Consumer;
```

index.js
```js
import React from 'react';
import ReactDOM from 'react-dom';
import TranslationProvider from './TranslationProvider.js';
import { BrowserRouter } from 'react-router-dom';

import App from './components/App';

ReactDOM.render(
    <TranslationProvider>
        <BrowserRouter>
            <App />
        </BrowserRouter>
    </TranslationProvider>,
    document.getElementById('root')
);
```

Any file where you want to set the locale
```js
import React from 'react'
import { LocaleSetter } from './TranslationProvider.js'

export default () => (
  <LocaleSetter>
    {(setLocale) => (
      <React.Fragment>
        <button onClick={() => setLocale('de-DE')>Deutsch</button>
        <button onClick={() => setLocale('en-GB')>English</button>
      </React.Fragment>
    )}
  </LocaleSetter>
)
```

Did this help him? 😄

**Comment by AndyOGo** [comment]
@DragonRaider5 
Thanks a lot for your effort, really appreciating it. I think it's very valuable for people consulting the examples.
For us, we have progressed meanwhile.

**Comment by redonkulus** [comment]
I’m going to close this, but @DragonRaider5 if you want to PR an update with local change we can get that in later.
