### ISSUE TITLE
window.App is not working

### ISSUE THREAD

**Issue by HackAsh96** [formatjs/react-intl#1261]
### Your Environment

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | VERSION |
| `npm ls react` | VERSION |
| `npm --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

| Browser | Version |
| --- | --- |
| NAME | VERSION |

**Comment by redonkulus** [comment]
Please provide more information.
