### ISSUE TITLE
FormattedMessage tagName propTypes should accept React.Fragment

### ISSUE THREAD

**Issue by slorber** [formatjs/react-intl#1262]
It's possibe to use FormattedMessage with a React.Fragment tagName if we want to avoid the extra span, but it generates a propTypes warning while it's safe.

Workaround is:

`delete FormattedMessage.propTypes["tagName"];`

**Comment by TrejGun** [comment]
you can pass it like this
```
 <IntlProvider textComponent={Fragment}>
```

**Comment by slorber** [comment]
Yes, it's exactly what I do and works like expected, but it generates a prop types warning

**Comment by slorber** [comment]
Hi,

in v3 the intl compo has been wrapped inside "withIntl". The new workaround for this (v2 + v3) is

```
// @ts-ignore
FormattedMessage.propTypes && delete FormattedMessage.propTypes['tagName'];
// @ts-ignore
FormattedMessage.WrappedComponent && FormattedMessage.WrappedComponent &&  delete FormattedMessage.WrappedComponent.propTypes['tagName'];
```

**Comment by phaux** [comment]
I think fragment should be the default

**Comment by blainemuri** [comment]
Seconded that fragment should be the default. Especially for SEO, it's not good to have too many html elements per page. And when building out pages with a lot of text, the default `<span>` return unnecessarily pollutes the DOM.

**Comment by redonkulus** [comment]
Relevant discussion about defaulting to string here https://github.com/formatjs/react-intl/issues/987
