### ISSUE TITLE
[Feature Request] Checking a name of passing variable

### ISSUE THREAD

**Issue by dev-nicelee** [formatjs/react-intl#1265]
### Feature Proposal

Checking a name of passing variable

### In Detail

Afaik, we have to check every variables' name in the current `react-intl` version.
So, I usually check what the name of passing variable exactly is. However, if there's missing word or typo, it's quite cumbersome to rewrite the code (Maybe I'm too lazy..😭)

If there's already this kind of feature exist, forgive me.

**Comment by redonkulus** [comment]
@dev-nicelee can you provide a code example or snippet of what you are referring to? Its hard to understand right now.

**Comment by redonkulus** [comment]
Closing as stale.
