### ISSUE TITLE
add a new region code en-PL

### ISSUE THREAD

**Issue by AndersM79** [formatjs/react-intl#1266]
### Expected behavior

get correct or custom format numbers, dates an hours for locals that isn´t defined under  \react-intl\locale-data for example en-PL, currently this return the default values for date, numbers and time.

### Current behavior

I tried to set locale with a en-PL value to get date and formats similar to en-MY or like any other defined inside \react-intl\locale-data, but it it´s not defined a file with en-PL isn´t defined there. is there any way to add this extra feature to support this region?

### Step to reproduce for BUG REPORT

environment production, development.

**Comment by redonkulus** [comment]
I believe the data comes from the `cldr-core` package, the [build script](https://github.com/formatjs/react-intl/blob/master/scripts/build-data.js#L4) leverages `formatjs-extract-cldr-data` which gets the data from [locales.js](https://github.com/formatjs/formatjs/blob/master/packages/formatjs-extract-cldr-data/lib/locales.js) script. I'm not too familiar with this part of the code base. @okuryu might have more knowledge.

**Comment by okuryu** [comment]
Certainly `en-PL` is not on the Unicode CLDR locale names list, but `en` (language code) and `PL`  (region code) don't seem wrong.
https://github.com/unicode-cldr/cldr-dates-full/tree/master/main
https://unicode.org/cldr/utility/languageid.jsp?a=en-PL

So linguistically I don't know the difference between `en-PL` and other ids like `en-US`, but you can send a request to Unicode CLDR if your request is correct.
http://cldr.unicode.org/index/bug-reports

**Comment by AndersM79** [comment]
Thanks a lot, as you said, i realized that en-PL is not on the Unicode CLDR locale names list. only i tried to set english language and pl region in order to get the correct date and number formats for poland. do you know if i can set a custom locale with custom formats for dates and numbers?. Thanks. !!

**Comment by DragonRaider5** [comment]
Yes, there's the `formatters` option on the `IntlProvider`.
I can't provide you with documentation though :P

**Comment by DragonRaider5** [comment]
Feel free to reopen if additional questions occur. Closing this for now :+1:
