### ISSUE TITLE
JSX message renders but still gives an error

### ISSUE THREAD

**Issue by tmartres** [formatjs/react-intl#1268]
**BUG / CONFUSION REPORT**

I expected to be able to just have a file of jsx messages that I could feed to the IntlProvider's messages prop without any error on the browser when using FormattedMessage. 

It renders it as expected but gives me the following errors : 

`[React Intl] Error formatting message: "slogan" for locale: "en"
TypeError: A message must be provided as a String or AST.`
&
`[React Intl] Cannot format message: "slogan", using message source as fallback.`

My idea was to have a `en.js` file and a `ar.js` file which content would be fed to the provider via redux so users can switch manually from english to arabic with a redux action creator. I would like to be able to put in custom html tags such as bold in messages (like in en.js below) so as to keep the code simple. 

**My question really is : why would it render what was expected but still give an error ?** 

Here is a simplified version of my implementation : 

```
//en.js

import React from 'react'

export default {
    "slogan": <span>Some <bold>slogan</bold></span>
}

```

```
// index.js
import React from 'react'
import ReactDOM from 'react-dom'

import english_content from './en.js'
import { Provider } from 'react-redux';
import { createStore } from 'redux';
import {App}  from './App.js'

import { IntlProvider } from 'react-intl';

const store = createStore()

ReactDOM.render(
    	<Provider store={store}>
            <IntlProvider locale='en' messages={english_content}>
                <App history={history}/>
            </IntlProvider>
        </Provider>,
    document.getElementById('root')
);
```

```
//App.js

import React from 'react'
import  { FormattedMessage } from 'react-intl'

export class App extends Component {
  render(){
    return <FormattedMessage id="slogan"/>
  }
}

```

Environment
| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` |  react-intl@2.8.0  |
| `npm ls react` | react@16.7.0 |
| `npm --version` | 6.5.0 |
| `node --version` | v9.5.0 |

**Comment by DragonRaider5** [comment]
The error is because `react-intl` isn't supposed to be used this way. HTML/JSX should (in most cases) be handled on the level of the component rendering the message - the message itself is intended to only hold the translated content, not any styling.

**Comment by DragonRaider5** [comment]
You also have the option to put html (no JSX) into your message *string* and use it with `FormattedHTMLMessage` or to provide JSX using the `values` prop.

@redonkulus close?
