### ISSUE TITLE
contextType of injectIntl is overridden by child component contextType

### ISSUE THREAD

**Issue by ChrisGitter** [formatjs/react-intl#1269]
### Expected behavior
`contextType` of react-intl should not be overridden

### Current behavior
`contextType` of react-intl is overridden by child component's `contextType` field. The reason is that: react-intl uses an old version (2.5.5) of `hoist-non-react-statics` which doesn't include the new `contextType` field in the statics blacklist.

Updating the dependency to the latest version should fix the problem!

### Step to reproduce for BUG REPORT
1. Add own context to a react component using `Component.contextType = Context` or inside a class with babel `static contextType = Context;`
2. Wrapp `injectIntl` around the component

See live example: https://codesandbox.io/s/yv1q6xq66x

### Your Environment

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.8.0 |
| `npm ls react` | 16.8.6 |

| OS | Version |
| --- | --- |
| Arch Linux | 5.0.9 |

| Browser | Version |
| --- | --- |
| Chrome | 73.0.3683.103 |

**Comment by SixYearsInFebruary** [comment]
I also met the same problem
