### ISSUE TITLE
Nested interpolation support?

### ISSUE THREAD

**Issue by vsarang** [formatjs/react-intl#1270]
### FEATURE REQUEST
String interpolation is supported by `react-intl` such that I can do this:

```json
"my.interpolated.message": "My values: {value1}, {value2}"
```
```js
props.intl.formatMessage({ id: 'my.interpolated.message' }, {
  value1: 'myFirstValue',
  value2: 'mySecondValue'
});
```
```
My values: myFirstValue, mySecondValue
```

I would like to be able to do something like this:
```json
"my.interpolated.message": "My values: {value}, {obj.value}"
```
```js
props.intl.formatMessage({ id: 'my.interpolated.message' }, {
  value: 'myRootValue',
  obj: {
    value: 'myNestedValue'
  }
});
```
```
My values: myRootValue, myNestedValue
```

I have two questions:
1. Is this supported today? (I'm pretty sure it's not)
2. Would this project's maintainers be receptive to a PR adding support for this functionality?

**Comment by MathieuDoyon** [comment]
Interested in this.
I also tried to flatten the values object like this.
```
"my.interpolated.message": "My values: {value}, {obj.value}"
```
```
props.intl.formatMessage({ id: 'my.interpolated.message' }, {
  value: 'myRootValue',
  'obj.value': 'myNestedValue'
});
```

it ouput:
```
My values: myRootValue, {obj.value}
```

**Comment by DragonRaider5** [comment]
Hey @vsarang,

thanks for your contribution.
As long as it doesn't harm performance in any meaningful matter, I'd love to see a PR for this!

What do you think @redonkulus?

Best regards
DragonRaider5

**Comment by redonkulus** [comment]
Ya performance would need to be tested, especially for deeply nested objects (unless we restrict it to only 1 level). @vsarang feel free to test this out and report your findings.

**Comment by DragonRaider5** [comment]
@redonkulus I think this wouldn't be an issue, as the path would be provided and there's no need to copy or scan the object.

I was more afraid of it slowing down the general usage for some reason (resulting in a lower performance even if our users don't make use of objects in their variables).

**Comment by redonkulus** [comment]
Good points, I'm open to a PR for this as well. We can let the community decide, if no one offers a PR, we can close the issue.

**Comment by vsarang** [comment]
@redonkulus I'm planning on taking a look at this next Friday (my company has a "hack day" every other Friday), so expect a PR!

**Comment by vsarang** [comment]
I spent some time on this today, but wasn't able to make any meaningful progress. I figured out that I needed to modify some upstream packages -- `intl-messageformat`, and `intl-messageformat-parser`, but I was unable to successfully set up local development with `npm link`.

First I had some issues even running the `npm link` command in `intl-messageformat-parser`, but after modifying the scripts in `package.json` I think I got it working. My main issue was getting `Uncaught TypeError: intl$messageformat$$.default.__addLocaleData is not a function` in the browser, which I have been unable to resolve. My hunch is that I have a version mismatch, but I'm not sure how to fix it.

Is there a development guide somewhere? I wasn't expecting it to be so hard just to get my dev environment set up.

**Comment by redonkulus** [comment]
@longlho might be able to provide some details on working with these upstream packages since he has been making some changes to them recently.

**Comment by longlho** [comment]
react-intl is still on `intl-messageformat@2` (latest is 3) so that's probably why your `npm link` won't work. Unfortunately I don't think we're planning to support deeply nested object because:
1. `intl-messageformat` follows [ICU MessageFormat](http://userguide.icu-project.org/formatparse/messages#TOC-MessageFormat) spec which works across other languages like C, C++ & Java and I believe they don't support this capability. We're trying to stay close to the spec as much as possible and yet there're features we have not implemented.
2. It complicates the compilation & tokenization process as it forces us to further parse a "mini" grammar within the variable name (e.g `foo.bar` or worse, `foo[0].bar.baz[2]`).

**Comment by vsarang** [comment]
@longlho That's what I was expecting to hear after realizing these rulesets were implemented in external packages. It's unfortunate that the standard doesn't support nested objects. Data is commonly organized in hierarchies, and it would be very useful to be able to reference that data arbitrarily without the need for complex preprocessing. This is especially useful when creating abstract frameworks where components don't understand the specifics of the messages they will display.

I know there's not much you can do about this, but I wanted to put my thoughts down. I'd like to thank the `react-intl` team either way (for taking the time to offer assistance and answer my questions).

Cheers!

**Comment by redonkulus** [comment]
Thanks for the kind words. `react-intl` is supported by the community in our spare time, so the kindness is appreciated.
