### ISSUE TITLE
babel config is wrong in the examples

### ISSUE THREAD

**Issue by keremciu** [formatjs/react-intl#1274]
It looks the config is for 'react-intl' babel-plugin but it's not there

https://github.com/formatjs/react-intl/blob/4109ef13e8a7b3b2af5f8d5fead06af9e5cfbb95/examples/translations/.babelrc#L7

**Comment by redonkulus** [comment]
@keremciu have you tried running the example locally? if so, does it fail?

**Comment by keremciu** [comment]
@redonkulus yes but the problem is this config for this babel plugin doesn't make sense.

as you can see below link there's no messagesDir config inside this babel plugin.
https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/blob/master/src/index.js 

you can see the problem in this commit, `messagesDir` was a config parameter for react-intl plugin.
https://github.com/formatjs/react-intl/commit/fcf9d4fc800efde553044cbdd27abc3cf7625d55#diff-12ea091f62ce6c62baeea4826fc5f9f8

**Comment by redonkulus** [comment]
@keremciu do you mind submitting a PR to fix this?

**Comment by keremciu** [comment]
@redonkulus yep yep, I created one https://github.com/formatjs/react-intl/pull/1278

**Comment by redonkulus** [comment]
Merged! Thanks for helping.
