### ISSUE TITLE
Update Migration Guide

### ISSUE THREAD

**Issue by redonkulus** [formatjs/react-intl#1281]
We need to update the [v3.0.0 Migration guide](https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md) to ensure it is easy for developers to upgrade.

We can follow the same format as previous releases.

**Comment by DragonRaider5** [comment]
WIP :smile:

**Comment by leoyli** [comment]
#1282, some documentation needed for how to use this (it's is a simple replacement for `injectIntl` HOC for function components).

**Comment by redonkulus** [comment]
@DragonRaider5 the upgrade doc has been moved to https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md. 

@leoyli good suggestion. Want to PR that to the doc above?

**Comment by leoyli** [comment]
@redonkulus, `Components` also have no `injectIntl` documented, maybe it belongs to other docs? (haven't look into details)

**Comment by redonkulus** [comment]
@leoyli Its actually in the [API](https://github.com/formatjs/react-intl/blob/master/docs/API.md#injection-api) docs. We should add `useIntl` to that doc as well.

**Comment by redonkulus** [comment]
@leoyli do you want to open a PR for adding `useIntl` to the API docs?

@DragonRaider5 @longlho anything else we need to call out for v3 migration?

**Comment by leoyli** [comment]
@redonkulus, I can do it in the weekend, if that is okay.

**Comment by redonkulus** [comment]
Its no problem, if there are no other tasks or bugs opened for v3, we can probably release it next week.

**Comment by leoyli** [comment]
@longlho, Could you elaborated a bit more on "removing `addLocaleData`" part in the upgrade guide for me?! I found I get a bit confused on what should I do if I have `addLocaleData` used.  Am I just simply remove it? And if I have to support IE11, then should I just keep it but adding polyfills in my build entries instead?! 

If you have good answer for me, please consider adding these into the doc.  I believe it would be super helpful to all users :pray:

**Comment by longlho** [comment]
Yeah for modern browsers where `Intl.RelativeTimeFormat` is supported, you don't need to do anything. For IE11 the locale data would be part of the `Intl.RelativeTimeFormat` polyfill here: https://github.com/formatjs/formatjs/tree/master/packages/intl-relativetimeformat

I'll add more details to the doc

**Comment by leoyli** [comment]
Thank you! It would be super helpful if we can cover these details, especially for IE11.  They should be minority now but it will keep alive until 2022 (or 2024 I forget...).  In some cases, they should be a major concerns, e.g. system existed in some governors. :eyes:

**Comment by mikeyshing88** [comment]
With the removal of `addLocaleData`, I'm getting ` Missing locale data for locale: "xx". Using default locale: "xx" as fallback.` error on server side. However, the client side is rendering correctly. Anybody else experiencing this since upgrading?

**Comment by longlho** [comment]
You'd have to use node w/ ICU. The instruction is here: https://nodejs.org/api/intl.html#intl_embed_the_entire_icu_full_icu I'll add that to the Upgrade guide

**Comment by leoyli** [comment]
Woo nice, the v3 looks really nice now, thank you @longlho!  And I just noticed that **FormattedRelativeTime** is missed on the top index in the the upgrade guide, maybe you would like update the doc quickly?!

**Comment by longlho** [comment]
> Woo nice, the v3 looks really nice now, thank you @longlho! And I just noticed that **FormattedRelativeTime** is missed on the top index in the the upgrade guide, maybe you would like update the doc quickly?!

yup I autogen TOC in #1340

**Comment by leoyli** [comment]
@longlho,

does

```
  defaultMessage="To buy a shoe, <a>visit our website</a> and <cta>eat a shoe</cta>"
```

was ment to

```
  defaultMessage="To buy a shoe, <link>visit our website</link> and <cta>eat a shoe</cta>"
```

in the doce here: https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#enhanced-formattedmessage--formatmessage-rich-text-formatting?

**Comment by longlho** [comment]
Oh yeah my bad
