### ISSUE TITLE
FormattedHTMLMessage renders nested FormattedMessage as [object Object]

### ISSUE THREAD

**Issue by szimek** [formatjs/react-intl#1284]
### Expected behavior
Given 2 translations, e.g.
```json
{
  "framework": "React",
  "message": "{framework} is awesome. Read more about it <a href='/'>here</a>"
}
```
and the following code:
```jsx
<FormattedHTMLMessage
  id="message"
  values={{ framework: <FormattedMessage id="framework" /> }}
/>
```
I'd expect that the following string would be rendered
```
React is awesome. Read more about it here.
```

### Current behavior
Currently it renders
```
[object Object] is awesome. Read more about it here.
```

It works fine, if I use `<FormattedMessage>` instead of `<FormattedHTMLMessage>`, but then of course all html tags are escaped.

### Step to reproduce
https://codesandbox.io/s/reactintl-formattedhtmlmessage-issue-4em87

**Comment by DragonRaider5** [comment]
Hey,
I think there won't be an easy fix to this, as `FormattedHTMLMessage` works by utilizing `innerHtml`.

This is why your jsx doesn't get rendered but instead it prints out `[object Object]`. If you first render your jsx to text, it'll work.

**Comment by DragonRaider5** [comment]
Follow-up:
If you only need to translate another message in there you might as well just use `injectIntl` or the upcoming `useIntl`.
```js
injectIntl(({ intl }) => (
  <FormattedHTMLMessage
    id="message"
    values={{ framework: intl.formatMessage({ id: "framework" }) }}
  />
))
```

Btw. I'd suggest using `defineMessages`.

**Comment by szimek** [comment]
Thanks! I'm currently using `intl.formatMessage` as a workaround, but considered this inconsistency in API as a bug.

**Comment by DragonRaider5** [comment]
It's not inconsistent, as JSX doesn't work at all in `FormattedHTMLMessage`.
That is because, as the name suggests, the entire message is interpreted as HTML - variables are also part of the message.

`FormattedMessage` also does not escape HTML tags, it just renders them like this would do:
```js
return (
  <div> { '<span>Hello World!</span>' } </div>
)
```

**Comment by DragonRaider5** [comment]
To be honest I never user (and would not suggest to do si) `FormattedHTMLMessage` as I don't think HTML should be part of a translation.
Also React is there for a reason and `FormattedHTMLMessage` kills it.

**Comment by szimek** [comment]
@DragonRaider5 Just curious - how do you handle translations like:
```
You agree with the <a href='{termsUrl}'>Terms of Use</a>, the <a href='{cancellationPolicyUrl}'>Cancellation Policy</a> and the <a href='{privacyUrl}'>Privacy Policy</a>.
```
?

**Comment by DragonRaider5** [comment]
I split it into separate components:
```
I agree with the {termsOfUse}, the {cancellationPolicy} and the {privacyPolicy}.
```
```js
const agreements = {
  termsOfUse: <Agreement message={messages.termsOfUse} url='...' />,
  cancellationPolicy: <Agreement message={messages.cancellationPolicy} url='...' />,
  privacyPolicy: <Agreement message={messages.privacyPolicy} url='...' />
}

export default () => (
  <FormattedMessage
    {...agreementMessage}
    values={agreements}
  />
)
```
Allows for full JSX in the agreements and makes the agreement strings + component reusable else where (e.g."Legal Infos" page).
Plus: translators don't need to know HTML.

**Comment by szimek** [comment]
Thank you! I'll investigate it a bit more, because it looks like a better solution than what we're doing currently. Fortunately, the translation service that we use, automatically figures out all html tags, interpolations etc. and provides a nice UI for translators, so they don't have to worry about it. 

Another issue we're having with some languages, mainly Japanese, that require us to use HTML, is that translators sometimes want to enter line breaks in the translated text, which requires us to add `<br>` tags.

**Comment by DragonRaider5** [comment]
Glad you like it!

Regarding Japanese translations: Maybe you can make use of the css property
```css
  white-sprace: pre-line;
```
and advise them to use the new line feed (perhaps there is a setting for this in the translation service you're using).

Depending on what you've set the `textComponent` on your `IntlProvider` to, you might even be able to do this in one sweep for all your `Formatted*` components.
