### ISSUE TITLE
IE & Edge bug: it doesn't format in fr_CA and de_DE correctly.

### ISSUE THREAD

**Issue by groverinho** [formatjs/react-intl#1288]
I'm trying to format the time in fr_CA and de_DE with `intl.formatTime(date)` but it returns different format in IE 11 and Edge browser.

### Expected behavior
fr_CA: _1 h 30 p.m._
de_DE: _4:00 PM_
### Current behavior
fr_CA: _1:30 ._
de_DE: _4.00 ._

On Chrome and Firefox works fine.

| Browser | Version |
| --- | --- |
| EDGE | 44.17763.1.0  |
| Internet Explorer | 11.192.16299.0 |

**Comment by DragonRaider5** [comment]
This most likely sparks from the way Microsoft implemented the API.

@redonkulus what do you think?

**Comment by redonkulus** [comment]
Makes sense, @groverinho can you see if there are any open MS bugs with this implementation?

**Comment by PerfectPixel** [comment]
I just tried this with `de-DE` (react-intl 2.8.0 / 2.9.0):
`<FormattedTime value={new Date('2019-01-01T16:15:00.000Z')} />` returns in Chrome, Firefox, Edge, and IE all the same `17:15` (its UTC+1 here). Which is correct.

`hour12` output of Edge and IE is a bit weird as it says `5:15 nachem.` while the other browsers show `5:15 PM`. However, nobody uses 12-hour format in German, spoken yes, written never.

**Comment by longlho** [comment]
Unfortunately this is a platform issue that's out of scope for this library :(
