### ISSUE TITLE
[RFC] Extract keys on build time

### ISSUE THREAD

**Issue by EduardoAC** [formatjs/react-intl#1292]
### FEATURE REQUEST

Currently, there is not feature that allow us to collect all the keys that need to be translated from the components and formatters in `React-intl` that means that we don't have an automate way to capture missing string in an effective way.

We are planning to work in a script that will extract all the keys through regular expressions and parse files which it's a feasible but expensive option.

### Wish behaviour

Given a folder where the package is installed, I would like to have a feature where we can extract all the keys from a repository.

For example:
Run command
```
yarn react-intl collect-translations src
```
`src` contains only one file `file.js`

``` src/file.js
import React, {Component} from 'react';
import ReactDOM from 'react-dom';
import {IntlProvider, FormattedMessage} from 'react-intl';

class App extends Component {
    ...

    render() {
        ...
        return (
            <p>
                <FormattedMessage
                    id="welcome"
                    defaultMessage="Hello world"
                />
            </p>
        );
    }
}

```

Result JSON file with following format
```
{
   "welcome":  "Hello world"
}
```

**Comment by redonkulus** [comment]
@EduardoAC You can also take a look at our babel plugin: https://github.com/formatjs/formatjs/tree/master/packages/babel-plugin-react-intl. Does this help you with what you need?

**Comment by EduardoAC** [comment]
@redonkulus that could make the work, I will try you and give you feedback. 🤞

**Comment by DragonRaider5** [comment]
This can be achieved as documented in the Babel-plugins README, using the `messagesDir` prop or the babel API.
