### ISSUE TITLE
Migrate to TS

### ISSUE THREAD

**Issue by longlho** [formatjs/react-intl#1306]
### Is this a BUG REPORT or FEATURE REQUEST? (choose one)
FEATURE REQUEST

### Expected behavior
We should migrate to TS incrementally since adding type allows easier contribution thanks to typechecking and clear APIs. This also means we'll get rid of TS issue due to DefinitelyTyped react-intl d.ts which is maintained separately from this repos.

All subrepos in formatjs/formatjs are already in TS so we can already write type-safe code here.

### Current behavior
TS definition are maintained separatedly in DefinitelyTyped/DefinitelyTyped 

cc @redonkulus 	@okuryu 	@leoyli @DragonRaider5

**Comment by leoyli** [comment]
Yeah, this sounds reasonable and pleasing to me.  But do we have a direction on the future improvements?

I don't want to say this, but his package let me feel it was half-way dead for a while after drop by Yahool!  I was happy to see the community is so strong (sticky?) and push this package close to v3 so I don't need to suffering from finding alternatives immediately.  That's been said, I actually have no confidence that this package is durable for much long term, and am thinking to migrate to `linguiJS` or `react-i18next`... To be more specific, I'm looking for a way to progressively load translation, and put my eyes close on React concurrent mode.

PS. I can make small contribution occasionally, but I don't have time to contribute as @DragonRaider5 or @redonkulus do, especially I've committed to support Storybook already...

**Comment by longlho** [comment]
I think at least from my POV this package is meant to do 1 thing and do it well, which is to provide React components and an API to native Intl primitives. linguiJS/i18next differentiates by providing comprehensive toolchain support, which IMO is an orthogonal problem to i18n. i18n itself is already complex and by staying as close to the spec & as lean as possible we're preparing for future spec churn as new Intl primitives are being defined. Toolchain support is a very messy place as well.

Right now as far as I can see, Intl spec has not actually utilized all of CLDR data yet, and new proposals are being made to use that (e.g [unified-intl-numberformat](https://github.com/tc39/proposal-unified-intl-numberformat) to handle things like `1 million` or `1M`). So for the foreseeable future I'll be working on impl for those in the [monorepo](https://github.com/formatjs/formatjs) and react-intl would get that benefit.

**Comment by DragonRaider5** [comment]
@longlho I completely agree!

@leoyli What makes you think progressive loading of translations isn't possible with `react-intl`?

**Comment by okuryu** [comment]
I'm confused by the title and description of this issue. What's this the purpose of this? To maintain the declarations file by formatjs team for TypeScript customers? To rewritten react-intl sources to TypeScript to improve maintability for formatjs team?

For the former, in my understanding, to do is to maintain only index.d.ts in this repository (we may need some test code). This is make sence to me to resolve problems that the type declarations file by DefinitelyTyped is volunteer maintenance and dealing with only the latest version of the react-intl.

Regarding the latter, I'm not against it, but I think we should work from a different perspective than the former problem.

**Comment by longlho** [comment]
It's both really since migration to TS means we officially support it and
codebase is typed which makes contributions easier (yarn recently migrated
to TS because of this)

**Comment by okuryu** [comment]
Thanks, I see. It sounds good.
