### ISSUE TITLE
addLocaleData v3

### ISSUE THREAD

**Issue by Fenopiu** [formatjs/react-intl#1307]
POSSIBLE BUG

Compiling I receive this error:

> Attempted import error: 'addLocaleData' is not exported from 'react-intl'.

### Expected behavior
Compiling without problem.

### Current behavior
It breaks and give this error:
> Attempted import error: 'addLocaleData' is not exported from 'react-intl'.

### Step to reproduce for BUG REPORT
`import { addLocaleData, IntlProvider, Locale } from "react-intl";`

### Your Environment
Visual Studio Code 1.34
"react": "^16.8.6",
"react-dev-utils": "^9.0.1",
"react-dom": "^16.8.6",
"react-intl": "^3.0.0-beta-7",
"react-redux": "^7.1.0-rc.1",
"react-router-dom": "^5.0.1",
"typescript": "^3.5.1",

| Executable | Version |
`npm ls react-intl` | 3.0.0-beta-7
`npm ls react` | 16.8.6
`npm --version` | 6.9.0
`node --version` | 10.15.1

| OS | Version |
macOS Mojave | 10.14.5

**Comment by longlho** [comment]
Yup we no longer load CLDR data in this lib since we rely on native Intl APIs now. Check out for potential polyfills :) https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#migrate-to-using-native-intl-api

**Comment by longlho** [comment]
I'll update the doc to reflect the fact that `addLocaleData` is no longer available as breaking change in the doc. I'll keep this open until that's resolved
