### ISSUE TITLE
Provider always sets locale to "en" on the server

### ISSUE THREAD

**Issue by rosskhanas** [formatjs/react-intl#1317]
It seems like `react-int` started using `intl-locales-supported` inside the Provider. However, `intl-locales-supported` checks for `Intl.Collator` and `Intl.Collator.supportedLocalesOf` always returns `en`. There is no polyfill available anywhere.

### Expected behavior

Provider receives passed `locale` and renders the page in that locale.

### Current behavior

Provider receives passed `locale` and renders the page in English.

### Step to reproduce for BUG REPORT

Render anything on the server.

### Your Environment
| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 3.0.0-beta-7 |
| `node --version` | v10.13.0 |

**Comment by rosskhanas** [comment]
There is related issue https://github.com/formatjs/formatjs/issues/12 but for some reason, it was closed.

**Comment by longlho** [comment]
I think you're running Node w/o ICU.
<img width="299" alt="Screen Shot 2019-06-11 at 1 03 21 PM" src="https://user-images.githubusercontent.com/198255/59291657-61a1b680-8c49-11e9-90d8-39bb39fd9d93.png">

**Comment by rosskhanas** [comment]
Thank you @longlho. Just in case other people have this problem, here is my solution:

```
yarn add full-icu
node --icu-data-dir=node_modules/full-icu ./app.js
```
