### ISSUE TITLE
Wrong date format for Slovakia

### ISSUE THREAD

**Issue by kalkusa** [formatjs/react-intl#1319]
### Expected behavior

As far as [Wikipedia says](https://en.wikipedia.org/wiki/Date_format_by_country) date format in Slovakia is `dd.mm.yyyy`, while in Slovenia it's `d. mm. yyyy or dd. mmmm yyyy`

### Current behavior
At this moment `formatDate` method used with `sk` locale generates `dd. mm. yyyy` formatted date.

### Step to reproduce for BUG REPORT
Modification of [Hello world example](https://github.com/formatjs/react-intl/tree/master/examples/hello-world):

App.js:

```
import React, {Component} from 'react';
import {
  injectIntl,
  intlShape,
} from 'react-intl';
import { addLocaleData } from 'react-intl';
import * as cs from 'react-intl/locale-data/cs';
import * as en from 'react-intl/locale-data/en';
import * as pl from 'react-intl/locale-data/pl';
import * as sk from 'react-intl/locale-data/sk';
import * as sl from 'react-intl/locale-data/sl';

addLocaleData(en[0]);
addLocaleData(pl[0]);
addLocaleData(cs[0]);
addLocaleData(sk[0]);
addLocaleData(sl[0]);

class App extends Component {
  
  render() {
    const {intl} = this.props;
    const date = intl.formatDate(new Date(),  { day: '2-digit', month: '2-digit', year: 'numeric' });
    return <div>{date}</div>;
  }
}

App.propTypes = {
  intl: intlShape.isRequired,
};

// export default App;
export default injectIntl(App);
```

index.js:

```
import React from 'react';
import ReactDOM from 'react-dom';
import {IntlProvider} from 'react-intl';
import App from './App';

ReactDOM.render(
    <IntlProvider locale="sk">
        <App />
    </IntlProvider>,
    document.getElementById('root')
);
```

### Your Environment

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.9.0 |
| `npm ls react` | 16.8.6 |
| `npm --version` | 5.6.0 |
| `node --version` | v8.11.4 |

| OS | Version |
| --- | --- |
| Windows 10 Enterprise | 10.0.17134 |

| Browser | Version |
| --- | --- |
| Chrome | 74.0.3729.169 |
| Firefox | 67.0 |

**Comment by longlho** [comment]
I think you're looking for `month: 'short'`
```
new Intl.DateTimeFormat('sl', { day: '2-digit', month: 'short', year: 'numeric' }).format(Date.now())
"12. jun. 2019"
```

**Comment by kalkusa** [comment]
@longlho 
Wait a second. I think you misunderstood me. I mean Slovakian date format should be without additional spaces: `dd.mm.yyyy`.

**Comment by longlho** [comment]
Thanks for the clarification!! This seems to be a data problem upstream w/ CLDR and I've created the ticket [here](https://unicode-org.atlassian.net/browse/CLDR-13107)

**Comment by dhlavaty** [comment]
@kalkusa FYI:
According to Slovak standard ( STN 01 6910 "Pravidlá písania a úpravy písomností pri písaní dátumu" ), version WITH spaces is the correct one. If the Wikipedia says the opposite, the wrong info is there.
