### ISSUE TITLE
Add `<FormattedList`> & `formatList`

### ISSUE THREAD

**Issue by longlho** [formatjs/react-intl#1328]
[`Intl.ListFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ListFormat) is stage 3 so API's stable enough for implementation.

**Comment by longlho** [comment]
@DragonRaider5 	do u wanna take this? Should be fairly straightforward. The only tricky thing is polyfill locale data but we can incrementally add it later on.

**Comment by redonkulus** [comment]
Looks like there is a polyfill that could be recommend as well. https://www.npmjs.com/package/intl-list-format

**Comment by petersendidit** [comment]
How do you see `<FormattedList>` working for a list of messages? 

```jsx
<FormattedList
  list={[
    <FormattedMessage id="message1" values={ num: 1 } />,
    <FormattedMessage id="messageA" />,
  ]}
/>

<FormattedList
  list={[
    intl.formatMessage({ id: 'message1', values: { num: 1 } }),
    intl.formatMessage({ id: 'messageA' }),
  ]}
/>

<FormattedList
  list={[
    { id: 'message1', values: { num: 1 } },
    { id: 'messageA' },
  ]}
/>
```

**Comment by longlho** [comment]
Good question. I haven't thought about it and am open to suggestions.

**Comment by DragonRaider5** [comment]
I'd say that's up to the user. Can be done using `useIntl` or `injectIntl`.

**Comment by petersendidit** [comment]
Guess the real question is will something like this work? Will FormattedList take in a list of react elements?
```jsx
<FormattedList
  list={[
    <FormattedMessage id="message1" values={ num: 1 } />,
    <FormattedMessage id="messageA" />,
  ]}
/>
```
If so then how will it handle when it's passed in a list of elements that aren't `FormattedMessages`?
```jsx
<FormattedList
  list={[
    <Widget>This is my <strong>Message</strong></Widget>
    <FormattedMessage id="messageA" />,
  ]}
/>
```

**Comment by longlho** [comment]
I have to dig into ICU messageformat/other references to see how these cases get handled. Will get back to u

**Comment by longlho** [comment]
This also opens up opportunity to do more granular relative time like `5 minutes and 45 seconds ago`

**Comment by longlho** [comment]
data source https://github.com/unicode-cldr/cldr-misc-full/blob/c0b0e878ecb76d2bbc1f61b6c0f986e356fbb97c/main/en-001/listPatterns.json

**Comment by bertho-zero** [comment]
Will it be possible to use `list`s in a `formatMessage`?

Example: `Les champs {fields, list} sont obligatoires`

**Comment by longlho** [comment]
Unfortunately the spec doesn't have that and also discourage from introducing more custom embedded format. MessageFormat v2 is tackling that I believe.
