### ISSUE TITLE
Do you have any option to return currency not number?

### ISSUE THREAD

**Issue by GnanaprakashChandiran** [formatjs/react-intl#1329]
I need a currency symbol based on currency.

I used formatNumber, its return currency symbol with NaN.

**My Requirement:** 

Example:

Input:
Currency: EUR

Expected Resultt: €

**Comment by longlho** [comment]
I don't think we support that in this library, but you can get that via the native `Intl.NumberFormat` API, e.g:

```js
new Intl.NumberFormat('es', {
	style: 'currency', 
	currency: 'EUR', 
	currencyDisplay: 'symbol' 
})
.formatToParts(1)
.filter(p => p.type === 'currency')[0].value
// €
```

**Comment by longlho** [comment]
This might be something we wanna support in https://github.com/formatjs/formatjs instead so feel free to open an issue there
