### ISSUE TITLE
Switch back to NPM

### ISSUE THREAD

**Issue by DragonRaider5** [formatjs/react-intl#1332]
Hey,

as NPM is quite mature at this point (and I think more common as it's the default package manager installed with Node) I wanted to suggest switching back to NPM for this package.

Thoughts?

Edit 1: Spelling.

**Comment by longlho** [comment]
Yeah let's do it!

**Comment by redonkulus** [comment]
Agreed. Let’s remove yarn and use npm. Please feel free to open a PR.
