### ISSUE TITLE
Make react-intl choose messages instead of providing them directly in IntlProvider (with bug)

### ISSUE THREAD

**Issue by croraf** [formatjs/react-intl#1333]
**Is your feature request related to a problem? Please describe.**
In the top level IntlProvider I have to manually provide locale object in messages. I would rather provide the messages wrapper.
```
const messages = {
  en: messages_en,
  de: messages_de,
  fr: messages_fr,
}

<IntlProvider 
     locale={locale}
     messages={messages[locale]}  ////<-have to specify locale messages
> 
     <MainRouter />
</IntlProvider>
```

**Describe the solution you'd like**
Why not just provide the wrapper
```
const messages = {
  en: messages_en,
  de: messages_de,
  fr: messages_fr,
}

<IntlProvider 
     locale={locale}
     messages={messages}  ////<-depending on the locale already given the exact subset is selected
> 
     <MainRouter />
</IntlProvider>
```

**Describe alternatives you've considered**
The current solution is the alternative. I don't know any problems with my proposal, but perhaps there are some.

**Additional context**
My proposal seems more natural, and with current proposal I encounter the following problem (bug):
When for example french locale is not initialized with `addLocaleData({ locale: 'fr', pluralRuleFunction: () => {}, });` it fallbacks to `en` locale but it still takes the messages from the `messages[fr]`.

**Comment by DragonRaider5** [comment]
Hey, thanks for your proposal!

In my opinion we should not change this, as it would encourage bad practice - to load all the translations at once.

However the fallback to english locale concerns me.
Should we maybe use the default messages in this case?

**Comment by longlho** [comment]
We prefer reducing complexity by delegating message locale resolution upstream since locale is more than just `en` or `de`, it's a full BCP-47 lang tag which can embed things like `numberingSystem` & Gregorian calendar, e.g `en-001-latn`...
