### ISSUE TITLE
Provide a way pass in already parsed messages by messageformat-parser

### ISSUE THREAD

**Issue by twop** [formatjs/react-intl#1335]
**Is your feature request related to a problem? Please describe.**
I need a way to provide precomputed AST instead of string to `IntlProvider`

**Describe the solution you'd like**
Either a new Provider component or overload for `IntlConfig`

```ts
// now
export interface IntlConfig {
  messages: Record<string, string>;
  // other props
}

// proposed
export interface IntlConfigV2 {
  messages: Record<string, string> | Record<string, AST>;
  // other props
}
```

**Describe alternatives you've considered**
Seems that it is not possible today?

**Additional context**
My understanding that the format used internally is  https://github.com/messageformat/messageformat/tree/master/packages/parser.

In our project we have an ability to precompute AST produced by it and save a little bit of time at runtime. Thus the ask to get a first class API support for that :)

Brainstorming potential API imlementations:
1. Accept a new shape for messages
```ts
export interface IntlConfig {
  messages: Record<string, string> | Record<string, AST>;
  // other props
}
```
Cons: maybe hard to disambiguate at runtime?

2. New Provider component
```ts

export const NewIntlProvider : React.FC<NewIntlConfig>  = props => {....} 
export interface NewIntlConfig {
  parsedMessages: Record<string, AST>;
  // other props
}
```
Cons: wider api surface area?

3. Make a new prop `parsedMessages` but require that only one of them would be present
```ts
export interface IntlConfig {
  messages?: Record<string, string>;
  parsedMessages?: Record<string, AST>;
  // other props
}
```

Cons: you can skip both of them and get only a runtime error (assuming ts usage). One way to type it is something like:
```ts
interface A { a: string, b?: never }
interface B { a?: never, b: string }
type Real = A | B
```

**Comment by longlho** [comment]
Since `intl-messageformat` already takes in AST [here](https://github.com/formatjs/formatjs/blob/master/packages/intl-messageformat/src/index.ts#L127) this shouldn't be too hard to wire up in v3 👍

**Comment by longlho** [comment]
@redonkulus 	@DragonRaider5 	@leoyli I do plan to support this. The other benefit is that we can expose a more lightweight version of react-intl w/ the parser from `intl-messageformat-parser` as part of an "Advanced" use case, this would drop the size by 30% (https://bundlephobia.com/result?p=react-intl@3.0.0-beta-10). Thoughts?

**Comment by longlho** [comment]
@twop I believe this might already be working, the PR just modifies types
