### ISSUE TITLE
useIntl hook documentation version

### ISSUE THREAD

**Issue by hamuk** [formatjs/react-intl#1336]
Hey just a small issue I've noticed in the documentation. In the hooks section it doesn't mention anything about them only being available in the 3.0.0 beta. I love the new hooks syntax so pretty excited to use it!

**Comment by longlho** [comment]
Thanks for submitting the issue. We have it in the [Upgrade Guide](https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#new-useintl-hook-as-an-alternative-of-injectintl-hoc). What is the hooks section u're mentioning?

**Comment by hamuk** [comment]
It's in the API section, [https://github.com/formatjs/react-intl/blob/master/docs/API.md#useintl-hook](https://github.com/formatjs/react-intl/blob/master/docs/API.md#useintl-hook)

**Comment by redonkulus** [comment]
Thats correct, we could probably add a "Available in 3.x" subtitle to be clearer. Want to PR it?
