### ISSUE TITLE
V3 Missing locale data

### ISSUE THREAD

**Issue by royderksroute42** [formatjs/react-intl#1339]
Using v2 worked fine, but I wanted to try out the hooks so I removed the addLocaleData, added the polyfills and prayed it would work. It doesn't, and i can't figure out why. Locale and message arive fine in the provider. It works fine for `en` locale

### Expected behavior

After removing addLocaleData for it to magically work with the polyfills added from the migration guide

### Current behavior

Shows default messages and errors out with :
`index.js?69b4:3671 [React Intl] Missing locale data for locale: "nl". Using default locale: "nl" as fallback.`

```
index.ts
import 'intl-pluralrules/polyfill';
import '@formatjs/intl-relativetimeformat/polyfill';
import '@formatjs/intl-relativetimeformat/dist/locale-data/nl';
import '@formatjs/intl-relativetimeformat/dist/locale-data/en';
```

```
const curLang = 'nl';
const messages = // dutch messages object, worked fine with v2
 <IntlProvider  defaultLocale={curLang} locale={curLang} key={curLang} messages={messages}>
              <App />
      </IntlProvider>
```
### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | react-intl@^3.0.0-beta-8 |
|      `npm ls react` | react@^16.3.0 |
|     `npm --version` | 6.9.0 |
|    `node --version` | v11.12.0 |

| OS   | Version | lang |
| ---- | ------- |---- |
| macOS Sierra | 10.14.4 | | English |

| Browser | Version | lang |
| Chrome | 75.0.3770.100 (Official Build) (64-bit) | English |

**Comment by longlho** [comment]
Thanks for reporting, we'll take a look asap

**Comment by longlho** [comment]
Can you do a `npm ls intl-locales-supported`? I can't seem to repro it

**Comment by royderksroute42** [comment]
Running that command gives:
`└── (empty)`

Adding the package didn't help.

**Comment by royderksroute42** [comment]
Hmmm this is odd, on safari it works perfectly fine.
`Version 12.1 (14607.1.40.1.4)`

**Comment by longlho** [comment]
Do you have the same issue on master?

**Comment by longlho** [comment]
We just released beta-10, you mind giving that a try? Thanks!

**Comment by royderksroute42** [comment]
Running on beta 10 seems to have fixed the issue, works like a charm!

**Comment by lcordier42** [comment]
Hi, I encountered the same problem in beta-18, I just get back to beta-17 and it's working!

**Comment by darekkay** [comment]
I can confirm it's broken in the latest versions. The `node_modules/react-intl/locale-data/`` folder ist missing.
It doesn't even work for `beta.17` for me. `beta-10` seems to work, though.

**Comment by longlho** [comment]
We no longer ships `locale-data`. Please see https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#migrate-to-using-native-intl-apis for migration steps.

**Comment by vishalrajole** [comment]
I am facing same issue on     
`"react-intl": "=3.11.0"`
Any fix?

**Comment by JeremyRichert** [comment]
Hi, same thing here with react-intl 3.11.0:
```
console.error node_modules/react-intl/dist/utils.js:54
    [React Intl] Missing locale data for locale: "fr". Using default locale: "en" as fallback.
```
Thanks in advance :)

**Comment by caike** [comment]
Same issue using v3.12.0

**Comment by longlho** [comment]
Our doc should provide some details on this https://github.com/formatjs/react-intl/blob/master/docs/Getting-Started.md#nodejs

**Comment by tr00st** [comment]
For reference for the next person trying to trawl through this issue, the docs are no longer in the repo, so the above links are broken. See their new locations:

https://formatjs.io/docs/react-intl/upgrade-guide-3x
https://formatjs.io/docs/runtime-requirements#nodejs

**Comment by mmudunuri** [comment]
I still have the same issue in v3.2.4? any help to resolve it apart from the original documentation

**Comment by mmudunuri** [comment]
> For reference for the next person trying to trawl through this issue, the docs are no longer in the repo, so the above links are broken. See their new locations:
> 
> https://formatjs.io/docs/react-intl/upgrade-guide-3x
> https://formatjs.io/docs/runtime-requirements#nodejs

https://formatjs.io/docs/guides/runtime-requirements/#nodejs
