### ISSUE TITLE
Dead links in documentation

### ISSUE THREAD

**Issue by bartolkaruza** [formatjs/react-intl#1341]
While trying to figure out an issue regarding the locale import, I've run into the following issue with the documentation; all of the links at this section are dead:

https://github.com/formatjs/react-intl/blame/master/docs/API.md#L8-L12

I would gladly help to edit it if I knew where the content is moved, but I unfortunately don't.

**Comment by longlho** [comment]
Thanks for reporting. We'll remove those links asap. In the latest beta-10 version of `react-intl` we no longer load locale data within this library anymore and rely on polyfills instead. The docs unfortunately points to v2 instead.

What's the locale import issue? Our [Upgrade Guide](https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#migrate-to-using-native-intl-apis) should cover any locale data issue.

**Comment by longlho** [comment]
fixed
