### ISSUE TITLE
TypeScript error: Cannot find name 'Omit'

### ISSUE THREAD

**Issue by ipanasenko** [formatjs/react-intl#1346]
Hey, guys.
Updated to latest beta (12) and project won't compile:
```
Type error: Cannot find name 'Omit'.  TS2304

    11 |     [k in IntlPropName]: IntlShape;
    12 | };
  > 13 | declare type WithIntlProps<P> = Omit<P, keyof WrappedComponentProps> & {
       |                                 ^
    14 |     forwardedRef?: React.Ref<any>;
    15 | };
    16 | export default function injectIntl<IntlPropName extends string = 'intl', P extends WrappedComponentProps<IntlPropName> = WrappedComponentProps<any>>(WrappedComponent: React.ComponentType<P>, options?: Opts<IntlPropName>): React.ComponentType<WithIntlProps<P>> & {
```

Error is coming from `node_modules/react-intl/dist/components/injectIntl.d.ts`.

My TypeScript version is 3.4.5.

Can you have a look, please? Thanks!

**Comment by ipanasenko** [comment]
Issue appeared in version `3.0.0-beta-10`

**Comment by longlho** [comment]
Omit was introduced in TypeScript 3.5 I believe. Can you try upgrading your
TS?

**Comment by ipanasenko** [comment]
Unfortunately I can't, because it breaks something else. I think you should specify TS version requirements somewhere, or remove `Omit`

**Comment by longlho** [comment]
yeah I'll drop the TS version and add that as `peerDep`
