### ISSUE TITLE
SyntaxError: invalid regular expression in React Native

### ISSUE THREAD

**Issue by igin** [formatjs/react-intl#1356]
### Step to reproduce for BUG REPORT
Have an app in react-native that first renders a splash screen an then after the app is loaded renders the app with an IntlProvider at the root. I couldn't reproduce this in a minimal app setup though. So there might be more specific properties of our app that make this fail.

### Expected behavior
Once the splashscreen disappears the app renders with the currently loaded locale.

### Current behavior
Once the splashscreen disappears an error is shown: 
![Screenshot_20190708-131853](https://user-images.githubusercontent.com/1157516/60806590-b3bff400-a183-11e9-926e-a114c2e0290f.jpg)

### Your Environment
```
    "react": "16.8.6",
    "react-intl": "3.0.0-beta.14",
    "react-native": "0.59.8",
```
This only happens while running the debug version on the phone (tested with android). If I attach the remote debugger (chrome browser) no error occurs.

Another strange thing is that if I insert ```console.log('hello', 'world')``` (notice that there are two arguments) in the constructor of IntlProvider the error doesn't occur anymore. ```console.log('hello')``` still fails. We therefore suspect it is somehow a timing issue. Although it is very reproducible with our setup so that speaks more for a weird side effect of console.log with two arguments that we are not aware of.

Any hints on where this error comes from would be appreciated.

**Comment by longlho** [comment]
Might be related to Intl.js polyfill. Do you guys use it? If you do can you
try removing it?

**Comment by igin** [comment]
Yes will try that.

**Comment by igin** [comment]
Removed the polyfill but React-Native doesn't seem to provide a Intl variable. Therefore it fails in provider.js: "Can't find variable Intl"

**Comment by longlho** [comment]
What runtime env are you running this in? Intl is supported in like IE11+

**Comment by igin** [comment]
React-Native JSC on Android ... I am looking into enabling Intl there now ...

**Comment by igin** [comment]
Yeah so configuring react-native to use an internationalized and update JavaScript core fixes the issue. I followed the steps described in 

https://github.com/react-native-community/jsc-android-buildscripts#for-react-native-version-059

and 

https://github.com/react-native-community/jsc-android-buildscripts#international-variant

to get everything working again.

**Comment by longlho** [comment]
Thanks for reporting I’ll update our docs to account for this issue!

**Comment by longlho** [comment]
closed via 8b4fc9bea0350314277fc83fccc7823e7d7f09ee

**Comment by sarmad1995** [comment]
@longlho 
I am getting this issue on IOS as well, any solution?

**Comment by longlho** [comment]
using Intl.js polyfill might be your best bet

**Comment by pca-homsi** [comment]
try to add this
Intl.__disableRegExpRestore()

**Comment by zabojad** [comment]
I use RN 0.61. I've installed latest jsc and put `def useIntlJsc = true` at the top of my `android/app/build.gradle` file but I still get `Reference Error: Can't find variable: Intl`.

Anyone experiencing the same thing?

@igin, did you move to RN 0.61?

**Comment by AlirezaInGitHub** [comment]
@zabojad Same problem here.
```
    "jsc-android": "^241213.1.0",
    "react": "16.9.0",
    "react-intl": "^4.3.1",
    "react-native": "^0.62.2",
```

**Comment by peterwiebe** [comment]
For anyone who has arrived here because they are using the Hermes engine and can't upgrade to `react-native@0.65` formatJS will not work for you (as far as I have been able to test at this point) because Hermes doesn't included the Intl api until 0.65.

**Comment by longlho** [comment]
We have polyfills. `intl.js` is archive but we've basically polyfilled all Intl APIs https://formatjs.io/docs/polyfills

**Comment by lucasbasquerotto** [comment]
I was able to solve issues of `react-intl` in Android using Expo (React Native) by using the Hermes Engine, defining:

```
"android": {
    ...
    "jsEngine": "hermes"
}
```

in `app.json` (https://docs.expo.dev/guides/using-hermes/).

I tried using `intl.js` but not only is the library deprecated, but it also gave lots of errors in certain cases like formating date and times (it was formatted wrong).
