### ISSUE TITLE
Update examples for v3

### ISSUE THREAD

**Issue by chimericdream** [formatjs/react-intl#1362]
[Translations example in this repo](https://github.com/formatjs/react-intl/tree/master/examples/translations)
[intl-messageformat-parser](https://github.com/formatjs/formatjs/tree/master/packages/intl-messageformat-parser)

With the changes made to `intl-messageformat` with 5.0, the translations example no longer works. It looks like `translator.js` and `printer.js` need to be modified to parse the AST correctly.

Since the latest version of `react-intl` is still technically a beta, I assume updating the examples has been a lower priority.

### Expected behavior

The examples should work with the latest versions of `react-intl` and related libs.

### Current behavior

See above. The new AST causes errors when running code copied from the example.

### Step to reproduce for BUG REPORT

* In a project using the latest beta of `react-intl` (the example is out of date and does not currently run at all), add a `build:langs` step like the one in the example, including the code to produce an "en-UPPER" locale.
* Run the script via `npm run build:langs`
* The script should fail

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | react-intl@3.0.0-beta.16 |
|      `npm ls react` | react@16.8.6 |
|     `npm --version` | 6.10.0 |
|    `node --version` | v12.6.0 |

| OS   | Version |
| ---- | ------- |
| Windows 10 | 1809 |

| Browser | Version |
| ------- | ------- |
| n/a    | n/a |

**Comment by longlho** [comment]
Thanks for reporting this we’ll fix it asap

**Comment by chimericdream** [comment]
No rush. I know that the actual code takes precedence, and it's still technically a beta release.

For anyone in the same situation, here's the workaround I am using to continue generating an "en-UPPER" locale for my users to test with:

`package.json`
```
"devDependencies": {
  ...
  "intl-messageformat-parser": "^2.0.1",
  "intl-messageformat-parser-legacy": "npm:intl-messageformat-parser@^1.8.1",
  ...
},
```

`scripts/lib/translator.js`
```
// Comment this line:
// import {parse} from 'intl-messageformat-parser';
// Replace with this:
import {parse} from 'intl-messageformat-parser-legacy';
```

It's worth noting that this only works with **npm 6.9.0 and above**, since package aliasing was only recently added. I don't use yarn, but I believe it supports a similar alias syntax.

**Comment by longlho** [comment]
@chimericdream PR's welcome as well :)
