### ISSUE TITLE
FormatMessage tagName does not seems to support styled-component very well

### ISSUE THREAD

**Issue by WillWuCaminer** [formatjs/react-intl#1363]
### Expected behavior

No Prop type checking warning in the Browser console

### Current behavior

![image](https://user-images.githubusercontent.com/45704808/61019989-bb270d80-a3ce-11e9-8a50-6393de9dc1d5.png)

### Step to reproduce for BUG REPORT

I try to use `FormattedMessage` in this way: 

```
const Title = styled.p`
  margin-top: 30px;
  text-align: center;
`;
<FormattedMessage tagName={Title} id={messageId} />
```

It works and passes typescript checking,  but I find some warnings in my Chrome browser console like the picture above.

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 2.9.0  |
|      `npm ls react` | 16.8.6  |
|     `npm --version` | 6.4.1 |
|    `node --version` | 10.15.3 |

| OS   | Version |
| ---- | ------- |
| macOS Majove | 10.14.5 |

| Browser | Version |
| ------- | ------- |
| Chrome    | 75.0.3770.100 |

**Comment by longlho** [comment]
Can you try out react-intl@next? That’s our latest beta.

**Comment by WillWuCaminer** [comment]
@longlho Are there any changes in the 3.0.0 beta version of importing `addLocaleData` ? There is an error in my teminal:

```
Attempted import error: 'addLocaleData' is not exported from 'react-intl'.
```

**Comment by redonkulus** [comment]
Take a look at our upgrade guide for details: https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#breaking-api-changes

**Comment by WillWuCaminer** [comment]
@redonkulus Got it, thanks!

**Comment by DragonRaider5** [comment]
This is not an issue with `styled-components` but with the prop types on `2.9.0`.
