### ISSUE TITLE
FormattedRelativeTime should support Date: `value: number | Date`

### ISSUE THREAD

**Issue by Arseniy-II** [formatjs/react-intl#1364]
**Is your feature request related to a problem? Please describe.**
I have to count days between two dates by myself. Previously `FormattedRelative` accepted value as a `Date`

**Describe the solution you'd like**
I would like same solution as it was for old component `FormattedRelative`. Component should count difference between now and date provided

**Additional context**
It would be nice if component will also accept strings

**Comment by longlho** [comment]
We've created `@formatjs/intl-utils` to ease the migration out of `intl-relativeformat`. Instructions are [here](https://github.com/formatjs/intl-relativeformat#migration-guide). You can basically do:

```ts
import { selectUnit } from '@formatjs/intl-utils';
const {value, unit} = selectUnit(Date.now() - 48 * 3600 * 1000);
// render
<FormattedRelativeTime value={value} unit={unit} />
```

**Comment by Arseniy-II** [comment]
@longlho this package is archived. 
And I don't like idea installing additional library and using utils.
I believe it would be better to have that feature out of the box.
Is there any reasons against it?

**Comment by longlho** [comment]
yup we've included the reasoning in our [Upgrade Guide](https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#formattedrelativetime)

**Comment by StorytellerCZ** [comment]
@longlho Would be nice to add your additional reasoning and the example how to get the functionality of v2 back, to the migration guide.

**Comment by longlho** [comment]
Mind creating a new gh issue for it?

**Comment by StorytellerCZ** [comment]
@longlho Created a PR: https://github.com/formatjs/react-intl/pull/1374
