### ISSUE TITLE
Uncaught TypeError: hoistNonReactStatics is not a function

### ISSUE THREAD

**Issue by nicolasbrugneaux** [formatjs/react-intl#1365]
### Expected behavior

react-intl doesn't crash

### Current behavior

react-intl crashes
![Screen Shot 2019-07-11 at 16 45 09](https://user-images.githubusercontent.com/3650621/61060863-87161180-a3fb-11e9-972e-3c6826439e7a.png)

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.0.0-beta.17 |

**Comment by longlho** [comment]
this seems like a `parcel` issue with `import` interop

**Comment by nicolasbrugneaux** [comment]
After quick investigation, this has been introduced in the recent commit: https://github.com/formatjs/react-intl/commit/0a6ca3f490283a4250d10b4d253ed3098ba85df5#diff-47c4eca2e98a5c48d07400da10351794 that uses `require` instead of `import`.

**Comment by longlho** [comment]
`require` is actually more correct, but that module doesn't export anything and namespace isn't callable.

**Comment by nicolasbrugneaux** [comment]
> `require` is actually more correct, but that module doesn't export anything and namespace isn't callable.

Alright, then maybe my PR isn't so helpful after all 😞 What would you suggest to make it work with parcel?

**Comment by longlho** [comment]
oh no you might be correct. Sorry I was looking at a different version. It looks like it does `export default` actually. Let me check the typings as well. Will get back soon.

**Comment by nicolasbrugneaux** [comment]
Okay so changing that line def. breaks the tests.

**Comment by longlho** [comment]
Nvm their dist uses `commonjs`. What's your `parcel` config? (specifically how are you transpiling your code?)

**Comment by nicolasbrugneaux** [comment]
Out of the box, no config file

**Comment by longlho** [comment]
1 of the workaround u can do is to import from `react-intl/dist/react-intl.js` just to unblock yourself for now.

**Comment by longlho** [comment]
The other thing u can try is aliasing `hoist-non-react-statics` (https://parceljs.org/module_resolution.html):

```
"alias": {
	"hoist-non-react-statics": "node_modules/hoist-non-react-statics/src/index.js"
}
```

**Comment by nicolasbrugneaux** [comment]
Either solutions didn't quite work (they break the build for the other users of `hoist-non-react-statics` (such as grommet). I was experimenting with `useIntl()` hook. But my master build is using 2.9.x release so I'll just rollback to that for the moment. Let me know if you find a fix!

**Comment by longlho** [comment]
if u have a sample reproducible repo that'd be great. Thanks for reporting!

**Comment by nicolasbrugneaux** [comment]
actually in a clean repo it works great... maybe I overlooked compatability issues with other things. 
This is being used in a lerna monorepo, I'll investigate a bit more when I have time.

**Comment by longlho** [comment]
thanks! I'll keep this open for now
