### ISSUE TITLE
v3 in react native

### ISSUE THREAD

**Issue by lithin** [formatjs/react-intl#1370]
It's very possible this isn't a bug report, it's just not entirely obvious from current docs how to upgrade to v3 in react native.

### Expected behavior

Everything works fine in RN after upgrading to v3 & updating dependencies

### Current behavior

After upgrading, translations with plural fail. In the upgrade docs, it states requirements for polyfilling in older browsers but it doesn't mention RN at all. Example of the message:

```
{
     defaultMessage: `Updated {minutes, plural,
            one {a minute}
            other {# minutes}
     } ago`,
     id: 'last-updated.updated-x-minutes-ago',
},
```

### Step to reproduce for BUG REPORT

- in an RN project with plural translations, upgrade to v3
- remove mentions of `react-intl/locale-data/*`
- remove `addLocaleData`
- run app and see error :)

<img src="https://user-images.githubusercontent.com/6726858/61186422-12421200-a65d-11e9-8af6-2c2c984647e1.png" alt="Error screenshot" width="400" />

### Your Environment

Running RN 0.59.x, behaviour observable on iOS simulator (iPhone 8)

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` |3.0.0.-beta.18 |
|      `npm ls react` | 16.8.x |
|     `npm --version` | 6.4.1 |
|    `node --version` | 10.15.3 |

| OS   | Version |
| ---- | ------- |
| iOS | iPhone 8, XCode 10.2 |

**Comment by longlho** [comment]
Does this help?
https://github.com/formatjs/react-intl/blob/master/docs/Getting-Started.md#intl-in-react-native

You might need intl-pluralrules & formatjs/intl-relativetimeformat
polyfills as well

**Comment by lithin** [comment]
That solved some issues, thanks @longlho !

Although most things are resolved now, I struggle with `FormattedRelativeTime` now. Using a component like `<FormattedRelativeTime value={0} />` (following the docs), I still get an error:

<img width="356" alt="Screenshot 2019-07-16 at 14 13 36" src="https://user-images.githubusercontent.com/6726858/61318905-1ba1ba80-a7d4-11e9-9a32-60a7f3b17dd3.png">

I did add `require('@formatjs/intl-relativetimeformat/polyfill');` to make sure we have the correct polyfill. I also logged out `locale` in `formatRelativeTime` and it says `en-us` as expected 🤔

**Comment by longlho** [comment]
Do u have a sample repo for this? Sorry I don't dev in react-native so it's hard to say for sure w/o some sample code

**Comment by lithin** [comment]
That was actually a great shout - I tried it in a new repo and it worked. It turns out our issue was that we supply `locale` into `IntlProvider` as `en-gb` (which works fine in v2) but the correct way in v3 is:

```
<IntlProvider local="en">...</IntlProvider>
```

Having said that, there's another hiccup I found. I think this piece of code
```
<FormattedRelativeTime value={0} unit="day">
```
should return `Today` for `en` locale but return `In 0 days`. Is that an intentional change or a bug? And is it relevant to this repo or the polyfill? 🤔

**Comment by longlho** [comment]
To get “today” you have to set numeric=“auto”

**Comment by longlho** [comment]
En-GB should work. Let me investigate that on our side. Thanks!

**Comment by lithin** [comment]
Amazing, thank you! Either way I think our issues have been resolved so I'm happy to close this issue. Thanks so much for your help :)

**Comment by longlho** [comment]
Would you mind opening 1 for the en-gb issue? Thanks a lot for reporting!!

**Comment by lithin** [comment]
Sure will do!

Before I close this one, if I use this

```
<FormattedRelativeTime value={-10,407,600,000} />
```

the outcome I see is `10,407,600,000 seconds ago`. I tried all kind of styles etc but nothing seemed to make it work the way it's described in the docs (ie going from `10 seconds ago` to `1 minute ago`) but it seems to be "stuck" on seconds. Is it because I'm doing something wrong or is that a bug? :)

**Comment by longlho** [comment]
Can you describe the use case? The default `unit` is always `second` which is why it renders that way.

**Comment by lithin** [comment]
Oh I thought it was the intended behaviour (based on the docs). This is what I mean:

<img width="339" alt="Screenshot 2019-07-24 at 15 59 54" src="https://user-images.githubusercontent.com/6726858/61804634-2db2d700-ae2c-11e9-83f2-e82545e31703.png">

We have some cases in which a time range can go from seconds to months - I know we can set units based on the . value but I assumed this was built in?

**Comment by longlho** [comment]
ohhh sorry that was definitely bad documentation then. I'll try to clarify it as much as possible in the docs, but the gist is:
1. In order for it to auto-update, u gotta turn on `updateIntervalInSeconds`.
2. Setting the `unit` will control the initial `unit` before it updates, e.g:
```tsx
<FormattedRelativeTime value={-1} unit="minute" updateIntervalInSeconds={10000} />
// initially render "1 minute ago"
// After 60s, it will render "2 minutes ago"
// After 59m, it will render "1 hour ago"
```

We don't auto-update more than days, simply bc the max timeout value in `setTimeout` exceeds #s of millis in a day.

**Comment by lithin** [comment]
Hmmmm that's fair enough, if you want it to be updated at certain intervals. In our case however, we quite often use this component to get relative time without needing it to update at all, for much larger time scales - from minutes to days to months (we essentially have sensors and display logs of activity they captured - which can be anything from a few seconds ago to months ago).

**Comment by longlho** [comment]
Yeah you can do that with setting the unit to “month”.

**Comment by lithin** [comment]
I can't set a `unit` longer than an hour if I'm using `updateIntervalInSeconds` which in turn is required for correctly changing from `30 seconds` to `3 hours` etc 🙈 Ideally I'd want to be able to do something like
```
<FormattedRelativeTime value={123456} unit="second" />
```
where the unit would be "flexible" in the sense that if it's too many seconds, it'll automatically use a higher (more sensible) unit.

I know I could write a wrapper for the component to make that work butI just hoped it'd be there . out of the box :D I'd be happy to write it/contribute but if this isn't at all your vision, I'm happy to figure it out in our codebase only.

**Comment by longlho** [comment]
ah looks like you're looking for a "best fit" behavior. We documented that as part of the Upgrade Guide here https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#formattedrelativetime

You can use @formatjs/intl-utils to get close to the previous behavior like this:

```tsx
import {selectUnit} from '@formatjs/intl-utils';
const {value, unit} = selectUnit(Date.now() - 48 * 3600 * 1000);
// render
<FormattedRelativeTime value={value} unit={unit} />;
```
Does that work?

**Comment by lithin** [comment]
Ohhh sorry missed that one! I think we don't mind in particular which way we go for things like "last week" vs "3 days ago" so we're all good. 

We did notice one more quirk though - if I'm using `selectUnit`, it considers a "quarter" as a usual unit. However I think that's quite specific to the US, we wouldn't use it in British English (or any other language in Europe that I'm aware of). I'm wondering if there's a way of setting up which thresholds we'd want? Or make this locale-specific?

Thanks so much for your help, it's been incredibly useful! 🙏

**Comment by longlho** [comment]
Ah so this is 1 of those cases where it's consumer requirement-specific. `quarter` is available in CLDR across a lot of languages (e.g `ar-DJ` https://github.com/unicode-cldr/cldr-dates-full/blob/master/main/ar-DJ/dateFields.json). I understand that it might not be used a whole lot, but from our perspective as a translation library unfortunately we can't make that distinction :(

Looks like you guys are looking for hybrid of auto-update `best fit` if it's less than a day, then manual unit conversion otherwise w/ only a selective set of unit. This is pretty complex for this library and I think it might have to be in user land for now.

The full list of unit is also quite large to account for things like `last Sunday`, `2 Sundays ago`...

**Comment by lithin** [comment]
I checked all the CLDR stuff and I find it a bit... bizarre? :) But I totally understand that it's not . something you'd (want to) change.

I'm thinking it'd be nice to have an option to skip some of these thresholds. Like you have option to change the threshold for seconds etc:
```
interface Threshold {
  second: number;
  minute: number;
  hour: number;
}
```
I wonder if we could have booleans for `days, week, quarter & year` so we can tell it to ignore that threshold? I'm nearly certain that `quarters` wouldn't be actually used by anyone in Europe so that's quite a big use-case :)

**Comment by longlho** [comment]
hmm I think that's possible, PR's definitely welcome :)

**Comment by lithin** [comment]
Great, happy to put something together. I'll open a new issue to track it and chat about the api :)

**Comment by kopax** [comment]
In which version does the fix has been released with please ?
