### ISSUE TITLE
[React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.

### ISSUE THREAD

**Issue by HowardTangHw** [formatjs/react-intl#1372]
```js
// root js
ReactDOM.render(
    <IntlProvider locale="en">
      <App />
    </IntlProvider>,
    document.getElementById('root')
  );
```

```js
// app.js
class App extends React.Component{
    componentDidMount(){
       const div = document.createElement('div');
       document.getElementById('app').appendChild(div);
        ReactDOM.render(<div>
            <FormattedMessage id='search_form_status' />
        </div>, div);
    }
    render(){
        <div id="app">Hello React intel</div>
    }
}
```

Show Error: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.

What should i do?

"react-intl": "^2.9.0",

**Comment by HowardTangHw** [comment]
i use `injectIntl` & `formatMessage` functio can fix it ,
but i want to know what happened

**Comment by HowardTangHw** [comment]
below code can fix it 
I don't know if it's the right way
```js
 componentDidMount(){
       const div = document.createElement('div');
       document.getElementById('app').appendChild(div);
        ReactDOM.render(
         <IntlProvider locale="en">
            <FormattedMessage id='search_form_status' />
         </IntlProvider>
        , div);
    }
```

**Comment by longlho** [comment]
It is. Every reactdom.render creates its own tree regardless of whether
it’s inside another react component or not

**Comment by ScriptedAlchemy** [comment]
Creating another instance of react, youd have to wrap it in a provider as well

**Comment by DragonRaider5** [comment]
Using the latest beta, it is possible. Question is: is it necessary @HowardTangHw?

**Comment by HowardTangHw** [comment]
> Using the latest beta, it is possible. Question is: is it necessary @HowardTangHw?

Yes, I have a global dialog component that needs to be appended to body

like [Antd Message ](https://ant.design/components/message/)

**Comment by longlho** [comment]
@HowardTangHw you should probably use `Portal` which allows appending things to a different tree, but preserve `context`

**Comment by ghost** [comment]
same problem, hope to resolve~
