### ISSUE TITLE
FormattedMessage values list?

### ISSUE THREAD

**Issue by Creaa** [formatjs/react-intl#1373]
Hello, 

Can I get the values list using this library? 
For example I have .json file with: 

```
{
	"test1": "ABC",
	"test2": "CBA",
	"test3": "test3: {test1} {test2}"
}
```
I know that, I can provide this data as a object, passing in FormattedMessage using a props:

```
FormattedMessage id="test3"
       ...
        values={{ test1: someData, test2: someData2 }} />

````
But there is any way to check, that is there any "variable" like that, build array or something?
And I finally, I'd like to replace...
So the output should be for result: "test3: ABC CBA" 

Thanks for any advice.

Greetings.

**Comment by longlho** [comment]
Technically you can inspect the AST generated by https://github.com/formatjs/formatjs/tree/master/packages/intl-messageformat-parser to know if there're variables.
