### ISSUE TITLE
FormattedMessage does not work with child function and values

### ISSUE THREAD

**Issue by ieugen** [formatjs/react-intl#1375]
### Expected behavior

I expect to be able to use the following snippet of code as described in the docs:
```
            <FormattedMessage
                id="accounts.add-sub-account.instructions.01"
                defaultMessage={'Welcome to {accountName}'}
                values={{
                  accountName: <strong>{displayName}</strong>,
                }}
              >
{ text => <p>{text}</p> }
</FormattedMessage>
```
However it does not work, as I get only `Welcome to ` .

I can make it work if I provide the following (notice I am not passing the child function `text =>{}`.

```
            <p>
              <FormattedMessage
                id="accounts.add-sub-account.instructions.01"
                defaultMessage={'Welcome to {accountName}'}
                values={{
                  accountName: <strong>{displayName}</strong>,
                }}
              />
            </p>
```
### Current behavior

I get only `Welcome to `, the variables is not replaced in the text.

### Step to reproduce for BUG REPORT

See the above snippets for examples.

 Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.0.0-beta.18 |
|    `npm ls react` | 16.8.6 |
|     `npm --version` | 6.9.0 |
|    `node --version` | v10.16.0 |

| OS   | Version |
| ---- | ------- |
| Debian | Buster |

| Browser | Version |
| ------- | ------- |
| Firefox    | 68 |

**Comment by DragonRaider5** [comment]
As mentioned in other issues, variable replacement results in an array of translated strings (as required for proper react string update detection).

**Comment by awaisdar001** [comment]
@DragonRaider5 Can you link some of those issues? can you tell what should be the workaround?

**Comment by DragonRaider5** [comment]
@awaisdar001 Sorry for the delayed answer; To clarify this means that you need to get all the fragments in your rendering function, not only the first one.

Using the example from above:
```jsx
<FormattedMessage
  id="accounts.add-sub-account.instructions.01"
  defaultMessage={'Welcome to {accountName}'}
  values={{
    accountName: <strong>{displayName}</strong>,
  }}
>
  { (...fragments) => <p>{ fragments }</p> }
</FormattedMessage>
```

I am not sure whether or not you'll have to provide keys when rendering the array. However the `console` will tell you so ;)
