### ISSUE TITLE
Undefined locale for relative time format in v3

### ISSUE THREAD

**Issue by lithin** [formatjs/react-intl#1378]
When developing a React Native app, we noticed an issue regarding `FormattedRelativeTime`.

### Step to reproduce for BUG REPORT

Using this code:  
```
<IntlProvider locale="en-gb">
    <Text>
        <FormattedRelativeTime value={0} />
    </Text>
</IntlProvider>
```

we get this error:

<img width="356" alt="Screenshot 2019-07-16 at 14 13 36" src="https://user-images.githubusercontent.com/6726858/61804733-589d2b00-ae2c-11e9-9b40-cdfb62d5d714.png">

However when we swap `locale="en-gb"` for `locale="en"`, it works again.

### Your Environment

Running RN 0.59.x, behaviour observable on iOS simulator (iPhone 8)

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` |3.0.0.-beta.18 |
|      `npm ls react` | 16.8.x |
|     `npm --version` | 6.4.1 |
|    `node --version` | 10.15.3 |

| OS   | Version |
| ---- | ------- |
| iOS | iPhone 8, XCode 10.2 |

**Comment by leoyli** [comment]
I think this have been fixed in the latest release, no?!

**Comment by longlho** [comment]
I haven't verified since i dont use react-native :(

**Comment by lithin** [comment]
I can have a look next week

**Comment by longlho** [comment]
closing due to stale

**Comment by okuryu** [comment]
I think we should leave it to the stale bot's care.

**Comment by lithin** [comment]
I can confirm this has been fixed 👍
