### ISSUE TITLE
Render empty component instead of 1970 when value is null

### ISSUE THREAD

**Issue by Zabaa** [formatjs/react-intl#1380]
**Describe the solution you'd like**
Currently when the value that I'm passing to **FormattedDate** component is null a value '01/01/1970' is rendering. Maybe it will be better if the result will be e.g. an empty string

**Comment by longlho** [comment]
This behavior is consistent with `Intl.DateTimeFormat` so we won't be changing it. It also allows i18n audit to quickly detect the issue instead of masking it.
