### ISSUE TITLE
Getting TypeError: intlProvider.getChildContext is not a function 

### ISSUE THREAD

**Issue by rameshrengasamy** [formatjs/react-intl#1384]
I am trying to follow the documentation here (testing with enzyme) -> 

https://github.com/formatjs/react-intl/blob/master/docs/Testing-with-React-Intl.md#helper-function-1

and import it in test file as 
import { shallowWithIntl } from "../jest-enzyme-utils";

### Expected behavior

Doesnt throw any error

### Current behavior

Getting TypeError: intlProvider.getChildContext is not a function 

### Step to reproduce for BUG REPORT

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.0.0-beta.20 |
|      `npm ls react` | 16.8.6 |
|    `node --version` | 12.5.0 |

**Comment by longlho** [comment]
Thanks for reporting we'll update the docs. In the mean time you can just use the `useIntl` hook to test.

**Comment by rameshrengasamy** [comment]
Thanks @longlho , is there an example you could point me to - like how to get jest/enzyme able to test a component that uses react hooks and react-intl (useIntl)

My issue context is, i m using jest with enzyme for testing and we use the new react hooks with react-intl (useIntl).

I tried the enzyme helper util method mentioned in this docs and got the above error.

I also tried the Jest mock method and got "TypeError: (0 , _reactIntl.useIntl) is not a function"

i really appreciate any help, thanks!

**Comment by longlho** [comment]
do u have a sample repo that reproduce this?

**Comment by wellyshen** [comment]
@rameshrengasamy You can mock useIntl hook as below:

```js
jest.mock('react-intl', () => ({
  useIntl: () => ({
    formatMessage: () => {}
  })
}));

it('test something', () => {
  // ....
});
```

**Comment by rameshrengasamy** [comment]
@wellyshen Thank you so much, that's how i ended up doing and it worked....

**Comment by mbifulco** [comment]
@wellyshen that snippet would make a great addition to the docs for this package 👍

**Comment by westandy** [comment]
I'm going to hold off on upgrading `react-intl` until this is fixed.

**Comment by longlho** [comment]
hmm until what is fixed?

**Comment by westandy** [comment]
That we don't have to put a mock into `jest`.

**Comment by longlho** [comment]
This issue is very old back in v3-beta and we're at v4 so idk if this is still an issue. There's also no repro link.

**Comment by longlho** [comment]
also, enzyme shallow rendering doesn't work w/ react hooks at all and there're nothing we can do about it.

**Comment by westandy** [comment]
A bot came along and gave us a react-intl upgrade (this was on Monday, 16 March 2020) and all of our unit tests broke for this very reason `intlProvider.getChildContext is not a function`.  That's why I came here.  

Hum hum hum.... hmm....

**Comment by longlho** [comment]
It’s a major version upgrade so breaking changes are expected. Take a look
at our Upgrade Guide docs

**Comment by longlho** [comment]
With that said you don’t have to upgrade if you don’t want to :)
