### ISSUE TITLE
FormattedNumber currency formatting

### ISSUE THREAD

**Issue by markkelsall** [formatjs/react-intl#1388]
### Expected behavior

FormattedNumber displays Euro symbol before value based only on currency passed in

### Current behavior

FormattedNumber displays Euro symbol after value if locale in Provider is en

### Step to reproduce for BUG REPORT

```import React from 'react';
import { IntlProvider, FormattedNumber, addLocaleData } from 'react-intl';

const usersLocale = 'en';
const translationsForUsersLocale = {};

addLocaleData(require(`react-intl/locale-data/${usersLocale}`));

function App() {
  return (
    <IntlProvider locale={usersLocale} messages={translationsForUsersLocale}>
      <div>
        <FormattedNumber style="currency" currency="EUR" value={100}/>
      </div>
    </IntlProvider>
  );
}

export default App;
```
Outputs: € 100

Change usersLocale to en
Outputs: 100 €

### Your Environment

Mac, Chrome 

| OS   | Version |
| ---- | ------- |
| Mac | High Sierra 10.13.4 |

| Browser | Version |
| ------- | ------- |
| Chrome    | 75.0.3770.142 |

**Comment by longlho** [comment]
I'm not sure I understand the issue, `€100.00` in `en` locale is correct.

**Comment by markkelsall** [comment]
Is it definitely? Is there any documentation about how currencies display in different languages?

**Comment by longlho** [comment]
http://cldr.unicode.org/ is our data source :)

**Comment by markkelsall** [comment]
In that case I will close this and apologise! Thanks for the info @longlho 👍
