### ISSUE TITLE
React should be a peer dependency

### ISSUE THREAD

**Issue by ZLJasonG** [formatjs/react-intl#1389]
Previously on the 2.9 release, React and similar modules were included as peer dependencies. However 3.0.0 beta releases have change this to include them as normal dependencies.
This has created a situation where it is no longer possible libraries to reference react-intl without locking react to the matching version.

**Comment by longlho** [comment]
Our React dependency version is `^16.3.0` bc we rely on the new `Context` API. AFAIK `peerDependency` is more appropriate for a plugin system like `gulp`/`grunt`/`babel` but `react-intl` actually relies on a specific version range to work properly :)

**Comment by ZLJasonG** [comment]
Peer dependencies can have minimum versions, the problem is normal dependencies cause a duplicate version of the library to be baked in. This leads to conflicts when attempting to use your library in another library.


Project/node_modules/@types/react/index.d.ts:2818:14 - error TS2300: Duplicate identifier 'LibraryManagedAttributes'.

2818         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
                  ~~~~~~~~~~~~~~~~~~~~~~~~

  Project/node_modules/react-intl/node_modules/@types/react/index.d.ts:2822:14
    2822         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
                      ~~~~~~~~~~~~~~~~~~~~~~~~
    'LibraryManagedAttributes' was also declared here.

On 2 Aug 2019, at 14:24, Long Ho <notifications@github.com<mailto:notifications@github.com>> wrote:


Our React dependency version is ^16.3.0 bc we rely on the new Context API. AFAIK peerDependency is more appropriate for a plugin system like gulp/grunt/babel but react-intl actually relies on a specific version range to work properly :)

**Comment by longlho** [comment]
Oh looks like your issue is `@types/react` instead of `react`. Yeah we can reduce the version for that.

**Comment by longlho** [comment]
should be fixed in 3bd63b44666656d9131ac7a1bb6976958fd5d373

**Comment by longlho** [comment]
feel free to reopen if u're still having issue

**Comment by GuillaumeAmat** [comment]
I just encountered a similar issue. I had React 16.8.6 in my project, along with react-intl 2.9.x.

I upgraded react-intl to the latest 3.1.5 version. SO far, so good. But when I replaced the Intl HOC by the new `useIntl` hook, React crashed and reported me that I possibly used two different versions of React.

Which was true:

* React 16.8.6 from my dependencies
* React 16.9.0 from the react-intl dependencies

I understand you point about the compatibility, but IMO that implementation creates more problems than it solves.

Package managers do check the versions of the peer dependencies, but they just display a warning if something is wrong. It's up to the user/developer to fix it or not, but he has the choice at least. Your way forces it.

Can you reconsider a policy change @longlho?

**Comment by redonkulus** [comment]
@GuillaumeAmat this is odd because we are specifying a minimum that should include your version as well: `"react": "^16.3.0"`. Are you hard coding a certain version or have a package lock file that is causing the duplication?

**Comment by GuillaumeAmat** [comment]
Oh my, good catch @redonkulus, it was the `yarn.lock` file. Weird...

It was stuck between those two versions for no reasons :/

Thanks for your help!

**Comment by rosskhanas** [comment]
I agree with many people thinking that `react` package should be listed in peer dependencies.

**Comment by redonkulus** [comment]
@rosskhanas Like I mentioned a few days ago, react-intl is just using `"react": "^16.3.0"` why would that imply that you have to use v16.9.0? Seems like either some other package is pulling in a newer version of react or you have a lock file issue like the user before.

**Comment by DragonRaider5** [comment]
They're right - it's listed as a dependency and that's wrong (see https://github.com/formatjs/react-intl/blob/964860653e34a3766f0bf4f1a808d2c75c3618cb/package.json#L47 ).

A peer dependency + dev dependency for testing would be the right choice here, as we want to incorporate the react package the user installed and not want to pull a new one.

**Comment by redonkulus** [comment]
I've checked a few other packages like react-dom, react-router and react-redux they all use peerDeps/devDeps. We will change and follow suit. Thanks @DragonRaider5 for fixing this.

**Comment by rosskhanas** [comment]
> @rosskhanas Like I mentioned a few days ago, react-intl is just using `"react": "^16.3.0"` why would that imply that you have to use v16.9.0? Seems like either some other package is pulling in a newer version of react or you have a lock file issue like the user before.

Because yarn resolves `^16.3.0` as a `16.3.0` which is correct, `^` allows any minor version change.

**Comment by longlho** [comment]
shouldn't `16.8.3` satisfy that semver as well? I have not seen that discrepancy in `npm` so it's quite puzzling

**Comment by rosskhanas** [comment]
> shouldn't `16.8.3` satisfy that semver as well? I have not seen that discrepancy in `npm` so it's quite puzzling

No, because it is as `16.8.3` which is required by React Native.

**Comment by longlho** [comment]
what I meant is, `react-intl` requires `^16.3.0` and the consumer declares `16.8.3` which satisfies `^16.3.0` so `yarn` shouldn't download any other React version.

**Comment by rosskhanas** [comment]
> what I meant is, `react-intl` requires `^16.3.0` and the consumer declares `16.8.3` which satisfies `^16.3.0` so `yarn` shouldn't download any other React version.

Agree, it was surprising to me that yarn was downloading 2 versions 😢

**Comment by longlho** [comment]
ok looks like that's intentional from `yarn`: https://github.com/yarnpkg/yarn/issues/3951#issuecomment-316424639
we'll make the fix specifically for `yarn` users and will note it as so. This is really weird...
