### ISSUE TITLE
Feature Backlog

### ISSUE THREAD

**Issue by longlho** [formatjs/react-intl#1392]
As we've shipped v3.0, we're looking to plan for what's coming. The list below is purely for brainstorming & will be updated when new feature requests come in.

# ~New CLI~

~The current `babel-plugin-react-intl` requires a build setup while extracting/translating i18n is becoming more standalone. We've also received a few requests for it.
https://github.com/formatjs/formatjs/issues/68~
We have released https://www.npmjs.com/package/@formatjs/cli

# ~ICU Date Time Skeleton support~

~ICU Skeleton is quite comprehensive: http://userguide.icu-project.org/formatparse/datetime#TOC-DateTimePatternGenerator. It's very likely we'll be releasing a separate package and introduce plugins to `intl-messageformat` as this needs additional CLDR. We can also try to propose new APIs to ECMA-402.
https://github.com/formatjs/formatjs/issues/94~
Now available in `react-intl@3.7.0`

# ~ICU Number Skeleton support~

~Similar to Date Time Skeleton support: http://site.icu-project.org/design/formatting/numbers/skeleton

https://github.com/formatjs/formatjs/issues/93~
Now available in `react-intl@3.8.0`

# ~`ListFormat` & `<FormattedList>`~

~This is stage-3 and quite ready.
https://github.com/formatjs/react-intl/issues/1328~
Now available in `react-intl@3.5.0`.

# Separate out formatters

Right now in order to use a single formatter you need to polyfill `Intl.PluralRules`, `Intl.RelativeTimeFormat` and its data. `intl-messageformat` especially will grow bigger as we try to match ICU. This might become unsustainable.

cc @pyrocat101

**Comment by skoging** [comment]
If you're aiming to support `formatToParts` at some point, I'd also like to see support for `resolvedOptions`

**Comment by longlho** [comment]
@skoging 	can u create a separate GH issue w/ your use case?

**Comment by YUFENGWANG** [comment]
What's the status of the cli? It seems that we need it too. we want to extract all i18n data in json file without building the whole project.

**Comment by longlho** [comment]
@pyrocat101 has an open WIP PR https://github.com/formatjs/formatjs/pull/234

**Comment by longlho** [comment]
@YUFENGWANG if you can try out `https://www.npmjs.com/package/@formatjs/cli` & give us feedbacks that'd be great.

**Comment by YUFENGWANG** [comment]
@longlho let me try it
