### ISSUE TITLE
createIntlCache is missing in top level index file

### ISSUE THREAD

**Issue by SpringNyan** [formatjs/react-intl#1393]
### Expected behavior

`import { createIntlCache } from "react-intl";` has no error.

### Current behavior

`import { createIntlCache } from "react-intl";` emits the error `'createIntlCache' is not exported from 'react-intl'`

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.0.0|
|      `npm ls react` | VERSION |
|     `npm --version` | VERSION |
|    `node --version` | VERSION |

| OS   | Version |
| ---- | ------- |
| NAME | VERSION |

| Browser | Version |
| ------- | ------- |
| NAME    | VERSION |

**Comment by longlho** [comment]
Thanks for reporting! We'll fix this asap
