### ISSUE TITLE
formatDate cannot parse valid value

### ISSUE THREAD

**Issue by liemdo** [formatjs/react-intl#1396]
I get error `RangeError: Invalid time value` when passing the timestamp to `formatDate`.

```javascript
formatDate('2019-08-06T15:16:23.000Z')
```

However, this works fine:

```javascript
formatDate(new Date('2019-08-06T15:16:23.000Z'))
```

### Expected behavior
formatDate should be able to parse the timestamp

### Current behavior
Get error `RangeError: Invalid time value`

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.1.1 |
|      `npm ls react` | 16.8.6 |
|     `npm --version` | 6.9.0 |
|    `node --version` | 12.4.0 |

| OS   | Version |
| ---- | ------- |
| macOS Mojave | 10.14.5 |

| Browser | Version |
| ------- | ------- |
| Chrome    | 75.0.3770.142 |

**Comment by longlho** [comment]
string `Date` parsing is inherently buggy & inconsistent cross browser so we typically recommend `number` instead. The native API itself doesn't take in `string` for this reason. There're also edge cases like `''` where `Intl.DateTimeFormat` would treat like `0`, but `Date('')` results in `Invalid Date`.

**Comment by longlho** [comment]
We'll special case this since it's convenient to pass in string TS but just
be wary of the inconsistencies 🙂
