### ISSUE TITLE
get FormattedRelativeTime old behavior for displaying time

### ISSUE THREAD

**Issue by pierrebiver** [formatjs/react-intl#1397]
In the v2, when using `FormattedRelative`, the time displayed was automatically adapted: if the time elapsed was 24hours, it will show `a day ago` but now with the v3 I can't get this feature anymore.

 When I pass my `value` in seconds, it shows the number of seconds elapsed even if it correspond to 1 day. Does it mean we have to handle ourself this trick where based on the time elapsed we have to convert the unit to a more human readable value ?

**Comment by longlho** [comment]
You can use @formatjs/intl-utils to get close to the previous behavior like this:
```tsx
import {selectUnit} from '@formatjs/intl-utils';
const {value, unit} = selectUnit(Date.now() - 48 * 3600 * 1000);
// render
<FormattedRelativeTime value={value} unit={unit} numeric="auto" />;
```

**Comment by pierrebiver** [comment]
great thanks ! 
maybe we would be nice to mention it explicitly in the migration guide ?

**Comment by longlho** [comment]
It's in the Upgrade Guide I believe but more clarification PR is definitely
welcome!

**Comment by cdeutsch** [comment]
A component that does this for you would be better.

That's a lot of boilerplate for everyone to duplicate every time you want to display a `FormattedRelativeTime`

Out of the box, `Intl.RelativeTimeFormat` has a poor API, and I get why you want to replicate to a point, but the old behavior (which most people will want) and a higher level, easier to use API would be nice.

**Comment by cdeutsch** [comment]
Here's what I ended up with, which is decently close to the old behavior.

```ts
import React from 'react';
import { FormatRelativeTimeOptions, useIntl } from 'react-intl';

import { formattedRelative } from 'shared/util';

export function formattedRelative(
  intl: IntlShape,
  value?: Date | number,
  options?: FormatRelativeTimeOptions
): string | undefined {
  if (!value) {
    return undefined;
  }

  const { value: selectedValue, unit } = selectUnit(value, undefined, { quarter: false });

  return intl.formatRelativeTime(selectedValue, unit, options);
}

export interface FormattedRelativeProps {
  options?: FormatRelativeTimeOptions;
  value?: Date | number;
}

export const FormattedRelative: React.SFC<FormattedRelativeProps> = ({ options, value, ...passthrough }) => {
  const intl = useIntl();

  return <React.Fragment>{formattedRelative(intl, value, options)}</React.Fragment>;
};

```

I did notice one, semi significant difference.

Give a date 12 days ago:

Old = "12 days ago"
New = "2 weeks ago"

Not sure why there's a difference or how to restore the old behavior.

**Comment by longlho** [comment]
the example you mentioned demonstrated the problem with the ambiguity of the old behavior. It is simply not i18n-safe to "smartly" determine the threshold, let alone that logic only applies to Gregorian calendar, but not Islamic or Chinese. 

CLDR data itself also supports things like `last Sunday`, `2 Sundays ago` which further complicate the algorithm.

More info: https://github.com/tc39/proposal-intl-relative-time/issues/14
