### ISSUE TITLE
V3 Jest Missing Locale Data for Locale Warning

### ISSUE THREAD

**Issue by xveganxxxedgex** [formatjs/react-intl#1401]
Hello, and thank you for this project! 

I've recently made the upgrade to v3, but am getting a warning message when running jest tests. I've tried looking through the release notes/upgrade guide and see that `addLocaleData` was removed so I removed that from my codebase, and I've also tried looking at all of the testing examples, but I can't seem to get rid of this warning. I've tried adding the polyfills, I've tried some of the helper examples in the tests documentation, but nothing seems to be getting rid of it when using a non en locale. 

### Expected behavior

The test should run without throwing the `[React Intl] Missing locale data for locale: "de". Using default locale: "en" as fallback.` warning.

### Current behavior

The test throws the missing locale warning when I try to run a test using a locale other than `en`

### Step to reproduce for BUG REPORT

`ToggleOption.js` - The component being tested - It's already being exported as wrapped with `injectIntl`

```
import { injectIntl } from 'react-intl';

const ToggleOption = ({ value, message, intl }) => (
  <option value={value}>{message ? intl.formatMessage(message) : value}</option>
);

export default injectIntl(ToggleOption);
```

`ToggleOption.test.js`

```
import { IntlProvider, defineMessages } from 'react-intl';

describe('components/ToggleOption', () => {
  // This does not throw the warning since it's using the en default
  it('should render default language messages', () => { 
    const defaultEnMessage = 'someContent';
    const message = defineMessages({
      enMessage: {
        id: 'boilerplate.containers.LocaleToggle.en',
        defaultMessage: defaultEnMessage,
      },
    });
    const option = <ToggleOption value="en" message={message.enMessage} />;
    const renderedComponent = shallow(
      <IntlProvider locale="en">{option}</IntlProvider>,
    );
    expect(renderedComponent.contains(option)).toBe(true);
  });

  // This one throws the warning
  it('should display value when message is not provided', () => {
    const renderedComponent = mount(
      <IntlProvider locale="de">
        <ToggleOption value="de" />
      </IntlProvider>,
    );
    expect(renderedComponent.text()).toBe('de');
    expect(renderedComponent.find('option').prop('value')).toBe('de');
  });
});
```

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.1.0 |
|      `npm ls react` | 16.8.6 |
|     `npm --version` | 6.9.0 |
|    `node --version` | 10.16.1 |

| OS   | Version |
| ---- | ------- |
| macOS Mojave | 10.14.4 |

| Browser | Version |
| ------- | ------- |
| Jest    | 24.8.0 |

**Comment by longlho** [comment]
1 possibility is you're running Node w/o ICU so you either compile Node w/ ICU, or use `full-icu` using this [instruction](https://nodejs.org/dist/latest-v10.x/docs/api/intl.html#intl_providing_icu_data_at_runtime).

**Comment by xveganxxxedgex** [comment]
Thank you for your fast response! I totally missed that and I did need to add it. I ended up installing the `full-icu` npm package, then using it in my script as `"test:jest": "cross-env NODE_ENV=test cross-env NODE_ICU_DATA=node_modules/full-icu jest`

Thanks so much!
