### ISSUE TITLE
Broken unpkg links in Getting Started

### ISSUE THREAD

**Issue by gamtiq** [formatjs/react-intl#1403]
[The react-intl Package section](https://github.com/formatjs/react-intl/blob/master/docs/Getting-Started.md#the-react-intl-package) inside `Getting-Started.md` contains broken links to [CommonJS](https://unpkg.com/react-intl@latest/lib/index.js) and [ES6](https://unpkg.com/react-intl@latest/lib/index.es.js) modules.

**Comment by redonkulus** [comment]
Care to open a PR to fix?
