### ISSUE TITLE
Support rich text from API

### ISSUE THREAD

**Issue by HollyPony** [formatjs/react-intl#1404]
I'm able to format rich text from Component but cannot find a way to do that from API. Oddly the XML parser seems called (see https://github.com/formatjs/react-intl/issues/1399).

```
import React from "react";
import ReactDOM from "react-dom";
import { IntlProvider, useIntl } from "react-intl";


const App = () => intl.formatMessage({
  id: "richText",
  values: {
    small: msg => <small>{msg}</small>
  }
})

<IntlProvider
  locale="en"
  messages={{ richText: `not <small>formatted</small>` }}>
  <App />
</IntlProvider>
```

Live : https://codesandbox.io/s/competent-pare-73p0d

It could be great to have a documented way to achieve this here : https://github.com/formatjs/react-intl/blob/master/docs/API.md#formatmessage the ame way it's here https://github.com/formatjs/react-intl/blob/master/docs/Components.md#rich-text-formatting

**Comment by longlho** [comment]
thanks for reporting. This is definitely a bug!

**Comment by longlho** [comment]
oh looks like you're passing params as object instead of sequential, for `formatMessage` the API documented is `formatMessage(descriptor, values)` so in your codesandbox it has to be:
```tsx
useIntl().formatMessage({ id: 'richText' }, { small: msg => <small>{msg}</small> })
```
I just tried and it works. Having a type system is quite handy :)

**Comment by HollyPony** [comment]
Thanks ! But my request was about document a "rich text" in the API doc the same it's done for Components. I was pretty sure there was no bug here ^^

**Comment by longlho** [comment]
oh sorry I'll reopen and update the doc
