### ISSUE TITLE
wiki link for "Testing with React Intl" is wrong

### ISSUE THREAD

**Issue by jensbodal** [formatjs/react-intl#1406]
### Expected behavior

Update link in wiki

### Current behavior

Google brought me to this page: 

`https://github.com/formatjs/react-intl/wiki/Testing-with-React-Intl`

Which has a link to: 

`https://github.com/formatjs/react-intl/blob/master/docs/Testing-with-React-intl.md`

The correct link is: 

`https://github.com/formatjs/react-intl/blob/master/docs/Testing-with-React-Intl.md` 
(capital **I** in **Intl**)

### Step to reproduce for BUG REPORT

n/a

### Your Environment

n/a

**Comment by longlho** [comment]
Thanks for reporting! We've fixed it.
