### ISSUE TITLE
initialNow is unknown prop of IntlProvider

### ISSUE THREAD

**Issue by bryanmig** [formatjs/react-intl#1409]
### Expected behavior

As per the docs, I should be able to specify an `initialNow` for a SSR'ed application:
```
<IntlProvider locale={this.props.locale} messages={this.getMessages()} initialNow={this.now}>
        {this.props.children}
      </IntlProvider>
```

See https://github.com/formatjs/react-intl/blob/master/docs/Components.md#intlprovider

### Current behavior

The following error is thrown during type checking:
```
Error:(32, 8) TS2322: Type '{ children: ReactNode; locale: string; messages: Record<string, string>; initialNow: number; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<IntlProvider> & Pick<Readonly<OptionalIntlConfig> & Readonly<{ children?: ReactNode; }>, "locale" | "children"> & Partial<...> & Partial<...>'.
  Property 'initialNow' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<IntlProvider> & Pick<Readonly<OptionalIntlConfig> & Readonly<{ children?: ReactNode; }>, "locale" | "children"> & Partial<...> & Partial<...>'
```

### Step to reproduce for BUG REPORT

Specify `initialNow` as prop in the `IntlProvider`

```
<IntlProvider locale={this.props.locale} messages={this.getMessages()} initialNow={this.now}>
        {this.props.children}
      </IntlProvider>
```

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | react-intl@^3.1.5 |
|      `npm ls react` | react@^16.8.6 |
|     `npm --version` | 6.9.0 |
|    `node --version` | v12.6.0 |

| OS   | Version |
| ---- | ------- |
| OSX | 10.14.6 |

**Comment by longlho** [comment]
`initialNow` has been removed in v3 so I've removed it from docs. Thanks for reporting!

**Comment by bryanmig** [comment]
No problem - saw that it was removed in the upgrade guide for another component\function but wasn't sure if it was still needed here.

Thanks for the quick response!
