### ISSUE TITLE
[regression >3.1.1] Type generics annotation do not get forwarded to FormattedMessage

### ISSUE THREAD

**Issue by emmenko** [formatjs/react-intl#1412]
This commit https://github.com/formatjs/react-intl/commit/660a546a87af198d84d119499c476857e798cac7 changed the exported component `message` component to be wrapped with `injectIntl`.

However, I believe that this change broke the TS generics, as the type of the values field does not get forwarded anymore.

Before I could do:

```tsx
<FormattedMessage<
  Record<string, (msg: React.ReactNodeArray) => JSX.Element>
>
  {...messages.paragraph1}
  values={{
    a: msg => (
      <a
        href={SUPPORT_PORTAL_URL}
        target="_blank"
        rel="noopener noreferrer"
      >
        {msg}
      </a>
    ),
  }}
/>
```

But now it breaks because the generic type that I pass gets ignored

<img width="441" alt="image" src="https://user-images.githubusercontent.com/1110551/62858810-a1dded80-bcfb-11e9-8c72-9d90614beb5c.png">

Can the component be rewritten using react hooks?

**Comment by emmenko** [comment]
@longlho what do you think? What is your preference for this? I guess we should either remove the HOC or forward the types.

I can open a PR if you point me in the right direction.

**Comment by longlho** [comment]
unfortunately we can't fully use hooks yet per https://github.com/formatjs/react-intl/issues/1290#issuecomment-520286819 so forwarding type would be best rn. PR's always welcome!

**Comment by emmenko** [comment]
I see, thanks for the info. I'll look into forwarding types then.
