### ISSUE TITLE
Can not find locale-data

### ISSUE THREAD

**Issue by pku145** [formatjs/react-intl#1418]
Hi.
I have installed react-intl by yarn add react-intl. But I can't find locale-data folder.
Please help me
Information:
React-intl version 3.1.17
node 11.10.1
OS : ubuntu 18.04
Thank you.

**Comment by longlho** [comment]
Our Upgrade Guide should have instructions on this: https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#migrate-to-using-native-intl-apis
