### ISSUE TITLE
FormattedRelativeTime missing "now"

### ISSUE THREAD

**Issue by gpopovic** [formatjs/react-intl#1419]
`<FormattedRelativeTime value={0} />`

### Expected behavior
"Now"

### Current behavior
"0 seconds ago"

**Comment by longlho** [comment]
`<FormattedRelativeTime value={0} numeric="auto" />` is what you're looking for.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RelativeTimeFormat#Parameters
