### ISSUE TITLE
"module not found" error for `intl-messageformat/core`

### ISSUE THREAD

**Issue by hmeinertrita** [formatjs/react-intl#1420]
### Expected behavior

React component imports IntlProvider without error

### Current behavior

Throws "module not found" error for `intl-messageformat/core`

```
This dependency was not found:
⠀
* intl-messageformat/core in ./node_modules/react-intl/lib/index.js, ./node_modules/react-intl/lib/utils.js
⠀
To install it, you can run: npm install --save intl-messageformat/core
```

### Step to reproduce for BUG REPORT

Clone this repo (https://github.com/hmeinertrita/react-intl-bug) and run `npm start`

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | react-intl@3.0.0-beta.23 |
|      `npm ls react` | react@16.8.6 |
|     `npm --version` | 6.10.0 |
|    `node --version` | v10.15.3 |

| OS   | Version |
| ---- | ------- |
| macOS Mojave | 10.14.5 |

**Comment by longlho** [comment]
v3 is already released so u should switch to that :)
