### ISSUE TITLE
Not possible to use umd build

### ISSUE THREAD

**Issue by bildja** [formatjs/react-intl#1423]
When adding react-intl from script tag like `<script src="https://unpkg.com/react-intl@3.1.8/dist/react-intl.js"></script>` it fails with "Uncaught ReferenceError: require is not defined".

The bundle contains this code for example:
```
var invariant = require('invariant');
```

regardless of umd branch, so it fails.

### Expected behavior

react-intl loaded and working

### Current behavior

does not load and fails

### Step to reproduce for BUG REPORT

1. Add script tag with link to umd bundle
2. See console

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.1.8 |
|      `npm ls react` | 16.9.0 |
|     `npm --version` | 6.10.3 |
|    `node --version` | 10.16.2 |

| OS   | Version |
| ---- | ------- |
| Mac OS X | 10.14.6 |

| Browser | Version |
| ------- | ------- |
| Chrome    | 75 |

JSbin: https://jsbin.com/xosufojube/edit?html,output

**Comment by bildja** [comment]
@longlho thanks for the fix, but it still does not work.
Now it fails with `Uncaught ReferenceError: process is not defined`.
because bundle contains 
```
    var NODE_ENV = process.env.NODE_ENV;
```

**Comment by longlho** [comment]
can u try to see if https://github.com/formatjs/react-intl/commit/473180552e4d9a507f3b975832572ecf5552265b fixes it for u? I can't get `react-is` to build correctly so have to defer it out to `external`

**Comment by bildja** [comment]
![image](https://user-images.githubusercontent.com/818546/63332859-02df7400-c341-11e9-88c7-ca1a2dbbcc2a.png)

@longlho

**Comment by longlho** [comment]
yeah so u'd have to load `https://unpkg.com/react-is@16.9.0/umd/react-is.production.min.js` before `react-intl`. I'm open to PR since honestly idk how to get rollup to package correctly.

What's ur use case for UMD?

**Comment by bildja** [comment]
@longlho usecase is to add locale from `intl-relativetimeformat/dist/locale-data/<%= locale =>` in html, depending on user locale decided by the server that renders that html. 
I just realized it might not need react-intl loaded before, so it can be used in the bundle (I'll check a bit later).

But adding one more request to load react-is from cdn is something I'd try to avoid

**Comment by longlho** [comment]
@bildja can u give `master` another try?

**Comment by bildja** [comment]
@longlho interesting.. I was just trying to remove react-is from externals and still saw some errors. After rebuilding master, looks like no more errors, thanks a lot!
