### ISSUE TITLE
Components throw a 'Symbol.iterator' error in Microsoft Edge

### ISSUE THREAD

**Issue by hwatersiv** [formatjs/react-intl#1424]
### Expected behavior

React-intl Components function without throwing an error in Microsoft Edge

### Current behavior

Currently, <FormatDate> and <FormatNumber> throw an error in Microsoft Edge 44.18362.267.0

`SCRIPT438: SCRIPT438: Object doesn't support property or method 'Symbol.iterator'`

### Step to reproduce for BUG REPORT

Use FormatDate or FormatNumber Component

For example:
used the React-intl Examples

### Your Environment

|          Executable | Version |
| --------------: | ------ |
| `typescript` | 3.5.3|
| `react-dom` | 16.9.0 |
| `npm ls react-intl` | 3.1.8 |
|      `npm ls react` | 16.9.0 |
|     `npm --version` | 6.7.0 |
|    `node --version` | 11.13.0 |

| OS   | Version |
| ---- | ------- |
| Windows 10 | 18362 |

| Browser | Version |
| ------- | ------- |
| Microsoft Edge | 44.18362.267.0|

**Comment by hwatersiv** [comment]
Issue does NOT occur in 3.1.1

**Comment by longlho** [comment]
Thanks for reporting we'll take a look soon.

**Comment by longlho** [comment]
I can't seem to repro. Our example works in both IE11 & Edge

![image](https://user-images.githubusercontent.com/198255/63139400-35d5e080-bfac-11e9-8dde-8e565dd14e74.png)

![image](https://user-images.githubusercontent.com/198255/63139412-3ff7df00-bfac-11e9-95bf-d28a5ae326c6.png)

**Comment by CGNonofr** [comment]
We face the same error, it seems related to https://github.com/formatjs/react-intl/commit/cb7da586230a94fa345b5e8ae03bb4657d49b1a8#diff-fe1b24f653b989ecd950765cabe4a1d5

**Comment by MaximeCheramy** [comment]
I confirm that rollbacking to 3.1.1 fixes that crash on Edge.

**Comment by ipanasenko** [comment]
Guys, any updates? Is v3.1.1 safe to use? I mean there were Firefox and empty string in values issues, are they present in 3.1.1?

**Comment by longlho** [comment]
What's your build setup? As I mentioned, IE11/Edge seems to work fine in our examples

**Comment by hwatersiv** [comment]
Unfortunately, I was not able to replicate with your demo code either but the issue still remains in my code base. The usage might be form the using the API.  something like this:
```
import { injectIntl, WrappedComponentProps as InjectedIntlProps } from "react-intl";

class ManagedProfilesAtAGlanceComponent extends PureComponent<IManagedProfilesAtAGlanceProps, IManagedProfilesAtAGlanceState> {
const monthName = this.props.intl.formatDate(new Date(), { "month": "long" })
     public render() {
          <div>{monthName}</div>
     }
}

const MyComponentWithIntl = InjectIntl(ManagedProfilesAtAGlanceComponent)
export const MyComponent = connect(mapStateToProps, mapDispatchToProps)(MyComponentWithIntl );
```

**Comment by longlho** [comment]
what's ur build setup (webpack/rollup config...)?

**Comment by hwatersiv** [comment]
We are using parcel.js out of the box

**Comment by longlho** [comment]
our demo also uses parcel out of the box :(

**Comment by longlho** [comment]
do u have custom babel config or something?

**Comment by hwatersiv** [comment]
ts.config:
```
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "jsx": "preserve",
    "isolatedModules": true,
    "lib": [
      "dom",
      "es7"
    ],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "outDir": "build/dist",
    "resolveJsonModule": true,
    "strict": true,
    "target": "es6",
    "skipLibCheck": false
  },
  "include": [
    "src",
    "types"
  ]
}
```

**Comment by longlho** [comment]
can u create a sample repo w/ ur setup? Looking at this

**Comment by malcolmmadsheep** [comment]
@longlho seems like your changes fixed Edge!
