### ISSUE TITLE
Webpack and react-intl

### ISSUE THREAD

**Issue by pinokara** [formatjs/react-intl#1425]
```
ERROR in ./node_modules/react-intl/lib/format.js
Module parse failed: Unexpected token (62:78)
You may need an appropriate loader to handle this file type.
|     return msg.replace(/'\{(.*?)\}'/g, `{$1}`);
| }
| export function formatDate({ locale, formats, onError, timeZone, }, state, ...[value, options = {}]) {
|     const { format } = options;
|     let defaults = Object.assign({}, (timeZone && { timeZone }), (format && getNamedFormat(formats, 'date', format, onError)));
```

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | VERSION |
|      `npm ls react` | VERSION |
|     `npm --version` | VERSION |
|    `node --version` | VERSION |

| OS   | Version |
| ---- | ------- |
| NAME | VERSION |

| Browser | Version |
| ------- | ------- |
| NAME    | VERSION |

**Comment by longlho** [comment]
looks like webpack is pulling in ES entry point so u'll need to transpile `react-intl` as well

**Comment by pinokara** [comment]
> looks like webpack is pulling in ES entry point so u'll need to transpile `react-intl` as well

Can you support more infomation :( i am a newbie
@longlho

**Comment by longlho** [comment]
whats ur webpack config?

**Comment by pinokara** [comment]
```
{
                test: /\.(js|jsx)$/,
                include: [
                    client,
                    path.join(__dirname, "node_modules/react-intl"),
                    path.join(__dirname, "node_modules/intl-messageformat"),
                    path.join(__dirname, "node_modules/intl-messageformat-parser")
                ],
                loader: 'babel-loader',
                exclude: resolveApp('node_modules')
            },
```
@longlho

**Comment by pinokara** [comment]
```
{
  "presets": [
    ["@babel/preset-env", {
      "modules": false,
      "targets": {
        "browsers": [
          "last 2 versions",
          "ie >= 11",
          "safari >= 10"
        ]
      }
    }],
    "@babel/react"
  ],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true}],
    ["@babel/plugin-proposal-class-properties", { "loose": true}],
    ["@babel/transform-runtime"],
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-syntax-dynamic-import",
    "syntax-dynamic-import",
    "transform-class-properties",
    ["import", { "libraryName": "antd", "libraryDirectory": "lib", "style": true}]
  ],
  "env": {
    "production": {
      "plugins": [
        "transform-react-remove-prop-types"
      ]
    }
  }
}
```
and that's .babelrc @longlho

**Comment by longlho** [comment]
since u have `include` u prob don't need `exclude`, they're conflicting and I'm not sure if that causes the issue

**Comment by pinokara** [comment]
https://github.com/crypto-critic/Crypto-critic/tree/developement
this is my repo :(
just comment "excludes"-line but still error

**Comment by longlho** [comment]
ah tks for the repo ill take a look soon

**Comment by pinokara** [comment]
@longlho please help me as soon as you can

**Comment by longlho** [comment]
@pinokara https://github.com/crypto-critic/Crypto-critic/pull/2 so looks like the path is resolved incorrectly and renaming `.babelrc` to `babel.config.js` fixes it as well (`.babelrc` has implicit inheritance)

**Comment by pinokara** [comment]
@longlho nice, it's worked! thanks bro!
