### ISSUE TITLE
Stop exporting ESM artifacts?

### ISSUE THREAD

**Issue by cdeutsch** [formatjs/react-intl#1427]
In the very large project I'm working on, of the 100s of NPMs I'm using, 'react-intl` is now the only one that [needs to be transpiled](https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#esm-build), and it took a day to figure out why IE11 and Edge weren't working.

Can these not still be compiled to ES5 before publishing to NPM? It's too early to publish as ES6+ modules when your primary audience is targeting browsers. To make it worse, for some reason your NPMs don't show up when I run `npx are-you-es5 check`.

I'm transpiling all of these NPMs:
@formatjs/intl-relativetimeformat
@formatjs/intl-utils|intl-format-cache
intl-locales-supported
intl-messageformat
intl-messageformat-parser
react-intl

And the site is almost working in IE11 and Edge, but every `FormattedMessage` is throwing this error:
![image](https://user-images.githubusercontent.com/404765/63132277-2e034580-bf86-11e9-973c-6ea96ea8eaf3.png)

I've been using `v2` for 2 years. 
After 3 days of upgrading to `v3`, I'm curious what the advantage to `v3` is, because I'm about to scrap all this and go back to `v2`.

**Comment by DragonRaider5** [comment]
Advantages: New context API, hooks, bugfixes.

I agree on transpilation.

Seems like you don't properly provide your translations to `react-intl`.

**Comment by longlho** [comment]
The reason there is ESM artifact, or rather ES6 artifacts is bc down-transpiling to ES5 means we're also packaging polyfills & utilities (like `__extends` instead of `Object.assign`, or worse, `async/await/yield` results in a whole state machine `regenerator` being included). You can alias `react-intl` to `react-intl/dist/react-intl.js` and you don't have to basically transpile anything.

Our https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md should have the changes & benefits.

**Comment by cdeutsch** [comment]
> Advantages: New context API, hooks, bugfixes.

Is there a list of the bug fixes?
 
> Seems like you don't properly provide your translations to `react-intl`.

It does seem like that, but I don't get the errors in Chrome or Firefox, so I was suspecting another browser polyfill issue, but now I'm wondering if  there is just a bug in `react-intl`

Has it been tested in IE11 and Edge?

**Comment by DragonRaider5** [comment]
There's no need to test this part of the package on different browsers, as it is pure React. By this means it is tested.

Can you maybe provide us with the code you're using to pass the translations to `react-intl`?

**Comment by cdeutsch** [comment]
Here's how I load the translations (using Webpack)

```js
// en.js

const areIntlLocalesSupported = require('intl-locales-supported').default;

module.exports = function loader(locale, cb) {
  if (areIntlLocalesSupported('en')) {
    require.ensure([
        '../translations/en.json'
        , 'numbro/dist/languages/en-AU.min', 'numbro/dist/languages/en-GB.min', 'numbro/dist/languages/en-IE.min', 'numbro/dist/languages/en-NZ.min', 'numbro/dist/languages/en-ZA.min'
      ], (require) => {
      const numbro = require('numbro');
      numbro.registerLanguage(require('numbro/dist/languages/en-AU.min'));
      numbro.registerLanguage(require('numbro/dist/languages/en-GB.min'));
      numbro.registerLanguage(require('numbro/dist/languages/en-IE.min'));
      numbro.registerLanguage(require('numbro/dist/languages/en-NZ.min'));
      numbro.registerLanguage(require('numbro/dist/languages/en-ZA.min'));
      numbro.setLanguage(locale);

      cb(require('../translations/en.json'));
    }, 'locale-en');
  } else {
      require.ensure([
        'intl-pluralrules',
        '@formatjs/intl-relativetimeformat/polyfill',
        '@formatjs/intl-relativetimeformat/dist/locale-data/en',
        '../translations/en.json'
        , 'numbro/dist/languages/en-AU.min', 'numbro/dist/languages/en-GB.min', 'numbro/dist/languages/en-IE.min', 'numbro/dist/languages/en-NZ.min', 'numbro/dist/languages/en-ZA.min'
      ], (require) => {
      require('intl-pluralrules');
      require('@formatjs/intl-relativetimeformat/polyfill');
      require('@formatjs/intl-relativetimeformat/dist/locale-data/en');

      const numbro = require('numbro');
      numbro.registerLanguage(require('numbro/dist/languages/en-AU.min'));
      numbro.registerLanguage(require('numbro/dist/languages/en-GB.min'));
      numbro.registerLanguage(require('numbro/dist/languages/en-IE.min'));
      numbro.registerLanguage(require('numbro/dist/languages/en-NZ.min'));
      numbro.registerLanguage(require('numbro/dist/languages/en-ZA.min'));
      numbro.setLanguage(locale);

      cb(require('../translations/en.json'));
    }, 'locale-en-poly-intl');
  }
};

```

There's one of these files for every locale supported so that Webpack will codesplit them.

I guess the reason it works in Chrome and Firefox is that it's loading the `non-polyfilled` version.

I must have something wrong with the `else` pass above. Not loading the correct polyfills or something.

I guess I'll pick this up Monday. Thanks for your fast responses.

**Comment by cdeutsch** [comment]
I figured it out.

`if (areIntlLocalesSupported('en')) {` above needs to be:

```js
if (global.Int && areIntlLocalesSupported('en')) {
```

`areIntlLocalesSupported('en')` is returning `true` for me in IE11 and Edge, and it [seems like it wouldn't](https://github.com/formatjs/formatjs/blob/124c66290cf831b47937c744e469deca0ff7d430/packages/intl-locales-supported/src/index.ts#L15). Maybe I'm doing something wrong.

I guess you can close this if you're going to stick to ES6 modules. I'm not sure what other libraries are doing but `react-intl` seems to be in the very small minority in this regard.

**Comment by longlho** [comment]
IE11 & Edge do have `Intl` support

**Comment by cdeutsch** [comment]
> IE11 & Edge do have `Intl` support

Any idea why they don't work without the polyfills loaded?

I guess this is why I asked if `react-intl` had been tested in IE11.

Just because `react-intl` is "just react", doesn't mean it's dependencies are.

> There's no need to test this part of the package on different browsers, as it is pure React. By this means it is tested.

**Comment by longlho** [comment]
We rely on native Intl APIs to be there and unfortunately IE11 does not have `Intl.PluralRules` & `Intl.RelativeTimeFormat`. In the future we're planning to make this lazy eval at the cost of runtime error creeping up, but it won't crash.

**Comment by jasonwilliams** [comment]
@longlho for future reference switching to .mjs was a breaking change, you probably should have done this on a major version, it broke our build as webpack was now pulling in .mjs files. And we had similar problems to https://github.com/formatjs/react-intl/issues/1395

https://github.com/formatjs/react-intl/releases/tag/v3.1.0 
should have been v4.0.0

**Comment by longlho** [comment]
@jasonwilliams 	that change we reverted a while ago
