### ISSUE TITLE
Detecting when to load polyfills for IE11, Edge, and Safari

### ISSUE THREAD

**Issue by cdeutsch** [formatjs/react-intl#1429]
What's your recommendation for detecting when to load polyfills for IE11 and Edge?  
https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#migrate-to-using-native-intl-apis

I was under the impression `intl-locales-supported` was made for this, but `areIntlLocalesSupported('en')` is returning `true` in IE11 and Edge for me, yet `react-intl` doesn't seem to work unless I load the following polyfills:
- intl-pluralrules
- @formatjs/intl-relativetimeformat/polyfill
- @formatjs/intl-relativetimeformat/dist/locale-data/en

I ended up using `detect-browser` NPM, but I'd rather not.

**Comment by longlho** [comment]
`areIntlLocalesSupported` is meant to detect if a certain `locale` is supported since env like default Node ships with `Intl.PluralRules` but doesn't support anything other than `en`.

I'll update the doc, but effectively you only need something like:
```tsx
if (!Intl.PluralRules) {
	import('intl-pluralrules')
}

if (!Intl.RelativeTimeFormat) {
	import('@formatjs/intl-relativetimeformat/polyfill')
	import('@formatjs/intl-relativetimeformat/dist/locale-data/en')
}
```

**Comment by roderickhsiao** [comment]
@longlho is there a way we can detect if the `locale-data` is there or not (intl-relativetimeformat)?

The reason is we might dynamically change the language (we load `@formatjs/intl-relativetimeformat/polyfill` first), and after the polyfill got loaded, browser will then have `Intl.RelativeTimeFormat` so we cannot really detect if we need the `locale-data`

I currently hack to check if `__localeData__` is in the `RelativeTimeFormat`, and also check if `RelativeTimeFormat.polyfilled` === true (to know the function is provided by polyfill)

**Comment by longlho** [comment]
off the top of my head u can do `new Intl.RelativeTimeFormat('fr', {numeric: 'auto'}).format(0, 'second') !== 'now'`. If that returns `true` that means `fr` is supported.

**Comment by roderickhsiao** [comment]
Neat but might not be reliable though, I search the `locale-data` seems other languages just has `now` exactly the same as English but not for other time format.

**Comment by longlho** [comment]
Hmm this might actually be a bug in our polyfill, `Intl.RelativeTimeFormat.supportedLocalesOf` should give the definite answer. Can u make a bug in https://github.com/formatjs/formatjs?

**Comment by roderickhsiao** [comment]
Roger that!
https://github.com/formatjs/formatjs/issues/157

We probably should add `Intl.RelativeTimeFormat` in the constructor check for `intl-locales-supported`? 

https://github.com/formatjs/formatjs/blob/master/packages/intl-locales-supported/src/index.ts#L28

**Comment by longlho** [comment]
Thanks for reporting!

On the `Intl.RelativeTimeFormat` check, let's make a new GH issue for discussion :) There's been tickets around people saying that they have to polyfill even though they never use `intl-messageformat` for example so overall I'm exploring how to handle that situation (making those checks more lazily is an option but having runtime error creeps up on u isn't great).

**Comment by roderickhsiao** [comment]
true, I guess as long as we are able to pass in optional array for constructor check its fine :)

**Comment by cdeutsch** [comment]
FWIW, I tried out the new version and `areIntlLocalesSupported('en')` is still returning `true` for IE11 and Edge, yet when I try to use `<FormattedMessage>` or `formatRelativeTime` I get a ton of warnings.

```
TypeError: Unable to get property 'bind' of undefined or null reference
   at Anonymous function (eval code:42:7)
   at Anonymous function (eval code:78:7)
   at Array.prototype.forEach (native code)
   at prewarmFormatters (eval code:50:3)
   at IntlMessageFormat (eval code:187:5)
   at Anonymous function (eval code:42:7)
   at formatMessage (eval code:220:7)
   at Anonymous function (eval code:81:11)
   at Array.prototype.map (native code)
   at render (eval code:77:7)
```

```
 [React Intl] Error formatting relative time.
TypeError: Unable to get property 'bind' of undefined or null reference
   at Anonymous function (eval code:42:7)
   at formatRelativeTime (eval code:134:5)
   at formattedRelative (eval code:410:3)
   at numberFormatter (eval code:1432:9)
   at handleResults (eval code:145:15)
   at Anonymous function (eval code:186:11)
   at Anonymous function (eval code:364:21)
   at executeAction (eval code:697:9)
   at res (eval code:688:9)
   at Anonymous function (eval code:107:13)
```

![image](https://user-images.githubusercontent.com/404765/63283942-28547b00-c278-11e9-9119-af7e34b3c208.png)

If I find time, I'll try setup a simple test case, but in the meantime I'm using browser detection to always load the polyfills for Edge and IE11.

**Comment by sliebner** [comment]
> If I find time, I'll try setup a simple test case, but in the meantime I'm using browser detection to always load the polyfills for Edge and IE11.

Did you find the cause for this? Getting the same Exceptions after upgrading. And I can see, that the polyfills have all been added by my webpack build.

**Comment by cdeutsch** [comment]
@sliebner I ended up doing:

```
const isIntlSupported = typeof Intl !== 'undefined' && Intl.DateTimeFormat && Intl.NumberFormat && Intl.PluralRules && Intl.RelativeTimeFormat;
```
