### ISSUE TITLE
React-native components as message values not working

### ISSUE THREAD

**Issue by 39otrebla** [formatjs/react-intl#1430]
### Expected behavior

Having a message `Hello{what}!`, I'd expect to be able to use a react-native component in place of `what`, i.e. passing `{ what: myComponent }` as `values` to `formatMessage` or `FormattedMessage` should be supported.

### Current behavior

React-native components as message values are not working:

- with `formatMessage()` react-native components become `[object Object]` in the output string
- with `<FormattedMessage> />`  the output message is interrupted at the first occurrence of a react-native component

### Step to reproduce

1.  Define the following message:
```javascript
const messages = {
  "DynamicHello": "Hello{what}!"
}
```
2. Define a react-native component to pass as `what` value:
```javascript
const whatText = <Text>, world</Text>;
```
3. Try `formatMessage`:
```javascript
intl.formatMessage({ id: "DynamicHello" }, { what: whatText });
// Output will be: `Hello[object Object]!`
```
4. Try `<FormattedMessage />`
```javascript
render() {
  return <FormattedMessage id="DynamicHello" values={{ what: whatText }} />;
}
// Output will be: `Hello`
```

### Environment

|          Executable | Version |
| ------------------: | :------ |
| `intl` | 1.2.5 |
| `react-intl` | 2.9.0 |
| `react-native-cli` | 2.0.1 |
|      `react-native` | 0.59.10 |
|     `yarn --version` | 1.16.0 |
|    `node --version` | v10.15.1 |

| OS   | Version |
| ---- | ------- |
| macOS Mojave | 10.14.6 |

| Device OS | Version |
| ------- | ------- |
| Android    | all |
| iOS    | all |

**Comment by longlho** [comment]
Can you try latest version? We no longer support v2.9

**Comment by 39otrebla** [comment]
@longlho sure, was doing it right now as I noticed we weren't on latest version. Just struggling finding how to add locale configs as `addLocaleDate` is no more in `react-intl` package.

**Comment by longlho** [comment]
There’s some info on react-native intl jsc in our Upgrade Guide & Getting
Started as well

**Comment by antoinerousseau** [comment]
v2 => v3 documentation on this, fyi:
https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#enhanced-formattedmessage--formatmessage-rich-text-formatting

**Comment by 39otrebla** [comment]
With this message:
```
{count, plural, one {Found} other {Found}} <CountText></CountText> {count, plural, one {result} other {results}}.\nAdd <FilterText>filters</FilterText> to your search or show all results in the list.
```

configured in this way:

```javascript
<TipText>
  <FormattedMessage
    id="TIP_COUNT_FOUND"
    values={{
      count,
      CountText: str => <TipText bold>{count}</TipText>,
      FilterText: str =>  <TipText uppercase color={COLORS.textgray}>{str}</TipText>
    }}
  >
    {msg => msg}
  </FormattedMessage>
</TipText>
```

I get this error: `[React Intl] Error formatting message "TIP_COUNT_FOUND" for locale: "fr"`.

**NOTE**: I don't think it is a `locale data` configuration error, because this message works:
```javascript
<FormattedMessage id='TIP_SELECT'>
  { (msg) => <TipText>{msg}</TipText> }
</FormattedMessage>
```

**Comment by longlho** [comment]
Have u tried https://github.com/formatjs/react-intl/blob/master/docs/Getting-Started.md#react-native ?

**Comment by 39otrebla** [comment]
@longlho I'm running on iOS for the moment, that's for Android. Isn't it?

**Comment by longlho** [comment]
Unfortunately I've never tried on react-native before so this is out of my wheelhouse. Will prob take me a while to debug.

What do these return for you?
```tsx
Intl.RelativeTimeFormat.supportedLocalesOf(['fr'])
new Intl.RelativeTimeFormat('fr').format(-1, 'second')
```

**Comment by 39otrebla** [comment]
`RelativeTimeFormat` doesn't seem to be present, neither in `intl` and `react-intl` packages nor using `intl` instance from React context.

**Comment by longlho** [comment]
hmm how about including the polyfill like in 2.9 as well, so something like
```
var IntlPolyfill    = require('intl');
Intl.NumberFormat   = IntlPolyfill.NumberFormat;
Intl.DateTimeFormat = IntlPolyfill.DateTimeFormat;
import 'intl-pluralrules'
import '@formatjs/intl-relativetimeformat/polyfill'
// more locale-data
```

**Comment by 39otrebla** [comment]
With the following

```
import 'intl'
import 'intl-pluralrules'
import 'intl/locale-data/jsonp/fr'
import '@formatjs/intl-relativetimeformat/polyfill'
Intl.NumberFormat   = require('intl').NumberFormat;
Intl.DateTimeFormat = require('intl').DateTimeFormat;
```

the output of `Intl.RelativeTimeFormat.supportedLocalesOf(['fr'])` is `[]`.

Also, I confirm that "normal" messages (e.g. `<FormattedMessage id=''>` work, whereas more complex messages with ReactNative components as values lead to a crash.

The error is thrown here: https://github.com/formatjs/react-intl/blob/v3.1.9/src/format.ts#L311 .

**Comment by 39otrebla** [comment]
Also, removing `<CountText></CountText>` and `<FilterText>filters</FilterText>` from this string:

```
{count, plural, one {Found} other {Found}} <CountText></CountText> {count, plural, one {result} other {results}}.\nAdd <FilterText>filters</FilterText> to your search or show all results in the list.
```
works!
So it really seems an issue in formatting a message with components as values, rather than a config issue.

**Comment by longlho** [comment]
ah this probably is due to we're using `DOMParser`. What if u polyfill `window.DOMParser = require('dom-parser')` (https://www.npmjs.com/package/dom-parser)?

**Comment by 39otrebla** [comment]
No luck... but error is changed, we might be on the right path?

New error: 
```console.error: "[React Intl] undefined is not an object (evaluating '(_a = FormatConstructor).bind') [...js bundle line...]
forEach@[native code] [...js bundle line...]
prewarmFormatters [...js bundle line...]
IntlMessageFormat@ [...js bundle line...]
```

**Comment by longlho** [comment]
ok try adding another polyfill: https://github.com/formatjs/date-time-format-timezone
thank u for ur patience!

**Comment by 39otrebla** [comment]
New error:

```
console.error: "[React Intl] Malformed XML message Found <countText></countText> results.
```

**Comment by longlho** [comment]
oh I'm sorry https://www.npmjs.com/package/xmldom is the right package, not `dom-parser`

**Comment by 39otrebla** [comment]
Under what name should it be available? Still "DomParser"? So:

```
window.DOMParser = require('xmldom')
```

**Comment by longlho** [comment]
yes

**Comment by 39otrebla** [comment]
Mmmmh.. it can't be under the same name, because now I get this error:

```
console.error: "[React Intl] Object is not a constructor (evaluating 'new DOMParser()')
```

It seems they both must be available.

**Comment by longlho** [comment]
`window.DOMParser = require('xmldom').DOMParser` is what you prob want

**Comment by 39otrebla** [comment]
Ok.. yes, that made the error disappear. But.... we reached the initial point, the one from which we started: following string:

```
{count, plural, one {Found} other {Found}} <CountText></CountText> {count, plural, one {result} other {results}}.\nAdd <FilterText>filters</FilterText> to your search or show all results in the list.
```

produces the string: `Found`, i.e. everything after the first ReactNative component disappears :(

**Comment by longlho** [comment]
can u paste the snippet where u translate the message?

**Comment by antoinerousseau** [comment]
Looks like the bug exists with RN web too: https://snack.expo.io/@antoine129/rn-issue-1430

**Comment by longlho** [comment]
oh perfect that's a lot easier to debug. I'll take a look soon

**Comment by 39otrebla** [comment]
I found the issue!

This is the NOT working version:
```javascript
<FormattedMessage
  id="TIP_COUNT_FOUND"
  values={{
    count,
    CountText: str => countTextComponent,
    FilterText: str =>  <TipText uppercase color={COLORS.textgray}>{str}</TipText>
  }}
  >
    {msg => msg}
</FormattedMessage>
```

whereas this is a working version (of course still with all those polyfills additions)

```javascript
<FormattedMessage
  id="TIP_COUNT_FOUND"
  values={{
    count,
    CountText: str => countTextComponent,
    FilterText: str =>  <TipText uppercase color={COLORS.textgray}>{str}</TipText>
  }}
/>
```

So, it seems that using `{msg => msg}` breaks up everything.

**Comment by 39otrebla** [comment]
Though, I would prefer to use the `{msg => msg}` version, because in that way we can return strings and components straight to the view hierarchy, without having them wrapper in some `Text` component.

On the web this is not a great deal because DOM is dead fast but in mobile the least components you have the better the performance (especially on Android).

Would you mind looking at the issue anyway? Maybe you can solve just by wrapping all in a `React.Fragment` when using the `{msg => msg}` version?

**Comment by antoinerousseau** [comment]
Why not unsetting `textComponent` on your `<IntlProvider>` instead? It defaults to `React.Fragment`.

https://github.com/formatjs/react-intl/blob/master/docs/Components.md#intlprovider

**Comment by 39otrebla** [comment]
@antoinerousseau I didn't know the default `textComponent` is a `React.Fragment`, that's perfect then.

The problem of setting a `textComponent` is that it is unique for all  INTL `consumers`, which is not always a good thing because we might want text wrapped in custom `Text` components in **some** cases.

**Comment by antoinerousseau** [comment]
True but I think that would over complicate this lib to make some specifics like this, better make a custom component if needed :)

Fyi `textComponent` defaults to `React.Fragment` instead of `span` since 3.x version:
https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#breaking-api-changes

**Comment by longlho** [comment]
Ah this is the issue where `react-native` doesn't allow returning `string` and forces you to always wrap it in `<Text/>` element?

**Comment by 39otrebla** [comment]
@longlho I don't think that could be the issue, because I was wrapping everything in a `TipText` component. This was the actual code:

```javascript
<TipText>
<FormattedMessage
  id="TIP_COUNT_FOUND"
  values={{
    count,
    CountText: str => countTextComponent,
    FilterText: str =>  <TipText uppercase color={COLORS.textgray}>{str}</TipText>
  }}
  >
    {msg => msg}
</FormattedMessage>
</TipText>
```

**Comment by 39otrebla** [comment]
@longlho @antoinerousseau could you please confirm that all the following libraries are **really** needed for react-native?

```javascript
require('intl')
require('intl-pluralrules') // why do we need to include this?

require('date-time-format-timezone')
require('@formatjs/intl-relativetimeformat/polyfill')
window.DOMParser = require('xmldom').DOMParser
```

Also, if I understood correctly, the following is NOT needed in the latest versions of the librarry because locale data will be taken from the JSC, right?

```javascript
require('intl/locale-data/jsonp/it')
require('intl/locale-data/jsonp/en')
require('intl/locale-data/jsonp/fr')
require('intl/locale-data/jsonp/de')
```

Would you mind updating the doc with a step-by-step guide for react-native? Or, if you prefer, I can make a PR for this. Thanks for support anyway.

**Comment by longlho** [comment]
PR is always welcome!

**Comment by longlho** [comment]
@39otrebla yeah I've added more details in https://github.com/formatjs/react-intl/blob/master/docs/Getting-Started.md#react-native-on-ios

**Comment by 39otrebla** [comment]
@longlho please reopen, I was going to write a PR for the doc. Or do you want me to open a specific issue for this?

**Comment by longlho** [comment]
That would be great! Thanks a lot!!

**Comment by 39otrebla** [comment]
@antoinerousseau @longlho did you change anything core between version `3.1.11` and `3.1.12`? Because it seems `3.1.12` is breaking our react native app....just wondering, as I'm not yet 100% if my Intl configuration (above) is really the proper one for both iOS and Android (btw, that's also why I didn't write any doc yet).

**Comment by longlho** [comment]
@39otrebla would u mind creating a new issue for RN docs? This issue is no longer relevant to that purpose so I'm closing. Thanks!
