### ISSUE TITLE
Curly braces should be escaped by single quotes

### ISSUE THREAD

**Issue by SlexAxton** [formatjs/react-intl#1437]
The ICU messageformat standard uses single quotes to escape syntax characters, but react-intl seems to use backslashes.

(This might be my fault since the intl-messageformat-parser is based on my old pegjs parser that used backslashes).

At stripe we use messages across multiple platforms and this is currently causing issues because they aren’t portable into our react-intl apps.

### Expected behavior

`This ‘{ curly brace should be escaped }’`

http://userguide.icu-project.org/formatparse/messages#TOC-Quoting-Escaping

We fixed this in `messageformat` a few years back, but it’s also how the java and ruby messageformat libs appear to work.

Here’s our parser update for extra context: https://github.com/messageformat/messageformat/blob/master/packages/parser/parser.pegjs#L100

Our similar issue: https://github.com/messageformat/messageformat/issues/171

(I don’t actually love quote eacaping, but the interop seems more important)

### Current behavior

This will throw an error because the string isn’t a valid identifier.

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | VERSION |
|      `npm ls react` | VERSION |
|     `npm --version` | VERSION |
|    `node --version` | VERSION |

| OS   | Version |
| ---- | ------- |
| NAME | VERSION |

| Browser | Version |
| ------- | ------- |
| NAME    | VERSION |

**Comment by longlho** [comment]
We fixed it in the newest version :) also parses skeletons now

**Comment by longlho** [comment]
We completely rewrote the parser & optimized its AST since Dropbox caches AST during preloading https://github.com/formatjs/formatjs/blob/master/packages/intl-messageformat-parser/src/parser.pegjs

**Comment by SlexAxton** [comment]
Ah great. It’s the current published version?

**Comment by longlho** [comment]
Yes latest greatest version

**Comment by SlexAxton** [comment]
Awesome thanks!
