### ISSUE TITLE
Rendering Righ Text on SSR

### ISSUE THREAD

**Issue by awwit** [formatjs/react-intl#1438]
If you build a static site (SSR), the rich text will not be rendered into the final html.
But, it works as expected in the browser.

### Expected behavior

```tsx
const values = {
  siteIcon (): JSX.Element {
    return (
      <span>
        <SvgLogo />
      </span>
    )
  }
}

function PoweredBy (): JSX.Element {
  return (
    <div>
      <FormattedMessage
        id='copyright.by'
        defaultMessage='Powered by <siteIcon /> Company'
        values={values}
      />
    </div>
  )
}
```

In html code of page

```html
<div>Powered by <svg>...</svg> Company</div>
```

### Current behavior

In html code of page

```html
<div>Powered by &lt;siteIcon /&gt; Company</div>
```

### Step to reproduce for BUG REPORT

Go to **Expected behavior**

### Your Environment

| Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.1.10 |
| `npm ls react` | 16.9.0 |
| `npm --version` | 6.9.0 |
| `node --version` | v12.4.0 |

| OS   | Version |
| ---- | ------- |
| openSUSE Tumbleweed | latest |

The error does not appear in the browser.

**Comment by longlho** [comment]
it's likely bc `DOMParser` isn't available in Node so u'd have to polyfill it. I'll update the doc accordingly but for now (https://www.npmjs.com/package/xmldom)
```tsx
global.DOMParser = require('xmldom').DOMParser
```

**Comment by awwit** [comment]
Thank you @longlho ! Your solution works.

**Comment by longlho** [comment]
I'll keep this open until I can update the doc

**Comment by JustFly1984** [comment]
Thank you @longlho ! You saved our day!

**Comment by longlho** [comment]
docs added in https://github.com/formatjs/react-intl/blob/master/docs/Getting-Started.md#domparser
