### ISSUE TITLE
V3 Does not work on iOS 9

### ISSUE THREAD

**Issue by r-tock** [formatjs/react-intl#1440]
Followed the upgrade docs, we have it working and tested on Safari 10+ IE 11+

We still get decent traffic from iOS 9 devices. I am getting Type error in the console. Has V3 officially dropped support for iOS 9?

**Comment by longlho** [comment]
Can you paste the err & stack trace?

**Comment by r-tock** [comment]
In iOS 9, there is no NumberFormat, Looks like we still need to use https://github.com/andyearnshaw/Intl.js

![image](https://user-images.githubusercontent.com/11711723/63395196-82446600-c388-11e9-871d-20fefb71ad18.png)

**Comment by longlho** [comment]
Yup that sounds like it.

**Comment by r-tock** [comment]
Can you update the upgrade docs to account for this? I think people should be aware. I think this relates to the right way to polyfill

**Comment by longlho** [comment]
yup, I've added more details in https://github.com/formatjs/react-intl/blob/master/docs/Getting-Started.md#runtime-requirements

**Comment by YufeeXing** [comment]
Do this can work well if I don't use NumberForma() for IOS9. I just want to use this to display different text with the same key in language.json files.  I used React Hooks and high order Component api provided by this package.
