### ISSUE TITLE
Messages provided from IntlProvider and defaultMessage have different behavior

### ISSUE THREAD

**Issue by inomdzhon** [formatjs/react-intl#1442]
### Expected behavior

- ✅ `FormattedMessage` with rich text combined with **HTML code** (ex: `Hello&nbsp;<tag>{text}</tag>`) provided by `defaultMessage` should return formatted message.
- ✅ `FormattedMessage` with rich text combined with **Unicode** (ex: `Hello\u0020<tag>{text}</tag>`) provided by `defaultMessage` should return formatted message.
- ✅ `FormattedMessage` with rich text combined with **HTML code** (ex: `Hello&nbsp;<tag>{text}</tag>`) provided by `InltProvider` should return formatted message.
- ✅ `FormattedMessage` with rich text combined with **Unicode** (ex: `Hello\u0020<tag>{text}</tag>`) provided by `InltProvider` should return formatted message.

### Current behavior

- ✅ `FormattedMessage` with rich text combined with **HTML code** (ex: `Hello&nbsp;<tag>{text}</tag>`) provided by `defaultMessage` formats message.
- ❌ `FormattedMessage` with rich text combined with **Unicode** (ex: `Hello\u0020<tag>{text}</tag>`) provided by `defaultMessage` doesn't format message.
- ❌ `FormattedMessage` with rich text combined with **HTML code** (ex: `Hello&nbsp;<tag>{text}</tag>`) provided by `InltProvider` doesn't format message (`[React Intl] Error formatting message: "..." for locale: "..."`).
- ✅ `FormattedMessage` with rich text combined with **Unicode** (ex: `Hello\u0020<tag>{text}</tag>`) provided by `InltProvider` formats message.

### Step to reproduce for BUG REPORT

Code example https://codesandbox.io/s/ig2g4

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.1.11 |
|      `npm ls react` | 16.8.6 |
|     `npm --version` | 6.9.0 |
|    `node --version` | 10.16.1 |

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.

**Comment by longlho** [comment]
related issues: https://github.com/formatjs/formatjs/issues/148

**Comment by inomdzhon** [comment]
🎉🎉🎉

Yeah! Thank you very much @longlho for efficiency!

---

PS

It's not so critical, but what about this case?

❌ `FormattedMessage` with rich text combined with Unicode (ex: Hello\u0020<tag>{text}</tag>) provided by `defaultMessage` doesn't format message.

**Comment by inomdzhon** [comment]
@longlho Yes, it is, but when we provide this text with Unicode to `FormattedMessage` from `IntlProvided` all works 🤔 You can check it here https://codesandbox.io/s/ig2g4 (v3.1.11)

**Comment by longlho** [comment]
@inomdzhon ok turns out it's bc attribute being passed in JSX Element behaves the same way, so in that scenario, since `messages` from `IntlProvider` are JS strings, it's passed down as `Hello {text}`, but in the case of `<FormattedMessage defaultMessage="Hello\u0020{text}" />` we actually got the string verbatim as `Hello\u0020{text}`.

Changing to `<FormattedMessage defaultMessage={'Hello\u0020{text}'} />` makes them behave the same way

**Comment by inomdzhon** [comment]
Oh, I see.
Ok, thank you again, @longlho  ✌️
