### ISSUE TITLE
A way to output message ids in testing environment (instead of actual translations)

### ISSUE THREAD

**Issue by surgeboris** [formatjs/react-intl#1443]
I'd like to use [`ByText`-like queries](https://testing-library.com/docs/dom-testing-library/api-queries#bytext) in my tests, however I do not want to couple my tests with actual English translations (since I expect lots of minor adjustments to them).

I'd like to output message ids instead of actual translations in my test environment. I've struggled to find a way of achieving that with `react-intl`, so I'm creating this feature request.

I do understand that I can just use [`ByTestId`-query](https://testing-library.com/docs/dom-testing-library/api-queries#bytestid), that you're using in [your example](https://github.com/formatjs/react-intl/blob/16fbd6d9cd05e165000689598a0dcee823f298d2/docs/Testing-with-React-Intl.md#react-testing-library)). However I think that [there is more value](https://testing-library.com/docs/guide-which-query#priority) in using [`ByText`-like queries](https://testing-library.com/docs/dom-testing-library/api-queries#bytext) over [`ByTestId` query](https://testing-library.com/docs/dom-testing-library/api-queries#bytestid).

**Comment by longlho** [comment]
I personally don't use `react-testing-library` so the example might be very out of date. Can you clarify what your expected outcome is?

**Comment by surgeboris** [comment]
@longlho Sorry, I've put too much emphasis on `react-testing-library` because its philosophy explains WHY I want that specific feature from `react-intl`.

But the feature itself is not tied to `react-testing-library`,  I just want to be able to set up my test environment in such a way that the following tests will pass:

**MyButton.jsx**
```jsx
import React from "react";
import { FormattedMessage } from "react-intl";

export function MyButton() {
  return (
    <button>
      <FormattedMessage id="message-id" defaultMessage="Actual translation" />
    </button>
  );
}
```

**MyButton.test.jsx**
```jsx
import React from "react";
import { render } from "react-dom";
import { IntlProvider } from "react-intl";

import { MyButton } from "./MyButton.jsx";

describe("MyButton", () => {
  const htmlString = renderHtmlString(<MyButton />);

  test("does not render actual translation message", () => {
    expect(htmlString.includes("Actual translation")).toBe(false);
  });

  test("does render message id", () => {
    expect(htmlString).toMatchInlineSnapshot(
      `"<button>message-id</button>"`
    );
  });
});

function renderHtmlString(componentJsx) {
  const hostElement = document.createElement("div");
  document.body.append(hostElement);
  render(<IntlProvider locale="en">{componentJsx}</IntlProvider>, hostElement);
  return hostElement.innerHTML;
}
```

**Comment by longlho** [comment]
You can pass in `messages` in your `Provider` during test to map ID -> ID so `FormattedMessage` always output ID. I think as a lib we're not positioned to do that, because i18n is part of business logic for a lot of apps, e.g at least at Dropbox:

1. String truncation logic is i18n-aware using `Intl.Collator`
2. Relative time format is also key business logic

I suppose we can pass down a flag in `IntlProvider` to just render out ID but I think that responsibility fits better in consumer land than this lib.
