### ISSUE TITLE
docs: v2 --> v3 Upgrade Guide

### ISSUE THREAD

**Issue by Aghassi** [formatjs/react-intl#1447]
I noticed there are upgrade docs for prior majors, but none for 3.x.x. The Changelog is also a little hard to follow due to all the betas (each having some changes, but the final v3 is pretty sparse). Can a migration guide be created for 3.x.x?

**Comment by longlho** [comment]
https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md
