### ISSUE TITLE
Running examples doesn't work

### ISSUE THREAD

**Issue by thoughtassassin** [formatjs/react-intl#1449]
### Expected behavior

When I run yarn example I excpect the example to work.

### Current behavior

I get an error like so: /react-intl/examples/TimeZone.tsx:2:59: Cannot resolve dependency '../' at '/react-intl'
    at Resolver.resolve (/react-intl/node_modules/parcel/src/Resolver.js:71:17)

### Step to reproduce for BUG REPORT

Run `yarn` and the `yarn example`

All of the .tsx files in the example directory import from '../'. How does that even work without an index.js in the root? Here is the import statement in question:

`import {FormattedDate, FormattedTime, IntlProvider} from '../';`

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | VERSION |
|      `npm ls react` | VERSION |
|     `npm --version` | VERSION |
|    `node --version` | VERSION |

| OS   | Version |
| ---- | ------- |
| NAME | VERSION |

| Browser | Version |
| ------- | ------- |
| NAME    | VERSION |

**Comment by longlho** [comment]
did u `build` before?

**Comment by thoughtassassin** [comment]
nope

**Comment by thoughtassassin** [comment]
is that necessary?

**Comment by longlho** [comment]
yes

**Comment by thoughtassassin** [comment]
Is that in the README.md? I didn't see that you had to run `build` first. I just saw that there were several "runnable examples": https://github.com/formatjs/react-intl/tree/master/examples
