### ISSUE TITLE
Much larger bundle size with polyfills

### ISSUE THREAD

**Issue by robrichard** [formatjs/react-intl#1450]
### Expected behavior

react-intl v3 should support all modern browsers without drastically increasing bundle sizes

### Current behavior

react-intl v3 is over 300% larger when supporting the latest released version of Safari.

#### react-intl@2.9.0

Set up a new repo with 
* react-intl@2.9.0
* react@16.9.0
* prop-types@15.7.2

Create an entry file:

```js
require('react-intl');
require('react-intl/locale-data/en');
```

Bundle this entry file:

```
$ node_modules/.bin/parcel build index.js
✨  Built in 2.81s.

dist/index.js.map    263.41 KB     35ms
dist/index.js         80.75 KB    2.54s
```

Bundle size is **80.75 KB** minified (19 KB gzipped)

#### react-intl@3.1.11

Set up a new repo with 
* react-intl@3.1.11
* react@16.9.0
* prop-types@15.7.2
* @formatjs/intl-relativetimeformat@2.8.2
* intl-pluralrules@1.0.3

Create an entry file with polyfills as recommend by the docs:

```js
require('react-intl');
require('intl-pluralrules');
require('@formatjs/intl-relativetimeformat/polyfill');
require('@formatjs/intl-relativetimeformat/dist/locale-data/en');
```

Bundle this entry file:

```
$ node_modules/.bin/parcel build index.js                            
✨  Built in 5.22s.

dist/index.js.map    ⚠️  1.01 MB     62ms
dist/index.js         313.15 KB    4.95s
```

Bundle size is **313.15 KB** minified (51 KB gzipped)

### Your Environment

bundled both with parcel-bundler@1.12.3

**Comment by longlho** [comment]
what's the difference when minzipped?

**Comment by robrichard** [comment]
Edited the original post to clarify the numbers are after minification.

react-intl@2: 80.75 KB minified, 19 KB gzipped
react-intl@3: 313.15 KB minified, 51 KB gzipped

**Comment by JustFly1984** [comment]
wow that is huge!

**Comment by longlho** [comment]
hmm not sure what that's the result, but a quick breakdown (minified) is:

![](https://badgen.net/badgesize/normal/https://unpkg.com/@formatjs/intl-relativetimeformat@2.8.2/dist/locale-data/en.js?label=@formatjs/intl-relativetimeformat%20locale-data%20en)
![](https://badgen.net/bundlephobia/min/@formatjs/intl-relativetimeformat?label=@formatjs/intl-relativetimeformat)
![](https://badgen.net/bundlephobia/min/intl-pluralrules?label=intl-pluralrules)
![](https://badgen.net/bundlephobia/min/react-intl?label=react-intl)

So total minified is roughly 77K, which is even smaller than react-intl@2 like u mentioned above primarily even though react-intl@2 uses old CLDR and new CLDR has more data.

react-intl itself got smaller https://bundlephobia.com/result?p=react-intl@3.1.11

**Comment by longlho** [comment]
and with parcel, same index file u posted:
```
PS C:\Users\holev\react-intl> npx parcel build .\index.js                                                               √  Built in 979ms.                                                                                                      
dist\index.js.map    421.11 KB     86ms                                                                                 dist\index.js        133.75 KB    359ms
```

**Comment by robrichard** [comment]
@longlho do the numbers you posted include transitive dependencies? I'm not sure why you got different results, I'm consistently getting 313 KB. Using source-map-explorer, the largest chunk of the bundle comes from `date-fns` at 161 KB.

[index.js.map.txt](https://github.com/formatjs/react-intl/files/3537265/index.js.map.txt)
[index.js.txt](https://github.com/formatjs/react-intl/files/3537266/index.js.txt)
[dist_index.js - Source Map Explorer.html.txt](https://github.com/formatjs/react-intl/files/3537268/dist_index.js.-.Source.Map.Explorer.html.txt)

(attachments are appended with .txt to allow uploading to github)

**Comment by longlho** [comment]
Looks like you’re not treeshaking it out then. date-fns aren’t used it’s
just part of utils

**Comment by longlho** [comment]
To put emphasis on tree-shaking, it's pretty important since our AST parser also contains AST printer that only works in Node (bc at runtime there's no use case for re-printing AST, only for build-time toolchain) so I think there's something going on with your setup.

**Comment by longlho** [comment]
@robrichard 	is there anything actionable here from our side?

**Comment by robrichard** [comment]
@longlho is there any way to get the bundle size down to parity with v2? Even with tree shaking, the bundle size increase (80.75 KB to 133.75 KB) is enough that we won't be able to upgrade to v3. Safari is the browser we get the most traffic from so we'll need to wait until a version that natively supports these APIs is released and enough of our users upgrade. It's a bit disappointing that we won't be able to move away from deprecated React features until then.

**Comment by longlho** [comment]
@robrichard 
```
~/react-intl ❯❯❯ cat index.js                                                                                                                                           import '@formatjs/intl-pluralrules/polyfill'
import '@formatjs/intl-pluralrules/dist/locale-data/en'
import '@formatjs/intl-relativetimeformat/polyfill'
import 'react-intl'
```
```
~/react-intl ❯❯❯ npx parcel build index.js                                                                                                                              Built in 373ms.                                                                                                                                                                
dist/index.js.map    342.63 KB    105ms                                                                                                                                            dist/index.js         96.86 KB    108ms       
```
If u use our polyfill for `@formatjs/intl-pluralrules` u can selectively load locale-data which has a lot smaller size.

**Comment by robrichard** [comment]
@longlho is `@formatjs/intl-relativetimeformat/dist/locale-data/en` needed as well? I can see both `dist/locale-data/en.js` and `/dist/en.js` are both included

**Comment by longlho** [comment]
it's bundled w/ `en` by default so that's not necessary

**Comment by cdeutsch** [comment]
I wouldn't upgrade to v3 yet

It seems like v3 hasn't been tested in Safari, Edge, or IE  😑 
https://github.com/formatjs/react-intl/issues/1427#issuecomment-522600305
https://github.com/formatjs/formatjs/issues/172

**Comment by longlho** [comment]
Not sure what you're talking about @cdeutsch 	multiple sites are running v3 in prod and supporting IE11, including Dropbox.

**Comment by cdeutsch** [comment]
I've been running it for a couple of weeks, and still finding bugs that would indicate this was never tested in anything but Chrome  
https://github.com/formatjs/formatjs/issues/172

It looks like the "Getting started" has been changed to not use `
`intl-locales-supported`, but bundling polyfills individually just creates more problems with the way our projects Webpack is setup to do code splitting.

Seriously considering going back to v2 at this point.

I still don't know what was gained with the upgrade.

**Comment by longlho** [comment]
I think you should do what's best for your product but we won't be supporting v2 anymore :)

**Comment by cdeutsch** [comment]
Another example is that your [Getting Started](https://github.com/formatjs/react-intl/blob/95418713787ad65c104012806788fb023cd03fd1/docs/Getting-Started.md#runtime-requirements) indicates to check for `Intl.PluralRules` support using...

```
if (!Intl.PluralRules) {
```

...yet this is `false` in IE11 (but the polyfill IS needed for it to work)

According to [Can I Use](https://caniuse.com/#feat=intl-pluralrules) and personal experience of actually trying to use `react-intl` in IE11, the `Intl.PluralRules` function exists but it's not implemented

I have a real hard time believing anybody working on this has tried to use `react-intl` in anything but Chrome.

**Comment by longlho** [comment]
hmm I don't think `Intl.PluralRules` exists in IE11

**Comment by cdeutsch** [comment]
> hmm I don't think `Intl.PluralRules` exists in IE11

Oops, you're right (I was looking at a polyfilled site) [I guess Can I Use is wrong]

**Comment by longlho** [comment]
It does say that it's avail on Edge 18 but methods are not implemented so that is a bug on our side. If u create a separate GH issue we can fix that.
