### ISSUE TITLE
FormattedRelativeTime with positive value and updateIntervalInSeconds. 

### ISSUE THREAD

**Issue by pierreferry** [formatjs/react-intl#1455]
Consider this
`<FormattedRelativeTime value={3} updateIntervalInSeconds={1} numeric="auto"/>`
### Expected behavior

It should display : 
- "in 3 seconds" 
- "in 2 seconds" 
- "in 1 second" 
- "now" 
- "1 second ago" 

### Current behavior

It displays : 
- "in 3 seconds" 
- "in 2 seconds" 
- "in 1 second" 
- "in 3 seconds" _// This is the buggy part_
- "1 second ago" 

Please check this code sandbox to witness the bug
https://codesandbox.io/s/react-intl-formatrelativedate-broken-1fuhp

**Comment by longlho** [comment]
Ah looks like a bad falsy check filtering out 0. Will fix soon
