### ISSUE TITLE
V3 - API and TypeScript - props problem

### ISSUE THREAD

**Issue by qweluke** [formatjs/react-intl#1457]
Hi am I unable to use intl API with Components. It is working fine with React.FC components.
I am using

### Expected behavior

I should be able to use react-intl API with TypeScript

### Current behavior

Property 'intl' does not exist on type 'Readonly<IProps> & Readonly<{ children?: ReactNode; }>'.  TS2339

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.1.13 |
|      `npm ls react` | 16.9.9 |
|     `npm --version` | 6.9.9 |
|    `node --version` | 10.16.0 |
|    `npm ls @types/react-intl` | 3.0.0 |
|    `npm ls typescript` | 3.5.3 |

| OS   | Version |
| ---- | ------- |
| MacOS | Mojave |

| Browser | Version |
| ------- | ------- |
| NAME    | VERSION |

My code:

```
import React, { Component } from 'react';
import { connect } from 'react-redux';
import Blockquote from '../../Blockquote/Blockquote';
import { FormattedMessage, injectIntl } from 'react-intl';

interface IProps {
}

class Dashboard extends Component<IProps > {
  constructor(props: any) {
    super(props);

   console.log(props); //contains props.intl  
  }

  render() {
    const { intl } = this.props;

    return (
      <Blockquote text={intl.formatNumber(2450)} subText={intl.formatMessage({ id: 'affiliate.tickets_sold' })} />
    );
  }
}

function mapStateToProps(state: any) {
  return state;
}

export default injectIntl(connect(mapStateToProps)(Dashboard));
```

**Comment by qweluke** [comment]
changing 
`class Dashboard extends Component<IProps & WrappedComponentProps> {...}`
solved the problem

**Comment by de83c78d1f** [comment]
You did not solve the problem, you evaded it. Types for 3.13 are broken compared to 3.11.
