### ISSUE TITLE
Self-closing tags in rich text are no longer supported?

### ISSUE THREAD

**Issue by awwit** [formatjs/react-intl#1458]
I have code that works well on `react-intl@3.1.10`

All problems concern rich text:

1. But after updating to `3.1.13`, self-closing tags stopped working. And tags with capital letters.
2. Why it was forbidden to use tags like `<br/>` ? I need them, but `react-intl` refuses to format the message in which there is `<br/>` and fallback message to `defaultMessage`.

### Expected behavior

```tsx
const values = {
  siteicon (): JSX.Element {
    return (
      <span>
        <SvgLogo />
      </span>
    )
  }
}

function PoweredBy (): JSX.Element {
  return (
    <div>
      <FormattedMessage
        id='copyright.by'
        defaultMessage='Powered by <siteicon /> Company'
        values={values}
      />
    </div>
  )
}
```

Render as

```html
<div>Powered by <span><svg>...</svg></span> Company</div>
```

### Current behavior

```html
<div>Powered by <span><svg>...</svg></span> <!-- After self-closing tag all content is deleted --></div>
```

### Your Environment

| Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.1.13 |
| `npm ls react` | 16.9.0 |
| `npm --version` | 6.9.0 |
| `node --version` | v12.4.0 |

| OS   | Version |
| ---- | ------- |
| openSUSE Tumbleweed | latest |

| Browser | Version |
| ------- | ------- |
| Chromium | 76.0.3809.100 (openSUSE Build), (64 bits) |

**Comment by longlho** [comment]
Thanks for reporting. You can replace self-closing tag with ICU placeholder `{placeholder}` since it's more spec-compliant. Please refer to this [section](https://github.com/formatjs/formatjs/tree/master/packages/intl-messageformat#caveats) for caveats. The technical issue is that custom self-closing tags are not HTML-compliant, and the use case is already covered by ICU so there's no strong use case for it.

The 2nd issue u mentioned is actually a bug. We'll take a look soon.

**Comment by longlho** [comment]
`<br/>` seems ok? https://codesandbox.io/s/zealous-murdock-k6hzk

**Comment by awwit** [comment]
@longlho Thank you for making an example!

I edited it: https://codesandbox.io/s/broken-resonance-dkfww

An error occurs if you try to convert br to tag.

**Comment by longlho** [comment]
Yeah that is intentional bc `<tag/>` is not valid HTML since it's not a void element. In general `{tag}` is definitely preferrable.

**Comment by awwit** [comment]
Well... it was better when it was possible with self-closing tags.

It doesn't matter if the html standard has self-closing tags if they are used in reality in html.

I do not like your solution, as it reduces the capabilities of the library. Which have already been implemented.

It is somehow strange...

As you wish, I will have to adapt.

**Comment by TymchenkoOleksandr** [comment]
using react-intl v5 and `<br></br>` with `values={{ br: () => <br /> }}` - works fine

**Comment by patcon** [comment]
Fwiw, this ICU placeholder solution doesn't work for something like `defaultRichTextElements`, where someone wants to define some global syntax and re-use it without passing in special:
https://formatjs.io/docs/react-intl/api/#defaultrichtextelements

As in, if we want translators to have an easy way to add a <nonBreakingSpace /> into arbitrary strings they're translating. For example, `Foo:` in English would be `Foo :` in french, and `Foo<nonBreakingSpace />:` would make it more clear what is going on, so translators don't accidentally replace it with normal spaces.

**Comment by barthharrison87** [comment]
Lol

definition
