### ISSUE TITLE
Compilation error from intl-messageformat

### ISSUE THREAD

**Issue by irandamay** [formatjs/react-intl#1459]
### Current behavior

After installing 3.1.12 and 3.1.13, my app no longer compiles with the following message:

```
Failed to compile

./node_modules/intl-messageformat/lib/core.js
Attempted import error: 'formatHTMLMessage' is not exported from './formatters'.
```

### Step to reproduce for BUG REPORT

This is a React app created with create-react-app.  There are no real steps to reproduce. react-intl 3.1.11 works fine and then 3.1.12/3.1.13 just give the above error in the console and browser window as soon as the new version is installed.

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.1.13 |
|      `npm ls react` | 16.9.0 |
|     `npm --version` | 6.11.2 |
|    `node --version` | 10.15.3 |

| OS    | Version |
| ----  | ------- |
| macOS | 10.14.6 |

| Browser | Version |
| ------- | ------- |
| Safari  | 12.1.2 |

**Comment by longlho** [comment]
do u have a codesandbox?

**Comment by longlho** [comment]
close due to stale
