### ISSUE TITLE
XML tags in FormattedMessage do not work when using a render prop

### ISSUE THREAD

**Issue by ralphholzmann** [formatjs/react-intl#1461]
### Expected behavior
Using XML tags in a message will work if you're using a function child (render prop).

### Current behavior
XML tags in a message do not work if you're using a function child (render prop).

### Step to reproduce for BUG REPORT

Bug reproduction: https://codepen.io/rlph/pen/JjPyYwM?editors=0010

### Your Environment

Seems to happen everywhere.

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.1.12 |
|      `npm ls react` | 16.9.0 |
|     `npm --version` | 6.9.0 |
|    `node --version` | v10.16.3 |

| OS   | Version |
| ---- | ------- |
| MacOS Catalina | 10.15 Beta |

**Comment by ralphholzmann** [comment]
Update per the render prop in message.tsx, it seems that you're now passing a spread array of nodes to the render prop. Perhaps the documentation should be updated to reflect this?

**Comment by longlho** [comment]
Thanks for reporting!
