### ISSUE TITLE
Latest <FormattedRelativeTime />: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by goodwin64** [formatjs/react-intl#1465]
### Expected behavior
Relative time works properly - update are applied using the defined interval.

### Current behavior
![Screenshot from 2019-09-02 12-04-22](https://user-images.githubusercontent.com/10671879/64103044-e6e4c500-cd79-11e9-9cfc-6720a1c98f87.png)

### Step to reproduce for BUG REPORT

minimum live example:
https://codesandbox.io/s/icy-fire-p60fu

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | react-intl@3.1.13 |
|      `npm ls react` | react@16.8.6 |
|     `npm --version` | 6.4.1 |
|    `node --version` | v10.15.0 |

| OS   | Version |
| ---- | ------- |
| Ubuntu | 18.04.1 |

| Browser | Version |
| ------- | ------- |
| Chrome    | Version 70.0.3538.77 (Official Build) (64-bit) |

**Comment by longlho** [comment]
The codesandbox works fine for me

**Comment by longlho** [comment]
oh looks like your chrome version is old & you need `Intl.RelativeTimeFormat` (avail in [Chrome 71+](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RelativeTimeFormat))

**Comment by longlho** [comment]
We have instructions on how to polyfill it

**Comment by goodwin64** [comment]
Wow! Browsers become outdated quite rapidly nowadays :)
Thank you for clarification!
