### ISSUE TITLE
Docs issue with Edge and loading `Intl.PluralRules` poloyfill.

### ISSUE THREAD

**Issue by cdeutsch** [formatjs/react-intl#1469]
According to [Can I Use](https://caniuse.com/#feat=intl-pluralrules) the `Intl.PluralRules` function exists but it's not implemented in Edge.

So the polyfill detection mentioned in [Getting Started](https://github.com/formatjs/react-intl/blob/95418713787ad65c104012806788fb023cd03fd1/docs/Getting-Started.md#runtime-requirements) won't work.

```
if (!Intl.PluralRules) {
```

Although as @longlho [mentions](https://github.com/formatjs/react-intl/issues/1450#issuecomment-527605874):  
>  we technically support 2 most recent browser versions + IE11

It's also not clear if all versions of Windows are going to have Edge updated to the Chromium version and when. 

My machine is still on Edge 44.X apparently. 
77.X and 78.X look to be the Chromium versions.

Ref:  
https://github.com/formatjs/react-intl/issues/1450#issuecomment-527605874

**Comment by longlho** [comment]
Hmm so I just tried on Edge 18 and `Intl.PluralRules` is there & its methods are functional, so looks like `caniuse` is wrong. MDN seems to agree with me https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/PluralRules#Browser_compatibility

Looks like `if (!Intl.PluralRules)` works as Edge detection as well.

**Comment by longlho** [comment]
Googling around seems to also indicate `caniuse` is wrong. IDK where they get that data form.

**Comment by cdeutsch** [comment]
Can confirm. Closing.
