### ISSUE TITLE
useIntl not included in typescript type definitions

### ISSUE THREAD

**Issue by intergalactic-overlords** [formatjs/react-intl#1470]
### Expected behavior

No typescript error when using `useIntl` hook.

### Current behavior

When using `useIntl` hook in a typescript project, I get the following error from typescript:
```
TS2305: Module '"react-intl"' has no exported member 'useIntl'.
```
Otherwise, the hook works as it should.

### Step to reproduce for BUG REPORT

Use `useIntl` hook in a typescript project and try to compile.

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.2.0 |
|      `npm ls react` | 16.9.2 |
|     `npm --version` | 6.4.1 |
|    `node --version` | 8.16.0 |

**Comment by longlho** [comment]
I can't repro this: https://codesandbox.io/s/heuristic-wildflower-gykb7

**Comment by intergalactic-overlords** [comment]
hmm, it seemed like there was another module installed (@comparaonline/react-intl-hooks) that caused this error. I removed it and everyting works ok.
