### ISSUE TITLE
Add `<FormattedDateTime>` & `formatDateTime`.

### ISSUE THREAD

**Issue by septs** [formatjs/react-intl#1471]
**Is your feature request related to a problem? Please describe.**
Reduce duplicate code

**Describe the solution you'd like**
Includes many `date + time` pattern in our designs

**Describe alternatives you've considered**
Packed instead of HOC

**Additional context**
N/A

**Comment by longlho** [comment]
both `FormattedDate` & `FormattedTime` allows u to pass in the full `Intl.DateTimeFormatOptions` object, so they are basically just aliases.

**Comment by septs** [comment]
`FormattedDate` and `FormattedTime`,
The semantics of writing code is not correct.

**Comment by longlho** [comment]
This is not the behavior we encourage bc date & time have different semantics so it's not safe to combine them. This is the same reason why combining them warrants separate options such as `dateStyle` & `timeStyle` in the spec. Whatever assumption you have when date time goes together it's typically for English and might not apply.

Example:
```
new Intl.DateTimeFormat('en', {dateStyle: 'full'}).format(new Date(2020, 1, 1, 0, 30))
// Saturday, February 1, 2020

new Intl.DateTimeFormat('en', {timeStyle: 'full'}).format(new Date(2020, 1, 1, 0, 30))
// 12:30:00 AM Eastern Standard Time

new Intl.DateTimeFormat('en', {dateStyle: 'full', timeStyle: 'full'}).format(new Date(2020, 1, 1, 0, 30))
// Saturday, February 1, 2020 at 12:30:00 AM Eastern Standard Time (notice the addition of the word `at`
```
