### ISSUE TITLE
How to add Punjabi (India) Locale under locale-data folder ?

### ISSUE THREAD

**Issue by msgill2017** [formatjs/react-intl#1475]
hi I am want to add Punjabi (India) language support to react-intl. But I didn't find the locale-data folder on react-intl repo.
Help me from where should I start ?
so next time when I  install react-intl it shows under locale-data folder like 
react-intl/locale-data/pb.js

**Comment by longlho** [comment]
react-intl v3 no longer distributes `locale-data`. Since we use CLDR, I believe punjabi (`pa`) is already supported

**Comment by Yvanovitch** [comment]
Hi,
would you mind to update the [Getting Started Guide](https://github.com/formatjs/react-intl/blob/master/docs/Getting-Started.md) ? There is a reference to "locale-data" which is confusing as a beginner.

There is also this [Migration Doc page ](https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#migrate-to-using-native-intl-apis) which states "React Intl v3 no longer comes with CLDR data and rely on native Intl API instead."

I'm confused with your message

**Comment by longlho** [comment]
Can you pinpoint which section in Getting Started you're referring to?

**Comment by Yvanovitch** [comment]
Yes, in the chapter [Runtime Requirement](https://github.com/formatjs/react-intl/blob/master/docs/Getting-Started.md#runtime-requirements), first code section

**Comment by longlho** [comment]
Hmm the `locale-data` is for polyfills. Do you have a suggestion on what to change it to?

**Comment by Yvanovitch** [comment]
I have no idea, I'm just trying to understand how to load messages in various languages from different files, I couldn't find anywhere a clear explanation. I thought locale-data was somehow related to this task.

**Comment by longlho** [comment]
Nope, this task is filed in the wrong repo
