### ISSUE TITLE
SCRIPT1006: Expected ')' in IE11, compiled with Webpack

### ISSUE THREAD

**Issue by MaximeCheramy** [formatjs/react-intl#1478]
I've upgraded react-intl from 2.9 to 3.2.1 and it crashes on IE11 with the following message: SCRIPT1006: Expected ')'
The line:
```
z={38:"&amp;",62:"&gt;",60:"&lt;",34:"&quot;",39:"&#x27;"},W=/[&><"']/g;function q(e,t,n={})
```

I suspect that my webpack uses the file lib/index.js which import lib/utils.js that won't work on IE11 (default argument). I do not run babel on the node_modules.

### Your Environment

react-intl 3.2.1
react 16.8.6
npm 6.11.3
node 10.14.2
webpack 4.39.2

**Comment by longlho** [comment]
You'd have to babel some libs in `node_modules` in v3 per https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#esm-build

**Comment by MaximeCheramy** [comment]
Thank you for your very quick answer! This information is not indicated here: https://github.com/formatjs/react-intl/blob/master/docs/Getting-Started.md

I'm curious to know the reason why you had to do this, I've more than a hundred of dependencies on my project and that's the first that requires to be babelized to work.

It seems to work with:

```
exclude: /node_modules\/(?!react-intl|intl-messageformat|intl-messageformat-parser\/)/
```

**Comment by longlho** [comment]
bc in general transpiled code comes with random polyfill helpers, like `__assign` instead of `Object.assign`, & stuff like this. Internally within corporate settings like DBX the preference is non-transpiled code to reduce size actually.

**Comment by MaximeCheramy** [comment]
I see, I agree but I believe this is usual and thus it should be clear to new users that this library requires babel to work on old browsers. I'd recommend to add more warnings in the documentation :).

Thanks again for the support and your work.

**Comment by longlho** [comment]
Yup I'll update `Getting Started`! Thanks for reporting!

**Comment by panuhorsmalahti** [comment]
Hi, could you reconsider this? The documentation states that IE11 is supported, this would imply that the dist files are already IE11 compatible.

My main issue with this is that if `react-intl` is used with a webpack TypeScript loader, e.g. `awesome-typescript-loader`, it's not possible (as far as I know) to use this loader with `react-intl` if IE11 support is required. Instead you need to add in a separate loader, .e.g `babel-loader` to transpile these couple of modules.

**Comment by longlho** [comment]
We do dist out ES5, sound like your toolchain might have picked up ES6 instead?

**Comment by panuhorsmalahti** [comment]
That's possible. I don't see "lib" property in package.json, do you mean this in package.json: `"module": "./lib/index.js",`?

Hmm, I should try to update react-intl (and it's dependencies) to see what is included with the latest version.
