### ISSUE TITLE
IntlProvider undefined in Jest test

### ISSUE THREAD

**Issue by MaronMariusz** [formatjs/react-intl#1482]
Hi,

can somebody tell me why IntlProvider once imported as: `import { IntlProvider } from 'react-intl'` in Jest test is value of `undefined` ?

In my App I normally use it and it is not `undefined`

I am using `react-intl: 3.2.1` with `react: 16.9.0`.

Am I missed something during v2 => v3 migration ?

Cheers!

**Comment by longlho** [comment]
Hmm we use jest to test react-intl and it’s not undefined. What’s your jest
config? Can you create a repo to repro?

**Comment by MaronMariusz** [comment]
I do not have any jest config defined. For my repo actually it is not possible to share and for newly created project via CRA works fine and modules of `react-intl` are available so it is hard for me to reproduce it. All other libs are imported properly but (as I see now) all of the `react-intl` components are undefined not only `IntlProvider`. Default export shows only `{}`. I will try to dive into this again but do not know on which area of the project it could be failed or what can have impact on this :) It seems that it is only issue on my side.

**Comment by webwelten** [comment]
Hey, I'm facing the same issue. Any news from your side?

**Comment by MaronMariusz** [comment]
Hi!

Yes, I found what caused this issue and it turned out that it was because of `/__mocks__/react-intl.ts`. I just forgot that I had code commented out there and Jest tried to export it as undefined. If you have this type of mock you should check what is going on there.

Cheers!
