### ISSUE TITLE
Partial Preset Context

### ISSUE THREAD

**Issue by septs** [formatjs/react-intl#1484]
**Is your feature request related to a problem? Please describe.**
Reduce duplicate code

**Describe the solution you'd like**
3 to 4 layer business nested, will prefix string for make it too long
e.q:
> path: settings page -> profile page -> avatar editor
intl id prefix: `settings.profile.avatar-editor` + `.[formatted component id]`

```jsx
<IntlPartial prefixId="parent-mdoule.sub-module" format={partialFormat}>
    <FormattedMessage id=".title" />
</IntlPartial>
```

Through `IntlPartial` context set **prefix id** and **format** definitions,
for sub-component using

Known issues:
1. How to differentiate, in `IntlPartial` not requires of prefix `formatted component` and `intl object`
2. My opinion is sub formatted component using id starts with `.`(dot), intl id: `.[name]`.

**Describe alternatives you've considered**
```jsx
const prefix = "[prefix intl id string]";

<FormattedMessage id={`${prefix}.title`} />
```

**Additional context**
N/A

**Comment by longlho** [comment]
Hmm we don't make assumption around how IDs are structured so I don't think this should be in the core lib. This can be solved in user space.

**Comment by septs** [comment]
OK
