### ISSUE TITLE
Unable to get working in IE11

### ISSUE THREAD

**Issue by jpreecedev** [formatjs/react-intl#1486]
I am unable to get React Intl working correctly in IE11.  Untranspiled code is ending up in the bundle and failing on IE11.  I have created an example repo that demonstrates the issue.  I am using Webpack, TypeScript and I have read all the documentation but to no avail.

### Expected behavior

Should display "Hello Eric, you have 1,000 messages" in IE

### Current behavior

Nothing appears because console error

### Step to reproduce for BUG REPORT

I have reproduced the issue in the simplest way I can and posted on GitHub.

https://github.com/jpreecedev/webpack-4-typescript-react-intl

Please run `npm i && npm start`, then navigate to `http://localhost:8080` to replicate the issue. 

### Your Environment

MacOS Mojave, VS Code, Webpack, TypeScript, Node 12, NPM 6.10, React@latest, ReactIntl@latest.

Works in Chrome, fails in IE11

**Comment by longlho** [comment]
Thanks for reporting. There were some typings issue on our side so I just released a fix. I've also updated the docs to include instructions on transpiling `react-intl`. `webpack` by default picks up `module` which is ES6: https://github.com/formatjs/react-intl/blob/master/docs/Getting-Started.md#webpack

For your specific use cases, the fix is:
```diff
diff --git a/tsconfig.json b/tsconfig.json
index 0f29065..1159e18 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -10,7 +10,7 @@
       "es2017.intl",
       "es2018.intl"
     ],
-    "allowJs": false,
+    "allowJs": true,
     "checkJs": false,
     "skipLibCheck": false,
     "noImplicitAny": false,
diff --git a/webpack.config.js b/webpack.config.js
index f5d39a3..2571a7e 100644
--- a/webpack.config.js
+++ b/webpack.config.js
@@ -1,4 +1,4 @@
-const { resolve } = require("path");
+const { resolve, join } = require("path");
 const { CleanWebpackPlugin } = require("clean-webpack-plugin");
 const HtmlWebPackPlugin = require("html-webpack-plugin");

@@ -11,9 +11,14 @@ const config = {
   module: {
     rules: [
       {
-        test: /\.tsx?$/,
+        test: /\.(t|j)sx?$/,
         loader: ["awesome-typescript-loader?module=es6"],
-        exclude: () => false
+        include: [
+          join(__dirname, 'src'),
+          join(__dirname, "node_modules/react-intl"),
+          join(__dirname, "node_modules/intl-messageformat"),
+          join(__dirname, "node_modules/intl-messageformat-parser"),
+        ],
       },
       {
         test: /\.js$/,
```

**Comment by jpreecedev** [comment]
Thanks, your comments helped me resolve the issue in this repo.  However, our real world use is slightly different and I apologise for not providing a more accurate representation of how we're using React Intl.  We are using Webpack with TypeScript, we have Express on the back end and we server side render everything and then re-hydrate on the client.

I've created a new repo and this structure exactly matches what we use in production.  Note that I have implemented your changes in `config/webpack.config.js/loaders.js` and in `tsconfig.json`.

All works fine in Chrome.  In IE the SSR version is served up but blows up on hydration.  In the `vendor` chunk there is uncompiled ES6 code.  Note it is not possible for us to use polyfill.io in production, we must pre-compile everything and ship polyfills ahead of time.

![image](https://user-images.githubusercontent.com/6689344/65128453-6c5eab00-d9f1-11e9-88cc-32ec03347a3d.png)

Here is the repo; https://github.com/jpreecedev/react-ssr-react-intl

Please run `yarn && yarn start` and navigate to `http://localhost:8080`.  All help is very much appreciated!

**Comment by longlho** [comment]
So if I run `npm run build`, it works in IE11
![Annotation 2019-09-18 084735](https://user-images.githubusercontent.com/198255/65150578-6ae1b280-d9f2-11e9-90f3-e186aa14b132.png)

Looks like `mode: "development"` does `exclude`/`include` differently. This fixes it. I changed the `webpack` loaders.js:
```
diff --git a/config/webpack.config.js/loaders.js b/config/webpack.config.js/loaders.js
index 6d554e7..b353ba8 100644
--- a/config/webpack.config.js/loaders.js
+++ b/config/webpack.config.js/loaders.js
@@ -11,14 +11,8 @@ const cssModuleRegex = /\.module\.scss$/
  */
 const typescriptLoader = {
   test: /\.(j|t)sx?$/,
-  exclude: /node_modules/,
-  loader: require.resolve("awesome-typescript-loader"),
-  include: [
-    path.join(__dirname, "../../", "src"),
-    path.join(__dirname, "../../", "node_modules/react-intl"),
-    path.join(__dirname, "../../", "node_modules/intl-messageformat"),
-    path.join(__dirname, "../../", "node_modules/intl-messageformat-parser")
-  ]
+  exclude: /node_modules\/(?!react-intl|intl-messageformat|intl-messageformat-parser)/,
+  loader: require.resolve("awesome-typescript-loader")
 }

 const cssModuleLoaderClient = {
```

**Comment by longlho** [comment]
I think u should submit an issue upstream in webpack cause that's a little odd

**Comment by jpreecedev** [comment]
Thanks for supporting me on this, I am going to raise an upstream ticket. It's a little frustrating that I only have this issue with React Intl, all other packages working fine.

**Comment by muratkemaldar** [comment]
Hi, 
I am also having issues in IE11, there is a `Syntax Error` in the IE11 console, which points to the same part as in the screenshot @jpreecedev posted.

In my case, I don't use TypeScript, and tweaked @jpreecedev 's repo to reproduce the Error in my own setup. Can you help me out with this setup? How would the solution be different without a typescript loader?

```
// webpack.config.js
const HtmlWebPackPlugin = require("html-webpack-plugin");
module.exports = {
  devtool: "source-map",
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader"
        }
      },
    ]
  },
  plugins: [
    new HtmlWebPackPlugin({
      template: "./src/index.html",
      filename: "./index.html"
    })
  ]
};
```


```
// index.js
import React, { Component } from "react";
import ReactDOM from "react-dom";
import { IntlProvider, FormattedMessage } from "react-intl";

class App extends Component {
  
  constructor(props) {
    super(props);
    this.state = {
      name: "Muri",
      unreadCount: 5000
    }
  }

  render() {
    const { name, unreadCount } = this.state;

    return (
      <p>
        <FormattedMessage
          id="welcome"
          defaultMessage={`Hello {name}, you have {unreadCount, number} {unreadCount, plural,
                      one {message}
                      other {messages}
                    }`}
          values={{ name: <b>{name}</b>, unreadCount }}
        />
      </p>
    );
  }
}

ReactDOM.render(
  <IntlProvider locale="en">
    <App />
  </IntlProvider>,
  document.getElementById("root")
);

```

```
{
  "name": "react-intl-3-ie11",
  "version": "1.0.0",
  "description": "",
  "main": "src/index.js",
  "scripts": {
    "start": "NODE_ENV=development webpack-dev-server --hot --config webpack.config.js",
    "build": "webpack --config ./webpack.config.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-intl": "^3.2.2"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/preset-env": "^7.6.2",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.6",
    "html-webpack-plugin": "^3.2.0",
    "webpack": "^4.40.2",
    "webpack-cli": "^3.3.9",
    "webpack-dev-server": "^3.8.1"
  },
  "browserslist": [
    "last 2 version",
    "IE >= 11",
    "iOS >= 9"
  ]
}

```

**Comment by longlho** [comment]
Same solution above which is to tweak exclude in your babel-loader config

**Comment by muratkemaldar** [comment]
Yep, that worked. Thanks a lot!

**Comment by minuseight** [comment]
Just incase anyone else gets stuck on this make sure you are using bable.config.js and not .babelrc as this ignores the exclude

**Comment by Hezard** [comment]
@minuseight  
Try this one, it should work on Windows and Unix systems
 I'm using .babelrc and webpack babel loader
exclude: /node_modules(?!(\/|\\)(react-intl|intl-messageformat|intl-messageformat-parser))/,

**Comment by AndreuMad** [comment]
Just import 'react-intl' like that: import *SOMETHING* from 'react-intl/dist';

So just add '/dist'
