### ISSUE TITLE
v3.2.2 not support SSR

### ISSUE THREAD

**Issue by ycjcl868** [formatjs/react-intl#1487]
relate commit https://github.com/formatjs/react-intl/commit/ace1a9d45e499405fa08aafb9ad2e539b71ba940.  

![image](https://user-images.githubusercontent.com/13595509/65142940-5deeae80-da46-11e9-8797-a89088c0d78a.png)

In node env, there's no `Intl.RelativeTimeFormat`, so it will throw Error. 

In my opinion, it's a breaking change, it shouldn't block the main process in Server-Side render

![image](https://user-images.githubusercontent.com/13595509/65142968-71017e80-da46-11e9-89d2-fde4298fc61b.png)

**Comment by longlho** [comment]
Yes you should polyfill Intl.RelativeTimeFormat in Node

**Comment by zombieJ** [comment]
@longlho,
Do not bring breaking change in patch version. This should move to minor version or use console warning in patch version instead.

**Comment by longlho** [comment]
Actually that was a mistake on our part. It has always required `Intl.RelativeTimeFormat`, just lazily.

**Comment by longlho** [comment]
fixed in 3.2.3. Thanks for reporting!
