### ISSUE TITLE
v3.2.3 is 20kb heavier than v3.2.2

### ISSUE THREAD

**Issue by cloud-walker** [formatjs/react-intl#1488]
As you can see from bundlephobia: https://bundlephobia.com/result?p=react-intl@3.2.3

Maybe its ok like that (due to tree-shaking), but maybe something lurked over?

Thanks in advance!

**Comment by longlho** [comment]
It’s not even treeshaking. We just import the types in and not actual code.

**Comment by JustFly1984** [comment]
I see the difference in dependencies:

in 3.2.3 there is new dependencies: @formatjs/intl-relativetimeformat and @formatjs/intl-utils

**Comment by longlho** [comment]
Oh actually there was a copy-paste issue, I'm releasing a new version.
Thanks for reporting!
