### ISSUE TITLE
Optimizations: Decrease npm dependency size

### ISSUE THREAD

**Issue by raDiesle** [formatjs/react-intl#1489]
react-intl: v3.2.3

Out of all npm dependencies used in my app, next to react-scripts, react-intl requires biggest size of peer modules to download.

It might be cause of huge size of language definitions.

Anyway, maybe it can be optimized.

┌─────────────────────────────────────┬───────────────┬─────────┐
│ name                                │ children      │ size    │
├─────────────────────────────────────┼───────────────┼─────────┤
│ react-scripts                       │ 5102          │ 559.97M │
├─────────────────────────────────────┼───────────────┼─────────┤
│ react-intl                          │ 16            │ 35.09M  │

**Comment by longlho** [comment]
Our dependencies include CLDR data which is sizable. `npm` dependency size is also not really something we put too much efforts in to optimize.
