### ISSUE TITLE
Rich text formatting with SSR

### ISSUE THREAD

**Issue by jancama2** [formatjs/react-intl#1497]
### Expected behavior

React-intl 3 FormattedMessage rich text formatting works correctly on the server side.

### Current behavior

FormattedMessage doesn't replace values with components on the server side, the text is left with tags in it.

### Step to reproduce for BUG REPORT
```
<FormattedMessage
   id="articles.saved.empty.text"
   values={{
       appLink: msg => (
           <Linkto={config.routes.appLink}>
               {msg}
           </Link>
       ),
   }}
/>

```
The code above works correctly on the client side (with `ReactDOM.render`) but doesn't replace `<appLink>text</appLink>` on the server side (with `ReactDOM.renderToString`).
### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.1.11 |
|      `npm ls react` | 16.9.0 |
|      `npm ls react-dom` | 16.9.0 |

**Comment by longlho** [comment]
https://github.com/formatjs/react-intl/blob/master/docs/Getting-Started.md#domparser should have more details
