### ISSUE TITLE
Disabling interpolation on formatMessage

### ISSUE THREAD

**Issue by arvinsim** [formatjs/react-intl#1498]
I am using [Uppy.io](http://uppy.io) to upload my files. 
I am passing strings to the `locale` prop for the `Dashboard` component.

```
const messages = defineMessage({
closeModal: {
 id: 'uppy.dashboard.locale-strings.import-from',
    defaultMessage: 'Import from %{name}'
  },
})

 <Dashboard
              uppy={uppy}
              id="dashboard"
              closeAfterFinish={false}
              height={250}
              locale={{
                strings: {
                  closeModal: intl.formatMessage(messages.importFrom)
 ...
```

The problem with using `react-intl`'s `formatMessage` is that it interpolates `{name}` in the original string. This causes problems with `Uppy` since it needs the raw `{name}` string.

Is there a way to disable interpolation on a `formatMessage` string?

**Comment by longlho** [comment]
Yes you can escape it with apostrophe like '{name}'
