### ISSUE TITLE
ES Module isn't transpiled except for import/export

### ISSUE THREAD

**Issue by AndyOGo** [formatjs/react-intl#1499]
### Expected behavior

I expect to import an **ES Module** and bundle it with Webpack/Rollup/Parcel without the need to transpile `react-intl` itself by Babel.

I'm talking about the provided `module` field as definied by the spec below:
https://github.com/formatjs/react-intl/blob/c736c2e6c6096b1d5ad1fb6be85fa374891d0a6c/package.json#L34

> `pkg.module` will point to a module that has ES2015 module syntax but **otherwise only syntax features that the target environments support**.
https://github.com/rollup/rollup/wiki/pkg.module

> Wait, it just means import and export – not other future JavaScript features?
> **Yes. ...**
https://github.com/rollup/rollup/wiki/pkg.module#wait-it-just-means-import-and-export--not-other-future-javascript-features

Babel allows you to disable just module syntax transpilation:
https://babeljs.io/docs/en/babel-preset-env#modules

And Rollup, Webpack etc can be configured to target a specific module syntax.

- [Rollup `output.format`](http://rollupjs.org/guide/en/#outputformat)
- [Webpack `output.libraryTarget`](https://webpack.js.org/configuration/output/#outputlibrarytarget)

**Todo:**

- [ ] fix build for `pkg.module` to support ES features of target environment (including IE11)

### Current behavior

If I `import` **ES Module** of `react-intl` v3 I have to whitelist it to be transpiled by Babel for any bundler/loader.

The docs state that custom transpilation is needed:
> This means you should configure your build toolchain to transpile those libraries.
https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#esm-build

### Step to reproduce for BUG REPORT

Install webpack v4, install `react-intl` v3 open it in a browser which can't parse ESnext.

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | V3 latest |
|      `npm ls react` | 16.9 |
|     `npm --version` | VERSION  |
|    `node --version` | 10 |

| OS   | Version |
| ---- | ------- |
| Windows 10 | VERSION |

| Browser | Version |
| ------- | ------- |
| IE    | 11 |

**Comment by glensomerville** [comment]
I'm having the same issue. It seems that the dependency of the `ansi-styles` module is the culprit at least in my case. Not sure why that ends up in the compiled frontend code though.

**Comment by mareklaco** [comment]
It seems that the documentation is also wrong:
https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#esm-build

The ESM builds of react-intl (and its underlying librarie) should be transpiled instead of having to transpile them on my own.
(If I understand correctly...)

**Comment by AndyOGo** [comment]
@mareklaco Thank you very much. Indeed the docs state that custom transpilation is necessary, though there is almost no library which provides ESM build like this - I will add it to my issue description.

**Comment by arthurgeron** [comment]
If we have to do custom transpilations then it doesn't really support IE11 like it says in the docs.

**Comment by longlho** [comment]
There's es5 version under dist if you don't wanna transpile. It is a little
bigger in size.

**Comment by AndyOGo** [comment]
Well webpack, rollup etc automatically pick the `module` field in favour of the `main` field. And tree shaking can be done much better based upon ES module syntax than commonjs

**Comment by longlho** [comment]
There's no es5 import/export. We don't dist half ES6 and half ES5. If you
expect ES6 import but es5 code it doesn't work that way. The ES6 dist is
intentional so you can close this issue.

**Comment by AndyOGo** [comment]
Please double check this. It is not common practices to provide ESM code with more esnext syntax than import export

**Comment by arthurgeron** [comment]
If ES6 is intentional do not say you support ie11 in the docs.

**Comment by longlho** [comment]
Again there's es5 under dist

**Comment by AndyOGo** [comment]
@longlho Thanks for your answer.

Please double check the purpuse and definition of `pkg.module`, as described here:
> `pkg.module` will point to a module that has ES2015 module syntax but **otherwise only syntax features that the target environments support**.
https://github.com/rollup/rollup/wiki/pkg.module

**Comment by MarekLacoAXA** [comment]
Maybe related:
According to recent NODE documentation (v12) it IS NOT recommended to use both `"main"` and `"module"` keys in `package.json`, see:
https://nodejs.org/api/esm.html#esm_compatibility_with_commonjs_only_versions_of_node_js

So, instead, react-intl could provide the ESM in es5 in a separate folder like `import { IntlProvider } from 'react-intl/esm/es5';`

What do you think?

**Comment by AndyOGo** [comment]
Well, that's okay for node packages.
Though `pkg.module` was invented for bundlers and loaders mainly for targeting browser environments, enable better tree-shaking, and such stuff.
https://github.com/rollup/rollup/wiki/pkg.module

**Comment by Zhouzi** [comment]
Also, changing the build tool's configuration might not be that easy (e.g when using create-react-app).

The simple fact that using react-intl requires a specific configuration seems to be a pretty good indicator that it's not working as most people expect it to. I can't imagine a world where I would need to change my configuration for each library.

**Comment by arthurgeron** [comment]
To complement @Zhouzi 's comment, you read in the docs that it supports IE 11, there's no visible mention that some custom transpiling is needed on the `docs/Runtime Requirements`, someone has to have their build broken, find out react-intl caused the bug, get confused because docs said it supports ie 11  then eventually land here just to find out custom tranpiling is needed.

Again, doesn`t matter what you call it, if you are exporting ES6 and it needs custom transpiling on the project's config it does NOT support IE 11.

**Comment by Zhouzi** [comment]
I'd love to move on from this issue and consider it solved. I can think of two ways it can go down:

1. The react-apollo team acknowledges that the library requires a specific build configuration to work in IE11.
2. The react-apollo team agrees to ship code that works in IE11 out of the box.

Obviously, we all hope for solution 2 but I think solution 1 is perfectly fine as long as it's documented and acknowledged. I'd be happy to submit a PR either way.

**Comment by longlho** [comment]
We ship 2 copies of artifacts, `dist` that uses CommonJS + ES5 & `lib` which is ES6. It is documented here: https://github.com/formatjs/react-intl/blob/master/docs/Getting-Started.md#esm-build

Unfortunately by default bundlers pick up `lib`, which is why extra transpilation is required.  The ES6 version is specifically for environments like Electron, Node and such.

**Comment by AndyOGo** [comment]
@longlho 
Thanks for your answer.
I have read your referenced documentation already.

> Unfortunately by default bundlers pick up `lib`

This is incorrect, bundlers pick up what ever you state in your `package.json` `module` field!
https://github.com/formatjs/react-intl/blob/6052c96b84fd573235983171b145ba1ef160e2ae/package.json#L129

This is the bug I'm talking about.
Please carefully study the official spec of the `module` field:
https://github.com/rollup/rollup/wiki/pkg.module

**Comment by longlho** [comment]
A bundler’s doc is not official spec. There is no spec for package.json.
Their default resolution hierarchy is module -> dist or whatever you config
it to be.

**Comment by AndyOGo** [comment]
@longlho Thanks for your answer.
Indeed spec is not the same as docs - I corrected my statement above.

Anyway, NPM's `package.json` file comes with 3 fields for distribution [`main`](https://docs.npmjs.com/files/package.json#main) (server side), [`browser`](https://docs.npmjs.com/files/package.json#browser) (client side) and [`bin`](https://docs.npmjs.com/files/package.json#bin) (for executable files).

The sole purpose of the [`module`](https://github.com/rollup/rollup/wiki/pkg.module) field is clearly documented at above link, it's meant for bundlers, thats all about it.

**Comment by longlho** [comment]
The problem here is bundlers’ behaviors are inconsistent. E.g parcel works
just fine out of the box, webpack/rollup needs extra config

**Comment by AndyOGo** [comment]
Well alright, that might be.

Anyway the [`module` proposal](https://github.com/dherman/defense-of-dot-js/blob/master/proposal.md) and the [ES6 Modules Draft for interoperability in Node](https://github.com/nodejs/node-eps/blob/4217dca299d89c8c18ac44c878b5fe9581974ef3/002-es6-modules.md#51-determining-if-source-is-an-es-module) give a clear reference.

Webpack has documented it's steps here:
https://webpack.js.org/guides/author-libraries/#final-steps

Rollup docs are here:
https://rollupjs.org/guide/en/#compatibility

Parcel modifies node's resolve algorithm:

> The Parcel resolver implements a modified version of the [node_modules resolution algorithm](https://nodejs.org/api/modules.html#modules_all_together).
https://parceljs.org/module_resolution.html

**Comment by longlho** [comment]
As you already saw, those are also all inconsistent. Node's ESM spec (https://nodejs.org/api/esm.html) requires `type: module` & does not have restrictions on ES version. `webpack` & `rollup`'s hierarchy was from the `jsnext:main` days and do not operate based on any spec & rather cargo-cult from one another. If they were following Node's ESM they would have used `main` as the entry point all along.

Again as I've mentioned, if there's a solution that works across ALL bundlers, Node & Electron-based ecosystem, which are our consumers, PR's always welcome.

**Comment by sombreroEnPuntas** [comment]
When using the latest yarn (1.19.2) and node (13.2.0) and webpack/babel.
Trying to build a project with `react-intl` and associated libs will yield:

```
(node:25216) Warning: require() of ES modules is not supported.
require() of /node_modules/intl-locales-supported/dist/index.js from node_modules/react-intl/dist/components/provider.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from node_modules/intl-locales-supported/package.json.
> Build error occurred
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /node_modules/intl-locales-supported/dist/index.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:13)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (/node_modules/react-intl/dist/components/provider.js:36:32)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by simon04** [comment]
I agree with @AndyOGo that the use of `module` by `react-intl` is not following the convention. In a project, from 33 front-end dependencies, `react-intl` is the only dependency that uses ES6+ features in its file specified by `module`. Very easy to overlook!

Here's a fix/workaround for webpack using [resolve.alias](https://webpack.js.org/configuration/resolve/#resolvealias):
```js
// webpack.config.js
const { resolve } = require("path");
module.exports = {
  resolve: {
    alias: {
      "react-intl": resolve(
        __dirname,
        "node_modules/react-intl/dist/react-intl.js"
      )
    }
  }
};
```

Alternatively, one could follow the `create-react-app` approach and run all `node_modules` dependencies through babel: https://github.com/facebook/create-react-app/pull/3776

**Comment by joshuar500** [comment]
I was trying to import like this:

`import { IntlProvider } from 'react-intl'`

But I'm using a static site generator (react-static), and was getting `TypeError: Cannot read property 'parse' of undefined` until I saw the resolution by @simon04 .

For me, it started working when i did `import { IntlProvider } from 'react-intl/dist/react-intl'`

I don't think the docs clearly explain the setup you have to get through, but like @arthurgeron said, I stumbled unto this thread to find out some hints to solving my problem.

**Comment by JustFly1984** [comment]
@joshuar500 I would advise to use gatsby.js instead of react-static. I've used react-static and had a lot of issues, cos react-static has very small community, and it is hard to get bugs fixed. Since I've switched to Gatsby, have much less issues and community support is amazing.
