### ISSUE TITLE
IntlProvider formats & defaultFormats seem broken in latest release (3.3.2).

### ISSUE THREAD

**Issue by zjr** [formatjs/react-intl#1500]
### Expected behavior

Using `formats` & `defaultFormats` should allow printing formatted messages with custom formats.

```jsx
<IntlProvider . . . defaultFormats={{ date: { 'short-weekday': { weekday: 'short' } } }} . . ./>
```

Should allow message with `"The day is {monday, date, short-weekday}."` to render as `"The day is Mon."`

### Current behavior

Instead `formats` and `defaultFormats` do nothing and date is rendered with default format (e.g. `"The day is 10/14/2019."`

I have verified that **this all works if I downgrade version to 3.0.0**, have not yet tested other versions.

### Step to reproduce for BUG REPORT

Use `IntlProvider` wherever, define a `defaultFormats`, try to use that in a `FormattedMessage` within/using the provider. Doesn't matter if injected or through hook or just nested.

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.3.2 |
|      `npm ls react` | 16.9.0 |
|     `npm --version` | yarn 1.19.1 |
|    `node --version` | 12.11.1 |

| OS   | Version |
| ---- | ------- |
| macOS Catalina | 10.15 |

| Browser | Version |
| ------- | ------- |
| Chrome    | 77.0.3865.90 |

**Comment by zjr** [comment]
After further testing it seems this issue was in fact introduced in the 3.3.2 release, 3.3.1 works as expected.

**Comment by longlho** [comment]
Do you have a codesandbox?

**Comment by zjr** [comment]
No and I'm not generally aware of a handy way to sandbox `react-intl`. I can tell you that after installing every version of the package since 3.0.0, 3.3.1 is the only version with an issue. If I have some more time later I will try to figure out how to get this package into a sandbox.

**Comment by longlho** [comment]
I mean codesandbox.io link to repro this

**Comment by zjr** [comment]
Here you go…

this is with v3.3.2, broken: https://codesandbox.io/s/focused-leakey-46yr4
here is with v3.3.1, works: https://codesandbox.io/s/blissful-zhukovsky-9oq4w

**Comment by longlho** [comment]
Thanks I'll take a look next week when I'm back from vacation
