### ISSUE TITLE
Support for Intl.NumberFormat notation option  

### ISSUE THREAD

**Issue by handsfelloff** [formatjs/react-intl#1501]
Currently `Intl.NumberFormat` option `notation` is not supported.

i.e.
```
<FormattedNumber value={1234} style='decimal' notation="compact"/>
```
`outputs: 1,234`

rather than the desired notation form:
```
Intl.NumberFormat("en",{notation: "compact"}).format(1234)
```
`outputs: 1.2k`

The property **notation** above is being stripped since it is not included in `number.ts` NUMBER_FORMAT_OPTIONS

**Comment by longlho** [comment]
Unified NumberFormat is stage 3 and we haven't polyfilled notation yet
which is probably why. I'll take a look next week. Pr's always welcome
