### ISSUE TITLE
When using the functional approach rich text formatting results in a truncated message. T

### ISSUE THREAD

**Issue by hanvyj** [formatjs/react-intl#1503]
### Expected behavior
The following two snippets
```
<FormattedMessage
        id="id"
        description="Test"
        defaultMessage="A {value} value"
        values={{
          value: <b>big</b>
        }}
      />
```
And
```
<FormattedMessage
        id="id"
        description="Test"
        defaultMessage="A {value} value"
        values={{
          value: <b>big</b>
        }}
      >
       {(message: string) => <span>{message}</span>}
</FormattedMessage>
```
Should produce identical output

### Current behavior

However, the functional message is cut off when using a value with rich-text. I'd expect `<span>A <b>big</b> value</span>` but get: `<span>A </span>`

### Your Environment

Only tested in Windows Chrome v77.0.3865.90.

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 2.8.0|
|      `npm ls react` | 16.9.0|
|     `npm --version` | 6.10.2|
|    `node --version` | v10.14.1 |

| OS   | Version |
| ---- | ------- |
| Windows 7 |  Enterprise SP1 |

| Browser | Version |
| ------- | ------- |
| Chrome | 77.0.3865.90|

**Comment by longlho** [comment]
The function receives a spread of chunks so your render fn should be `(...chunks) => <span>{chunks}</span>` instead
