### ISSUE TITLE
FormattedNumber and intl.formatNumber with notation prop not working 

### ISSUE THREAD

**Issue by MustaMohamed** [formatjs/react-intl#1504]
I'm using `react-native` with `react-intl`, and I'm working with many numbers, so I'm using `FormattedNumber` component and `intl.formatNumber` function, when I'm using prop `notation='compact'` it's not working.

### Expected behavior
 ` <FormattedNumber value={20000} notation={'compact'}/>`
`output: 20K`

### Current behavior
Current output like this
 ` <FormattedNumber value={20000} notation={'compact'}/>`
`output: 20,000`

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.4.0|
|      `npm ls react` | 16.8.6|
|     `npm --version` | 6.10.3|
|    `node --version` | 12.10.0|

| OS   | Version |
| ---- | ------- |
| Windows| 1903|

Any help?

**Comment by longlho** [comment]
notation is stage-3 so it’s only in latest chrome. Idk what JSC has.
formatjs has a polyfill but doesn’t cover notation yet
