### ISSUE TITLE
Random space in FormattedNumber appears when using Node 12

### ISSUE THREAD

**Issue by cnolimit** [formatjs/react-intl#1505]
I'm currently upgrading my project from Node 8 to Node 12 and I'm having issue with the Format of the currency.
In our setup we use snapshot testing and when we upgrade our node version we start seeing random spaces just after the currency and can't seem to determine why this is happening.

I've looked into the issue #1165 although it seems to be a different issue, related to locales.

### Expected behavior

I expect that the currency would be consistent between the two versions.
Node 8 Output: `NOK1,000.00`

### Current behavior

When upgrading to Node 12, a space is introduced to the format
Node 12 Output: `NOK 1,000.00`

### Step to reproduce for BUG REPORT

I have setup a minimum project on codesandbox to download and test locally as you won't be able ot update the node version on the browser.
https://codesandbox.io/s/musing-keldysh-t54tm

Created a screen recording of the issue: [Video](https://streamable.com/13tp2)

<img width="580" alt="Screenshot 2019-11-01 at 11 59 05" src="https://user-images.githubusercontent.com/6928300/68023484-142cf100-fc9f-11e9-8a2e-7e714a4cb2ce.png">

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.4.0 |
|      `npm ls react` | 16.11.0 |
|     `npm --version` | 6.4.1 / 6.10.3 |
|    `node --version` | 8.16.2 / 12.10.0 |

| OS   | Version |
| ---- | ------- |
| macOS Catalina | 10.15.1 |

| Browser | Version |
| ------- | ------- |
| n/a    | n/a |

**Comment by longlho** [comment]
This is expected since underlying CLDR data versions are different between Node 8 & Node 12 natively. Things like this happen all the time since CLDR releases roughly twice a year.

**Comment by cnolimit** [comment]
Thanks 👍
