### ISSUE TITLE
Build brakes after upgrade, missing type InjectedIntl

### ISSUE THREAD

**Issue by TheKnarf** [formatjs/react-intl#1506]
### Expected behavior

Expect build not to break.

### Current behavior

Build brakes after upgrade.

```
 yarn build
yarn run v1.19.1
$ cross-env REACT_APP_ALP_ENV=production react-scripts build
Creating an optimized production build...
Failed to compile.

/Users/knarf/projects/alp/packages/frontend/src/components/autocomplete.tsx
TypeScript error in /Users/knarf/projects/alp/packages/frontend/src/components/autocomplete.tsx(15,22):
Module '"../../../../../../../../Users/knarf/projects/alp/node_modules/react-intl/dist"' has no exported member 'InjectedIntl'. Did you mean 'injectIntl'?  TS2724

    13 | import FormControl from '@material-ui/core/FormControl';
    14 | import InputLabel from '@material-ui/core/InputLabel';
  > 15 | import { injectIntl, InjectedIntl } from 'react-intl';
       |                      ^
    16 | import './autocomplete.css';
    17 |
    18 | const AutocompleteInput = withStyles((theme: Theme) =>


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Code usage:

```
interface Props {
 intl: InjectedIntl
};

class MyClass extends React.Component<Props> { ... }

export default injectIntl(MyClass);
```

### Step to reproduce for BUG REPORT

Upgraded react-intl

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` |`react-intl@^3.4.0` |
|      `npm ls react` | `react@^16.8.6` |
|     `yarn --version` | `1.19.1` |
|    `node --version` | `v12.12.0` |

| OS   | Version |
| ---- | ------- |
| macOs Mojave | `10.14.6` |

**Comment by longlho** [comment]
`react-intl@3` is not backwards compatible with `react-intl@2`. There was no official support for types in `react-intl@2` so I don't know where `InjectedIntl` comes from. You can follow our https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md in order to upgrade.
