### ISSUE TITLE
Pluralization doesn't work on web browsers on iPad

### ISSUE THREAD

**Issue by tomaass** [formatjs/react-intl#1507]
It works well on all browsers and all other platforms. But pluralization doesn't work on iOS12

Version of react-intl:  3.3.2

Tested via Browser Stack on iPad Pro 12.9.2010 iOS 12 in Chrome Browser

![Screenshot 2019-11-05 at 09 52 15](https://user-images.githubusercontent.com/2611275/68193580-9117dd80-ffb3-11e9-8496-0570cf62c67c.png)

It works well on Android devices or desktop browsers.

![Screenshot 2019-11-05 at 10 18 38](https://user-images.githubusercontent.com/2611275/68194729-d3421e80-ffb5-11e9-84eb-4710150e5b98.png)

**Comment by longlho** [comment]
Do you have any stack trace?
Safari/WebKit does not have support for `Intl.PluralRules` so you'd have to polyfill it with https://www.npmjs.com/package/@formatjs/intl-pluralrules

**Comment by woohling** [comment]
one kind reminder, pls keep them in order, in case u use prettier or other lint that requires alphabetized ordered-import and u accidently fixed it and it will no longer work. (Cause me two hours until realizing it.   
```
import '@formatjs/intl-pluralrules/polyfill';
import '@formatjs/intl-pluralrules/dist/locale-data/en'; 
```

**Comment by tomaass** [comment]
@woohling thank you for a solution
