### ISSUE TITLE
 addLocaleData is not exported

### ISSUE THREAD

**Issue by DWNEWS-jixiaohong** [formatjs/react-intl#1508]
`
import { addLocaleData } from "react-intl";
addLocaleData([
      ...en,
      ...zh,
]);
`
when i use this function , there throw an error
`
Attempted import error: 'addLocaleData' is not exported from 'react-intl'.
`
so how can i resolve this error ? my version is 3.4.0

**Comment by longlho** [comment]
We no longer export that in react-intl@3. You can take a look at our https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md for more details on how to upgrade.

**Comment by redonkulus** [comment]
FYI the docs are located here now: https://formatjs.io/docs/react-intl/upgrade-guide-3x
