### ISSUE TITLE
v3.5.0's replacement of `defineMessage` leads to error "must be wrapped in "createMacro""

### ISSUE THREAD

**Issue by tdeekens** [formatjs/react-intl#1511]
### Expected behavior

The replacement of `defineMessages` in `react-intl` to forward to `formatjs/macro` to not need any action no a consumers side as it's a feature release.

### Current behavior

Updating to v3.5 we receive this error

```
The macro imported from "@formatjs/macro" must be wrapped in "createMacro" which you can get from "babel-plugin-macros". Please refer to the documentation to see how to do this properly: https://github.com/kentcdodds/babel-plugin-macros/blob/master/other/docs/author.md#writing-a-macro
```

### Step to reproduce for BUG REPORT

1. Given both `react-intl` and `babel-plugin-react-intl` are updated
2. And our application is rebuilt
3. Then our tests fail with the error message above

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.5.0   |
|      `npm ls react` | 16.11.0 |
|     `npm --version` | VERSION |
|    `node --version` | 12.13   |

| OS   | Version |
| ---- | ------- |
| macOs Catalina | 10.15.1 |

**Comment by longlho** [comment]
I'm not sure how to replicate this. Do you have a sample codesandbox or something?

**Comment by longlho** [comment]
tracking the issue over at `babel-plugin-macros` because there's nothing we can do here: https://github.com/kentcdodds/babel-plugin-macros/issues/131

**Comment by tdeekens** [comment]
Thanks and sorry for not being able to provide a repro case. Been a too busy week.

**Comment by AndyOGo** [comment]
Unfortunately we still face this error.

Here is the reuslt of `npm ls`:

```sh
@axa-ch/aletheia@1.21.9 git-repos\aletheia
+-- babel-plugin-macros@2.8.0
+-- babel-plugin-react-intl@5.1.11
+-- import-all.macro@2.0.3
| `-- babel-plugin-macros@2.8.0  deduped
`-- react-intl@3.9.1
```

**Comment by tdeekens** [comment]
We also face the same error. We tried to update end of last week.

**Comment by AndyOGo** [comment]
Alright, to whom it may concerns.

We had to extend our Babel config to supply a custom `isMacrosName()` function.
https://github.com/kentcdodds/babel-plugin-macros/blob/2cac571a5809c42671c2bcbd74921df65036369e/src/index.js#L5-L6

**babel.config.js:**

```js
// Fixes https://github.com/formatjs/react-intl/issues/1511
//       https://github.com/kentcdodds/babel-plugin-macros/issues/131
const macrosRegex = /[./]macro(\.js)?$/;
const testMacrosRegex = v =>
  macrosRegex.test(v) && v.indexOf('@formatjs/macro') === -1;
module.exports = {
  plugins: [
    [
      'macros',
      {
        isMacrosName: testMacrosRegex,
      },
    ],
  ],
};
```

**Comment by thadk** [comment]
What is the resolution to this issue within create-react-app when it is preferred to not modify babel? I just tested and it is still broken for `react-scripts: 3.3.0-next.80`.

**Comment by tdeekens** [comment]
Also, should the fix above if deemed appropriate be exported fro, the lib? Feels like unexpected breaking changes can occur and some implementation details are leaking somewhat.

**Comment by longlho** [comment]
Unfortunately this is not something we can fix because `babel-plugin-macro` seems to have a default monopoly on any package w/ the word `macro`.

**Comment by thadk** [comment]
It seems like he is suggesting the internal package be renamed?
