### ISSUE TITLE
Upgrade guide fails to mention InjectedIntlProps is no longer available in v3

### ISSUE THREAD

**Issue by stevenroussey-privicy** [formatjs/react-intl#1515]
### Expected behavior

Expected `InjectedIntlProps` to remain.

### Current behavior

Errors everywhere. If I just remove that from the Props definition to get rid of that error, I get another:

![image](https://user-images.githubusercontent.com/42726156/68807352-877a1f80-061c-11ea-954e-d86179e53f67.png)

### Step to reproduce for BUG REPORT

Upgrade to version 3.x

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | react-intl@3.6.0 |
|      `npm ls react` | react@16.11.0 |
|     `npm --version` | 6.13.0 |
|    `node --version` | v12.8.0 |

| OS   | Version |
| ---- | ------- |
| MacOS | 10.15.1 |

Other than saying that react-intl is now written in typescript, there are zero instructions on how to use it with typescript.

**Comment by stevenroussey-privicy** [comment]
I guess that was coming from @types 

Solution: s/InjectedIntlProps/WrappedComponentProps/g

**Comment by longlho** [comment]
Yeah we don’t own/maintain that typings

**Comment by Zhouzi** [comment]
Thanks @stevenroussey-privicy, I hadn't noticed that `InjectedIntlProps` was renamed to `WrappedComponentProps` and ended up adding `{ intl: IntlShape }` everywhere.

@longlho the types are packed in with react-intl so I'm unsure to understand what you meant by "we don't own/maintan that typings". Do you mean that it's considered "private" and thus likely to break?

**Comment by longlho** [comment]
React-intl@3 has official TS support so we do own that but react-intl@2
typings comes from @types/react-intl package which we don’t own/maintain.

**Comment by Zhouzi** [comment]
Thanks @longlho that makes perfect sense! I opened a PR to add a mention about the new types in case you'd think that it's ok. Otherwise, feel free to close it.
