### ISSUE TITLE
intlProvider.getChildContext removal isn't mentioned in upgrade guide

### ISSUE THREAD

**Issue by callumlocke** [formatjs/react-intl#1519]
As far as I can tell, `intlProvider.getChildContext()` stopped working after I upgraded from v2 to v3. But there's no mention of it in the [upgrade guide](https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#typescript-support), or anywhere in the codebase now.

Our code used `intlProvider.getChildContext()` in a custom test helper:

```ts
import { mount } from 'enzyme';
import * as React from 'react';
import { IntlProvider, intlShape } from 'react-intl';

const mountWithIntl = (component: JSX.Element, locale: string) => {
  const intlProvider = new IntlProvider({ locale }, {});
  const { intl } = intlProvider.getChildContext();
  return mount(React.cloneElement(component, { intl }), {
    context: { intl },
    childContextTypes: { intl: intlShape },
  });
};

export default mountWithIntl;
```

I believe this was a fairly common pattern? It would be good to update the upgrade guide with some pointers on what to do now.

**Comment by longlho** [comment]
I think I’ve updated the testing guide in our docs folder but will add the
link to the Upgrade Guide as well. PR is also always welcome!

**Comment by leileili** [comment]
> As far as I can tell, `intlProvider.getChildContext()` stopped working after I upgraded from v2 to v3. But there's no mention of it in the [upgrade guide](https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#typescript-support), or anywhere in the codebase now.
> 
> Our code used `intlProvider.getChildContext()` in a custom test helper:
> 
> ```ts
> import { mount } from 'enzyme';
> import * as React from 'react';
> import { IntlProvider, intlShape } from 'react-intl';
> 
> const mountWithIntl = (component: JSX.Element, locale: string) => {
>   const intlProvider = new IntlProvider({ locale }, {});
>   const { intl } = intlProvider.getChildContext();
>   return mount(React.cloneElement(component, { intl }), {
>     context: { intl },
>     childContextTypes: { intl: intlShape },
>   });
> };
> 
> export default mountWithIntl;
> ```
> 
> I believe this was a fairly common pattern? It would be good to update the upgrade guide with some pointers on what to do now.

Hello , can you please share how to fix the "intlProvider.getChildContext() not found issue comes out of this? Thank you. I have a stackoverflow question asking for suggestion for this too. detail in https://stackoverflow.com/questions/59671390/typeerror-intlprovider-getchildcontext-is-not-a-function.

**Comment by longlho** [comment]
I’ve updated our testing guide and you can you createIntl instead

**Comment by leileili** [comment]
Thank you, in the upgrade docs (https://github.com/formatjs/react-intl/blob/master/docs/Testing-with-React-Intl.md#testing-with-react-intl) . the sample code is using createRenderer which seems the package "react-addons-test-utils" is already depreciated.  
import {createRenderer} from 'react-addons-test-utils';
so where is this "createRenderer" ?

**Comment by longlho** [comment]
If you're using enzyme this should be relevant: https://github.com/formatjs/react-intl/blob/master/docs/Testing-with-React-Intl.md#enzyme

Can you post a sample code that demo your usage?

**Comment by leileili** [comment]
my detail sample code is in : 
https://stackoverflow.com/questions/59671390/typeerror-intlprovider-getchildcontext-is-not-a-function.
Thank you,

**Comment by longlho** [comment]
OK so replace
```
const intlProvider = new IntlProvider({ messages, locale }, {});
const { intl } = intlProvider.getChildContext();
```
with
```
const intl = createIntl({ locale, messages })
```
and that should work

**Comment by leileili** [comment]
Thank you. I updated my test helper file and it works now.

**Comment by mmcknett** [comment]
The link to testing with enzyme above can now be found at: https://formatjs.io/docs/react-intl/testing#enzyme

(And the markdown is at: https://github.com/formatjs/formatjs/blob/main/website/docs/guides/testing-with-react-intl.md#enzyme)
