### ISSUE TITLE
Rich text html not rendering

### ISSUE THREAD

**Issue by sccdGyan** [formatjs/react-intl#1521]
### Expected behavior

Render rich text using FormattedMessage component

### Current behavior

Nothing rendered

### Step to reproduce for BUG REPORT

place a tag in the message as documentation described 

For example:
```
message: "<bold>{text}</bold>"
values: {{bold: text => <b>{text}</b> }}
```
### Your Environment
|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.6.1 |
|      `npm ls react` | 16.9.0 |
|     `npm --version` | 6.12.0 |
|    `node --version` | 12.13.0 |

| OS   | Version |
| ---- | ------- |
| macOS Catalina | 10.15.1 |

| Browser | Version |
| ------- | ------- |
| Chrome    | Latest |

I copy & pasted the same code from https://github.com/formatjs/react-intl/blob/master/examples/Advanced.tsx for rich text, it still won't render.

**Comment by longlho** [comment]
do you have a codesandbox.io?

**Comment by sccdGyan** [comment]
> do you have a codesandbox.io?

Hi I made a quick one....https://codesandbox.io/s/react-intl-formattedmessage-using-plural-g14st

it renders the text without replacing the tag, I'm not sure if I did something wrong..? thanks!

**Comment by longlho** [comment]
oh rich text formatting is only available in `react-intl@3`. If you're using v2, we have an https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md here

**Comment by sccdGyan** [comment]
Ah nice catch, thank you.

**Comment by sccdGyan** [comment]
So I noticed something, I was doing 

boldText = "this is my <bold>bold</bold> message"
```
                    <FormattedMessage
                        values={{
                            msg: "my message",
                            bold: msg => <b>{msg}</b>
                        }}
                        id="boldText"
                   >
                    {text=> <div>{text}</div>}
                     </FormattedMessage>
```

this didn't work. it only rendered until `this is my`

but if i changed to
```
                    <FormattedMessage
                        values={{
                            msg: "my message",
                            bold: msg => <b>{msg}</b>
                        }}
                        id="boldText"
                   />
```
it works

**Comment by longlho** [comment]
https://github.com/formatjs/react-intl/blob/master/docs/Components.md#rich-text-formatting render-as-a-function takes in `(...chunks)` as its params
