### ISSUE TITLE
support render from enzyme for testing

### ISSUE THREAD

**Issue by sccdGyan** [formatjs/react-intl#1522]
in the v3 docs, shallow and mount from enzyme are working fine https://github.com/formatjs/react-intl/blob/master/docs/Testing-with-React-Intl.md#enzyme.

Would there be same thing supported for render too?
I tried to use render but it would output errors with intl not found in context.

**Describe the solution you'd like**
something like this for intl-enzyme-test-helper file
```
export function renderWithIntl(node: React.ReactElement) {
    return render(node, {
        wrappingComponent: IntlProvider,
        wrappingComponentProps: {
            locale,
            defaultLocale,
            messages
        }
    })
}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by longlho** [comment]
do you have a codesandbox.io to demo the issue? I personally have not used `render`

**Comment by sccdGyan** [comment]
> do you have a codesandbox.io to demo the issue? I personally have not used `render`

Hi, thank you for the reply. I created a sample one here: https://codesandbox.io/s/react-react-intlv3-f1gc9

**Comment by longlho** [comment]
I don't think `render` actually uses those options the same way as `mount`/`shallow`. This seems to be an `enzyme` issue IMO so can you create an issue there? Their React 16 context support isn't completed yet AFAIK
