### ISSUE TITLE
Missing locale data for: "ka". Using default locale: "en" as fallback

### ISSUE THREAD

**Issue by Zurab1996** [formatjs/react-intl#1526]
I used to v2 version and had no problem but I updated it to v3 version and start throwing this error in console. in the application, it not cause any problem yet.

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.7.0 |
|      `npm ls react` | 16.8 |
|     `npm --version` | 6.9.0 |
|    `node --version` | 12.0 |

| OS   | Version |
| ---- | ------- |
| NAME | VERSION |

| Browser | Version |
| ------- | ------- |
| NAME    | VERSION |

**Comment by balazsnemeth** [comment]
Same for me too

**Comment by longlho** [comment]
did u follow our https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md ? Do u have a codesandbox.io repro?

**Comment by Zurab1996** [comment]
@longlho I followed the guide but on "ka"-Georgian language throwing an error on console. For example, on 'de', 'fr' or 'ru' it is not throwing an error

**Comment by ac1dr3d** [comment]
Hello.
Same here...
only Chrome is giving this error. tho it is latest (78) version.

Any idea how to solve this issue?
(using formatjs or without it, it gives same error, but not on safar or firefox)

**Comment by longlho** [comment]
Looks like Chrome does not support `ka` locale
```
Intl.DateTimeFormat.supportedLocalesOf('ka') // returns []
```

so it'll fall back to English. If you want `ka` support then you'd prob have to polyfill using Intl.js (for `DateTimeFormat` & `NumberFormat` according) and other Intl.* APIs and load `ka` locale specifically.

Here are the list of locales supported in Chrome: https://cs.chromium.org/chromium/src/third_party/icu/scripts/chrome_ui_languages.list

Chrome recently changed its behavior where it fixed an issue that always return `[<locale_even_though_it_is_not_supported>]` for all locales. See https://bugs.chromium.org/p/chromium/issues/detail?id=1003861#c7
