### ISSUE TITLE
Why we can't capitalize FormattedMessage result ?

### ISSUE THREAD

**Issue by gothraven** [formatjs/react-intl#1527]
**Is your feature request related to a problem? Please describe.**
I would like to use <FormattedMessage> component to write some text and I want it to be capitalised. I tried some workaround but it has some disadvantages.

**Describe the solution you'd like**
```jsx
<FormattedMessage {...} capitalize >
```

**Describe alternatives you've considered**
since the v2 I used to do something like this but it has some issues for example when the first char is not a letter
```jsx
function FormattedMessage({ capitalize, ...props }) {
  return (
    <IntlFormattedMessage {...props}>
      {(text: string) => (capitalize ? text.capitalize() : text)}
    </IntlFormattedMessage>
  );
}
```

**Additional context**
I dont want this to be handled by CSS because i only want to capitalize the firs letter of the sentence and not every letter and i don't want to use the ::first-letter css because it doesn't exist in react native

**Comment by longlho** [comment]
Capitalization is locale-dependent (e.g Chinese/Japanese). This is unfortunately out of scope for this library.
