### ISSUE TITLE
FormattedNumber on iOS

### ISSUE THREAD

**Issue by kaldebert** [formatjs/react-intl#1528]
On iOS (Safari, Chrome), FormattedNumber does not use the thousand separator.

### Expected behavior

The number should use the thousand separator.

### Current behavior

The number does not use the thousand separator.

https://codesandbox.io/s/brave-lamarr-pdqkw

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.4.0 |
|  `npm ls react` | 16.11.0 |
|  `npm --version` | 6.13.0 |
|  `node --version` | 10.16.0 |

| OS   | Version |
| ---- | ------- |
| iOS | 13.2.2 |

| Browser | Version |
| ------- | ------- |
| Safari    | |
| Chrome | 3.7 |

### iOS
![Screenshot 2019-11-29 at 11 19 45-redacted](https://user-images.githubusercontent.com/10433270/69863844-079bb880-129e-11ea-9f69-6eac205b8f4e.png)

### Android
![Screenshot 2019-11-29 at 11 19 53-redacted](https://user-images.githubusercontent.com/10433270/69863817-f94d9c80-129d-11ea-8793-fd8f98571046.png)

**Comment by longlho** [comment]
This seems to be a WebKit issue since the native `Intl.NumberFormat` itself doesn't respect grouping correctly: https://codesandbox.io/s/serene-elgamal-he2hi

Unfortunately there's nothing we can do and you'd have to submit a bug to webkit itself.

**Comment by kaldebert** [comment]
For those who are interested in, I have opened a bug in WebKit: https://bugs.webkit.org/show_bug.cgi?id=205442
