### ISSUE TITLE
Incorrect `intl.locale` during SSR

### ISSUE THREAD

**Issue by IcanDivideBy0** [formatjs/react-intl#1531]
When using `ReactDOMServer.renderToString`, `intl.locale` context value is not the value given to `IntlProvider`.

### Expected behavior

`intl.locale` should have the same value as the locale provided to `IntlProvider`

### Current behavior

`intl.locale` is "en"

```js
import React from "react";
import { IntlProvider, useIntl } from "react-intl";
import ReactDOMServer from "react-dom/server";

const Foo = () => {
  const intl = useIntl();

  return <div>locale is {intl.locale}</div>;
};

const FooApp = ({ children }) => {
  return (
    <IntlProvider locale="fr">
      <Foo />
    </IntlProvider>
  );
};

const result = ReactDOMServer.renderToString(<FooApp />);

console.log(result);
// output:
// <div>locale is <!-- -->en</div>
```

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.9.1 |
|      `npm ls react` | 16.12.0 |
|     `npm --version` | 6.12.1 |
|    `node --version` | 12.10.0 |

| OS   | Version |
| ---- | ------- |
| Debian | Linux debian 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux |

| Browser | Version |
| ------- | ------- |
| Chrome    | 77.0.3865.90 |

**Comment by longlho** [comment]
Do you have a codesandbox.io to demo?

**Comment by IcanDivideBy0** [comment]
Damn, works fine on codesandbox. https://codesandbox.io/s/runtime-morning-u3n3r
Problem should come from somewhere else. Sorry for the noise

**Comment by longlho** [comment]
@IcanDivideBy0 so there's a possibility that your Node does not have `full-icu`, which is why things fall back to `en`. `intl.locale` is the resolved locale after locale negotiation process (e.g `en-AI` -> `en-001` -> `en`).

**Comment by IcanDivideBy0** [comment]
@longlho thanks for the hint, it was effectively related to node missing intl polyfill.

Added this a init time and everything works fine now.
```
global.Intl = require('intl');
```

**Comment by longlho** [comment]
@IcanDivideBy0 for performance & correctness I strongly suggest you use `full-icu` instead of the `intl` polyfill (or use Node 13 which has `full-icu` by default) 😄

**Comment by IcanDivideBy0** [comment]
Ok, just in case someone stumble upon this, here's what i ended up with:
```sh
node --icu-data-dir=$(node -e 'process.stdout.write(require("full-icu").datPath())') my-ssr-script.js
```

**Comment by longlho** [comment]
you can do
```
NODE_ICU_DATA=node_modules/full-icu node my-script.js
```
