### ISSUE TITLE
How to get translated text to javascript variable

### ISSUE THREAD

**Issue by ErcinDedeoglu** [formatjs/react-intl#1533]
Hi,
How can I get translated text to a javascript variable?

I would like to assign value to a variable dynamically.
For example:
`let value = FormattedMessage("user-login-success");
`
Is there a ready to use function to do it?

Thanks for awesome plugin.

**Comment by ErcinDedeoglu** [comment]
I just solved:
```

import React, { Component } from "react";
import IntlMessages from "../helpers/IntlMessages";

export function errorTypes(errorType) {
  return dictionary[errorType]
}

const dictionary = {
  0 : <IntlMessages id="error.unknown" />,

  101 : <IntlMessages id="error.user.login.email-verify-required" />,
  102 : <IntlMessages id="error.user.login.email-in-use" />,

  201 : <IntlMessages id="error.user.register.email-verify-required" />,
  202 : <IntlMessages id="error.user.register.user-not-found" />,
};
```

Is it best practice?

**Comment by longlho** [comment]
Our recommendation is to declare the messages inline. If you wanna use it outside of `react`, take a look at the `createIntl` API we offer.

**Comment by ErcinDedeoglu** [comment]
Could you specify some line of code please? I'm really new on React. Thanks.

**Comment by longlho** [comment]
https://github.com/formatjs/react-intl/blob/master/docs/API.md#createintl should have some more details and examples
