### ISSUE TITLE
intl.formatList return type is React.ReactNode instead of string

### ISSUE THREAD

**Issue by andrew--r** [formatjs/react-intl#1537]
### Expected behavior

Return type of `intl.formatList` is `string`, like `intl.formatMessage`.

### Current behavior

<img width="778" alt="Screen Shot 2019-12-10 at 13 23 32" src="https://user-images.githubusercontent.com/2734841/70521455-507e2780-1b50-11ea-9847-f41b2a297766.png">

Return type of `intl.formatList` is `React.ReactNode`. It makes impossible to use `intl.formatList` inside `intl.formatMessage`, for example:

```ts
intl.formatMessage(fileTypeErrorMessage, {
  fileTypes: intl.formatList(['txt', 'md'], {type: 'union'})
});
```

### Your Environment

`react-intl@3.9.1`

**Comment by JoeQuattrone** [comment]
This is breaking so many parts of code base making it impossible to upgrade. is there a workaround to convert reactnode to a string?
