### ISSUE TITLE
Unable to use relativeTimeFormat on IE11 even after importing polyfill

### ISSUE THREAD

**Issue by jgfidelis** [formatjs/react-intl#1538]
This may be a issue on my side, but from my console.logs I am doing the Polyfill right.

On IE11, whenever I try to `intl.formatRelativeTIme(-8, 'day')` I get the result `-8` and not `8 days ago`.

We are importing the polyfills.

I have two console logs that show that everything seems fine:
```
console.log('teste is polyfilled: ', window.Intl.RelativeTimeFormat.polyfilled)
console.log('teste WINDOW: ', window.Intl.RelativeTimeFormat.localeData.en)
return intl.formatRelativeTime(newValue, unit)
```

Both console logs show that window.Intl.RelativeTimeFormat.polyfilled is true and that window.Intl.RelativeTimeFormat.localeData.en has the data needed

### Expected behavior

It should display `8 days ago`.

### Current behavior

Throws error and displays -8.

### Your Environment
 Happening on IE11
tried with react-intl@3.9.1 & `@formatjs/intl-relativetimeformat@4.5.1` AND
react-intl@3.3.2 & `@formatjs/intl-relativetimeformat@4.2.0`

Happens the same thing in both versions.

**Comment by longlho** [comment]
You'd need to polyfill `Intl.PluralRules` as well. We have `@formatjs/intl-pluralrules` for that.

**Comment by jgfidelis** [comment]
Yes I have them both polyfilled

**Comment by longlho** [comment]
do you have a sample codesandbox.io link?

**Comment by jgfidelis** [comment]
Our hypothesis is that when the Provider was being created, the polyfill was still not loaded.

After ensuring that the Provider is first rendered only after the import promises are resolved, the bug does not happen.

**Comment by longlho** [comment]
Ah yeah. The creation of the Provider assumes the environment to be polyfilled already.
