### ISSUE TITLE
Is it possible to provide global values? 

### ISSUE THREAD

**Issue by ieugen** [formatjs/react-intl#1539]
Hi, 

**Is your feature request related to a problem? Please describe.**

We are developing an application in which we have a user context (authenticated user). 
Some of our texts require genderization -> the use of `{gender, Male { Hello male }, Female {Hello female}, Unknown { Hello}  }` 

**Describe the solution you'd like**

We would like to be able to supply a global value (via IntlProvider, make it updatable via some sort of hook ?!) that is available to all components of formatted messages so that we don't pass it to each FormattedMessage component like:

```
<FormattedMessage
  id="app.greeting"
  defaultMessage="{gender, Male { Hello male }, Female {Hello female}, Unknown { Hello}  }"
  values={{
    gender: XXX,
  }}
/>
```
Above, the gender is passed. We would like for it to be accessible in a "global values" scope, like the language. 

User can overwrite any global value via the values property. 

**Describe alternatives you've considered**

Pass the gender value to all components?!

If this feature exists, it would be nice to have it documented.

Thanks,
Eugen

**Comment by longlho** [comment]
This falls into the user realm and we don't provide anything out of the box for it since it's not in our core problem set. Some of the things I've seen:
- Have concentrated platform props that include `gender`, `name`, `intl` object along with other contextual things
- Have them passed down wholesale like `platformProps` and drill through, or have them in `PlatformContext` and use React context API.

**Comment by ieugen** [comment]
Hi, 

I don't think I explained things very well. I know I can use context api to pass them down.
What I am asking is to have support inside IntlProvider. 
The way we set locale and messages we could set values - that end up in this `global` context.

Regards,
Eugen

**Comment by longlho** [comment]
Thanks for the clarifications. The criteria for things we set in `IntlProvider` is that they are necessary for the system to function so unfortunately we don't plan to add user-space support to that.

**Comment by ieugen** [comment]
I hope you reconsider. Global values is not something that is required but I believe it would be a very useful feature. 

Thanks,
