### ISSUE TITLE
what can I do to make a react front-end web-app using react-intl compatible with IOS9?

### ISSUE THREAD

**Issue by YufeeXing** [formatjs/react-intl#1540]
the polyfill about ES6 or JSX has already been handled.

**Comment by longlho** [comment]
We rely on a couple of primitives like [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat) in modern browsers (IE11+). iOS9 doesn't seem to have them so we technically don't support it. You can try polyfilling with https://github.com/andyearnshaw/Intl.js to see if that works.
