### ISSUE TITLE
IntlProvider with Route, Navigation not working

### ISSUE THREAD

**Issue by chetankumars** [formatjs/react-intl#1542]
Hello, I failed to navigate from one page to another while wrapping '< App/ >'component with< IntlProvider >. 
  < IntlProvider locale={locale} messages={messages}>
                    < App / >
                < /IntlProvider >
App component 
< Layout>
            < Switch>
                < Route exact path='/' component={Login} />
                < Route path='/home' component={Home} />
                 < Route path='/counter' component={Counter} />
                < Route path='/fetch-data/:startDateIndex?' component={FetchData} />
            < /Switch>
        < /Layout>

**Comment by TrejGun** [comment]
this works perfectly fine

**Comment by longlho** [comment]
is there a codesandbox.io URL?
