### ISSUE TITLE
react-intl v3 doesn't render formatted message inside a <span/> tag by default

### ISSUE THREAD

**Issue by michalica** [formatjs/react-intl#1544]
### Expected behavior
Formatted message should be wrapped in span by default

### Current behavior

Formatted message is not wrapped by span

### codesandbox.io link to reproduce for BUG REPORT
https://codesandbox.io/s/prod-fire-bthu8

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.9.2 |

This issue already happened:
https://github.com/formatjs/react-intl/issues/1445

**Comment by jgfidelis** [comment]
https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#breaking-api-changes

"Change default textComponent in IntlProvider to React.Fragment. In order to keep the old behavior, you can explicitly set textComponent to span."

Its a breaking change in v3.x

**Comment by michalica** [comment]
@jgfidelis thanks, I didn't find it before
https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#breaking-api-changes
