### ISSUE TITLE
Variables between single quotes are not replaced

### ISSUE THREAD

**Issue by jalik** [formatjs/react-intl#1545]
After upgrading my npm packages, I noticed that variables between single quotes were not replaced, but it was before like in the code below.

```
<FormattedMessage
  id="elementCreated"
  defaultMessage="'{name}' was created with success !"
  values={{ name }}
/>
```

I found that the issue #1437 is the origin of this breaking change.
I don't mind having to change my code, but now how do I get the previous behavior ?
Displaying a variable (that is replaced) between single quotes ?

### Expected behavior

Before the output was for example "TEST was created with success !"

### Current behavior

The ouput is now "{name} was created with success !"

### Your Environment

react-intl@3.9.2

**Comment by longlho** [comment]
So ICU uses apostrophe to escape, so you gotta do `defaultMessage="''{name}'' was created with success !"`

**Comment by joshunger** [comment]
@longlho do you happen to have a link?

**Comment by longlho** [comment]
A link to what though?

**Comment by joshunger** [comment]
@longlho oh is there a link to the ICU standard for apostrophes? We're receiving translations back in the format `'<strong>text</strong>'` but according to you they should be escaping so we should be receiving `''<strong>text</strong>''` is that correct? I wanted to send them the documentation. Thank you!

**Comment by longlho** [comment]
so the apostrophe escaping only applies to ICU reserved tokens and not HTML one. You can see the doc here: https://unicode-org.github.io/icu/userguide/format_parse/messages/#quotingescaping

The HTML escaping behavior using apostrophe is our own custom behavior. Are you looking for just raw HTML? You can pass `ignoreTag` to preserve HTML although you'd have to clean those HTML yourself to prevent XSS.

**Comment by joshunger** [comment]
I don't think we want raw HTML but is there a way to tell compile to not strip it out?

**Comment by longlho** [comment]
Maybe I'm missing something cam you provide a codesandbox?

**Comment by joshunger** [comment]
Yes, sorry I wasn't clear!

nl-NL.json
```
{
  "4hp/IQ": {
    "defaultMessage": "Deze Algemene Voorwaarden (deze '<strong>Voorwaarden</strong>') bevatten de voorwaarden"
  }
}
```

Running this command `./node_modules/.bin/formatjs compile --ast nl-NL.json` strips them out -

```
{
  "4hp/IQ": [
    {
      "type": 0,
      "value": "(<strong>Voorwaarden</strong>)"
    }
  ]
}
```

We still want them -
```
{
  "4hp/IQ": [
    {
      "type": 0,
      "value": "Deze Algemene Voorwaarden (deze '"
    },
    {
      "children": [
        {
          "type": 0,
          "value": "Voorwaarden"
        }
      ],
      "type": 8,
      "value": "strong"
    },
    {
      "type": 0,
      "value": "') bevatten de voorwaarden"
    }
  ]
}
```

How do you recommend we fix this? Should we process the `.json` files once we receive them from our vendor? And if so, do you happen to have a script?
