### ISSUE TITLE
Support data-attributes

### ISSUE THREAD

**Issue by zohrenweiss** [formatjs/react-intl#1551]
It would be great to support data-attributes to the components for those of us who would like to make things easily automatable. It's generally fairly trivial to do, and would be quite helpful for many.

**Comment by longlho** [comment]
What’s your use case?

**Comment by zohrenweiss** [comment]
Primarily for use with automation tools such as Selenium, TestCafe, Puppeteer, etc.

**Comment by longlho** [comment]
You can put that in the parent component right?

**Comment by zohrenweiss** [comment]
Not if we don’t have a parent component.

- Zoh

**Comment by zohrenweiss** [comment]
Or if the parent component doesn’t support them either.

- Zoh

**Comment by longlho** [comment]
This is not something we plan to support natively in the library. The solution is to add a parent component.

**Comment by foxdoubt** [comment]
FWIW, I completely agree @zohrenweiss. We're using Cypress to automate our app and being able to pass a data attribute prop to react-intl would make our tests break far less often and make life a lot less stressful. Adding a parent component is not always an option in a complex and mature application @longlho

**Comment by longlho** [comment]
I mean `FormattedMessage` isn't even guaranteed to be rendered in a tag (it renders as a `Fragment` by default, and we have render-as-a-function support) so adding a data-attribute actually isn't possible.
