### ISSUE TITLE
Could `MessageDescriptor['id']` change to `string | number` ?

### ISSUE THREAD

**Issue by xiaoboost** [formatjs/react-intl#1552]
**Is your feature request related to a problem? Please describe.**

In our project, we use intl like this:
```typescript
// messages
export const enum i18nKey {
    name,
    test,
}

const messages = {
    [i18nKey.name]: 'English',
    [i18nKey.test]: 'text context',
};

// component
import { useIntl } from 'react-intl';
import { i18nKey } from 'src/i18n';

function Component() {
    const { formatMessage: t } = useIntl();

    return (
        <div>{t({ id: i18nKey.name })}</div>
    );
}
```

we consider two advantages writing this:
* Use the feature of constant enum to effectively reduce the length of the message key and reduce code redundancy.
* the enum type has code hints, which is much better than the string type. 

but now, type of MessageDescriptor['id'] is string, cannot use numeric enum

**Describe the solution you'd like**
change this type:
https://github.com/formatjs/react-intl/blob/master/src/types.ts#L154

```typescript
export interface MessageDescriptor {
  id?: string | number;
  description?: string | object;
  defaultMessage?: string;
}
```

**Comment by longlho** [comment]
hmm sure I don't see why not. Wanna make a PR?

**Comment by longlho** [comment]
fixed in #1553

**Comment by Andreeh** [comment]
How come the id is set to optional, but required in the docs? (I don't want it set to optional since I would like to have the ability to use formatMessage with only an id referenced from a MessageDescriptor and not handle a potential undefined id)

**Comment by longlho** [comment]
`id` is marked optional because toolchain can populate that during compilation process. I'll update the doc w/ that detail
