### ISSUE TITLE
Using ICU Message syntax with currency in FormattedMessage

### ISSUE THREAD

**Issue by amosbastian** [formatjs/react-intl#1555]
I want to use `<FormattedMessage />` or `formatMessage` and format a currency. In the `en.json` file I'm using I have the following for example:

```
"wallet-content.wallet-balance": "Your balance is {balance, number, currency}."
```

and would like to call it in my code like

```
<FormattedMessage id="wallet-content.wallet-balance", values={{ balance: "10" }} />
```

Obviously this complains that a `Currency code is required with currency style react-intl`, but how are you meant to provide this value?

I am currently using this as an alternative:

```
// en.json
 "wallet-content.wallet-balance": "Wallet balance is {balance}."
// React component
formatMessage({ id: "wallet-content.wallet-balance" }, {
        balance: formatNumber(balance ? +balance : 0, { style: "currency", currency: "USD" })
```
but there surely must be a better way that I am simply missing, right?

**Comment by longlho** [comment]
You can use the [skeleton feature](https://github.com/unicode-org/icu/blob/master/docs/userguide/format_parse/numbers/skeletons.md) in ICU that we do support:
```
{amt, number, ::currency/JPY}
```

Codesandbox:
https://codesandbox.io/s/serene-elgamal-he2hi

**Comment by amosbastian** [comment]
> You can use the [skeleton feature](https://github.com/unicode-org/icu/blob/master/docs/userguide/format_parse/numbers/skeletons.md) in ICU that we do support:
> 
> ```
> {amt, number, ::currency/JPY}
> ```
> 
> Codesandbox:
> https://codesandbox.io/s/serene-elgamal-he2hi

I want to pass the currency to it from a React component (so in your example `JPY`) instead of hardcoding it.

**Comment by longlho** [comment]
Yeah then your best bet is to tokenize it separately.
