### ISSUE TITLE
FormattedNumber with currency doesn't use the correct Region as specified in locale

### ISSUE THREAD

**Issue by nirshubz** [formatjs/react-intl#1558]
### Expected behavior

FormattedNumber should be using the correct region when using currency style

### Current behavior

FormattedNumber is using the default region when using currency style

### codesandbox.io link to reproduce for BUG REPORT

https://codesandbox.io/s/late-grass-wbbfg

Thank you!

**Comment by longlho** [comment]
This seems like a Chrome bug to me so can you file a bug https://bugs.chromium.org/p/chromium/issues/list accordingly? Based on [CLDR data for `en-DE`](https://github.com/unicode-cldr/cldr-numbers-full/blob/master/main/en-DE/numbers.json) it should have been like `12,55 €` actually

**Comment by nirshubz** [comment]
Thanks @longlho 

I added a new issue here:
https://bugs.chromium.org/p/chromium/issues/detail?id=1043519&can=2&q=currency%20Intl
