### ISSUE TITLE
Add keys, if we have few elements.

### ISSUE THREAD

**Issue by Slonevskyi08** [formatjs/react-intl#1559]
Maybe I missed something, but if we have several variables, they need a unique key, maybe it’s worth adding an automatic addition of keys, so as not to write manually?
`formatMessage({ id: "rules" }, {
            eu: str => (
              <a target="_blank" href="/rules-eu">{str}</a>
            ),
            ukr: str => (
              <a target="_blank" href="/rules-ukr">{str}</a>
            )`

**Comment by longlho** [comment]
can you elaborate your use case more?

**Comment by Bazze** [comment]
I think @Slonevskyi08 is referring to warnings like below which we seem to be getting when providing values to the `formatMessage` function.

<img width="419" alt="Screenshot 2020-07-27 at 13 57 00" src="https://user-images.githubusercontent.com/1932208/88539250-31fe6b00-d011-11ea-946d-2a938d1721bb.png">

This is from a statement like this:

```javascript
// defaultMessage: "Sent by {name} on {date}"
formatMessage(..., {
  name: <b>{createdBy}</b>,
  date: <b>{startDate}</b>,
})
```

**Comment by longlho** [comment]
ah yeah we have `wrapRichTextChunksInFragment` for that: https://formatjs.io/docs/react-intl/components/#intlprovider

**Comment by Bazze** [comment]
@longlho Perfect, thanks. Did not know about that option!
