### ISSUE TITLE
Best practice to format numbers and strings separately.

### ISSUE THREAD

**Issue by mfelmy** [formatjs/react-intl#1561]
I'm wondering what is the best/safest way to format numbers and strings separately.

My setup requires that the user can set the language and number format individually. For example, the user chooses English (`en`) as the display language and want's to have numbers formatted in German (`DE`), e.g. 1.000,95.

So I tried feeding `en-DE` as `locale` to `IntlProvider` and it does work as expected
- string: Hello (expected format/language)
- number: 1.000,95 (expected format)
- date: 01/22/2020 (expected format)

However, if I try `de-US` for example, the output is
- string: Guten Tag (expected format/language)
- number: 1.000,95 (NOT expected format)
- date: 22.01.2020 (expected format)

Can you give me a hint at how to handle this scenario? Thank you a lot in advance!

**Comment by longlho** [comment]
Combining locale only works if that locale actually produces different formatted value. Your best bet is to override locale to your number to be `de-DE` or `en` or whatever

**Comment by mfelmy** [comment]
I think I don't fully understand your answer.

> Your best bet is to override locale to your number to be `de-DE` or `en` or whatever

--> Do you mean setting the locale based on the desired number format? And what/where exactly to override?

**Comment by longlho** [comment]
Do you have a codesandbox.io link to demo your use case?

**Comment by mfelmy** [comment]
Here I tried to demo my use case: https://codesandbox.io/s/react-intl-independent-text-and-number-formatting-i9zgb

For example (as shown on startup) the user wants an English app (text in English language, dates and relative times in English) but with german number formatting. and it does kind of work.

But when I try to set another use case, let's say german app (again text and dates) and US number formatting, it doesn't seem to work.

I hope that I could explain my use case. Thank you a lot for your help!

**Comment by longlho** [comment]
ah kk. You'd have to create a different `intl` per locale if u wanna format number differently vs messages
