### ISSUE TITLE
Add fallback based on other message id

### ISSUE THREAD

**Issue by avalenti89** [formatjs/react-intl#1564]
In our use case, we need to set specific dictionary (defineMessages) for each page/component but sometime it could be helpful set a text from another dictionary (defineMessages) as default value.

I think that could be useful let to set another message descriptor as fallback instead of string.

```interface MessageDescriptor {
   ...
    defaultMessage?: string | MessageDescriptor;
}```
A type guard may check if it can continue with string or re-iterate with the other message

**Comment by longlho** [comment]
We don't have any plan to support this anytime soon. This can be done at a high level than the message itself (e.g component level)
