### ISSUE TITLE
use methods as imports instead of props

### ISSUE THREAD

**Issue by marcosanfilippo** [formatjs/react-intl#1566]
How can I import `formatDate` and `formatMessage` from the lib?
I need to use somewhere else that is not a component.

**Comment by longlho** [comment]
You can use https://github.com/formatjs/react-intl/blob/master/docs/API.md#createintl

**Comment by marcosanfilippo** [comment]
I tried that, with JS version `2.9.0` there is no `createIntl` export.

**Comment by longlho** [comment]
Oh we don’t really support 2.x

**Comment by marcosanfilippo** [comment]
Given that we still have legacy code, here my solution, hopefully others can take the most from it.
```
import { IntlProvider } from 'react-intl';
// ...

    const intlConfig = {
      locale: '...',
      messages: {...},
    };

    const {
      intl: {
        formatDate,
        formatMessage,
      },
    } = new IntlProvider(intlConfig).getChildContext();

// use imperatively
```
