### ISSUE TITLE
[React Intl] Jest test throwing Missing locale data for locale: "de". Using default locale: "en" as fallback.

### ISSUE THREAD

**Issue by vishalrajole** [formatjs/react-intl#1568]
### Expected behavior
Jest tests should not throw warnings for locale data for 'de' or 'fr'.
react-intl V3 + jest test setup throwing warnings for locale data for all locale other than 'en'.
since 'addLocaleData' is deprecated in newer version, react-intl v3 doesn't find locale data when used in jest tests.

I already have polyfill added for browser.
```
if (!Intl.PluralRules) {
  require('@formatjs/intl-pluralrules/polyfill');
  require('@formatjs/intl-pluralrules/dist/locale-data/de'); // Add locale data for de
}

if (!Intl.RelativeTimeFormat) {
  require('@formatjs/intl-relativetimeformat/polyfill');
  require('@formatjs/intl-relativetimeformat/dist/locale-data/de'); // Add locale data for de
}
```

### Current behavior
```
 console.error node_modules/react-intl/dist/utils.js:54
    [React Intl] Missing locale data for locale: "de". Using default locale: "en" as fallback.

  console.error node_modules/react-intl/dist/utils.js:54
    [React Intl] Missing locale data for locale: "fr". Using default locale: "en" as fallback.
```

NOTE: I don't want to suppress these warnings using onError callback function.
### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | @3.11.0 |
|      `npm ls react` | @16.12.0 |
|     `npm --version` | 6.13.4 |
|    `node --version` | v12.14.0 |

| OS   | Version |
| ---- | ------- |
| macOS Catalina | 10.15.2 |

**Comment by pyrocat101** [comment]
What does your Jest test case look like?

**Comment by vishalrajole** [comment]
created codesandbox https://codesandbox.io/s/react-intl-v3-jest-tests-1ljym for jest cases. code sandbox not throwing warning.

**Comment by pyrocat101** [comment]
@vishalrajole have you tried running your test with full ICU support? See: https://nodejs.org/api/intl.html#intl_providing_icu_data_at_runtime
