### ISSUE TITLE
[React Intl] Missing locale data for locale: "ga". Using default locale: "en" as fallback.

### ISSUE THREAD

**Issue by shostkevych** [formatjs/react-intl#1570]
**Experiencing an issue with console error stating "[React Intl] Missing locale data for locale: "ga". Using default locale: "en" as fallback." with react-intl v3 and using Gaelic language. Futhermore everything is working fine and proper translations are applied. Just error in console. Other languages like 'de', 'fr', 'it', works fine without errors in console.**

### Expected behavior

**No console error message "[React Intl] Missing locale data for locale: "ga". Using default locale: "en" as fallback."**

### Current behavior

**Console error message "[React Intl] Missing locale data for locale: "ga". Using default locale: "en" as fallback."**

### codesandbox.io link to reproduce for BUG REPORT

https://codesandbox.io/s/react-intl-bfumh

**Try to switch English <-> Gaelic and experience and console error.**

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.12.0 |
|      `npm ls react` | 16.9.0 |
|     `npm --version` | 6.12.0 |
|    `node --version` | 12.13.0 |

| OS   | Version |
| ---- | ------- |
| macOS Catalina | 10.15.1 |

| Browser | Version |
| ------- | ------- |
| Chrome    | 79.0.3945.130 |

**Comment by longlho** [comment]
Seems like your Node isn't supporting full-icu https://github.com/formatjs/react-intl/blob/master/docs/Getting-Started.md#runtime-requirements

**Comment by shostkevych** [comment]
@longlho , I'm trying to use react-intl with browser javascript and not with node.js. So seems full-icu is relevant only for node.js projects ? I'm getting this error in runtime.

Futhermore issue is not reproducible in Firefox.

**Comment by longlho** [comment]
ah ok looks like browsers don't bundle `ga` locale which is the problem. Looks like u'd have to polyfill it with `Intl.js`

**Comment by neelamshah02** [comment]
I am also getting same error for 'no' lang. is there any solution available ?

**Comment by longlho** [comment]
@neelamshah02 can you provide more details in a separate GH issue?

**Comment by stovt** [comment]
> I am also getting same error for 'no' lang. is there any solution available ?

@neelamshah02 use `nb` locale instead of `no` for the NO lang :slightly_smiling_face:

**Comment by neelamshah02** [comment]
Thank you @stovt 'nb' resloved my issue.
