### ISSUE TITLE
React-intl with SSR TypeError: Cannot read property 'formatHTMLMessage' of null

### ISSUE THREAD

**Issue by stefankuburovic** [formatjs/react-intl#1571]
### Expected behavior

On npm run serve SSR is started and translations work

### Current behavior

On npm run serve, I got error **TypeError: Cannot read property 'formatHTMLMessage' of null**

I added translations to my app, and when I want to start it over SSR I got error TypeError: Cannot read property 'formatHTMLMessage

TypeError: Cannot read property 'formatHTMLMessage' of null
    at Object.children (/.../react-app/node_modules/react-intl/dist/components/html-message.js:47:42)

### Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.12.0 |
|      `npm ls react` | 16.7.0 |
|     `npm --version` | 6.12.0 |
|    `node --version` | 11.10.0 |

| OS   | Version |
| ---- | ------- |
| macOS Mojave | 10.14.5 |

| Browser | Version |
| ------- | ------- |
| Chrome | 79.0.3945.130 |

**Comment by longlho** [comment]
Do you have a codesandbox.io link?
