### ISSUE TITLE
Change in FormattedMessage component behavior between versions 3.10.0 and 3.11.0

### ISSUE THREAD

**Issue by krash83** [formatjs/react-intl#1574]
Hello,
From what I can see there was a change in FormattedMessage behavior between 3.10.0 and 3.11.0
If I am right it's because of [this change](https://github.com/formatjs/react-intl/pull/1550) in [this line](https://github.com/formatjs/react-intl/commit/8c3c5c78afa16d605933c82571f3b92b15363c27#diff-2e7e587cd1ae6346c4522c1d245745adR206)

**codesandbox.io link to reproduce**
[https://codesandbox.io/s/bold-cdn-63krs](https://codesandbox.io/s/bold-cdn-63krs)
to see a difference just change react-intl version to 3.10.0

If 'someKey' has a value 'first line {br}second line' then:
 - In 3.11.0
```
<FormattedMessage id="someKey" values={{br: <br/>}}>
{(...messageParts) => {
    console.log(messageParts) // [{$$typeof: Symbol(react.element), type: Symbol(react.fragment), key: null, ref: null, props: {…}, …}]
    return messageParts;
}}
</FormattedMessage>
```
- In 3.10.0
```
<FormattedMessage id="someKey" values={{br: <br/>}}>
{(...messageParts) => {
    console.log(messageParts) // ["first line ", {$$typeof: Symbol(react.element), type: "br", key: null, ref: null, props: {…}, …}, "second line"]
    return messageParts;
}}
</FormattedMessage>
```

Before 3.11.0 we had message parts as function params now we have only React.Fragment element

**Comment by longlho** [comment]
Yes this is to fix the `missing key` issue. Is this causing some issues on your part?

**Comment by rafalmaciejewski** [comment]
This is a breaking change for someone that was using this API, e.g. when transforming messageParts.

**Comment by longlho** [comment]
Hmm I don't think our API guarantees what a specific chunk is. It is an implementation detail that is private intentionally. Transforming specific chunk isn't necessarily linguistically safe and the order of those chunks might change. Right now we don't have a chunk type API or anything like that to identify those chunks so whatever is being done to them is pure speculation.

**Comment by rafalmaciejewski** [comment]
Is it still `...chunks` when now there is only one React element returned with chunks as children? Anyway I used this feature more or less like this:

```tsx
function renderChunk(chunk, index) {
    if (React.isValidElement(chunk)) {
        return React.cloneElement(chunk, {key: index});
    }
    if (typeof chunk === 'string') {
        return htmlEntities.decode(chunk);
    }
    return chunk;
}

export class FormattedMessageWrapper extends React.Component {
    render() {
        return (
            <FormattedMessage {...this.props}>
                {(...chunks) => chunks.map(renderChunk)}
            </FormattedMessage>
        );
    }
}
````

Could you suggest an alternative approach for achieving this without transformation before passing messages into provider?

**Comment by longlho** [comment]
AFAIK the number of chunks is the same (no guarantee) and they do have `key` now so for your use case specifically you shouldn't have to insert the `key` attribute in anymore.

In terms of html entities that's a separate issue and I'm not sure why you'd need to handle that separately? Do you have an example?

**Comment by rafalmaciejewski** [comment]
Messages that i work with come from various sources and can contain entities like `&lt;`, without this transformation they are rendered as string. Workaround is to use dangerouslySetInnerHtml but it breaks when messages contains also parts that are react components.

**Comment by longlho** [comment]
Can you create a separate GH issue for that along w/ examples? I'm sure we've encountered your use case somewhere but need more context on it.
