### ISSUE TITLE
Cannot work with Galician

### ISSUE THREAD

**Issue by barreeeiroo** [formatjs/react-intl#1576]
I am trying to build a localized app, and I need as base language Galician (a regional language in Spain). I have tried with `gl` (ISO 639-1) and `gal` (ISO 639-3), but could not get it working.
However, I tried with Catalan, `cat`, and it worked.
I am following this tutorial: https://github.com/vlaja/multilanguage-routing-react

### Expected behavior

It seems like Galician language is missing.

### Current behavior

I cannot use Galician in my web app, even though I am using my own strings.

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | react-intl@3.12.0 |
|      `npm ls react` | react@16.12.0|
|     `npm --version` | 6.13.14|
|    `node --version` | v12.15.0|

| OS   | Version |
| ---- | ------- |
| Windows 10 | |

| Browser | Version |
| ------- | ------- |
| Chrome    | 79 |

**Comment by longlho** [comment]
Do you have a codesandbox link? 

Looks like browsers don't come with `gl` so you'd have to polyfill it using `intl.js` and friends.
