### ISSUE TITLE
All messages using FormattedHTMLMessage are not translated at loading page. It displays defaultMessage instead.

### ISSUE THREAD

**Issue by Steffi3rd** [formatjs/react-intl#1578]
Hello guys, 

I have a bug : 

On build, All messages using `<FormattedHTMLMessage />` are not translated at loading page. It displays defaultMessage instead. Whereas `<FormattedMessage />` are translated.

So I have 2 lang is the same time when the page is loading and fully loaded.

I have to change the lang to make it work.

On develop, I have no problem on any component, everything works as excepted. 

Is there a solution for that bug please ? 

### Expected behavior

Everything should be translated in the same language.

### Current behavior

`<FormattedMessage />` are translated. 

`<FormattedHTMLMessage />` is the default lang is defined, otherwise it uses the defaultMessage.

### Your Environment

  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/opt/node@10/bin/node
    Yarn: 1.19.2 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/opt/node@10/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 72.0.2
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.0.0 => 2.15.24 
    gatsby-cli: ^2.4.16 => 2.7.50 
    gatsby-image: ^2.0.26 => 2.2.21 
    gatsby-plugin-emotion: ^4.0.1 => 4.1.7 
    gatsby-plugin-google-tagmanager: ^2.1.4 => 2.1.10 
    gatsby-plugin-manifest: ^2.2.13 => 2.2.18 
    gatsby-plugin-mdx: ^1.0.44 => 1.0.44 
    gatsby-plugin-netlify: ^2.0.12 => 2.1.15 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.1.8 
    gatsby-plugin-sharp: ^2.0.17 => 2.2.25 
    gatsby-plugin-sitemap: ^2.2.3 => 2.2.14 
    gatsby-source-filesystem: ^2.0.12 => 2.1.26 
    gatsby-transformer-sharp: ^2.1.10 => 2.2.17 
  npmGlobalPackages:
    gatsby-cli: 2.4.8

**Comment by Steffi3rd** [comment]
Maybe related ? https://github.com/formatjs/react-intl/issues/1571

**Comment by longlho** [comment]
Do you have a codesandbox.io link?

**Comment by DragonRaider5** [comment]
@Steffi3rd can you replicate this in a demo project or a [sandbox](http://codesandbox.io)?

**Comment by longlho** [comment]
close since `FormattedHTMLMessage` is removed in v4
