### ISSUE TITLE
Spontaneously error "undefined is not an object (evaluating '(new Intl.NumberFormat).resolvedOptions().locale')"

### ISSUE THREAD

**Issue by jannnik** [formatjs/react-intl#1579]
### Expected behavior

No bug occurs. 

### Current behavior

Without changing anything, we experience an error in one of our production pages where we use react-intl. The bug still occurs after upgrading to the latest dependency version and after removing unneeded polyfills. 

`undefined is not an object (evaluating '(new Intl.NumberFormat).resolvedOptions().locale')`

Unfortunately we can't figure out how to reproduce the error, we only get it reported in Sentry because it occurs when customers visit our page. You can try to reproduce it at https://trial.meisterplan.io/

We're not sure how to find out what triggers the bug and whether it is really related to react-intl at all. 

A possibly interesting fact is that on our site google analytics is included and google analytics itself includes various other trackers. 

I am happy for every tip!

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | react-intl@3.12.0 |
|      `npm ls react` | react@16.12.0 |
|     `npm --version` | 6.13.4 |
|    `node --version` | v13.5.0 |

| OS  | Version |
| -------------:| :---------- |
|Chrome| 71 - 79|
|Firefox|69 - 72|
|Safari|13.0.3|

**Comment by longlho** [comment]
That means they're using an unsupported browsers (e.g IE10) that doesn't have `Intl` API. We support IE11+.

**Comment by jannnik** [comment]
The error occurs on the browsers I listed in the issue: Chrome, Firefox, Safari .
They have an `Intl` API.

**Comment by longlho** [comment]
hmm that's not possible. I'd recommend instrumenting your code & log out `Intl` methods to see what's going on. W/o looking at your traffic pattern I can't really tell what the issue is.

**Comment by jannnik** [comment]
@longlho Do you have any ideas what a useful debug log could be? We already added some debug log which tells us that `Int.Numberformat` is defined, but `resolvedOptions` returns undefined. 

After hours of research I did not find any hints or similar errors. 

I can't imagine it's a polyfill problem since it occurred in these browsers:

Chrome 75.0.37705
Chrome 73.0.36834
Chrome 74.0.37293
Chrome 79.0.39453
Chrome 71.0.35783
Chrome 78.0.39043
Firefox 72.02
Chrome 72.0.36262
Firefox 70.02
Firefox 66.0

**Comment by longlho** [comment]
did u accidentally include mock/stub or anything in ur production code?
