### ISSUE TITLE
Double curly brackets

### ISSUE THREAD

**Issue by johnico** [formatjs/react-intl#1580]
is it possible to support double curly brackets ? 

for example  "message_id": "hello {{name}}"

**Comment by longlho** [comment]
Nope because ICU doesn’t support it

**Comment by morsha** [comment]
So escaping double curly brackets is also unavailable?
for example "message_id": "'{{name}}'" => '{{name}}'

**Comment by longlho** [comment]
I'm not sure I understand, if you escape then that would be `'{{name}}'` with name = John would result in `{John}`
