### ISSUE TITLE
IntlProvider defaultMessage='en' 

### ISSUE THREAD

**Issue by rasik88** [formatjs/react-intl#1581]
Is there a way to set default language file if a certain "key" is not present in a language.

i.e I don't want to define defaultMessage=" English version" every time in "FormattedMessage"

**Comment by longlho** [comment]
that should happen at build time when you build your `messages`, e.g You'd add that ID w/ the english string in your non-en messages if that ID is not translated

**Comment by rasik88** [comment]
> that should happen at build time when you build your `messages`, e.g You'd add that ID w/ the english string in your non-en messages if that ID is not translated

Yes, its is one way to handle this, But is there a reason why we don't have a primary/default lang set, like it has a defaultLocal prop but not defaultLanguage prop or something so for just printing the missing key itself, it prints value of primary language.

**Comment by longlho** [comment]
I'm not sure I understand your suggestion. Can u clarify?

**Comment by rasik88** [comment]
> I'm not sure I understand your suggestion. Can u clarify?

my code

`
```
//index.js
<IntlProvider locale={locale} messages={lang[jp}>
      <App />
</IntlProvider> 

// translation json files 
en.json
{
"1":"abcd",
"2':"efgh"
}
jp.json
{
"1":"mkln"
}

//my output file

<FormattedMessage id="2">
```
`

so the output is '2', cause it cannot find any key "2" in jp.json, but I wanted that the is outputs "efgh" as if it doesn't find a key it takes the en.json file as a failsafe.

**Comment by longlho** [comment]
Right that part I got, and you can solve that by merging messages at build time. Is that not an option for you?

**Comment by rasik88** [comment]
> Right that part I got, and you can solve that by merging messages at build time. Is that not an option for you?

Yup I am using object merging and seems like it does the job 

```
const lang = {
        'hi': hi,
        'en': en,
    };
  let t={...lang['en'], ...lang[language]}
  const messages = language === 'en' ? lang['en'] : t;
```

Also is there a reason it doesn't have a fallback primary language or it's just not there.
Thanks for the replays btw.

**Comment by longlho** [comment]
TBH we haven't seen that solution in the wild. Most of the i18n pipelines I've seen do build time merging because otherwise you have to load 2 messages json blob which is a performance & availability concern. Most TMSes (Translation Mgmt System) also offer the capability to prefill missing translations with English so there's no need for further processing.
