### ISSUE TITLE
Weird substitution behaviour

### ISSUE THREAD

**Issue by daggmano** [formatjs/react-intl#1583]
I'm not really sure where to start with this one. We are migrating from react-intl v2 to v3, and after going through the migration process everything seems to be working correctly, with the exception of placeholder substitution. If there is any format or type information provided (e.g. `plural`, `number`, etc) in the defaultMessage all works as expected.

However, if the placeholder is a simple value, the resultant string contains a date/time rather than the provided value.

### Expected behavior

Given the invocation:
`formatMessage({ id: 'myid', defaultMessage: 'Do you want to delete <strong>{name}</strong>?' }, { name: 'Internet Explorer' }))`

I would expect the output:
Do you want to delete **Internet Explorer**?

### Current behavior

The output is:
Do you want to delete **@@Tue Feb 18 2020 10:16:47 GMT+1030 (Cen. Australia Summer Time)_1@@**? 

### Your Environment

Windows 10, all browsers

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.12.0 |
|      `npm ls react` | 16.12.0 |
|     `npm --version` | 6.13.7 |
|    `node --version` | 13.7.0 |

**Comment by longlho** [comment]
Do u have a codesandbox.io link to repro?
In v3 we treat tags as placeholder as well so you'd do
```
formatMessage({ 
	id: 'myid', 
	defaultMessage: 'Do you want to delete <strong>{name}</strong>?' 
}, { 
	name: 'Internet Explorer',
	strong(...chunks) {
		return <strong>{chunks}</strong>
	}
}))
```

**Comment by longlho** [comment]
If you want to preserve this old behavior, you can use `FormattedHTMLMessage` but keep in mind embedding raw HTML in your message is subject to XSS so this is not something we encourage.

**Comment by daggmano** [comment]
Happily (sort of) unable to reproduce in codesandbox, so it's likely more a config error on our end. Will try to report back here if we find the issue in case anyone else has this problem. Would be interested if anyone knows where that date string may come from, though...

**Comment by longlho** [comment]
We tokenize all placeholders to [current date in ms + some counter](https://github.com/formatjs/formatjs/blob/master/packages/intl-messageformat/src/formatters.ts#L280) to guarantee uniqueness so that's where it comes from.

**Comment by daggmano** [comment]
Now able to reproduce this, see https://github.com/formatjs/formatjs/issues/534
