### ISSUE TITLE
"ReferenceError: Can't find variable: Intl" on older browsers on import

### ISSUE THREAD

**Issue by pjlee11** [formatjs/react-intl#1584]
### Expected behavior

To be able to:
1) import `react-intl` prior to polyfilling `Intl`
2) Then polyfill Intl after the import
3) Use any of the `react-intl` API - EG: `<IntlProvider>`

### Current behavior

As of version `react-intl@3.6.0` (which pulls in `intl-formatmessage@7.5.1`) any browser that doesn't have Intl throws a runtime execution error at time of importing `react-intl`. In our use case we want to conditionally load the polyfill and locale-data based on browser compatibility, and we do this via dynamic imports. Therefore the polyfill is downloaded asynchronously and even though we wait for the polyfill before executing the app (which is where we use react-intl) the above error is thrown.

This seems to comes from this line https://github.com/formatjs/formatjs/blob/243a67e101a0ea31cb40a8142bbccc7838938f41/packages/intl-messageformat/src/core.ts#L161 (added in [this commit](https://github.com/formatjs/formatjs/commit/3a74c2e7c6592de3a4f5ca182c5846fe095abe55#diff-436dcc33138852399a91fe6e46835da0R160)) which is directly creating a new instance of Intl without inside the constructor. So as soon you import `react-intl` in your application on a browser without Intl you get a JS execution error. 

IMO this doesn't feel like the common approach to polyfilling a required dependency where the import cannot be resolved without error.

### codesandbox.io link to reproduce for BUG REPORT

Didn't make a code sandbox as it didn't run on the test device - iPhone 6, iOS v9, Safari (on browserstack)

### Your Environment

iPhone 6, iOS v9, Safari (on browserstack) 

Should be reproducible on any browser that doesn't have `Intl`

**Comment by longlho** [comment]
Unfortunately we don't support loading `react-intl` before polyfills. You'd have to make sure your environment is adequate before loading a specific library that requires a specific runtime. You should chain your app bootstrap to be after polyfills, which is what basically everyone does (Yahoo, Dropbox... places I've been/seen). They also inject polyfill as the 1st script in a page, dynamically using things like https://polyfill.io/v3/

The complexity of checking for API availabilities will turn into runtime cost of basically checking & memoizing whether `Intl` API and its methods are available, which we don't plan to take on.

**Comment by pjlee11** [comment]
Thanks for clarifying and for such a swift response!
