### ISSUE TITLE
FormattedMessage does not pass extra props to tagName component

### ISSUE THREAD

**Issue by VincentLanglet** [formatjs/react-intl#1588]
### Expected behavior 

When writing
```
<FormattedMessage tagName="option" value="foo" id="unitAccountsTable.button.select" />
```

I expect
```
<option value="foo">Translation</option>
```

### Current behavior

```
<option>Translation</option>
```

**Comment by longlho** [comment]
You can use render as a function for this

**Comment by VincentLanglet** [comment]
Indeed I can, and I did.
But I see no drawback to pass the extraProps to the tag.

**Comment by longlho** [comment]
To prevent future collision. MessageFormat spec right now is being worked on

**Comment by VincentLanglet** [comment]
> To prevent future collision. 

In this case, it's possible to add a props call `tagProps`.

```
<FormattedMessage tagName="option" tagProps={ 'value': 'foo' } id="unitAccountsTable.button.select" />
```

**Comment by longlho** [comment]
We already have a solution for this use case so we’re not looking to add
another one. The tagName prop was already a workaround before render props
was a thing so it’s likely gonna be gone in the future.
