### ISSUE TITLE
ReferenceError: Can't find variable: Intl

### ISSUE THREAD

**Issue by duongkhoangiam** [formatjs/react-intl#1591]
I am using react-intl with expo to build my mobile app
here is code
```
import React, { Component } from 'react';
import { FormattedMessage, IntlProvider } from 'react-intl';
import { StyleSheet, Text, View } from 'react-native';
import arLang from './locales/ar.json';
import enLang from './locales/en.json';

class LanguageTest extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>
          {' '}
          <FormattedMessage id="text_hi" />{' '}
        </Text>
      </View>
    );
  }
}
export default class App extends Component {
  render() {
    const messages = { ar: arLang, en: enLang };
    return (
      <IntlProvider locale="en" messages={messages['en']}>
        <LanguageTest />
      </IntlProvider>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center'
  }
});

```

en.json
```
{
  "text_hi": "Hello Engish"
}

```

this code ready working well in IOS emulator but for android emulator i am got error
```
ReferenceError: Can't find variable: Intl
```

When i using debug mode in android emulator it will work
I do not know what exactity problem in there!

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.12.0 |
|      `npm ls react` | 16.9.0 |
|     `npm --version` | 6.13.7 |
|    `node --version` | v13.9.0 |

| OS   | Version |
| ---- | ------- |
| macOS Catalina | 10.15.3 |

**Comment by andyliuzs** [comment]
I ’m like you, and found that this problem happened after the debug was turned off, did you solve it?

**Comment by duongkhoangiam** [comment]
i solved by add
```
import "intl";
import { Platform } from "react-native";
import "intl/locale-data/jsonp/en";

if (Platform.OS === "android") {
    // See https://github.com/expo/expo/issues/6536 for this issue.
    if (typeof (Intl as any).__disableRegExpRestore === "function") {
        (Intl as any).__disableRegExpRestore();
    }
}
```

in top of app page
can you read this in
https://github.com/expo/expo/issues/6536

**Comment by andyliuzs** [comment]
thunks

**Comment by andyliuzs** [comment]
thanks!

**Comment by simon-lund** [comment]
Hello,

I'm a bit late to the party, but I had the same error today and fixed it by changing the `jscFlavor` variable in my *android/app/build.gradle* to `def jscFlavor= 'org.webkit:android-jsc-intl:+'`

Worked like a charm.

**Comment by wardbeyens** [comment]
> Hello,
> 
> I'm a bit late to the party, but I had the same error today and fixed it by changing the `jscFlavor` variable in my _android/app/build.gradle_ to `def jscFlavor= 'org.webkit:android-jsc-intl:+'`
> 
> Worked like a charm.

This works, thanks!

**Comment by lucasbasquerotto** [comment]
I was able to solve issues of `react-intl` in Android using Expo (React Native) by using the Hermes Engine, defining:

```
"android": {
    ...
    "jsEngine": "hermes"
}
```

in `app.json` (https://docs.expo.dev/guides/using-hermes/).

I tried using `intl.js` but not only is the library deprecated, but it also gave lots of errors in certain cases like formating date and times (it was formatted wrong).
