### ISSUE TITLE
@formatjs/macro leads to incompatibility with create-react-app

### ISSUE THREAD

**Issue by chrisalbert** [formatjs/react-intl#1592]
### Expected behavior

It is possible to use react-intl with create-react-app without ejecting.

### Current behavior

Currently when running the tests they fail with the message:

`The macro imported from "@formatjs/macro" must be wrapped in "createMacro" which you can get from "babel-plugin-macros". Please refer to the documentation to see how to do this properly: https://github.com/kentcdodds/babel-plugin-macros/blob/master/other/docs/author.md#writing-a-macro`

### Steps to reproduce

1. Setup new CRA
2. Add react-intl and a test file using <IntlProvider>
3. Run tests

`babel-plugin-macros` added a `isMacrosName` option to override their macro RegEx in the babel configuration which is the only thing they can do on their end. Even if CRA would make the babel config somehow configurable (which I don't think they will) for only this option, it would require each CRA user to do this kind of setup when they choose to use react-intl.

Renaming @formatjs/macro is painful and would probably require a new major version, but it seems to me to be the solution that causes the least friction for the community.

I'm aware of #1511 , but I wanted to reopen the discussion of how to proceed. Our company uses cra + react-intl in many different teams and we are locked into version 3.4.0 currently, without being able to use the cool new features of >=3.5.0.

**Comment by arvinsim** [comment]
> I'm aware of #1511 , but I wanted to reopen the discussion of how to proceed. Our company uses cra + react-intl in many different teams and we are locked into version 3.4.0 currently, without being able to use the cool new features of >=3.5.0.

I am in `3.4.0` and I get this issue.

Not sure how to solve this since both [react-intl](https://github.com/formatjs/react-intl/issues/1511) and [babel-plugin-macros](https://github.com/kentcdodds/babel-plugin-macros/issues/131) are not doing anything with it.
