### ISSUE TITLE
error TS2694: Namespace 'Intl' has no exported member 'PluralRules'

### ISSUE THREAD

**Issue by Callenowy** [formatjs/react-intl#1593]
Hello, while running command: 
```
tsc -p . --target ES6 --module es6 --jsx preserve --outDir ./src/extracted
```
tsc throws an errors: 
<img width="1680" alt="obraz" src="https://user-images.githubusercontent.com/10743192/75594773-2884cd00-5a8a-11ea-99d7-743f6fdbcfcb.png">

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.12.0 |
|      `npm ls react` | 16.12.0 |
|     `npm --version` | 6.11.3 |
|    `node --version` | 11.9.0 |
|    `tsc -v` | 3.7.2|

| OS   | Version |
| ---- | ------- |
| macOS Catalina | 10.15.3 |

| Browser | Version |
| ------- | ------- |
| Firefox    | 72.0 |

tsconfig.json libs:
```
    "lib": [
      "es2017",
      "esnext.intl",
      "dom"
    ],
```

Regards,
Callenowy

**Comment by longlho** [comment]
you need `es2018.intl` or something of the like in your tsconfig
