### ISSUE TITLE
FormatMessage: ignores br tags

### ISSUE THREAD

**Issue by marcohamersma** [formatjs/react-intl#1597]
I'm trying to update from v3 to v4, and running into one issue with line breaks. One of the translation messages has line breaks in them, and for some reason they are not being replaced by the function in the component's `values` prop. Perhaps because they are self-closing?

### Expected behavior

Line breaks are replaced by the `<br/>` tags supplied in the values prop.

### Current behavior

It leaves the <br/> tags as plain text in the rendered output

### codesandbox.io link to reproduce for BUG REPORT

I've created this codeSandbox for reproduction: https://codesandbox.io/s/elated-neumann-ugsyr

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 4.1.1 |
|      `npm ls react` | 16.13.0 |
|     `npm --version` | 6.9.0 |
|    `node --version` | 10.16.0  |

| OS   | Version |
| ---- | ------- |
| Mac OS | 10.14.6 |

| Browser | Version |
| ------- | ------- |
| Firefox    | 74.0b9 |

**Comment by longlho** [comment]
You can change to:
```
import React from "react";
import { IntlProvider, FormattedMessage } from "react-intl";

const messages = {
  testMessage:
    "This is a <em>message</em>, and something went wrong{linebreak}{linebreak}Maybe try again?"
};

export default function App() {
  return (
    <IntlProvider locale="en" defaultLocale="en" messages={messages}>
      <FormattedMessage
        id="testMessage"
        defaultMessage="testMessage"
        values={{
          em: (...chunks) => <em>{chunks}</em>,
          linebreak: <br />
        }}
      />
    </IntlProvider>
  );
}
```
Per our release notes https://github.com/formatjs/react-intl/releases/tag/v4.0.0
> We don't allow formatting self-closing tags because we already use ICU {placeholder} syntax for that.

**Comment by webduvet** [comment]
what about thousands of existing messages provided by 3rd party? this should be reopened it looks like regression bug.
the only way how I was able to go around this is using `dangerouslySetInnerHTML` property.

**Comment by funkybob** [comment]
I've just run into this same issue, and see the same response given elsewhere, such as the rather dismissive locking of https://github.com/formatjs/formatjs/issues/1616

Why only support a sub-set of HTML?

Whilst the placeholder hack is fairly simple to implement, it does mean every dev team now has to explain to their translators a special case for <br />

Why force users to use the placeholder hack to work around this?

What was the developer rationale for omitting support for self-closing elements?

**Comment by jerlam06** [comment]
Many years later, it still makes NO SENSE, but devs still do not care...This is indeed a regression and not and an update.

**Comment by atracz-polcode** [comment]
It only seem to work when you put something like that in your translation
`<br></br>`

but for me it doesn't have any sense at all...

**Comment by garvae** [comment]
It's 2025 and this problem is still driving us crazy.
