### ISSUE TITLE
Recommended way to ensure that interpolated values are passed when calling `intl.formatMessage`

### ISSUE THREAD

**Issue by shirleymiao** [formatjs/react-intl#1600]
Hi there,

We're using react-intl in our Typescript codebase. 

When I define a MessageDescriptor (say, `someDescriptor`) using `defineMessages`, the `defaultMessage` frequently contains a value (say, `someNumber`) that will be interpolated. This value is passed at the call site of `intl.formatMessage(someDescriptor, { someNumber: value }`. 

Is there a recommended way to ensure that this call to `formatMessage` doesn't typecheck if `someNumber` isn't passed?

**Comment by longlho** [comment]
we have a linter for that https://www.npmjs.com/package/eslint-plugin-formatjs#enforce-placeholders
