### ISSUE TITLE
Generate IDs during component message extraction

### ISSUE THREAD

**Issue by donovanhiland** [formatjs/react-intl#1601]
**Is your feature request related to a problem? Please describe.**

We're trying to migrate a project away from another intl implementation to `react-intl`. Currently we _only_ use a default message without an ID and the ID is generated for us automatically. The migration would be much easier if either `defaultMessage` OR `ID` were required but not both (which is what I'm gathering from testing out the cli/babel plugin?

**Describe the solution you'd like**

There's a cli option to set how ids are generated for missing ids. I can't seem to find a scenerio where that happens. Being able to automatically generate ids for a message would help us out a ton.

Maybe there's something I'm missing and we should instead be using ids for something. If this is the case I'd love to know what the ids give us.

*Edit:* This only seems to be the case for the `<Formatted*` components. What's the purpose of requiring an id in that case?

**Comment by longlho** [comment]
We do have @formatjs/cli package that does that for you so take a look :)

**Comment by donovanhiland** [comment]
Maybe you can clarify, but this doesn't seem to be the case for `FormattedMessage`: https://github.com/formatjs/formatjs/blob/master/packages/babel-plugin-react-intl/src/index.ts#L430

If the component does not have an `id` and a `defaultMessage` it's not extracted.

**Comment by longlho** [comment]
ah we'll take a look at this issue soon thanks for reporting

**Comment by longlho** [comment]
fixed in latest babel-plugin-react-intl
