### ISSUE TITLE
Any polyfill for FormattedNumberParts ?

### ISSUE THREAD

**Issue by chawax** [formatjs/react-intl#1602]
Hi,

I try to use `FormattedNumberParts` with React Native on iOS simulator.
It works in debug mode, not release mode, so I guess I need a polyfill.
But I can't find any polyfill for `FormattedNumberParts`.

Any idea where I can find that ?

Thanks in advance.

**Comment by longlho** [comment]
Try our polyfill @formatjs/intl-unified-numberformat

**Comment by chawax** [comment]
It works, thanks a lot !
