### ISSUE TITLE
Simple get function for Translated Strings

### ISSUE THREAD

**Issue by BurakKartal1** [formatjs/react-intl#1603]
Redux is essential to most projects that use react. To be honest i never have seen any react project that doesnt use Redux. In saga files im returning a message to the reducer or using notification to show message about what is going on. How can someone localize these error/status messages ?

For Example:

````
import { all, call, fork, put, takeEvery } from 'redux-saga/effects';
// other necessary imports ...

function* getUserDetailData({ payload }) {
    try {
        const userData = yield call(getUserDetailDataAsync, payload);
        if(
            userData.status !== undefined &&
            userData.status === 200
        ) {
            if(userData.data.somethingImportant != 'what is expected') {
                        yield put(getUserDetailError('You forgot to do something...'));
            } else {
                        yield put(getUserDetailSuccess(userData.data, payload.selectedPageSize));
            }
        } else {
            yield put(getUserDetailError('Something went wrong, please try again.'));
        }
    } catch (error) {
        console.log('getUserDetailData Caught Error:  -->', error);
        yield put(getUserDetailError(error));
    }
}


export default function* rootSaga() {
    yield all([
        fork(watchgetUserDetail),
    ]);
}
````

I have seen some similar issues in this repo that requested this feature yet answers were very inconvenient workarounds in my opinion. #749 #1051

simple get function would be very usefull i think, i18n does this very simple.

Thanks.

**Comment by longlho** [comment]
We do have a creatIntl API that translate without React

**Comment by BurakKartal1** [comment]
creatIntl doesnt seem to be mentioned in either of those issues or in API Documentation.
https://github.com/formatjs/react-intl/blob/master/docs/API.md

Can you be more specific on how to implement it ? Very simple example would be usefull to alot of people i think. @longlho

**Comment by longlho** [comment]
https://github.com/formatjs/react-intl/blob/master/docs/API.md#createintl

**Comment by BurakKartal1** [comment]
This just requires for me to copy paste same codes all over my middlewares. In addition to that its not raw string.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String

When i say inconvenient i didnt meant this. If this feature implementation is unprofessional or for some reason is not going to be implemented. You can just tell me it wont. Instead of replying with docs link. @longlho

**Comment by longlho** [comment]
Not sure I understand what you mean, you'd create intl as a global object and use it wherever you want

```
const intl = createIntl({
  locale: 'fr-FR',
  messages: {}
}, cache)

// In your reducer, get a reference from the `intl` object
intl.formatMessage('A message')
```

**Comment by BurakKartal1** [comment]
For example:

/lang/index.js
````
import { addLocaleData } from 'react-intl';
import enLang from './entries/en-US';
import enRtlLang from './entries/en-US-rtl';

const AppLocale = {
    en: enLang,
    enrtl:enRtlLang
};
addLocaleData(AppLocale.en.data);
addLocaleData(AppLocale.enrtl.data);

export default AppLocale;
````

/src/App.js
````
import { IntlProvider } from 'react-intl';
import AppLocale from './lang';

    render() {
        const currentAppLocale = AppLocale[locale];
                <IntlProvider
                    locale={currentAppLocale.locale}
                    messages={currentAppLocale.messages}
                >
                    <React.Fragment>
................//

const mapStateToProps = ({ settings }) => {
    const { locale } = settings;
    return { locale };
};

export default connect(
    mapStateToProps,
    {}
)(App);
````

So i can change locale of App from only one point. For this to work in middlewares wouldnt it be necessary to pass the locale as paramater on all calls ? am i missing something ? @longlho

**Comment by longlho** [comment]
Hmm first of all you’re using v2 and we’re at v4 now. You can add a
middleware the produces a cached instance of the intl object per locale and
pass it along to the reducer

**Comment by BurakKartal1** [comment]
I think that would've caused performance issues in long run. Since im always gonna use localized error messages at user interface, and cases that handles errors in reducers are almost same i decided to use global action for all of my reducers for this problem. maybe its overkill but whatever at least redux is cleaner without notification boilerplate and better for performance i think.

/redux/actions.js
````
export const GENERAL_ERROR = "GENERAL_ERROR_";
````

/redux/general/actions.js
````
export const deliverErrorMessage = (reducer, errorObj) => ({
    type: GENERAL_ERROR+`${reducer}`,
    payload: { errorObj }
});
````

/redux/auth/reducer.js
````
case GENERAL_ERROR+'AUTH':
    const { errorObj } = action.payload;
    return {
        ...state,
        loading: false,
        error: {
            ...state.error,
            notificationType: errorObj.notificationType,
            intlTitle: errorObj.intlTitle,
            intlMessage: errorObj.intlMessage
        }
    };
````

/redux/auth/saga.js
````
yield put(deliverErrorMessage('AUTH', {
    notificationType: 'error',
    intlTitle: 'error.auth',
    intlMessage: 'general.server_error'
}));
````

finally, /some-component.js
````
    componentDidUpdate(prevProps) {
        const { error, intl } = this.props;
        if(
            prevProps.error !== error &&
            error.notificationType != null &&
            error.notificationType != ''
        ) {
            NotificationManager[[error.notificationType]](
                intl.messages[error.intlMessage],
                intl.messages[error.intlTitle]
            );
        }
    }
````
