### ISSUE TITLE
How to change the locale if using RawIntlProvider?

### ISSUE THREAD

**Issue by sangdth** [formatjs/react-intl#1607]
I've tried to dig this repo issues as well as next.js repo issue but seem can not find a good answer.

In short, I would like to let user changes the language while using the app.

I followed this example: https://github.com/zeit/next.js/blob/canary/examples/with-react-intl/server.js

**Comment by longlho** [comment]
Seems like you can do that here https://github.com/zeit/next.js/blob/canary/examples/with-react-intl/pages/_app.js#L10 and have state containing the `locale` & `messages`, and initially set it to the `__NEXT_DATA__` or something like that.

I'm not super familiar w/ next.js to give a great answer

**Comment by sangdth** [comment]
The locale and messages are generated from `server.js` and injected into the ctx object of Nextjs. If I want to have local state in the `_app.ts` then I have to declare it again, almost copy all the functions from server.ts, which raise a question, Why do they do that? Is there anyway like `intl.setLocale('...')`?

**Comment by longlho** [comment]
seems like their setup is for initial page load. IDK what their suggestions for SPA is. 
There's no `intl.setLocale` you just create a new intl object.

**Comment by sangdth** [comment]
Thank you, I will go with that option.
