### ISSUE TITLE
How to format self-closting tags now that FormattedHTMLMessage is gone?

### ISSUE THREAD

**Issue by joostdecock** [formatjs/react-intl#1616]
I am currently updating my app to v4 of react-intl, which means I'm going through my code to change every `FormattedHTMLMessage` to a `FormattedMessage` using the new structure.

That works fine for regular HTML tags. Eg: `this is an <b>important</b> word` is rendered as expected when I use:

```jsx
<FormattedMessage id="someId" values={{
  b: (...chunks) => <strong>{chunks}</strong>
}}/>
```

But I cannot seem to figure out how to get this to work for a self-closing tag. For example, `this really<br />needs a linebreak` does not seem to work when using:

```jsx
<FormattedMessage id="someOtherId" values={{
  br: (...chunks) => <br />
}}/>
```

# Expected behavior

Insert the `<br />` tag as *raw html*.

### Current behavior

The `<br />` in the source string is printed as regular text.

### codesandbox.io link to reproduce for BUG REPORT

https://codesandbox.io/s/solitary-tdd-9nkgz

### Your Environment

See codesandbox reproduction

**Comment by longlho** [comment]
You can write the string as `line{br}newline` and values as `br: <br/>`: https://codesandbox.io/s/damp-thunder-mxfd3

**Comment by joostdecock** [comment]
The question is: how can I used a string with `<br />` in it.
Sure, I can go and update all my translation, but that seems overkill.
Not to mention that now the source strings are valid html, and this would break that.

Surely there's gotta be a way. And if not, that's a bug.

**Comment by longlho** [comment]
That's why we bump major version. This is a breaking change. You can read our release note on the rationale: https://github.com/formatjs/react-intl/releases/tag/v4.0.0

**Comment by joostdecock** [comment]
> We don't allow formatting self-closing tags because we already use ICU {placeholder} syntax for that.

Wow.

**Comment by VladimirPittner** [comment]
So this is is? You expect people to change their data because you failed to implement self-closing tags and you call it breaking change? :D

This is an issue that should be fixed in my opinion.
