### ISSUE TITLE
dist of babel plugin broken just for 7.4.2

### ISSUE THREAD

**Issue by slorber** [formatjs/react-intl#1619]
Hi,

Something wrong has been published for babel plugin 7.4.2, there's a dist/src folder, the extra src folder breaks the main package.json field and makes the plugin unable to resolve by babel 

![image](https://user-images.githubusercontent.com/749374/79143600-cc69d400-7dbd-11ea-8fdd-3a0e0d57634b.png)

**Comment by pyrocat101** [comment]
Thanks for reporting. It is probably due to my misconfiguration. Let me deprecate this version on npm.

**Comment by pyrocat101** [comment]
Marked 7.4.2 as deprecated. For now please ping your dependency to v7.4.1.
We will follow up with a fix and some plan to avoid this incident in the future.

**Comment by longlho** [comment]
We've disted 7.4.3 in case the dep graph is broken
