### ISSUE TITLE
FormattedRelativeTime inside of FormattedMessage

### ISSUE THREAD

**Issue by gpinto67** [formatjs/react-intl#1621]
Not a bug, but a support question, since I can't find in the documentation how to include a FormattedRelativeTime inside a FormattedMessage.

I found this older issue (https://github.com/formatjs/react-intl/issues/370), but applying the same technique replacing FormattedRelative with FormattedRelativeTime does not work. I want to output a localized string that reads "Your trial will expire in 10 days".

I've tried:

```
<FormattedMessage
  id="MAIN.TRIAL_EXPIRY_RELATIVE_TIME_FUTURE"
  defaultMessage="Your trial will expire {futureExpiration}"
  values={ {
    futureExpiration: <FormattedRelativeTime
      value={ 10 }
      unit={ 'day' }
    />
  } }
/>
```
How do I accomplish this?
Thanks

**Comment by longlho** [comment]
that looks like it should work. Can you create a codesandbox.io to demo?

**Comment by gpinto67** [comment]
You are correct. It works in a simple environment as codesandbox.io:

https://codesandbox.io/s/epic-antonelli-u3yk9?file=/src/App.js

But not in my project, which uses Next.js for SSR. Need to dig in, on my side, see what is going on. Thanks.
