### ISSUE TITLE
documentation: code splitting + static type safety example

### ISSUE THREAD

**Issue by giogonzo** [formatjs/react-intl#1622]
It'd be great to have an example of how to achieve *static type safety* for translation keys (as in: you can only `formatMessage` valid translation keys, not any string, and you want to make sure that every language provides the same translation keys) and *by-language lazy-loading* (code splitting) with webpack.

I've recently bootstrapped a new project and, thanks to webpack and TS [dynamic imports](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html#dynamic-import-expressions) and the recent [import type](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#-type-only-imports-and-export) TS feature, these two objectives combined are now quite easy to obtain.

I'd be glad to submit an additional example showcasing the simplest possible setup to obtain such features, if it's something that you think might be of interest.

I've been using react-intl for years, but never used the babel plugin or the `defineMessage` API: I always define the complete set of messages in plain JSON files, so the example I'm proposing is only minor changes compared to what I was always used to do, but might be something that is not suggested by the maintainers.

---

contrived example:
```ts
// en.json
{
  "foo": "bar"
}

// it.json
{
  "foo": "baz"
}

// intlHelpers.ts
import type sourceOfTruth from "./en.json"; // import type ensures en messages aren't bundled by default
import { useIntl } from "react-intl"

export type LocaleMessages = typeof sourceOfTruth;
export type LocaleKey = keyof LocaleMessages;

export function useFormatMessage(): (
  id: LocaleKey, // only accepts valid keys, not any string
  values?: Record<string, string>
) => string {
  const intl = useIntl();
  return (id, values) => intl.formatMessage({ id }, values);
}

// return type here enforces all languages have the same translations defined
export function importMessages(locale: SupportedLocales): Promise<LocaleMessages> {
  switch (locale) {
    case "en":
      return import("./messages/en.json");
    case "it":
      return import("./messages/it.json");
  }
}

// component.tsx
export function Component() {
  return useFormatMessage("foo") // only valid keys can be passed here
}

// index.tsx
// ...
importMessages(locale).then(messages => (
  <IntlProvider locale={locale} messages={messages} key={locale}>
    <Component />
  </IntlProvider>
))
```

**Comment by JustFly1984** [comment]
```
import type sourceOfTruth from "./en.json";
```

works for us only with @babel/core@7.9.0 set in `resolutions` in package.json

**Comment by longlho** [comment]
yup we're definitely open to more examples in the project!

**Comment by giogonzo** [comment]
Created the PR above ^

@JustFly1984 thanks for pointing that out, I added a note to the example code

As a sidenote, in our project we are also enforcing that components only render correctly translated strings (and not plain `string`s), by redefining the React Children type that the components accept. But I left that out of the example since it's probably too much unless you are nazi like me 😛

**Comment by ganeshmahajan1985** [comment]
Hi guys,
I have implement this in my code successfully, 

1. Now I want to have language dropdown from where the user will switch to other language, how that can be achieved? Please guide me? 

2. Also, what if I want to keep the language selected by user so next time when he comes back he should see a page in his last time selected language?

Thanks

**Comment by ganeshmahajan1985** [comment]
I solved it, LocaleKey is the way to handle everything.

**Comment by giogonzo** [comment]
Hi @ganeshmahajan1985 , in my code base I have:
- the `SupportedLocales` type definition
- a parser to validate that unknown values are valid for the `SupportedLocales` type (e.g. to parse the browser preferred locale, or to parse the previously selected locale from localstorage)
- a list of values ti display dropdowns, etc. `Array<SupportedLocales>`

All of the above can be greatly simplified using [`io-ts`](https://github.com/gcanti/io-ts)
```ts
import * as t from 'io-ts'

// parser/codec definition using io-ts:
const SupportedLocales = t.keyof({ en: true, it: true })

// type derivation - using io-ts it is always in sync with the codec
type SupportedLocales = t.TypeOf<typeof SupportedLocales> // 'en' | 'it'

// list of values derivation - using io-ts it is always in sync with the codec
const supportedLocales = Object.keys(SupportedLocales.keys) as Array<SupportedLocales>  // ['en', 'it']
```
but any other way would work too

**Comment by ganeshmahajan1985** [comment]
@giogonzo thank you very much for your reply, much appreciated. 
Yes, I figured out how can I handle it in my application. :)
