### ISSUE TITLE
Locale-specific number abbreviations

### ISSUE THREAD

**Issue by niklaskorz** [formatjs/react-intl#1625]
For certain numbers, like `12,500,000`, there are abbreviations like `12.5 million` or `12.5 MM`. Certain websites use these for counters where the magnitude is more important than the precise value. For example, `12,500,100` would be abbreviated to `12.5 million` as well.
Depending on the locale, this might change to something like "crore" (unit for 10 millions) or "lakh" (unit for hundred thousands). https://en.wikipedia.org/wiki/Crore
Does something like this exist for `<FormatNumber />` or in the browser's `Intl` API?

**Comment by longlho** [comment]
Yes but you'd need a polyfill: https://github.com/formatjs/react-intl/blob/master/docs/Getting-Started.md#stage-3-intl-features (It's called unified numberformat)
