### ISSUE TITLE
Currency Format not showing accurate only for Spanish and Canada

### ISSUE THREAD

**Issue by AbhijeetGaware** [formatjs/react-intl#1627]
### Expected behavior
when I pass value 1234.56 for converting into Euro Spanish it should give result into 1.234,56.
and for en-CA 1234.56

### Current behavior
and we are getting 1234,56   -Spanish (spain)
and we are getting 1,234.56 - English(Canada)en-CA

<FormattedNumber currency ={"EUR"}

        value={123456}

        style={"currency"}

        />

### Your Environment
|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | @4.5.0 |
|      `npm ls react` | @16.13.1 |
|     `npm --version` | 6.13.4 |
|    `node --version` | v12.16.1 |

| Windows 10 | 1607 |

| Browser | Version |
| ------- | ------- |
| NAME    | VERSION |

| Chrome | 80.0.3987.163 |

-->

**Comment by longlho** [comment]
This seems to be a Chrome issue and not specific to us.
```
new Intl.NumberFormat('es-ES', {style: 'currency', currency: 'EUR'}).format(1234.56)
"1234,56 €"
```
So you can submit a bug to chromium :)

**Comment by amore4193** [comment]
same issue I am facing for es-ES browser locale. so in which chrome version this formattedNumber functionality is working fine for all browser locale.?

**Comment by longlho** [comment]
Our library sits on top of native Intl APIs so these issues are all browser issues effectively. I'm not sure if it works in any version tbh.
