### ISSUE TITLE
Trailing dot for currency in denmark

### ISSUE THREAD

**Issue by JacobEkedahl** [formatjs/react-intl#1628]
### Expected behavior
Value = 2800
currency = DKK
locale = da
Example: 2.800 kr

### Current behavior
Example: 2.800 kr.

### codesandbox.io link to reproduce for BUG REPORT
      <IntlProvider locale="da">
          <FormattedNumber
            value={2800}
            style="currency"
            currency="DKK"
            minimumFractionDigits={0}
            maximumFractionDigits={0}
          />
      </IntlProvider>

### Your Environment
Windows 10, chrome browser
"react-intl": "4.4.0",

**Comment by ghostd** [comment]
Hi,

This does not seems to be a bug of react-intl, it seems rather be a Chrome bug. To check you can type this into the Chrome console:
```js
new Intl.NumberFormat('da', {style: 'currency', currency: 'DKK'}).format(1234.56)
```

react-intl "simply" uses the native API of the browsers.

Regards

**Comment by longlho** [comment]
yup that's correct this is a browser issue actually
