### ISSUE TITLE
Chrome rendering incorrect LastResort font for Japanese when lang attribute is missing

### ISSUE THREAD

**Issue by lookitsatravis** [formatjs/react-intl#321]
I'm not sure how best to provide information on this issue. I looked through the open/closed issues and couldn't find anything that matched by keyword. Apologies if this is a duplicate.

We are using 2.0.0-beta2 and switching content between English and Japanese. On my colleague's browser (Canary), it works fine. But, on my own machine (Chrome 48), the rendering for Japanese is incorrect and Chrome uses it's fallback font LastResort. My example is the FormatJS.io home page because this issue happens there, too.

The example at the top looks like this when I select "ja-JP".

<img width="877" alt="screen shot 2016-02-17 at 17 09 47" src="https://cloud.githubusercontent.com/assets/606978/13128168/8a26ea22-d599-11e5-96ef-03ed2ebcd6d2.png">

And here is the rendered element:

``` html
<span data-reactid=".6mthfcomio.1.0.$=1${&quot;currentLocale&quot;=02&quot;ja-JP&quot;,&quot;currentNumPhotos&quot;=021000}" class="">Annieは2016年2月17日に1,000枚写真を撮りました。
</span>
```

In order to fix this, I have to add the `lang` attribute to the element. So...

``` html
<span data-reactid=".6mthfcomio.1.0.$=1${&quot;currentLocale&quot;=02&quot;ja-JP&quot;,&quot;currentNumPhotos&quot;=021000}" class="" lang="ja">Annieは2016年2月17日に1,000枚写真を撮りました。
</span>
```

Appears like:

<img width="822" alt="screen shot 2016-02-17 at 17 13 21" src="https://cloud.githubusercontent.com/assets/606978/13128210/c65f1848-d599-11e5-857d-fc6895a1bdaf.png">

We solved it with a side effect in our reducer (gasp) which sets `document.documentElement.lang` to the current locale. This allows it to render properly when the language is changed. I'm opening this issue because I'm not sure if this is a config problem on my Chrome installation, or if this is a legitimate issue which needs to be addressed. I tried this after disabling all of my extensions, and it still happens. I'm not sure what else to try.

Happy to provide more info as necessary.

**Comment by ericf** [comment]
> Happy to provide more info as necessary.

Thanks for providing this info, and sure provide more. I can plan to add some details to the docs.

**Comment by lookitsatravis** [comment]
Thanks!

In addition to setting the `lang` attribute on the individual element, or on the document's `html` element, I also found that adding/updating `Content-Language` meta tag had the same affect of fixing the incorrectly rendering fonts.

```html
...
  <head>
    <meta http-equiv="Content-Language" content="ja">
  </head>
...
```

**Comment by ericf** [comment]
@lookitsatravis was the response sent with `Content-Encoding: UTF-8` or `chunked`?

**Comment by lookitsatravis** [comment]
@ericf On my project, I get `Content-Encoding: gzip`. I also checked the formatjs.io index since that was used in my example above, and it is sent the same way.

**Comment by ericf** [comment]
Sorry, I meant:
```
Content-Type: text/html; charset=utf-8
```

**Comment by lookitsatravis** [comment]
Ah yes, `Content-Type: text/html; charset=utf-8` is in sent with the response in each case where I checked.
