### ISSUE TITLE
Parsing ICU templates issue

### ISSUE THREAD

**Issue by denova** [formatjs/react-intl#407]
Hello guys!

It seems to me that template parser works wrong sometimes.

[Here](https://github.com/denova/react-intl/blob/parsing-template-issue-1/examples/nested/src/client/components/widgets/greeting.js#L10) I made five cases based on 'Nested' example with following five template messages:
1. `'{holiday, select, empty {} other {I have a holiday on {holiday}}}'` where `holiday` is `'empty'`
2. `'{holiday, select, empty {Random String} other {I have a holiday on {holiday}}}'` where `holiday` is `'empty'`
3. `'{holiday, select, empty {} other {I have a holiday on {holiday}}}'` where `holiday` is `'Monday'`
4. `' {holiday, select, empty {} other {I have a holiday on {holiday}}}'` where `holiday` is `'empty'`
5. `' {holiday, select, empty {} other {I have a holiday on {holiday}}}'` where `holiday` is `'Monday'`

The result looks like following:

![64527917ee](https://cloud.githubusercontent.com/assets/1096682/14465014/fa3c36da-00d9-11e6-8041-4c3b0d1a7005.png)

When there is nothing in output braces [1] template is not rendered. Spaces cannot help here as well. If there is something in braces [2] it works. Also it works if some character is added before the braces (like first space character in template 4).

For me following workaround works well:
`'{holiday, select, empty {{emptyString}} other {I have a holiday on {holiday}}}'` where `holiday` is `'empty'`, `emptyString` is `<b></b>`.

Is this a bug or am I missing something? Thanks.

**Comment by ericf** [comment]
Seems likely to be a bug.

It's likely that the `intl-messageformat` package isn't properly handling this case. Here's the AST from the first message:
```json
{
  "type": "messageFormatPattern",
  "elements": [
    {
      "type": "argumentElement",
      "id": "holiday",
      "format": {
        "type": "selectFormat",
        "options": [
          {
            "type": "optionalFormatPattern",
            "selector": "empty",
            "value": {
              "type": "messageFormatPattern",
              "elements": []
            }
          },
          {
            "type": "optionalFormatPattern",
            "selector": "other",
            "value": {
              "type": "messageFormatPattern",
              "elements": [
                {
                  "type": "messageTextElement",
                  "value": "I have a holiday on "
                },
                {
                  "type": "argumentElement",
                  "id": "holiday",
                  "format": null
                }
              ]
            }
          }
        ]
      }
    }
  ]
}
```

**Comment by ericf** [comment]
I think the best place to start is opening a PR against this file with a filing test case using your example message that isn't working right:
https://github.com/yahoo/intl-messageformat/blob/master/tests/index.js

**Comment by ericf** [comment]
I dug into this more and see what's going on. This comes down to an interesting design question. What's happening is React Intl's message formatting considers an empty string as a problem for the user and prefers to display something…in this case the message source string.

Basically, we want to avoid situations like this:
```html
<button></button>
```

Where the content is missing because it's an empty string. Is there any reason why you don't conditionally format the message _if_ you have a value, instead of formatting to an empty string?

**Comment by ghostd** [comment]
@ericf Not sure it's the responsibility of React Intl to check whether the string is empty or not. I think it's a developer/tester responsibility to provide the finest experience to the final user.
