### ISSUE TITLE
Server/Client time correctness

### ISSUE THREAD

**Issue by Rendez** [formatjs/react-intl#443]
Many Windows users do not sync their OS clocks as do OSX users autom. Very often Relative times will render time differences that are too big for a good User Experience...

A quick example of a random UI rendering/data flow:

`Date.now()` -> generates -> `Message sent 1 second ago` -> Server responds > `{created_at: <Date>}` -> React UI refreshes value -> `Message sent 35 seconds ago` (respond took 2 secs).

Not long ago `initialNow` was introduced, would it make sense to add something like `serverNow`?

**Comment by ericf** [comment]
The main reason for `initialNow` is to make sure `<FormattedRelative>` is always rending as a function of props+state, and not a side-effect like the current time. Stabilizing "now" for the initial render on the client also ensures there's no React checksum error for isomorphic/universal React apps.

In your example which one do you think should be displayed? The client's calculation of "35 seconds ago" or the server's time of "3 seconds ago"?

**Comment by Rendez** [comment]
Thanks for taggin' this correctly. So agreed `initialNow` is something different.

> which one do you think should be the correct answer if you ignore the initial render? The client's calculation of "35 seconds ago" or the server's time of "3 seconds ago"?

So obviously 35 seconds ago, but my point here is that React-Intl could take care of client's erroneous (according to development) calculation in concordance with a server/service with a synchronized clock.

One answer could be that this time diff should be calculated outside the scope of React-Intl. One would probably be right. I am not sure at which point in the start-up time of an app would be useful to pass the timediff (custom value) to the ReactIntl provider so that future calculations are corrected for out-dated clients...

**Comment by Rendez** [comment]
My team and I thought that is often the case when data arrives to the client, to receive the "Date" header from the HTTP server (say after fetching JSON), from which one could determine the time diff (and initially done via assignment backend-to-javascript variable). It wouldn't require an extra call to the server. This could be passed dynamically. For the initial diff

**Comment by ericf** [comment]
> So obviously 35 seconds ago, but my point here is that React-Intl could take care of client's erroneous (according to development) calculation in concordance with a server/service with a synchronized clock.

I'm confused now. I thought you were saying that the client's calculation of "35 seconds ago" is _wrong_ because its clock is off and it should be "3 seconds ago" which is what the server would compute it as.

**Comment by Rendez** [comment]
That's right.

**Comment by Rendez** [comment]
The solution reflected in this answer could be a good one. http://stackoverflow.com/a/19629658

**Comment by longlho** [comment]
fixed via #1327
