### ISSUE TITLE
Inlining translations as a build step

### ISSUE THREAD

**Issue by leoasis** [formatjs/react-intl#455]
Hi there! We are analyzing options for internationalizing our app, and we're heavily considering using react intl because of the completeness and support for most of the i18n and localization use cases.

However, I was wondering if there was some way to achieve some production optimizations, if they make sense, and if so, if they are feasible to be done somehow using react-intl.

Basically what we would like to do is to have a build step, probably only for prod, that would replace all the calls to `FormattedMessage` and also `IntlMessageFormat` for non react strings, with the localized string already inlined (looked up in the translations file for the proper locale, which would be a bundle parameter, or an env variable or something). That is, if the string has no interpolation values, it'd just inline in the file the string as it is, and if it contained values, generate the string with `+` if in a non react context, or if it is, probably by rendering children inside a `<span>` element, with proper JSX interpolation, for example:

``` js
<FormattedMessage id="TITLE" defaultMessage="Hello World" />
// is transformed at bundle time to:
<span>Hello World</span>
```

``` js
<FormattedMessage id="TITLE" defaultMessage="Hello {who}" values={{who: this.props.who}} />
// is transformed at bundle time to:
<span>Hello {this.props.who}</span>
```

The idea is to generate a bundle per locale, and avoid lookups as much as possible, inlining as much as we can. Localization info for dates and numbers would probably still be done the same way by providing localeData directly.

Regarding gender stuff, with the `select` message format, it would probably be possible to inline a function that switches over the count and returns the message depending on each possible value, with the inlined translation text for each possible case.

I haven't seen anything (a babel plugin probably) yet implemented, but just wanted to see if there were plans to doing this, if it is interesting enough, and if there are any caveats or potential issues somebody sees about this approach. Most importantly, if it's worth doing.

Thanks for reading, and hope this is not entirely nonsense!

**Comment by ericf** [comment]
There isn't anything that I'm aware of that would do this inlining. It would have to be something that you'd have to write. A hard, common one would be plurals which would still require a pluralization function generated from CLDR data — which React Intl supplies in its locale data.

I wrote a Babel plugin to extract the default messages, but it doesn't do anything to inline them: https://github.com/yahoo/babel-plugin-react-intl

In your example would you be taking a translated message, then parsing it to split it apart, and fill in the placeholders with references to the corresponding RHS expression?

I'm also curious about your concerns related to perf. What numbers are you seeing with the current approach, and where do you want to get to? Also is this on the client, server, or both?

One feature you'll be opting out of is hot-swapping locales in the client. Many people have open issues asking how to do this, so I know it's somewhat of a popular thing to do. You'd need to resort to a full page reload if you had a feature like this.

In terms of future direction. I think we'd more more likely to towards something like this:
```js
<FormattedMessage id="greeting">
    Hello {this.props.who}
</FormattedMessage>
```

Which would be _extracted_ to:
```
Hello {0}
```
And transformed to:
```js
<FormattedMessage 
    id="greeting"
    defaultMessage="Hello {0}"
    values={[this.props.who]}
/>
```

So it's interesting that you're wanting to do the reverse…

**Comment by leoasis** [comment]
Hey! Thanks for the response.

I looked at the babel plugin you created, and that's really handy to extract the keys in order to generate the files for other languages. The idea I'm talking about is, given those files already exist, in production, inline the strings by doing the lookups in those files at _build time_.

So the idea is to keep having the babel plugin you created, and also have another one to do this inlining.
Regarding pluralization, not sure how that works, but I think it could fallback to just doing what react-intl does at execution time if it doesn't understand how to perform the lookup at build time.

> In your example would you be taking a translated message, then parsing it to split it apart, and fill in the placeholders with references to the corresponding RHS expression?

Basically yes, the idea is to generate an inline version that would avoid all the indirection of having i18n in the first place, because the idea is to have a bundled file that just supports one locale.

> I'm also curious about your concerns related to perf. What numbers are you seeing with the current approach, and where do you want to get to? Also is this on the client, server, or both?

Honestly I don't have any numbers to back the idea, BUT I'm seeing sites like Facebook have this feature as well, I looked at the bundled source code and they have the translations inlined in there. Also [this webpack plugin](https://github.com/webpack/i18n-webpack-plugin) caught my attention.

I know this optimization may not be necessary for most apps, but if this could be done as a performance optimization (like the babel plugin that hoist react elements), we can avoid dynamic things that in some use cases are static. Which brings me to:

> One feature you'll be opting out of is hot-swapping locales in the client.

I don't think this is a _very_ useful feature, at least in most cases. Users just stick with a language and mostly never change it, and if they do, they don't do that often, so it is not a concern that they have to download another bundle of JS, if that's going to make it a little bit more performant after that for the rest of the site usage. I can imagine quite a lot less things being calculated over and over especially in pages with a lot of content that is translated.

Anyway, again, don't have any numbers, but was curious that Facebook was inlining and I also saw that webpack plugin. Will explore a little bit with the approach, and see if I can bring some numbers to the discussion. Wanted to open the issue anyway since this has a lot of reach and it could bring people that may have a thing to say regarding this approach.

**Comment by ericf** [comment]
Inlining will indeed help perf. It seems like you're only looking to inline message strings, is that correct?

I'm curious what you think about flipping around the authoring in my example above: https://github.com/yahoo/react-intl/issues/455#issuecomment-218282929. This direction would still be compatible with inlining (maybe even make it easier?), while creating a more natural authoring environment.

If you're planning on doing server-rendering would you leave the `<FormattedMessage>` instances in-tact, or would you run different code on the server per locale?

**Comment by leoasis** [comment]
> It seems like you're only looking to inline message strings, is that correct?

Yes, that's the idea mainly. Probably could also be useful for, say, number or dates formatting as well, I think it could also be done.

Regarding the direction `FormattedMessage` is going, yeah, I think that still allows inlining, and indeed probably make things easier. Anyway in that formatting, same question you made me: How will that handle pluralization and select? Probably using some helper functions? BTW I'm using `defineMessages` and I really like how that allows to colocate messages in the same file, while having them grouped to quickly see which and how many translations I have in the file. I think it'd be good to still support it if the other way is going to be added (guess it'd stop being an identity fn and would transform `defaultMessage` to `children`, or still allow the `defaultMessage` prop in the component?)

> If you're planning on doing server-rendering would you leave the <FormattedMessage> instances in-tact, or would you run different code on the server per locale?

In my current use case, we have different server instances handling a single locale each, so it would be possible to just do the inlining on the server too. But for other use cases, I think it'd be just fine to do lookup there and inline in the client. There'd be a problem with the checksum though if we do different things in client and server... Haven't thought about how to solve that. Perhaps doing something similar to inlining, but still doing the lookup as a JS function, that doesn't create the component so that the checksum can still be the same? That's a good question though 😛.

**Comment by hjylewis** [comment]
Hi all! ✌️

I came up with a [solution](https://github.com/hjylewis/babel-plugin-inline-i18n-messages) that would inline your localized messages for all the reasons you've already listed out and more. See [this](https://github.com/hjylewis/babel-plugin-inline-i18n-messages#Motivation) for more info on the motivation for it.

Check it out here: [babel-plugin-inline-i18n-messages](https://github.com/hjylewis/babel-plugin-inline-i18n-messages)

This idea would it would inline the messages like this:
```javascript
<FormattedMessage id="key.path.hello" />
<FormattedMessage id="key.path.sup" />

      ↓ ↓ ↓ ↓ ↓ ↓

import { addMessages } from "i18n/addMessages.js";
addMessages([
  ["key.path.hello", "hello, world"],
  ["key.path.sup", "sup, world"],
]);
<FormattedMessage id="key.path.hello" />
<FormattedMessage id="key.path.sup" />
```

It plays very nicely with `react-intl`. [Here's an example](https://github.com/hjylewis/babel-plugin-inline-i18n-messages/tree/master/examples/react-intl)

I'd appreciate you all checking it out and letting me know if it solves your inlining issues 🙇 

cc @leoasis

**Comment by dincozdemir** [comment]
[leoasis](https://github.com/leoasis) I am looking for this exact feature! Have you achieved this?

**Comment by psalv** [comment]
Hey, we developed a babel plugin for formatjs to do this!

[You can check out the article we wrote about it here](https://craft.faire.com/reducing-web-bundle-burden-by-code-splitting-translations-96d9ca7dc1f1), or check out the plugin itself here: https://github.com/Faire/babel-plugin-formatjs-localized-bundle
