### ISSUE TITLE
How to define localization with defineMessages method?

### ISSUE THREAD

**Issue by furydam** [formatjs/react-intl#463]
I want to localize my component. I use yahoo/react-intl lib. I define some messages

```
const messages = defineMessages({
    greeting: {
        id: 'app.home.greeting',
        description: 'Message to greet the user.',
        defaultMessage: 'Hello!'
    },
  });

```

I don't know how to define a localizable text for message so I got this error

```
app.js:27785[React Intl] Missing message: "app.home.greeting" for locale: "nl", using default message as fallback.
```

Example of using

```
<input type="text" {...firstName} placeholder={intl.formatMessage(messages.greeting)} />
Does anyone know how to define localized messages?
```

Thanks in advance.

**Comment by jardakotesovec** [comment]
@vdzundza You need to pass translated messages to `IntlProvider`

 ```<IntlProvider messages={translatedMessages}/>```

Here is [example](https://github.com/yahoo/react-intl/wiki#creating-an-i18n-context). Does it help?

**Comment by ericf** [comment]
`defineMessages` helps you co-locate the string messages for your _default language_ so that they can be extracted via `babel-plugin-react-intl`. https://github.com/yahoo/react-intl/wiki/API#definemessages

As @jardakotesovec mentioned, translations like your `nl` messages, should be passed into `<IntlProvider>` at runtime.

I've received this question serveral times recently, so I'll leave this open as a docs issue…

**Comment by chapati23** [comment]
so it is *not* possible to add translations locally within a component?

we try to heavily enforce self-containedness for our components so what i'm trying to achieve is this kind of file-structure:

```
|- app.js
|- components/
|--- ComponentA/
|------ index.js
|------ index.spec.js
|------ styles.css
|------ translations/
|-------- en.json
|-------- de.json
|-------- es.json
```

now how I first thought `addLocaleData` would work is that i could pass it additional messages to append to the given locale. but as far as i could see, that's not the case, right?

can the approach above be achieved with the current react-intl or do you HAVE to pass in the translations at root-level?

P.S. I guess the alternative would be to wrap all of our components into `<IntlProvider />` which I would consider DRY exactly…

**Comment by ericf** [comment]
> so it is not possible to add translations locally within a component?

If by _translations_ you mean your app's default language is in English and you want to include English, Spanish, and German strings all together within the component, then no, that's not really how this library is designed. There's an assumption made that your localizers aren't your programmers.

If you meant _translations_ == your app's default strings, say English, then yes.

> now how I first thought addLocaleData would work is that i could pass it additional messages to append to the given locale. but as far as i could see, that's not the case, right?

[`addLocaleData`](https://github.com/yahoo/react-intl/wiki#locale-data-in-browsers) is used to provide React Intl with the data _the library_ needs to perform its formatting functions — you would think of it similar to polyfilling the runtime. Any data locale configuration or data (i.e. translated strings) specific to your app are provided via [`<IntlProvider>`](https://github.com/yahoo/react-intl/wiki/Components#intl-provider-component).

> can the approach above be achieved with the current react-intl or do you HAVE to pass in the translations at root-level?
> 
> P.S. I guess the alternative would be to wrap all of our components into <IntlProvider /> which I would consider DRY exactly…

This pattern of nested `<IntlProvider>` components is supported, there's even an [example app](https://github.com/yahoo/react-intl/tree/master/examples/nested).

But why can't you just aggregate all of your `translation/*.json` files per language into one collection which you feed in at the root?

Either pattern is supported, having a single `<IntlProvider>` at the root that's feed the aggregated collection of translations is simpler, but for more advanced apps using lazy-loaded components, etc. you can use the nested `<IntlProvider>` approach — that's what we use at Yahoo.

**Comment by chapati23** [comment]
thanks for the quick reply.

**1) Reasoning for separate language-files**
A couple of our components will be used in other applications so it'd be nice if we could just `npm install component-xyz` and be up and running with translations included.

Having one global `translations/*.json` would require us to cherry-pick the relevant translations out and manually copy-and-paste them to the new app.

**2) Achieving localized translations pattern with current API**
Would this work:
- Use `defineMessages()` within components to define ids & default messages
- Let [babel-plugin-react-intl](https://github.com/yahoo/babel-plugin-react-intl) extract all `defineMessages()` it can find into a translations-folder
- Use this generated translations-folder's json-files to pass in to our root `<IntlProvider>`

**Comment by ericf** [comment]
> Having one global `translations/*.json`

It can be a build artifact, it doesn't have to be checked-in to Git.

----

I'm not sure I understand what you're asking now.

**Comment by chapati23** [comment]
by build artifact, you mean a script that bundles all translation-files generated by `babel-plugin-react-intl` together like [this one](https://github.com/yahoo/react-intl/issues/251#issuecomment-165863247)?

---
re: understanding my issue. i'm basically looking for a tradeoff where I can at least define the messages locally (via `defineMessages`) and then translate inside the generated global files. for example, if i had 4 files (pseudo-code):

```javascript
// /translations/en.js
export default const en = {
  'header.title': 'A nice header'
}
```

```javascript
// /translations/i18n.js
export en from './en.json'
export de from './de.json'
…
```
```javascript
// /components/App.js
…
import * as generatedMessages from '../translations/i18n'
…
class App extends Component {
…
<IntlProvider locale={userLocale} messages={generatedMessages[userLocale]} />
  <main>
    <HeaderComponent />
    {this.props.children}
  </main>
</IntlProvider>
…
}
```

```javascript
// /components/Header/index.js
…
const componentMessages = defineMessages({
  headerTitle: {
    id: 'header.title',
    defaultMessage: 'A nice default message'
})
…
class Header extends Component {
  render() {
      <header>
        <FormatMessage {...componentMessages.headerTitle} />
      </header>
  }
```
using `babel-plugin-react-intl` i'd have all my messages automatically exported into an arbitrary directory and could hand over this directory to translators, would this approach work? or am I totally misunderstanding the purpose of `defineMessages`?

**Comment by ericf** [comment]
> by build artifact, you mean a script that bundles all translation-files generated by babel-plugin-react-intl together like this one?

I mean a file derived as part of the build process; e.g., Babel takes files from `src/` and outputs build artifacts into `build/`.

> i'd have all my messages automatically exported into an arbitrary directory and could hand over this directory to translators, would this approach work?

Yes, you'd have a directory with the same structure as your source directory but instead of containing `.js` files, it would contain a `.json` file for every `.js` source which which defined default messages that `babel-plugin-react-intl` extracted. You'd likely want to then process this directory to either merge all of these `.json` files into one, or some other organizational process before passing along the directory to your translators.

**Comment by chapati23** [comment]
ok. i've taken the above approach and it works. what i don't like about this solution, though, is that my `en.json` is now basically a build artifact (because i'm just using the `defaultMessages` for english) and doesn't need to be under version control but other locales can't be generated because i would lose previous translations when the scripts overwrites for example `es.json`)

```
|-i18n/
|---definitions/ <= bundling results of babel-plugin-react-intl
|---translations/
|------en.json <= generated by [your bundle script](https://github.com/yahoo/react-intl/issues/251#issuecomment-165863247)
|-----es.json <= can't be generated because i would lost previous translations
```

how do you typically update `es.json` (or any other locale than the default) with new messages and translations?

**Comment by oscar-b** [comment]
@chapati23 Have you seen this: https://www.npmjs.com/package/react-intl-translations-manager

**Comment by natterstefan** [comment]
Hi @oscar-b, thanks for the link. Can you please elaborate how to use this package to achieve having multiple translation *.json's (see comment https://github.com/yahoo/react-intl/issues/463#issuecomment-228989785) in more detail? This would be very helpful to me. Thank you.
