### ISSUE TITLE
Rich text formatting and translations

### ISSUE THREAD

**Issue by geekyme** [formatjs/react-intl#513]
## Issue

Say i have a string: 

```
To buy a shoe, 
<a class="external_link" target="_blank" href="https://www.shoe.com/">visit our website</a>
and
<strong class="important">eat a shoe</strong>
```

According to https://github.com/yahoo/react-intl/wiki/Components#formattedmessage, I need to format my text this way: 

```
<FormattedMessage
    defaultMessage='To buy a shoe, { link } and { cta }'
    values={{
        link: <a class="external_link" target="_blank" href="https://www.shoe.com/">visit our website</a>,
        cta: <strong class="important">eat a shoe</strong>
    }}
/>
```

When doing string extraction with https://github.com/yahoo/babel-plugin-react-intl, I would get:

 `To buy a shoe, { link } and { cta }` to be translated. 

This isn't good because I lose the context and texts from the rich content for `link` and `cta`. 
## Suggestion

I think we should have some special delimiters to surround rich text content so translators can still translate the text as a whole:

`To buy a shoe, @visit our website@ and @eat a shoe@`

Thoughts?

**Comment by ericf** [comment]
@geekyme can you explain more how this would work?

**Comment by geekyme** [comment]
What I have in mind is `FormattedMessage` should look at the string presented in `defaultMessage`, and if it finds an opening and closing `@`, it takes the contents between them and look up a list of rich markups and interpolate the text inside the markup. 

Eg. `visit our website` gets interpolated between `<a class="external_link" target="_blank" href="https://www.shoe.com/"></a>`. This can be done using `React.cloneElement` then providing the text as children. Same thing for `eat a shoe`

```
<FormattedMessage
    defaultMessage='To buy a shoe, @visit our website@ and @eat a shoe@'
   interpolate={[
       <a class="external_link" target="_blank" href="https://www.shoe.com/"></a>,
       <strong class="important">eat a shoe</strong>
   ]}
/>
```

**Comment by ericf** [comment]
This sounds related to: https://github.com/yahoo/react-intl/issues/455#issuecomment-218282929

Trying to make your example work can quickly break down, imagine if someone had:
```html
<strong>eat a <em>shoe</em></strong>
```

**Comment by azmenak** [comment]
Came across a similar problem today, maybe there's a better way to do this that I'm not seeing at the moment.

If I want to "format" links in a message, the only option I see right now is passing an additional `<FormattedMessage />` in the `values` of the parent. IE.

```jsx
<FormattedMessage
  id="messageTextId"
  defaultMessage="Hello {name}, please go visit {link}"
  values={{
    name: <strong>{this.props.name}</strong>,
    link: (
      <Link to="/visit-me">
        <FormattedMessage
          id="messageTextID.linkText"
          defaultMessage="translated link title"
        />
      </Link>
    ),
  }}
/>
```

This works, but its quite a bit to add for each link inside a message (we have a lot of them). Maybe @ericf or someone else can shed some light on a better solution for this?

I kind of imagined defining a custom format for messages IE.

```jsx
<FormattedMessage
  defaultMessage="Hello {name}, please go visit {linkKey, link, {href}}."
  values={{
    name: this.props.name,
    linkKey: "Text inside the link",
    href: "/some-page",
  }}
/>
```

but AFAIK, you can't define a custom format which isn't a number, date, or time.

**Comment by thelamborghinistory** [comment]
I am also currently running into this. I like the idea of nested placeholders like
```javascript
<FormattedMessage
  defaultMessage="Hello {name}, please go visit {somekey(Text inside the link)}."
  values={{
    name: this.props.name,
    somekey: <Link to="/some-page">{someArbitraryPlaceholder}</Link>,
    href: "/some-page",
  }}
/>
```

Even if it looks complicated, I think this would simplify the creation of natural messages files, where you wouldn't have to rip the link text out of the context of the parent message.

**Comment by kamilio** [comment]
I needed some simple formatting in my messages so I just run it through markdown.

```
import React, { Component, PropTypes } from 'react';
import Markdown from 'react-remarkable';

class FormattedMessageMarkdown extends Component {
    render() {
        const { formatMessage } = this.context.intl;
        const { id, defaultMessage, values, description } = this.props;
        const messageDescriptor = { id, defaultMessage, values, description };
        const message = formatMessage(messageDescriptor);
        return (<Markdown source={message}/>);
    }
}

FormattedMessageMarkdown.contextTypes = {
    intl: PropTypes.object.isRequired
};

export default FormattedMessageMarkdown;
```

Works pretty well, highly recommended.

**Comment by ptomasroos** [comment]
Thats pretty epic @ericf !

**Comment by esquevin** [comment]
I'd love for react intl to support your syntax

```
<FormattedMessage [id] [values]>
     defaultMessage
</FormattedMessage>
```

Internally we have implemented something similar but a less advanced that already allows us to do:

```
const messages = defineMessages({
  main: {
    id: 'forbidden_text__link',
    defaultMessage: "You're not authorized to access this page.\n" +
                    'Please contact your admin or <Link>go back to homepage</Link>.',
  }
});

// [...]

<FormattedReact
        {...messages.main}
        components={{ Link: props => <Link to="/" {...props} /> }}
/>
```

It's a use case that should be natively handled by react intl and I can't wait for what you proposed to be released

**Comment by firaskrichi** [comment]
@ericf any progress on this? It would be awesome!!

**Comment by tricoder42** [comment]
If anyone interested, feel free to take a look at [`js-lingui`](https://github.com/lingui/js-lingui/). It supports any component inside translated messages:

```jsx
// Developer is allowed to use any component inside <Trans>. All valid JSX is converted to ICU message format:
<Trans>See the <a href="/more">description</a> below.</Trans>

// Under the hood babel transforms component above to this:
<Trans id="See the <0>description</0> below." components=[<a href="/more" />] />
```

Pros:
- supports any component (builtin, custom, pair, self-closing)
- prop types of inner components doesn't affect translations (e.g: change of className doesn't require update of translations)
- translator-friendly - only one message per <Trans> component is generated (unlike current version of `react-intl` which require separate translations for inline components)
- easy setup - doesn't require extra variable to store inline component. There's no difference between writing translated/untranslated text.

Cons:
- requires extra babel plugin
- translators might require information about what's the <0> tag (e.g: link, emphasis, etc)

I guess the babel plugin could be ported to support `react-intl` and then only a subtle change of `<FormattedMessage />` API is required (and a bit more internally).

**Comment by bjbrewster** [comment]
Thanks @kamilio.  Your markdown method works fantastic!  Here is my updated version that works with interpolation values (`formatMessage` accepts values as 2nd param) and ES2015.

```
import React from 'react'
import { intlShape } from 'react-intl'
import Markdown from 'react-remarkable'

const FormattedMarkdown = ({ id, defaultMessage, values }, { intl: { formatMessage } }) =>
  <Markdown source={formatMessage({ id, defaultMessage}, values)} />

FormattedMarkdown.contextTypes = {
  intl: intlShape
}

export default FormattedMarkdown
```

I use my own helper methods `t` and `tm` as I find FormattedMessage too verbose in most cases:
```
import React from 'react'
import { intlShape, FormattedMessage } from 'react-intl'
import FormattedMarkdown from './FormattedMarkdown'

export const t = (id, values = {}) =>
  <FormattedMessage id={id} values={values} defaultMessage={values.default} />

export const tm = (id, values = {}) =>
  <FormattedMarkdown id={id} values={values} defaultMessage={values.default} />
```

**Comment by eliseumds** [comment]
@bjbrewster I guess `babel-plugin-react-intl` wouldn't be able to extract messages if you use factories like that. It would work if you use `defineMessages`, though:

```js
export const t = (message, values) =>
  <FormattedMessage {...message} values={values} />
```

And then:

```js
import { defineMessages } from 'react-intl';

const messages = defineMessages({
  requiredFieldMsg: {
    id: 'form.errors.required_field',
    defaultMessage: 'Field {fieldName} is required'
  }
});

function SomeComponent() {
  return t(messages.requiredFieldMsg, { fieldName: 'Phone Number' });
}
```

**Comment by bjbrewster** [comment]
@eliseumds Thanks for the tip.  I don't use the extract messages babel plugin but I am keen to try it out.  I currently have one json locale file with all the message text for my app that is getting unwieldy. React Components really deserve putting their locale text in the Component's file/folder so if you delete the component, its locale text is automatically cleaned up. I have worked on too many projects with monolithic string tables with MANY unused strings.

**Comment by oyeanuj** [comment]
@ericf Curious if you have any ideas of how soon (or not) is your proposed implementation might make it? 

_(The current solution is breaking down for us if say we have two or three inline links in a paragraph and are using `defineMessages` method - some context is shifted to the react component while other stays in the messages file)_

**Comment by Hurtak** [comment]
Hi, what is the status of the proposed solutions to this?

**Comment by Ephys** [comment]
And here you go:
https://github.com/ephys/react-intl-formatted-xml-message/

**Comment by joseph-galindo** [comment]
@ericf I think that proposal looks pretty cool...would definitely be a nicer way of allowing complex messages with components nested inside the message. For example, something that compiles to this:
```
<p>Please visit our helpdesk at <a href="https://foo.com">this link</a>, and please leave any feedback.</p>
```
Where the <a> tag could be any arbitrary React component from an outside consumer, but that component needs to very specifically wrap the "this link" text.

**Comment by dan-lee** [comment]
As we need this functionality right now, I created this package: [`react-intl-enhanced-message`](https://github.com/dan-lee/react-intl-enhanced-message).

**Comment by priyajeet** [comment]
@box we are also experimenting with React components within the messages
https://github.com/box/box-ui-elements/tree/master/src/components/i18n

**Comment by longlho** [comment]
parser work: https://github.com/formatjs/formatjs/commit/ad42f1fe3ef5ca51226e73ac04a182abc476fd2a

**Comment by longlho** [comment]
This unfortunately cannot be done in the parser due to complexity in parsing XML. We'd have to embed a XML parser for this to work reliably in both DOM & Node. What other libraries do seem to be re-parsing the translated message as XML (not HTML), then do another round of formatting which might be the safest way to do it. Performance-wise it won't be great, but does provide better translation context.

**Comment by longlho** [comment]
Upstream change: https://github.com/formatjs/formatjs/pull/124

**Comment by longlho** [comment]
`3.0.0-beta.20` should have this already.

**Comment by Ephys** [comment]
I'm so happy to see this being included natively, thank you for the hard work @longlho!

**Comment by ValeryVS** [comment]
@longlho 
Should we add some example to documentation, or new docs are already in progress?
I made example here
https://codesandbox.io/s/charming-swartz-6bl13

**Comment by longlho** [comment]
I think there's already some examples in the docs but PR's definitely
welcome! Our docs could def use some ❤️
