### ISSUE TITLE
Highlight all FormattedMessages

### ISSUE THREAD

**Issue by miracle2k** [formatjs/react-intl#514]
I find very useful the idea described in this Sentry blog post: https://blog.getsentry.com/2016/01/07/react-i18n.html - they are highlighting all translated strings, so that the ones that not can easily be identified.

I would like to propose and contribute the following patch:
- IntlProvider gets a new property "messageClassName".
- If set, all FormattedMessage and FormattedHTMLMessage render this classname for their <span>.
- The user can provide the styles for highlighting.

**Comment by ericf** [comment]
I think it would make more sense to do this in user-land because it would be more flexible. In your app you could do something like this:

```js
import {
    injectIntl,
    FormattedMessage,
    FormattedHTMLMessage,
} from 'react-intl';

function highlightMissing(Component) {
    return injectIntl(({intl, ...props}) => (
        <span className={intl.messages[props.id] ? null : 'missing_message'}>
            <Component {...props}/>
        </span>
    ));
}

export const HighlightedFormattedMessage = highlightMissing(FormattedMessage);
export const HighlightedFormattedHTMLMessage = highlightMissing(FormattedHTMLMessage);
```

**Comment by miracle2k** [comment]
I actually want to highlight *all* the ``FormattedMessage`` outputs, regardless of whether a message exists. The point is to catch those texts that have been written directly as non-localized strings (i.e. not using react-intl).

Still, you are certainly right that wrapping very ``FormattedMessage`` inside my own Higher-Order component is a very reasonable solution. Maybe I just want to avoid the pain of changing all my imports.

**Comment by ericf** [comment]
Okay I see what you're after now, and I think this falls within the realm of improving the developer experience. There's some other related features like using a pseudo translation which helps test the UI for being adaptable to languages which have longer test, like German.

This is something I'd like to think through more in a way that's grouped together with other DX features. So for now I'd suggesting the HOC approach, while more details are worked out.

**Comment by JonathanUsername** [comment]
Hi, we were having issues with this in our codebase, and we wanted a quick hack that would flag up missing values. I'll include the insane bash hack that I wrote below in case it helps anyone else, but I feel it's not an optimum solution to say the least! 

It works by checking the keys of our translation file (which conform to `/^[a-zA-Z\.]+$/` against occurrences of strings after FormattedMessage or FormatMessage). It misses all sorts of things, like any dynamically created keys etc., but it caught a few bugs so far, so I was encouraged to put it up in case it helps anyone else:

```
diff --side-by-side --suppress-common-lines <(\
  egrep -r '[fF]ormattedMessage|[fF]ormatMessage' src/* |\
  sed -e 's/.*\([fF]ormattedMessage\|[fF]ormatMessage\)//g' \
    -e "s/.*['\"]\(.*\)['\"].*/\1/" |\       # get string value
  egrep '^[a-zA-Z\.]+$' |\                   # discard anything more than letters and dots
  sort |\
  uniq \
) <(\
  cat src/translations/en.json |\
  jq -r 'keys[]' |\
  sort |\
  uniq \
) | egrep '^[a-zA-Z]' | awk '{print $1}'
```

**Comment by longlho** [comment]
This can prob be achieved with the `textComponent` prop
