### ISSUE TITLE
How to translate react-router Route paths (SEO URLs)

### ISSUE THREAD

**Issue by danieleleoni** [formatjs/react-intl#608]
Hi guys, we are developing a multilanguage web application, italian and english for the moment.
We need to translate all the routes as well. For example we have the terms and condition page that has two paths (one per locale):
- it/termini
- en/terms

We would like to obtain something like this:

``` javascript
// routes.js
const routes = (
  <Route path="/" component={App}>
    <IndexRoute component={HomePage} />
    <Route path="(it/termini)(en/terms)" component={TermsPage} />
    <Route path="*" component={NotFoundPage} />
  </Route>
)
```

As you can see this funky solution is not so good for the scalability of the application.
How SEO URLs are supposed to be translated? Any idea? We googled a lot, but we cannot find any solution for our needs.

The same question on stackoverflow
http://stackoverflow.com/questions/39080119/how-to-translate-react-router-route-paths

Thanks guys!!

**Comment by ericf** [comment]
Do you want your routes do go be translated through your normal translation pipeline with your UI strings?

The simplest solution would be to have a mapping of a route name to path for each language and then select the route mapping table based on the current locale.

**Comment by cloud-walker** [comment]
We already use react-intl in our project, and yes, the problem is more complicated than it seems, for example:

we have two routes it/termini and en/terms who must point to the same page component, but at the same time we need to change url on changeLocale component, there is a fragment: 

```javascript
const LanguageChooser = ({current, createOnChangeLocale}) => {
  return (
    <div className="wdo-lang-chooser">
      {locales.map(createFlag(current, createOnChangeLocale))}
    </div>
  )
}

LanguageChooser.propTypes = {
  current: PropTypes.string.isRequired,
  createOnChangeLocale: PropTypes.func.isRequired,
}

const mapStateToProps = ({intl}) => ({current: intl.locale})
const mapDispatchToProps = dispatch => ({
  createOnChangeLocale: locale => e => {
    e.preventDefault()
    document.cookie = `locale=${locale}`
    return dispatch(changeLocale(locale))
  },
})

export default connect(
  mapStateToProps,
  mapDispatchToProps,
)(LanguageChooser)
```

So yes, maybe a simple routes mapping, without involving react-intl its a idea. But what about more complicated routes like `en/state/:state_id/(/city/:city_id)` ?

I know that this issue come from other popular packages we have used, like react-router and redux, so maybe the solution is not react-intl, but the problem seems a lot common to me, for SEO based applications. Every hint is appreciated!

**Comment by ericf** [comment]
I don't think it makes sense to do add anything specific to routes into React Intl. But the `messages` feature is generic enough that you could use React Intl to supply the translated routes. Then in combination with `injectIntl()` you could access the `intl.messages` context to provide the translated URL as the `href` of your link components, etc.

**Comment by Degee** [comment]
Guys, can you tell me, how you solved it? Some example would be nice. Thank you!

**Comment by jamiehill** [comment]
Ok, it is indeed do-able and I'm in the middle of putting together a demo repo atm.  Until that's ready, you basically just need to build all of your routes asynchronously.

Here's a snippet from my implementation:

``` javascript

import { i18nPath } from 'util/RouteUtil'
import { async } from 'util/AsyncUtil'

export default {

	path: i18nPath('route.bonuses'),
	getComponent: async(BonusesView, 'expand'),

	getChildRoutes(next, cb) {
		cb(null, [{
			path: i18nPath('route.bonuses.sports'),
			getComponent: async(SportBonusTilesView)
		}, {
			path: i18nPath('route.bonuses.casino'),
			getComponent: async(CasinoBonusTilesView)
		}])
	}
}
```

without giving you all the code, the i18nPath helper is just translating the provided key, and the async helper loading the component asynchromously.  As long as child routes are encapsulated under `getChildRoutes` they'll be compiled on-demand, and pick up the locale you need.  

Bear in mind that you'll possibly need some additional helpers, for translating `<link to="" />` and other entry points into the browser history.

I asked a [similar question](https://github.com/ReactTraining/react-router/issues/3640), of the `react-router` guys a while back, which I'm posting for brevity.

Will add a demo link when I can.  Good Luck!

**Comment by jamiehill** [comment]
Here you go, have managed to finish an [example for you](https://github.com/jamiehill/react-intl-router) - here's hoping it's still of some use to you, if not someone else.

Will add README etc, and further clean up the code over the next couple of days.

**Comment by pkrakas** [comment]
My solution:

### App.js
```javascript
<FormattedMessage id="route.login">
{
    route => {
        return <Route path={route} component={Login} />;
    }
}
</FormattedMessage>
```

### Navbar.js

```javascript
<FormattedMessage id="route.login">
{
    route => {
        return (
           <Link to={route} style={{ textDecoration: "none" }}>
               <Button>
                   <FormattedMessage
                        id="login.title"
                        defaultMessage="Login"
                    />
               </Button>
          </Link>
        );
    }
}
</FormattedMessage>
```
