### ISSUE TITLE
Question: Custom error handling for translations in DEV and PROD

### ISSUE THREAD

**Issue by m4recek** [formatjs/react-intl#613]
Hi,
we would like to report all missing translations to our error reporter. Is there a way to provide custom error handler when translation is missing?

**Comment by ericf** [comment]
Nope, it uses `console.error`. Why do you need to run the code to determine which translations are missing?

**Comment by m4recek** [comment]
Hi, sorry for long delay. We had national holiday in the meantime :)

Our translation process is not in sync with development, and translators can change live translations even in deployed version of product. So we want to have error reporting when

**Comment by ericf** [comment]
So there isn't a way to validate a translation before it's pushed live by comparing it with the app's default messages?

Can you provide a more detailed proposal of how you're thinking this feature should work?

**Comment by m4recek** [comment]
Well, having a callback function for errors in IntlProvider or some other component will be enough

**Comment by ericf** [comment]
@m4recek this seems similar to [React Router's `onError` feature](https://github.com/reactjs/react-router/blob/master/docs/API.md#onerrorerror). Do you agree? If so, I can look into implementing this, where the default is `console.error`. For the API, would you expect the function you pass to `onError` to be called with an `Error` object?

**Comment by m4recek** [comment]
yes it is basically same feature. `Error` object as a param is ok, I don't have a strong preference. Only difference I expect betweeen `onError` callback and `console.error` is that `onError` callback should be called even in production environment.

**Comment by ghostd** [comment]
Here is a first proposal (without Error object for now): #880

**Comment by abologna-r7** [comment]
Implementation could return a promise when calling formatMessage, with a resolved status...

**Comment by papasmile** [comment]
Hi, @m4recek et al, is this issue resolved by changes in #880?  Or what is left?
