### ISSUE TITLE
Using a different message variables format?

### ISSUE THREAD

**Issue by coluccini** [formatjs/react-intl#663]
Hi,
Is there's a way to config react-intl to be able to use a different variable format inside messages?
Now they need to be {var}, but I'm sharing the translation files with another apps and they are using %var% and I would like to avoid to duplicate and modify the files every time they get updated

**Comment by ericf** [comment]
There isn't currently a way.

**Comment by irot** [comment]
@coluccini I'm having the same issue. 

While I'm hoping for a similar featured I doubt it's an easy fix to implement. 

My solution for now is to parse the imported translations file and standardise the variable before passing into my `<IntlProvider />` component. In my case, `{.Var}` becomes `{var}` -- remove leading '.' character and lowercase everything.

**Comment by coluccini** [comment]
hi @irot,
Yes, that's what I did too. I created a server endpoint that return (and cache) the translated messages standardised.
Thanks!

**Comment by ericf** [comment]
It could become easier to do this through this proposed abstraction: https://github.com/yahoo/react-intl/issues/513#issuecomment-252114827

**Comment by redonkulus** [comment]
We are following the ICU standard. It could be possible to support other ones but not a priority right now.
