### ISSUE TITLE
How does React-Intl handle 'Right to Left' Locales?

### ISSUE THREAD

**Issue by NickCain** [formatjs/react-intl#725]
I am working on an application that will need to support languages that read right to left.
What would be the best way to impliment this using `React-Intl`? 

I have noticed that the localeData is there for these languages, e.g. Arabic, however it does not align the text to read Right to Left.

Is there a sensible solution for this? Has anyone come up with a solution for this before?

Thanks in advance.

**Comment by ericf** [comment]
Can you provide an example page with the issue?

You might need to setup the `dir="rtl"` on the body.

**Comment by NickCain** [comment]
An example snippet of code:

``` <CardTitle
            className={cardTitleClass}
            title={
              <FormattedMessage
                id='search.header'
                description='Main header on the search page'
                defaultMessage='search'
              />
            }
          />```

So this string int he FormattedMessage will become Arabic when the language is set, however it doesn't move this text to read from Right to Left.

Taking your point on board, I have made a switch to check for `rtl` locales and apply the dir='rtl' onto the body.

Maybe this is something React Intl could do automatically at some point when a right to left local is being used.

**Comment by ericf** [comment]
Adding `direction` metadata to the ECMAScript Intl spec is something we've been working on. But your point is interesting because CLDR has metadata about a locale's direction and it could be used by `<IntlProvider>` to output a wrapping `<div>` with `direction` set.

**Comment by NickCain** [comment]
Awesome, glad to hear you are working on something as well, if you require any further input or anything let me know.

Also, thanks for getting back to me, React-Intl is an awesome library and I've used it in many applications now. Keep up the good work! 👍

**Comment by mbrevda** [comment]
>  it could be used by <IntlProvider> to output a wrapping <div> with direction set

I think that setting the direction [once](https://github.com/yahoo/react-intl/issues/725#issuecomment-260484336) would be a better idea.

**Comment by sag1v** [comment]
@ericf hi, any news about that?

> Adding direction metadata to the ECMAScript Intl spec is something we've been working on. But your point is interesting because CLDR has metadata about a locale's direction and it could be used by <IntlProvider> to output a wrapping <div> with direction set.

**Comment by zraees** [comment]
Hi @NickCain, 
Did you fix RTL issue, I am facing the same. can you give some example how to set 'dir=rtl' in body tag and from which action you trigger this?

waiting for the reply.
thanks

**Comment by Verten** [comment]
is there have any solution for this?

thanks

**Comment by reergymerej** [comment]
I don't think this library is meant to identify, let alone set, any RTL properties.  What about using something like https://www.npmjs.com/package/rtl-detect to examine the client's locale?
