### ISSUE TITLE
To optimize loading of locale data files so that these files can be bundles separately in chunks

### ISSUE THREAD

**Issue by PoojaSSW** [formatjs/react-intl#731]
The approach defined in this lib for accessing the locale data forces all files in the locale-data directory to be bundled by Webpack. 
```
import ja from "react-intl/locale-data/ja";
import { addLocaleData } from "react-intl";
addLocaleData([...ja]);`
```

I tired something like:
```
function locale(locale, callback) {
  require.ensure([], function(require) {
    callback(require("react-intl/locale-data/"+ locale));
  });
}

this.locale(locale, addLocaleData);
```

It works only for "en" and fails for the rest of languages.
Is there a better way of loading the localedata so that the files can be bundles separately in chunks and not one big bundled file. just feel cumbersome to manage.

**Comment by ericf** [comment]
Try removing the `.default`

**Comment by piyaa** [comment]
tried..no change..:(

**Comment by piyaa** [comment]
So here is a strange behavior i noticed. I constantly keep getting this error on executing the above func:
``[React Intl] Missing locale data for locale: "ja". Using default locale: "en" as fallback.`
and does not render the translated files. However , when I hard-code the locale, eg in the above case"ja":
```
function locale(locale, callback) {
  require.ensure([], function(require) {
    callback(require("react-intl/locale-data/ja").default);
  });
}
```

it magically works, Im confused with this behavior. why should it fail on something dynamically entered as opposed to hardcoding the locales. Any ideas?

**Comment by piyaa** [comment]
So another question I have is how can I pass the object to the messages prop in the IntlProvider using the above approach i.e:
```
 const index = function(locale, cb) {
        require.ensure([], function (require) {
          cb(require("./languages/" +locale+ ".json"));
        }, "index");
      };
return {
 <IntlProvider  timeZone="Asia/Tokyo" locale={locale} messages={?..[object]}></IntlProvider>
}
```

the index is a function, how can I make it return an object that I can pass into the messages prop to load the desired locale object for translations?

**Comment by ericf** [comment]
I'm not sure, I'm not an expert on this Webpack feature.

**Comment by ericf** [comment]
@piyaa did you end up figuring this out?

**Comment by sedubois** [comment]
@ericf I agree this is an issue, the current setup forces people to inline the script into HTML, as you do in the Next.js example: https://github.com/zeit/next.js/pull/1055/files#diff-dd019086ce3601872fbb8c5885d9f10dR23

There should be a better way, e.g just passing a serializable JSON object or similar (which can be passed from server to client e.g for SSR).

**Comment by ericf** [comment]
@sedubois it's not JSON-serializable, the locale data contains functions for pluralization.
