### ISSUE TITLE
Library not behaving correctly when Array.prototype gets modified.

### ISSUE THREAD

**Issue by v29neil** [formatjs/react-intl#732]
When some third party library modify the Array.prototype. Library throws error.
TypeError: Cannot read property '_mergeFormats' of null
![react-intl-error_1479196153135](https://cloud.githubusercontent.com/assets/6794259/20297378/41a044b0-ab36-11e6-8a96-f38969ac84fe.jpg)

To replicate this , Add this  library to page (http://app.hatchbuck.com/OnlineForm/js/cdn/jotform.js?ver=1.2.2)

**Comment by ericf** [comment]
Does React generally work correctly when Prototype.js is on the page?

**Comment by v29neil** [comment]
I first tried it with https://cdnjs.cloudflare.com/ajax/libs/prototype/1.7.3/prototype.min.js  . And It is working correctly with veresion 1.7.3 . 
But when i try with version 1.7 which jot form is using, It is throwing same error.

**Comment by ericf** [comment]
If you can provide details on whether or not React even works with Prototype.js and how React Intl can defend against Prototype.js, that would be helpful.

**Comment by athimannil** [comment]
@ericf I have the same issue with 

`"app.components.TeaserContent.kooy":["your personal selection.", "outfits styled for you.", "new favourite items.", "your new wardrobe."],
`
for 
```
import { defineMessages } from 'react-intl'
export default defineMessages({
  typeText: {
    id: 'app.components.TeaserContent.kooy',
    default: 'dfgdfgdf'
  },

console.log(intl.formatMessage({ ...messages.typeText }))
```
and getting error in console same as in the question
