### ISSUE TITLE
Unable to translate strings in the user desired language 

### ISSUE THREAD

**Issue by PoojaSSW** [formatjs/react-intl#746]
I'm unable to translate the file in the desired lang. In my root module:

```
export default class Main {
render() {
const messages= require.context("ja.json", );
return (
 <IntlProvider  locale={locale} messages={messages}> //messages has the required translation object
            <App
              //content inside
              />
            </IntlProvider>
)
}
}
```

in the App frame comp i have:
```
render() {
<p>  <FormattedMessage
       id="test.id"
        defaultMessage="Defualt test"/></p>
}
```
en.json:

`"test.id": "Hellow Worlds"`

ja.json:

`"test.id": "新しいダッシュボード"`

It constantly render the defaultMessage in this case. what im i missing?

**Comment by ericf** [comment]
I wouldn't be able to say without see the code and being able to run it. You might want to look at how the apps in the `examples/` folder work to help you when debugging.

**Comment by piyaa** [comment]
hmm..i  did followed the exact way from the examples section, also went through other wiki pages, still dont know what im i missing!

**Comment by ericf** [comment]
Did you make sure the value of `messages` is correct? I'm not sure what `require.context()` does.

**Comment by piyaa** [comment]
Sorry my bad, corrected code:

```
export default class Main {
render() {
const messages= require("./languages/"+locale+".json")
//messages= {test.id: "新しいダッシュボード"}
return (
 <IntlProvider  locale={locale} messages={messages}> //messages has the required translation object
            <App
              //content inside
              />
            </IntlProvider>
)
}
}
```

the object passed to messages looks fine correct?Also here is the way I'm adding the addLocaleData to get the translations. This is way for making sure the webpack renders the files in chunks rather one big bundled file:
```
require.ensure([], function(require) {
      addLocaleData(require("react-intl/locale-data/"+ locale));
    });
```
locale in all above cases is set "ja" for now.

**Comment by ericf** [comment]
@piyaa is this still an issue?

**Comment by gtournie** [comment]
I have the same issue. I'm struggling with for 2 days already...
Please find a runnable example here: https://github.com/gtournie/intl-provider-test

Once the page loaded, in Root.js, change "Test EN" into "Test EN!!" (the hot loader refresh the data)... 
=> displays "Test FR" (the translation is finally correct)

**Comment by gtournie** [comment]
For now I use this class as a workaround:

```
class IntlProviderWrapper extends Component {
  render() {
    return (
      <IntlProvider {...this.props}>
        {this.props.children}
      </IntlProvider>
    );
  }
}
```

weird, uh?

**Comment by arvinsim** [comment]
I am also getting this same issue. It doesn't matter if I set the language manually.

I also double checked the messages that were passed to `IntlProvider`. They seem to be correct.
