### ISSUE TITLE
Support for old browsers (Android 4.0)

### ISSUE THREAD

**Issue by apsavin** [formatjs/react-intl#788]
Hi, guys!
It seems that there is a bug in `react-intl`.

How to reproduce: Open a project with react-intl on Android 4.0

Current behaviour: Exceptions.

1. Syntax error
1. Cannot assign to read only property '__esModule' of Object

How to fix:

In `react-intl/lib/index.js`

1. replace `extends: _extends,` with `"extends": _extends,`
1. replace `Object.defineProperty(exports, '__esModule', { value: true });` with `exports.__esModule = true`

I understand that it's generated code. 
I think, in order to fix the second problem correctly, you can use `loose` mode for es6 modules compilation. 
I can come with a pull request, but at first I want to know - do you want to support such old platforms?
And how to add tests? It seems that you run tests only on node platform at the moment.

**Comment by ericf** [comment]
I would like to support platforms that React supports. Does React support Android 4.0?

**Comment by apsavin** [comment]
Well, our React 15 app works well. With monkey--patched react-intl though)
I'd like to remove the patch and to fix it on the react-intl side. It seems
that we'll not  need to change the code - we'll need only to fix the
transpilation.

**Comment by ericf** [comment]
For the Syntax Error, I can look into why `extends` isn't being considered a reserved word that needs quoting. I'm already adding the Babel ES3 transforms. It appears its an issue with how Rollup is pulling in the Babel helpers which is leaving the `extends` unquoted.

As for the O.dP, the expectation is that the runtime is ES5, so you'll likely need to add an ES5 shim to make sure APIs like O.dP are present. This is even in React's own docs: https://facebook.github.io/react/docs/react-dom.html#browser-support

**Comment by apsavin** [comment]
About Object.defineProperty - the problem is not that this function is absent in Android 4.0.

See http://stackoverflow.com/questions/35461830/cannot-assign-to-read-only-property-esmodule

I'll try to come with more info and/or with PR.

**Comment by RafaelKeramidas** [comment]
This issue also affects the PS4 browser (webkit based).

**Comment by leoyli** [comment]
@redonkulus, This one is quite outdated, maybe we should close it?!
