### ISSUE TITLE
react-intl 3 should be completely flowtyped

### ISSUE THREAD

**Issue by steida** [formatjs/react-intl#793]
We need type checking and autocomplete. 
We can leverage https://flowtype.org/docs/typeof.html
String keys suck. We should use https://flowtype.org/blog/2015/07/03/Disjoint-Unions.html for that.

Pattern like that https://github.com/este/este/blob/87a72259a6660ed3c9e58a64e7a98439b0741162/src/common/types.js#L99 but probably composed.

This is what we want. Typed and autocompleted intl.

```js
placeholder={intl.formatMessage(intl.messages.newTodoMessages.placeholder)}
```

**Comment by steida** [comment]
Pattern like that https://github.com/este/este/blob/87a72259a6660ed3c9e58a64e7a98439b0741162/src/common/types.js#L99 but probably composed.

**Comment by steida** [comment]
This is what we want. Typed and autocompleted.

`placeholder={intl.formatMessage(intl.messages.newTodoMessages.placeholder)}`

**Comment by steida** [comment]
https://github.com/marudor/flowInterfaces/blob/master/packages/iflow-react-intl/index.js.flow

**Comment by ericf** [comment]
Why would it have to be v3?

**Comment by steida** [comment]
Good question. Maybe I am wrong, but I suppose it would have the impact to API. Not sure yet.

**Comment by redonkulus** [comment]
There is a DefinitelyTyped solution that exists today. If someone wants to create a Flow version, that would be great. But its not something that will be supported here directly.

**Comment by leoyli** [comment]
But I think we are going with TypeScript here I believe, as other parts in the FormatJs project

**Comment by steida** [comment]
Flow died meanwhile. TS 👍
