### ISSUE TITLE
injectIntl(component) does not add intl to props

### ISSUE THREAD

**Issue by SanthoshHari912** [formatjs/react-intl#810]
@peramsathyam @ericf : I have the following code wherein I inject intl on LoginPage component. 
On debugging, I found intl object is added to **this._reactInternalInstance._context**.  Guide me on how can I add it to the props object .

```
const messages = defineMessages({
			userNamePlaceHolder: {
				id: 'LOGIN--TEXT',
				defaultMessage: '{username}!',
				description: 'place holder for user name'
			}
		});
LoginPage.proptypes={	intl: intlShape.isRequired }
```
And inside render,

```
const {formatMessage} = this.props.intl;
<input type="text" title={ this.state.usernameText } placeholder={formatMessage(messages.userNamePlaceHolder,{username:this.state.usernameText})  } />
```
Also exposed the class as,
`export default injectIntl(LoginPage);`

But I get the following error,
**Uncaught TypeError: formatMessage is not a function**
(As intl is not added to props)

Regards
Santhosh

**Comment by ericf** [comment]
It does work, please see the examples in the repo. Or provide a PR with a failing test case. This is likely some issue in your code that you should step through with the debugger.

**Comment by p10ns11y** [comment]
@SanthoshHari912 as a quick look it should work. Did you forget to 
import { injectIntl, intlShape } from 'react-intl'

**Comment by Dinkelborg** [comment]
I'm having this exact same issue I've been reading several tutorials now, checking their source code etc... I have the same imports, same code nothing works... I checked and props just doesn't include any attribute called "intl" - do I have to pass this into each component by hand? And if so, what should I pass into it... I find the docs on this to be very unclear.

**Comment by paolostyle** [comment]
I had a similar problem just a moment ago and it was obviously my dumb mistake.
```
export class MyComponent extends Component { ... }

export default injectIntl(MyComponent)
```
and then `import { MyComponent } from './MyComponent.jsx';`, so no wonder that intl was undefined - I just imported the wrong component, I shouldn't have exported that class in the first place, of course. Make sure you didn't do the same mistake I did.
