### ISSUE TITLE
US locale but currency symbol in another locale?

### ISSUE THREAD

**Issue by Dindaleon** [formatjs/react-intl#812]
Hello,

I want to have US locale, but I want to have VEF currency which uses a comma for decimals instead of a dot. Furthermore, when I set currency symbol in react-intl settings, nothing shows up. It should show BsF. Is this possible to have?

**Comment by ericf** [comment]
The way to accomplish this is using a nested `<IntlProvider>` to set the locale to get the different number formatting you're looking for. You'll also want to be sure to load the React Intl locale data for both languages.

**Comment by Dindaleon** [comment]
What about the currency symbol? I set the currency as VEF, but there is no symbol showing up. I need it as Bs. 100 or BsF. 100

**Comment by ericf** [comment]
Did you try what I suggested?

**Comment by celinrayen** [comment]
Hi @Dindaleon / @ericf Any success on this?

I'm also facing similar situation. Where I need to format PLN as `zł 1,000.00`
I tried with `<IntlProvider locale='en'>`  & `<IntlProvider locale='pl'>` below are the results respectively.

`PLN 1,000.00` & `1 000.00 zł`

Please suggest.
