### ISSUE TITLE
eslint plugin

### ISSUE THREAD

**Issue by khankuan** [formatjs/react-intl#823]
Hi, I'm wondering if there are any strategies to detect unformatted strings in jsx for eslint. Cheers!

**Comment by ericf** [comment]
The main approach for this type of thing is [Pseduolocalization](https://en.wikipedia.org/wiki/Pseudolocalization).

This is something I'd love to support for Real Intl, I just haven't had time to work on that feature.

**Comment by iilei** [comment]
I am using the eslint plugin [getsentry/jsx-needs-i18n](https://github.com/getsentry/eslint-plugin-getsentry) for detecting unformatted strings.
