### ISSUE TITLE
Fallback hook

### ISSUE THREAD

**Issue by Exomnius** [formatjs/react-intl#824]
For my current application, I retrieve json files containing my translation messages from my API for usage with react-intl. These json files are cached on the client, which could cause outdated/missing translations.

Is it possible, when a message is not found (when it displays the warning), to hook into the fallback procedure and in my case send another API call?

Regards
Cornel Janssen

**Comment by ericf** [comment]
This issue with this is rendering is sync while fetching updated translations and passing them to `<IntlProvider>` is async.

You might be able to wrap `<FormattedMessage>` and do something like this with `injectIntl()` to check whether a message exists or not, and if not issue our API request: https://github.com/yahoo/react-intl/pull/488#issuecomment-224945705

**Comment by ghostd** [comment]
Maybe this issue could be resolved with #613?
