### ISSUE TITLE
[Idea] FormattedMessageWithProps component

### ISSUE THREAD

**Issue by peramsathyam** [formatjs/react-intl#854]
Whenever I didn't want to use `intl.formatMessage` imperative way for translation, I often end up using FormattedMessage function-as-child pattern. The code readability suffer a bit due to lots of `{}`. 

Why don't we export a component like `FormattedMessageWithProps`. Here is the one I wrote to create custom styled `FormattedMessage`

```
import React, { PropTypes, isValidElement } from 'react';
import { FormattedMessage } from 'react-intl';
import warning from 'warning';

const { shape, string, object } = PropTypes;
const { createElement: e } = React;

export const descriptorShape = {
  id: string.isRequired,
  defaultMessage: string.isRequired,
  description: string
};

export function FormattedMessageWithProps(props) {
  // restProps contains className and other props as an Object
  const {
    tagName,
    values,
    descriptor,
    ...restProps
  } = props;

  const isValidComponent = isValidElement(e(tagName, null));

  warning(
    isValidComponent,
    "Invalid 'tagName' prop %s is passed. 'span' will be used instead",
    tagName
  );

  const Component = isValidComponent ? tagName : 'span';

  return (
    <FormattedMessage {...descriptor} values={values}>
      {(...formattedMessage) => e(Component, restProps, formattedMessage)}
    </FormattedMessage>
  );
}

FormattedMessageWithProps.propTypes = {
  descriptor: shape(descriptorShape).isRequired,
  tagName: string,
  values: object
};

FormattedMessageWithProps.defaultProps = {
  tagName: 'span',
  values: {}
};
```

It helps create `button` , `a` tags with  event `handlers` and `classNames` and git rid of `{}` 

@ericf What you think?

**Comment by ericf** [comment]
My recommendation is to wrap `<FormattedMessage>` with another element which you can style. The proposed approach is to eventually get to this: https://github.com/yahoo/react-intl/issues/513#issuecomment-252114827

**Comment by Soreine** [comment]
@ericf an obvious caveat is that all non-inherited CSS properties cannot be applied the content of `<FormattedMessage>` if you just wrap it in a styled component.
For example, you have no way to vertically align the text in it https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align

**Comment by e110c0** [comment]
is there a reason why react-intl does not pass down additional props to the created element? at least properties like className and style should be passed so they are added to the html element in the end .
this would solve this problem. But it will make #975 a real bug as well :(

**Comment by leonaves** [comment]
@Soreine @e110c0  Just use `React.Fragment` as the `textComponent` when creating the `IntlProvider` (https://github.com/yahoo/react-intl/wiki/Components#intlprovider):

```js
  <IntlProvider
    locale={ this.getLanguage() }
    messages={ this.getMessages() }
    textComponent={ React.Fragment }
>
```

Then there won't be any HTML nodes between the wrapping node and the text node.

**Comment by abologna-r7** [comment]
That is a great approach @leonaves , however, it won't work for apps using React v15.x.x :/ 
I still think className and other additional props should be passed down to its child component.

**Comment by anishprvn** [comment]
Having className and other props passed down could keep the code clean without the need to wrap a element around it.

**Comment by e110c0** [comment]
What is the reason this issue was closed? Is it a won't do to not break current behaviour or lack of resources. If there is a consensus to change this (and maybe solve #975 at the same time), I'd put some effort in it and create a PR
