### ISSUE TITLE
How to define FormatJS formats in ICU json

### ISSUE THREAD

**Issue by jdmswong** [formatjs/react-intl#859]
https://formatjs.io/guides/message-syntax/#plural-format

How does one represent this ( and the other formats ) in the ICU json file supplied to `addLocaleData`?

In other words, how do add `<FormattedPlural />` support to https://github.com/gpbl/isomorphic500/blob/master/src/intl/en.js

**Comment by ericf** [comment]
I'm not sure I follow what you're asking. Can you explain more?
