### ISSUE TITLE
Range pluralization rules

### ISSUE THREAD

**Issue by dciesielkiewicz** [formatjs/react-intl#868]
I'd like to ask if there is any way to use range pluralization rules with FormattedMessage.
Accoring to [unicode docs](http://www.unicode.org/cldr/charts/28/supplemental/language_plural_rules.html) it should be possible using:
`
one+other
other+one
other+other
`

Can anyone send me an example of usage if something like this exists?

**Comment by mrfelton** [comment]
I'm also looking for this:

For example:

```
Estimated Delivery: {targetConfs, plural, 1~2 {less than 1 hour} 3~5 {1-6 hours} 6~8 {1-24 hours} other {> 24 hours}}
```

**Comment by bertho-zero** [comment]
> I'm also looking for this:
> 
> For example:
> 
> ```
> Estimated Delivery: {targetConfs, plural, 1~2 {less than 1 hour} 3~5 {1-6 hours} 6~8 {1-24 hours} other {> 24 hours}}
> ```

Still no possibility to pluralize according to ranges?

**Comment by longlho** [comment]
I think you're just looking for a switch statement, not really plural rules.
