### ISSUE TITLE
Can I style individual elements of a <FormattedDate />  ?

### ISSUE THREAD

**Issue by aziz-boudi4** [formatjs/react-intl#874]
I'm using  **FormattedDate**  to display the time, and I was wondering If I could style every individual part of the time.
I managed to style the hour and minutes but what about the "AM" && "PM".
my goal is to have something similar the attached image
![screen shot 2017-02-28 at 5 44 26 pm](https://cloud.githubusercontent.com/assets/7435015/23443051/299efc46-fde1-11e6-8944-dfcc74f17f42.png)

**Comment by ericf** [comment]
This is not currently possible, but this is the exact use-case for the `formatToParts()` API that we standardized as part of JavaScript! https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/formatToParts

Eventually we'll use this API directly within React Intl.

**Comment by aziz-boudi4** [comment]
Thanks for the quick answer.
Do you have any suggestions for a similar library that would solve my problem ?
