### ISSUE TITLE
how to add new custom locale js formatting to react-intl

### ISSUE THREAD

**Issue by arivua** [formatjs/react-intl#884]
I have a requirement to create my own customized locale say "en-TBD" and enable formatting based on my terms.
is it possible to do it react-intl

**Comment by abbish** [comment]
Same question

**Comment by typhoon1978** [comment]
Also same question for me. Is it possibile to specify:

- date format
- number format (decimal separator, thousand separator...)
- currency symbol

Thanks,
Alex.

**Comment by ghostd** [comment]
You can create your own locale then call [addLocaleData](https://github.com/yahoo/react-intl/wiki/API#addlocaledata) to provide currency symbol and the number format.

**Comment by typhoon1978** [comment]
Hi, thanks for the answer.

I see the <locale>.js is a minified javascript, is it possible to implement it in TypeScript simply providing the object { ... } ?
Can you provide a sample with all the keys to implement a full customization of the locale?
Where can I find the key definitions?

Thanks in advance,
Alex

**Comment by typhoon1978** [comment]
I see that the locale object has this shape:

![locale](https://user-images.githubusercontent.com/1161397/31882723-00325d28-b7e8-11e7-92d0-64d18f464cdf.png)

but I can't see the date format for example nor the number format... can you help me ?

Best regards,
Alex

**Comment by ghostd** [comment]
Hi,

There a similar ticket #1050 with some informations.
