### ISSUE TITLE
Different locale for numbers and dates?

### ISSUE THREAD

**Issue by zerok** [formatjs/react-intl#885]
Is it somehow possible to use different locales for numbers/monetary-values and dates or strings? An example would be an English application but the users are used to German number-formatting.

**Comment by zerok** [comment]
I take that as a "no"? 🙂

**Comment by DragonRaider5** [comment]
This issue was closed as it was stale. Would you be willing to provide a PR?
One can currently provide custom formatting functions, maybe you could use this to your advantage.

**Comment by zerok** [comment]
The issue was initially meant as a question and we've now also worked around this. If we run into the the issue that triggered this issue in another project, we will perhaps also be able to provide a PR :)
