### ISSUE TITLE
react Intl with Container architecture

### ISSUE THREAD

**Issue by loick** [formatjs/react-intl#886]
Hi there, 

I had a quick question about React-Intl, I'm working with the Container / View system and I'm a bit confused. Wrapping React Intl around my View components to format the numbers/messages seems weird to me, I would rather deal with it on the container side. 

It just feels strange to relate some agnostic-dataProvider-components to the context to get the translations in the view. What do you think about it, is there any recommendations ? 

Thank you !

**Comment by ghostd** [comment]
I'm not sure to understand your point. Can you elaborate with example?

**Comment by e-e-e** [comment]
You can wrap the container in the injectIntl HOC and then simply pass intl as a prop to any simple components - or even better translate strings/values before passing them as props.
