### ISSUE TITLE
How to handle HTML with formate message

### ISSUE THREAD

**Issue by m1m6** [formatjs/react-intl#887]
I have the following HTML in my message:
Here is some {bolded} text.

 i tried to use the following:
`formatHTML('Here is some {bolded} text.','Here is some {bolded} text.',{
                      bolded: (
                        <strong>
                          <FormattedMessage
                            id='bolded'
                            defaultMessage='bolded' />
                        </strong>
                      )
                    })`

fomatHTML function looks like:
`export function formatHTMLMessage(id,defaultMessage = '',values = {}) {
  return intl.formatHTMLMessage({id:id,defaultMessage:defaultMessage},values);
}`

How ever the output of this message is:
`Here is some [object Object] text.`

how can i handle html with react-intl ?

**Comment by ghostd** [comment]
I'm not sure to understand your use case.
If you need rich text with your translation you can follow this documentation:
https://github.com/yahoo/react-intl/wiki/Components#formattedmessage

If your translation contains some HMTL tags you can use https://github.com/yahoo/react-intl/wiki/Components#formattedhtmlmessage
Note formatHTMLMessage *does not* handle `values` with React element.

**Comment by m1m6** [comment]
Thanks @ghostd, will try and see what happen.
