### ISSUE TITLE
Can't get simple strings from json

### ISSUE THREAD

**Issue by mbinet** [formatjs/react-intl#904]
Hi,
after spending a lot of time browsing the wiki and testing the examples, I still can't manage to get simple strings from a json file.

### JSON
```
// en.json
{
    "welcome": "Hello",
}
```

### Component

```
import React from 'react';
import en from 'react-intl/locale-data/en';
import { IntlProvider, FormattedMessage, addLocaleData } from 'react-intl';

addLocaleData([...en]); 

class Test extends React.Component {

    render() {
        return (
            <IntlProvider locale='en'>
                <FormattedMessage
                        id="welcome"
                        defaultMessage={`Test`}
                    />
            </IntlProvider>
        );
    }
}
export default MovieBox;

```

My idea for this code is to print `Hello` but it prints `Test`

I am surely missing a point here, I hope someone can help.
And sorry for the stupid question... 😕

**Comment by langpavel** [comment]
Where you inject `messages` to `<IntlProvider>`?
https://github.com/yahoo/react-intl/wiki/Components#intlprovider

**Comment by mbinet** [comment]
I thought it was done with this `addLocaleData([...en]);` ...
I guess it should like 
```
<IntlProvider locale='en' message={en}
>
```

?

(This doesn't actually work)

**Comment by langpavel** [comment]
You must provide your own distionary to `messages` (not `message`). Read the manual carefully

**Comment by ghostd** [comment]
@mbinet see https://github.com/yahoo/react-intl/issues/907#issuecomment-287563047
