### ISSUE TITLE
Translating Messages Documentation

### ISSUE THREAD

**Issue by Liamonade** [formatjs/react-intl#907]
Please could someone help me.

I can't find anywhere in the documentation that shows how messages should be structured in locale objects / files.

Am i missing something?

I assumed that i need to do something like this:

```
import {addLocaleData} from 'react-intl';
import en from 'react-intl/locale-data/en';
import fr from 'react-intl/locale-data/fr';

addLocaleData([...en,...fr,
    {
        locale:"en",
        messages: {
              welcome_message: "Welcome!"
        }
    },
    {
        locale:"fr",
        messages: {
              welcome_message: "Welcome!"
        }
    }, 
    require('./locales/my-other-locale-from-file')
]);
```

but I get the error
`Missing message: "welcome_message" for locale: "de", using default message as fallback.`

Then I thought maybe it needed to be done like this:

```
var messages = {
    en: {
        welcome_message: 'Welcome!' 
    },
    fr: {
        welcome_message: 'Bienvenue'
    }
};

var locale = navigator.languages[0];

ReactDOM.render(
    <IntlProvider locale={ locale } messages={ messages }>
        { dom } 
    </IntlProvider>
, el);
```

But I got the same error.

I can add a line of code to choose the correct messages based on the locale. But the previous error messages suggests there's something built in to handle this. In this code I am basically doing the language selection part myself which doesn't seem right.

```
var messages = {
    en: {
        welcome_message: 'Welcome!' 
    },
    fr: {
        welcome_message: 'Bienvenue'
    }
};

var locale = navigator.languages[0];

var messages = messages[locale];

ReactDOM.render(
    <IntlProvider locale={ locale } messages={ messages }>
        { dom } 
    </IntlProvider>
, el);
```

Thanks :)

**Comment by langpavel** [comment]
I'm not sure where you readed about dictionaries putted alongside with locale data...

You should put your dictionary to `messages` property in `<IntlProvider>`.

Try read documentation again

**Comment by Liamonade** [comment]
@langpavel Ok thanks, so it is up to me to handle making sure the correct translation of messages are passed to the IntlProvider? i wasn't sure if i was supposed to pass in all translations and then allow the component to work out which one to display. Makes sense though just wanted to make sure im doing this right.

**Comment by langpavel** [comment]
@Liamonade Yes, it is your own responsibility to deliver dictionary to `IntlProvider`. This is well documented I think..

**Comment by ghostd** [comment]
@Liamonade you can find the answer in the [documentation](https://github.com/yahoo/react-intl/wiki#creating-an-i18n-context) and the [examples](https://github.com/yahoo/react-intl/blob/master/examples/)

You can try this:
```
const locale = "end"
const messages = {
  "app.hello_world": "Hello world",
}
...
<IntlProvider locale={locale} messages={messages}>
    <App />
</IntlProvider>
```
Here is a turorial: https://www.smashingmagazine.com/2017/01/internationalizing-react-apps/
