### ISSUE TITLE
Translating Placeholders

### ISSUE THREAD

**Issue by Liamonade** [formatjs/react-intl#908]
Can this be used for translating react placeholders?

E.g.

`<input type="text" placeholder="Your Name" />`

The TranslateMessage component returns the text within a span so it can't be used here. I saw injectIntl method but can only see this used for dates. Could you explain how i would use this in this scenario.

Thanks!

**Comment by ghostd** [comment]
Try this (no tested):
```
const Component = ({intl: { formatMessage }, otherProp}) => {
    return (<input type="text" placeholder={formatMessage({id: 'my.placeholder.id'})} />)
}
export default injectIntl(Component)
```

**Comment by damonbauer** [comment]
It's not true that `injectIntl` can only be used for dates. Any of the `format` components have the inject capability.

**Comment by saadaouad** [comment]
Thanks @ghostd +1

**Comment by mixalezhnev** [comment]
![image](https://user-images.githubusercontent.com/13313643/30690056-00c0e6e2-9ed4-11e7-9d32-34e332216a5e.png)
Consider this possibility.

**Comment by uinz** [comment]
@mixalezhnev 
how to handle this ?
```jsx
<input title={fotmattedTitle} placeholder={formattedPlaceholder} />
```

-----


```jsx
<FormateedMessage id='input.title'>
  {title =>
    <FormateedMessage id='input.placeholder'>
      {placeholder => <input title={title} placeholder={placeholder} />}
    </FormateedMessage>
  }
</FormateedMessage>

this is too ugly!!
think about nested many times?

**Comment by Moriartty** [comment]
@Arvinzhu  maybe you can write like this
>```
>import {FormattedMessage,injectIntl,defineMessages} from 'react-intl';
>class Test extends React.Component{
>    render(){
>        const intl = this.props.intl;
>        return (
> <FormItem {...formItemLayout} label={
>    <FormattedMessage id="app.basic-form.form-title" defaultMessage="Title"/>
>  }>
>   {getFieldDecorator('title', {
>       rules: [
>           {
>              required: true,
>              message: <FormattedMessage id="app.basic-form.form-title-required" defaultMessage="Please enter the title"/>,
>               },
>          ]
>     })(
>        <Input placeholder={intl.formatMessage({id:'app.basic-form.form-title-required'})}/>
>    )}
> </FormItem>
>        )
>    }
>}
>export default injectIntl(Test);
>```

**Comment by umutcanbolat** [comment]
> ![image](https://user-images.githubusercontent.com/13313643/30690056-00c0e6e2-9ed4-11e7-9d32-34e332216a5e.png)
> Consider this possibility.


this solves the problem, thanks :smiley:

**Comment by NajmZaga** [comment]
> > ![image](https://user-images.githubusercontent.com/13313643/30690056-00c0e6e2-9ed4-11e7-9d32-34e332216a5e.png)
> > Consider this possibility.
> 
> this solves the problem, thanks 
> 
> ```js-jsx
>     <FormattedMessage id="app.search.placeholder" defaultMessage="Search username">
>         {
>             placeholder => (
>                 <Input placeholder={placeholder} size="large" allowClear 
>                     value={this.state.input} onChange={this.onChange} />
>             )
>         }
>     </FormattedMessage>
> ```

In my case it returns the English value when it's supposed to fetch the French value. Also, I have an error:

```
Error: [React Intl Error MISSING_TRANSLATION] Missing message: "password" for locale: "fr" 
    at formatMessage (message.js:58)
```
