### ISSUE TITLE
React Native iOS simulator

### ISSUE THREAD

**Issue by Ekhoo** [formatjs/react-intl#910]
Sorry if it's a noob question, I am new on React Native. On an iOS device, `react-intl` works well. But on the iOS simulator, I have an error that ask me to add a polyfill. Should I really need a polyfill on the simulator ? And if I use it, I got an `core.js: Cannot read property 'tokens' of undefined`

Thank you :)

**Comment by bodhi** [comment]
@Ekhoo look here: https://github.com/andyearnshaw/Intl.js/pull/264

**Comment by nenti** [comment]
But there is still no fix released. Neither from react-native nor from intl. Can we get a new release please.
