### ISSUE TITLE
Is it possible to use default message as message id?

### ISSUE THREAD

**Issue by epico** [formatjs/react-intl#912]
Currently we plan to internationalize tripleo-ui project.

It will receive some strings from the server side, but we need
to translate it in react client side, will copy and mark strings as translatable in react code.

The problem is that from the client code, there is no message id, only default message received from server side.

Is it possible to use default message as message id?

**Comment by ghostd** [comment]
Your message id can be what ever you wish.
Maybe your question is related to #609

**Comment by epico** [comment]
Thanks for the information!

**Comment by rosendi** [comment]
@epico Did you find a solution?

**Comment by epico** [comment]
This is the latest discussion:
http://lists.openstack.org/pipermail/openstack-dev/2017-April/115168.html

After discussion, tripleo-ui needs to load the translation from
object storage or some URL dynamically.
Because tripleo plan to support third-party template files with strings.

How to load the translation dynamically in react-intl?

**Comment by EmmanuelPREVOST** [comment]
Hello,

Yes it is.

```javascript
import { FormattedMessage, useIntl } from 'react-intl';

function toto() {
  const intl = useIntl();

  return (
    <FormattedMessage 
      id={an.intl.id.not.found.so.default.message.id.used} 
      defaultMessage={intl.formatMessage({ id: 'an.intl.id' })} 
    />

    <Field
      type="text"
      placeholder={intl.formatMessage({ id: 'an.intl.id' })}
    />
  )
}
```

It worked for me.
