### ISSUE TITLE
How to load all translations once at runtime?

### ISSUE THREAD

**Issue by windse7en** [formatjs/react-intl#920]
We are using `react-intl` as our react I18n solution. We keep all translations across each component. For example:
```
  components/
      |-  I18n/
             |-  translations/
                     |- en.js
                     |- en-US.js
      |-  DatePicker/
             |-  translations/
                     |- en.js
                     |- en-US.js
      |-  Banner/
             |-  translations/
                     |- en.js
                     |- en-US.js
```
The reason we keep this structure is, we release I18n(I18n module to guarantee all required locale data loaded before React rendering) and DatePicker as separated npm packages. We want to guarantee all translations stored in component level, so the translations update won't block any I18n dependent module. 

So the problem we are facing is how to load required translations at runtime. After doing some research work, we currently have two approaches:
1. Try to load all translations across all installed components(DatePicker, Banner components are optional). As we don't have too many translation in total, this approach is acceptable. But we have to use conditional require which we want to avoid. Code example:
```javascript
  let messages = require('translations/en.js');
  if (isInstalled(DatePicker) { datePickerMessages = require('DatePicker/translations/en.js') }
  if (isInstalled(Banner) { bannerMessages = require('Banner/translations/en.js') }
  messages = Object.assign({}, datePickerMessages, bannerMessages);
  module.export default = {
     locale: 'en',
     messages
  };
```
2. Load translations at each component level, like `DatePicker` translations, are loaded when it's used. But by this way, we have to have translations loading logic on each component. And at runtime, there will be extra HTTP request for a tiny chunk of translations. The process will be:
  * Use internal state to check if translations are ready
  * load component translations by locale
  * render the component after translations loaded

We are using ES6 syntax and webpack. Currently, we want to find a proper way to load all translations once at runtime. But we can't find the right direction. Could I have any pieces of advice on loading all translation or other approaches? @ericf

**Comment by artemjackson** [comment]
bump

**Comment by longlho** [comment]
I think a lot of companies (at least Dropbox & Yahoo) aggregate them into a bundle and serve it that way
