### ISSUE TITLE
Is the behaviour of auto-triming messages a bug or a feature?

### ISSUE THREAD

**Issue by e-e-e** [formatjs/react-intl#935]
I have encountered an issue where I require white space before a translated string, but have found that `formatMessage` is automatically trimming.

For example 
```js
const messages = defineMessages({
  and: {
    id: 'and',
    defaultMessage: ' and',
  },
};

const text = intl.formatMessage(messages.and);
```
In this instance `text` is equal to `and` where I expected it to equal `_and`.

I know this appears odd, but the exact use is for conjugating a dynamic array of other messages.

Is this expected behaviour? and if so whats the best way of formatting dynamic lists with grammatical conjugation with Intl?

**Comment by bright-sea** [comment]
+1

**Comment by DethAriel** [comment]
Another example is localizing a comma for delimiting item lists:

```js
const messages = defineMessages({
  delimiter: {
    id: 'delim',
    defaultMessage: ', ',
  },
};
```

There's an arabic comma (`"،"`, `U+060C`) that might be required in such cases, and having the message be whitespace-trimmed can mess up the layout a bit.
Could there be an override option to preserve that space character? E.g. `options.preserveWhitespace: [true|false]`.

**Comment by jnields** [comment]
Is there any way to work around this? I am encountering another usage to combine two sentences. In Chinese, sentences aren’t spaced but in European languages they are

**Comment by Romex91** [comment]
There is an undocumented babel plugin option `preserveWhitespace`
