### ISSUE TITLE
Can we return just a formatted string using the lib instead of the entire FormattedMessage comp?

### ISSUE THREAD

**Issue by PoojaSSW** [formatjs/react-intl#942]
This is not a issue, but more of a dicussion..So currently we see that the intl returns a FormattedMessage comp to convert the string into specific lang. it possible for it to return only a string of formatted message instead of the entire comp? Like, im suing a function to get the values, keys and pass them to the 
FormattedMessage comp:

```
function intl(key, values) {
  return <FormattedMessage id={key} defaultMessage={key} values={values} />;
}
```
instead is it possible for the lib to just return a string:
```
function intl(key, values) {
  return key;
}
```

**Comment by ghostd** [comment]
Hi,

I think you're looking for this: https://github.com/yahoo/react-intl/wiki/API#formatmessage

**Comment by piyaa** [comment]
this is perfect, however I was going through  ways to use this function outside react comp and I came across some threads related to it: https://github.com/yahoo/react-intl/issues/631
I dont quite understand how would it be best used if we try and export this function instead of adding contextTypes inside a react comp. something like:
function intl(key, values) {
  return formattedMessage({id:"123", defaultMessage:"some message"});
}

Is this possible?

**Comment by bichenkk** [comment]
Yes, I want to ask the same if we can use formattedMessage with injecting intl to the React components.

**Comment by bmueller-sykes** [comment]
Let me add my 👍 to this.

In my specific case, what I'd like to do is do as much of my data/string manipulating and formatting outside of my React components. In my specific case, I'd like to be able to do all this work inside the Redux lifecycle, specifically using `reselect` to compose/cobble together my data, and then I can simply have my React component reference a single selector with all of the data ready to go. In this context, I'd need to be able to call "formatMessage()" outside of the React component context. Does that make sense?

**Comment by ghostd** [comment]
If you don't need the react declarative way or you prefer to translate your strings into your reducers/selectors (or whatever other redux ecosystem part that is not related to react), maybe you could directly use [intl-messageformat](https://github.com/yahoo/intl-messageformat) and/or [format-js](https://formatjs.io/guides/runtime-environments/)

**Comment by bmueller-sykes** [comment]
I'd thought of that, certainly, but there are plenty of places where I would like to do the translation in the component. Basically, I want to have my cake and eat it, too. But you're right, if react-intl is constrained to components, then I may not really have a choice.

**Comment by ghostd** [comment]
In this case, you can use injectIntl(MyComp) then this.props.intl.formatMessage({id: 'my-message-id'})

**Comment by ghostd** [comment]
In this case, you can use injectIntl(MyComp) then this.props.intl.formatMessage({id: 'my-message-id'})

**Comment by greatbody** [comment]
this may help you。
```jsx
import React from 'react';
import { intlShape } from 'react-intl';

export default class A extends Component {
    static contextTypes = {
       intl: intlShape,
    }
    constructor(props, context) {
        context.intl.formatMessage(messages.placeholderIntlText);
    }
}
```

ref: [React-Intl How to use FormattedMessage in input placeholder](https://stackoverflow.com/questions/39630620/react-intl-how-to-use-formattedmessage-in-input-placeholder/39753280)

**Comment by greatbody** [comment]
also ref: [String without FormattedMessage](https://github.com/yahoo/react-intl/issues/749)
see 3rd floor.

**Comment by ycjcl868** [comment]
I think you want this,

```js
import React, {PropTypes} from 'react';
import { injectIntl, FormattedMessage } from 'react-intl';
 
/**
* {
* "hello": "Hello",
* "world": "World"
* }
*/
 
// pure function
const PureFunciton = injectIntl(({ intl }) => {
return (
  <div>
    <p>{intl.formatMessage({ id: 'hello' })}</p>
    <p><FormattedMessage id="world" /></p>
  </div>
)
});
 
// class Component
class componentName extends Component {
  handleStr = () => {
    // return 'Hello';
    const { intl } = this.props; 
    return intl.formatMessage({ id: 'hello' })
  }
  render() {
    return (
      <div>
        <p>{this.handleStr()}</p>
        <p><FormattedMessage id="world" /></p>
      </div>
    );
  }
}
 
export default injectIntl(connect(componentName));
```

**Comment by victorrodrigues** [comment]
@ycjcl868 thank you for the example using pure functions.

**Comment by epeicher** [comment]
We have resolved the problem in a slightly different way:

```
import React, { Component } from 'react';
import { Helmet } from 'react-helmet';
import { FormattedMessage, injectIntl } from 'react-intl';


const injectGetMessage = (fn) => 
  React.createElement(injectIntl(({ intl }) => fn(intl.formatMessage)));

class App extends Component {
  render() {
    return (
      <div>
        {injectGetMessage((getMessage) => <Helmet title={getMessage({ id: 'myId' })} />)}
        <h1>
        <FormattedMessage id='myId' />
        </h1>
      </div>
    );
  }
}

export default App;
```
The `injectGetMessage ` accepts a function that will receive as a parameter the react-intl `formatMessage` function thus allowing to return a formatted string inside the component that requires it. In this example the `<Helmet>` component
