### ISSUE TITLE
Custom Date and Number for format for 'en' locale

### ISSUE THREAD

**Issue by AjayU** [formatjs/react-intl#950]
Hi,

How do I pass the IntlConfig to the IntlProvider so that I could specify custom date and number format for the user locale. When I use default locale of 'en' it gives me date format of month/date/year format.

For number it always uses 1000 separator whereas what we want is a 100 separator. 

I wanted the format to be year, month/day. 
I have tried passing the IntlConfig to the IntlProvider viz. formats props object with date attribute as year, month/day. But it doesn't work. 

Can you please help here.

**Comment by papasmile** [comment]
You can see an example in unit tests for `formats`: https://github.com/yahoo/react-intl/blob/d09d744aa852b680ed2cfb0758736c7ecf2a7d69/src/format.js

If you still have an issue maybe you can post your code.

**Comment by papasmile** [comment]
sry that's source, test is at https://github.com/yahoo/react-intl/blob/d09d744aa852b680ed2cfb0758736c7ecf2a7d69/test/unit/format.js

**Comment by karl** [comment]
It would be awesome if we could get some details on custom formats in the docs, it's taken me a while to chase down this info!

**Comment by redonkulus** [comment]
Please feel free to add this info to the docs for others.
