### ISSUE TITLE
defaultFormats example for date in IntlProvider

### ISSUE THREAD

**Issue by chin-idean** [formatjs/react-intl#954]
There are example for time, but not date

I've tried to add defaultFormats for `FormattedDate` but it doesn't work, no doc mentions it if i should have a named format or normal one

My defaultFormats looks like : 
```
{
    date: {          
      timeZone: 'America/New_York',
      day: '2-digit',
      month: 'numeric',
      year: 'numeric',
      hour12: true,
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit'
    },
    time: {
      timeZone: 'America/New_York'
    }
  }
```

**Comment by dvakatsiienko** [comment]
+ 1 I'm llong for same exact foeature, how to setup default date format in IntlProvider props

**Comment by papasmile** [comment]
There a few examples of `defaultFormats` in unit tests[1][2]. It looks like you might be missing is a key for your defaults under date/time e.g.
{code}
defaultFormats: {
  date: {
    'year-only': {
      year: 'numeric',
    },
  },
}
{code}
[1] https://github.com/yahoo/react-intl/blob/b82a899a59c762fcc590e1fa824b87da6ad409d9/test/unit/format.js
[2] https://github.com/yahoo/react-intl/blob/4c7a766ec59f3fdceb5f0079359ca3919a23c5e3/test/unit/components/provider.js

**Comment by rodoabad** [comment]
@papasmile have you tried that example? That looks like you're creating a custom format `year-only` that you still have to explicitly use `<FormattedDate value={...} format='year-only'/>` to make it work.

@redonkulus  not sure if this thread is closed i.e. there's an answer.

**Comment by kaisermann** [comment]
Hey 👋 I'm also trying to understand how to provide a default format for formatting numbers i.e. I can't seem to find where [`defaultFormats` is used inside the `@formatjs/intl`](https://github.com/formatjs/formatjs/blob/main/packages/intl/src/dateTime.ts) package 🙈  

Is my understanding of this property right? It seems that it should define the default way of formatting the given data:

```ts
createIntl({
  defaultFormats: {
    // time is formatted like this by default if not asked otherwise
    time: { 
      hour: 'numeric',
      minute: 'numeric'
      hour12: false
    }
  }
})
```

**Comment by longlho** [comment]
It's being passed to intl-messageformat effectively

**Comment by kaisermann** [comment]
@longlho Ah, thanks for pointing that out. I think there's some confusion around what the "default" term means in this context. 

For me, `defaultFormats` would be the formats used when formatting time/date/number if I __haven't explicitly defined another format_. It seems that it's actually the same as `formats` but _only used if the formatting message doesn't exist in the dictionary of the current locale_. Is this correct? 

If that's the case, is there a way to have a specific formatting options for number/time/date as the "default" for that type? Without having to specify a `parseTime(time, { format: 'default' })`?

Thanks for your attention 🙏
