### ISSUE TITLE
Managing Descriptions with Translation Management Software

### ISSUE THREAD

**Issue by Floriferous** [formatjs/react-intl#957]
From what I can tell, most SaaS solutions that handles translation can often only upload files with key-value pairs in a variety of formats. But JSON options hardly allow any sort of description upload along with it.

Has someone here had experience with any of these apps and successfully imported the ids, descriptions, and defaultMessages?

Trying to figure out what a good workflow would be.

**Comment by ghostd** [comment]
Hi,

I think there is no official way. But you can look at this [link](https://github.com/volebo/dev/issues/11
) which points to many other interesting tools and discussions. I also found [this tool](https://github.com/GertjanReynaert/react-intl-translations-manager)
