### ISSUE TITLE
intl-enzyme-test-helper not providing access to wrapped component

### ISSUE THREAD

**Issue by timtime4** [formatjs/react-intl#964]
I'm having significant trouble with using jest and enzyme with internationalized components. 

Here's how I'm using it

**myComponent.test.js**
```
const setup = propOverides => {
    const props = {
      ...propOverides
    }
    const component = mountWithIntl(
      <MyComponent {...props}/>
    );

    return component;
};

it('it should get images when mounted', () => {
    const getResourcesSpy = expect.spyOn(MyComponent.prototype, 'getResources');
    const myComponent = setup();
    expect(getResourcesSpy).toHaveBeenCalled();
    expect(getResourcesSpy.calls.length).toEqual(1);
    getResourcesSpy.reset();
 });
```

**myComponent.component.js**
```
class MyComponent extends Component {
  constructor(props) {
    ...
    this.getResources = this.getResources.bind(this);
  }


static propTypes = {
  intl: PropTypes.object.isRequired,
}

getResources() {
  ...
}

componentWillMount() {
  this.getResources();
}

}

export default injectIntl(MyComponent);
```
**Error**
```
/components/spotlight/myComponent.component.js › it should get images when mounted

Cannot spyOn the 'getResources' property; it is not a function
```

I'm using intl-enzyme-test-helper as it's posted here 

https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl

```
/**
 * Components using the react-intl module require access to the intl context.
 * This is not available when mounting single components in Enzyme.
 * These helper functions aim to address that and wrap a valid,
 * English-locale intl context around them.
 */

import React from 'react';
import { IntlProvider, intlShape } from 'react-intl';
import { mount, shallow } from 'enzyme';

const messages = require('../../locales/en.json'); // en.json
const intlProvider = new IntlProvider({ locale: 'en', messages }, {});
const { intl } = intlProvider.getChildContext();

/**
 * When using React-Intl `injectIntl` on components, props.intl is required.
 */
function nodeWithIntlProp(node) {
  return React.cloneElement(node, { intl });
}

export function shallowWithIntl(node) {
    return shallow(nodeWithIntlProp(node), { context: { intl } });
};

export function mountWithIntl(node) {
    return mount(nodeWithIntlProp(node), {
      context: { intl },
      childContextTypes: { intl: intlShape }
    });
};
```

Does anyone have any thoughts here? I also noticed that it says on testing wiki page that "Jest will automatically mock react-intl, so no any extra implementation is needed, tests should work as is". This does not seem to be the case to me, unless there are any additional configurations that I'm missing.

**Comment by xdamman** [comment]
I'm also struggling with this.
Looks like `React.cloneElement` is not anymore passing the context as or React 14. That's probably the issue (and that wiki page https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl is probably not up to date). Not clear what's the new way to achieve this.

**Comment by aperkaz** [comment]
Any insights in the issue? 
I am also facing the same when using Enzyme with Jest.

**Comment by xdamman** [comment]
This solved it for me: https://gist.github.com/mirague/c05f4da0d781a9b339b501f1d5d33c37/

**Comment by 0nse** [comment]
@xdamman which code exactly did you use (original or from the comments?)? The Gist features the code given by the OP and is basically identical to that given on the Wiki page.

**Comment by kevinverelst** [comment]
Any news on this?
