### ISSUE TITLE
whats recommended way to show currency symbol derived from locale value set in IntlProvider?

### ISSUE THREAD

**Issue by gibbsonn** [formatjs/react-intl#969]
I'm trying to find out what the recommended way to show currency symbols for prices

Before looking around I originally thought that the currency would automatically be inferred from 
the locale set in `<IntlProvider locale='en-GB'`

But all the examples I've seen do something like this

```
  <FormattedNumber
      style="currency" currency="USD" value={10}/>
```

In my code I need the currency to reflect the current locale, so with en-GB it should be £ and with en-US it should be $.

So I need to know

* does react-intl provide any way to automatically infer the currency symbol out of the box?
* if not, what's the recommended way to do this, I have a few ideas but I think it's best to here from the experts.

**Comment by gibbsonn** [comment]
Anyone able to help with this?

**Comment by papasmile** [comment]
Not a committer, just chiming in: Intl.NumberFormat does not provide any default value when creating a new instance (see Parameters > currency)[1].  I don't see any ISO 4217-style[2] map in react-intl but I suppose you could add something for relevant countries then do simple lookup.  Oversimplified example:

```
const currencies = { en_US: 'USD', en_GB: 'GBP' };
...
<FormattedNumber style="currency" currency={ currencies[locale] } value={ 10 } />
```
Other libraries e.g. globalize[3] have currency mapping rolled in.

[1] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat
[2] https://www.iso.org/iso-4217-currency-codes.html
[3] https://github.com/globalizejs/globalize#currency-module
