### ISSUE TITLE
FormattedPlural style prop conflict

### ISSUE THREAD

**Issue by vlw0052** [formatjs/react-intl#975]
`FormattedPlural` options `style` prop conflicts with React's style prop. So I receive a warning when setting 

```
<FormattedPlural
	value={2}
	one='st'
	two='nd'
	few='rd'
	other='th'
	style={`ordinal`}
	/>
```
![screen shot 2017-07-01 at 9 49 28 pm](https://user-images.githubusercontent.com/6472191/27766892-521ca4a8-5ea7-11e7-9261-59cec0a7a32a.png)

A warning is thrown during development and this doesn't allow the ability to style the Component.
Wondering if there's a possible way to send this ordinal value another way. that way a style can still be added.

Recreated [here](https://github.com/vlw0052/React-INTL-Example)

P.S. If someone can give me a template to run React using ES6 class syntax in **jsbin**, **jsfiddle**, or **codepen**. So can send later issues to that instead. That'd be awesome.

**Comment by ghostd** [comment]
Hi,

It is not related to react-intl but to an eslint plugin:
https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/style-prop-object.js#L44
This plugin seems enforces this rule whatever the prop-types defined by the component.

[Disable this rule](http://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments), and all should be fine.

PS: Your example code miss "yarn add react-intl"

**Comment by e110c0** [comment]
just found this since I ran into the same warning. While disabling eslint will hide this issue, it still is an issue. The style property of all react-intl components clash with the react/html style property.

There is a reason for this rule and I'd rather not disable eslint rules to 'fix' a non-standard use of the style property.

**Comment by slomski** [comment]
To make eslint happy you can define you props 
`const numberFormatOptions = { style: 'currency', currency, currencyDisplay: 'code' };`
and spread it `<FormattedNumber value={row.rate} {...numberFormatOptions} />`

**Comment by e110c0** [comment]
While this workaround works nicely, My original argument holds true: using the `style` property for other purposes than css styling is still confusing and ambiguous use
