### ISSUE TITLE
Packet messages can't be modularized

### ISSUE THREAD

**Issue by TongDaDa** [formatjs/react-intl#981]
Want to modularize packets, because every time you introduce them from messages is flat, there is no module structure
![qq 20170707131529](https://user-images.githubusercontent.com/23241188/27944009-5d159b4e-6316-11e7-9d39-7877f762a388.png)

I want to do this, but the id attribute in the FormattedMessage component can only correspond to the attributes in messages, and I want the module structure

**Comment by okovpashko** [comment]
@TongDaDa You can use nested objects in your messages file and flatten them before passing to `IntlProvider` using a package like [flat](https://www.npmjs.com/package/flat).
