### ISSUE TITLE
Inconsistent formatting between Ie/Edge and other browsers

### ISSUE THREAD

**Issue by Jarory13** [formatjs/react-intl#985]
I'm noticing an inconsistent pattern between browsers when formatting Date objects. In Chrome I can get the following: 

"Wed 05/03/2017"

However the exact same field on the exact same page renders the following in IE: 
"Wed, 5 3, 2017"

The locale hasn't changed for me so I can't imagine a reason why I would see different formatting styles. My locale is en-US for reference. Has this happened to anyone else?

**Comment by Jarory13** [comment]
The function I'm using to format my date objects looks like this by the way:

`	formatDate = (date) => {
		const { formatDate } = this.props.intl;
		const weekday = this.props.weekdayFormat ? this.props.weekdayFormat : this.props.weekdayFormat === null ? undefined : 'short';
		const month = this.props.monthFormat ? this.props.monthFormat : this.props.monthFormat === null ? undefined : 'numeric';
		const year = this.props.yearFormat ? this.props.yearFormat : this.props.yearFormat === null ? undefined : 'numeric';
		const day = this.props.dayFormat ? this.props.dayFormat : this.props.dayFormat === null ? undefined : 'numeric';
		return formatDate(date, {
			weekday: weekday,
			month: month,
			year: year,
			day: day,
		});
	};`

**Comment by ghostd** [comment]
Hi @Jarory13 

react-intl uses the [Intl API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat) to format the date. Do you have the expected behavior when you directly use it? (see the examples of the MDN documentation)

**Comment by Jarory13** [comment]
@ghostd I do not. I get the same behavior in IE with the date reading ‎"Tue‎, ‎7‎ ‎11‎, ‎2017" for en-US regardless of whether I use the Intl API directly or React Intl. This is incorrect. I figured this must happen to other folks and was seeking to find if anyone had begun working on a solution. 

As an aside, I can't help but wonder if the windows format settings are somehow overriding whatever JavaScript is trying to do?

**Comment by ghostd** [comment]
So, this is not a react-intl issue. Did you load and try the [polyfill](https://github.com/andyearnshaw/Intl.js)?
