### ISSUE TITLE
Dates in summer periods in years before introduction of DST are shifted and thus formatted incorrectly

### ISSUE THREAD

**Issue by nightlyop** [formatjs/react-intl#989]
Dates which are in the summer period of a year for which daylight saving time was not introduced yet, get an unexpected time shift.  I wrote a [fiddle](https://jsfiddle.net/nightlyop/d0hypvtz/46/) to test some dates. A Date object is created from a string and then formatted by formatDate. The output when running it on my computer (Windows 10, Firefox and Chrome, Switzerland):

> Summer but no DST
> initial date:  1980-04-18 00:00:00
> Date:  Fri Apr 18 1980 00:00:00 GMT+0200
> formatDate  04/17/1980
> formatDate full  04/17/1980, 11:00:00 PM Central European Standard Time
> WRONG, I expect April 18, 1980
> 
> Summer and DST introduced
> initial date:  1981-04-18 00:00:00
> Date:  Sat Apr 18 1981 00:00:00 GMT+0200
> formatDate  04/18/1981
> formatDate full  04/18/1981, 12:00:00 AM Central European Summer Time
> April 18, 1981 is CORRECT
> 
> Winter
> initial date:  1980-01-02 00:00:00
> Date:  Wed Jan 02 1980 00:00:00 GMT+0100
> formatDate  01/02/1980
> formatDate full  01/02/1980, 12:00:00 AM Central European Standard Time
> Correct, dates in winter are no problem

The date we want to format is a date of birth, hence the time is always midnight. However, the time shift also occurs if the time is not midnight.

DST was introduced in Switzerland in 1981, one year after it was introduced in Europe. DST was already in use in the years 1941/42 in Switzerland, but then the summer period was different (unfortunately I found that [info](https://de.wikipedia.org/wiki/Sommerzeit) only in German).

**Comment by papasmile** [comment]
I ran your fiddle on Mac, and dates are working as expected (see below).  Perhaps you have a Windows bug as described in https://stackoverflow.com/questions/43454520/timezone-issue-with-intl-datetimeformat-for-old-dates and https://stackoverflow.com/questions/41967837/time-difference-between-chrome-edge-on-windows-10

![screen shot 2017-07-17 at 11 47 09 am](https://user-images.githubusercontent.com/3638363/28279428-0ff7bc52-6ae6-11e7-8a7d-582b92ea867f.png)

**Comment by nightlyop** [comment]
I was able to reproduce the error on a Mac and on an iPad (that's actually the device on which the error occured in our app at the beginning and made me writing the fiddle). However, the fiddle works as expected when changing the time zone of my computer to UTC.

I checked https://github.com/eggert/tz and I think the change of DST is configured in https://github.com/eggert/tz/blob/master/europe#L3508.

**Comment by lauterry** [comment]
Hi

Could this issue be related to https://github.com/yahoo/react-intl/issues/991 ?

**Comment by nightlyop** [comment]
Yes, this might be the same issue @lauterry. If you display the hours and minutes as well, you might see how much the time is shifted exactly.

**Comment by nightlyop** [comment]
We did some more tests and it looks like date() has some bugs. We didn't make a fiddle and the bugs seem to depend on browser, locale and the point in time (e.g. we had less problems with dates after 1.1.1970). Thus our problem with formatDate() seem to be caused by date(). We are going to use momentjs to format dates for the moment.
